import { FormEvent, useEffect, useMemo, useState } from 'react';
import { ArrowLeft, CalendarDays, CheckCircle2, Clock3, FileText, MapPin, Plus, Ruler, Search, User, XCircle } from 'lucide-react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { getActiveCompanies, getCustomerById, getPartyById } from '../../services/core/coreRepository';
import { getCustomerSummaries } from '../../services/core/coreRepository';
import { createMeasurement, getMeasurement, listMeasurements, markMeasurementCancelled, updateMeasurement, type AssignedMode, type Measurement, type MeasurementActivity, type MeasurementListRow, type MeasurementStatus } from '../../services/measurements/measurementRepository';
import { useAuth } from '../../auth/AuthContext';
import './measurements.css';

const statusMeta:Record<MeasurementStatus,{label:string;next:string}>={
  PLANNED:{label:'Planificada',next:'Asignar medidor'},ASSIGNED:{label:'Asignada',next:'Iniciar medición'},IN_PROGRESS:{label:'En curso',next:'Completar medición'},
  COMPLETED:{label:'Completada',next:'Generar presupuesto'},QUOTED:{label:'Presupuestada',next:'Seguimiento'},CLOSED:{label:'Cerrada',next:'Sin acciones'},CANCELLED:{label:'Cancelada',next:'Sin acciones'}
};

function StatusBadge({status}:{status:MeasurementStatus}){return <span className={`measurement-status ${status.toLowerCase()}`}>{statusMeta[status].label}</span>}
function formatDate(value:string|null){return value?new Intl.DateTimeFormat('es-ES',{day:'2-digit',month:'2-digit',year:'numeric'}).format(new Date(`${value}T12:00:00`)):'—';}
function isPast(value:string|null){return !!value && new Date(`${value}T23:59:59`).getTime()<Date.now();}

export function Measurements(){
  const {id}=useParams<{id:string}>();
  if(id) return <MeasurementDetail measurementId={Number(id)} />;
  return <MeasurementList/>;
}

function MeasurementList(){
  const navigate=useNavigate();
  const [rows,setRows]=useState<MeasurementListRow[]>([]); const [search,setSearch]=useState(''); const [status,setStatus]=useState('active'); const [loading,setLoading]=useState(true); const [error,setError]=useState('');
  async function load(){setLoading(true);setError('');try{setRows(await listMeasurements(search,status as never));}catch(e){setError(e instanceof Error?e.message:'No se pudieron cargar las mediciones.');}finally{setLoading(false)}}
  useEffect(()=>{const t=setTimeout(load,220);return()=>clearTimeout(t)},[search,status]);
  return <div className="module-page measurements-page">
    <div className="page-head"><div><div className="eyebrow">GESTIÓN / MEDICIONES</div><h1>Expedientes de medición</h1><p>Seguimiento de visitas, medidas y origen de presupuestos.</p></div><button className="primary-button" onClick={()=>navigate('/gestion/mediciones/nuevo')}><Plus size={17}/> Nueva medición</button></div>
    <div className="toolbar measurement-toolbar"><div className="search-box"><Search size={17}/><input autoFocus value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar por número, referencia, cliente o población…" aria-label="Buscar medición"/></div><select value={status} onChange={e=>setStatus(e.target.value)} aria-label="Estado"><option value="active">Activas</option><option value="planned">Planificadas</option><option value="assigned">Asignadas</option><option value="in_progress">En curso</option><option value="completed">Completadas</option><option value="quoted">Presupuestadas</option><option value="closed">Cerradas</option><option value="cancelled">Canceladas</option><option value="all">Todas</option></select><span className="result-count">{rows.length} expedientes</span></div>
    {error&&<div className="inline-error">{error}</div>}
    <div className="table-panel measurement-table"><table><thead><tr><th>Expediente</th><th>Cliente</th><th>Ubicación</th><th>Fecha</th><th>Medidor</th><th>Estado</th></tr></thead><tbody>{loading?<tr><td colSpan={6}>Cargando…</td></tr>:rows.length===0?<tr><td colSpan={6}><div className="empty-state"><Ruler size={28}/><strong>No hay mediciones</strong><span>Crea un expediente nuevo o cambia los filtros.</span></div></td></tr>:rows.map(r=><tr key={r.id} className="clickable-row" onClick={()=>navigate(`/gestion/mediciones/${r.id}`)}><td><div className="measurement-code">{r.code}</div>{r.reference&&<div className="secondary">{r.reference}</div>}</td><td><strong>{r.customer_name_snapshot||'—'}</strong></td><td>{r.site_city||r.site_street?<><MapPin size={13}/> {r.site_city||r.site_street}</>:'—'}</td><td><div>{formatDate(r.measurement_date)}</div>{isPast(r.measurement_date)&&r.status!=='COMPLETED'&&<span className="measurement-warning">Fecha pasada</span>}</td><td>{r.assigned_mode==='SELF'?'Medidas propias':r.assigned_user_id?'Usuario asignado':'Sin asignar'}</td><td><StatusBadge status={r.status}/></td></tr>)}</tbody></table></div>
  </div>
}

function MeasurementDetail({measurementId}:{measurementId:number}){
  const navigate=useNavigate(); const {user}=useAuth();
  const [companyId,setCompanyId]=useState<number|null>(null); const [measurement,setMeasurement]=useState<Measurement|null>(null); const [activities,setActivities]=useState<MeasurementActivity[]>([]);
  const [customers,setCustomers]=useState<any[]>([]); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [error,setError]=useState(''); const [editing,setEditing]=useState(measurementId===0); const [customerSearch,setCustomerSearch]=useState('');
  const [draft,setDraft]=useState<Partial<Measurement>>({status:'PLANNED',assigned_mode:'UNASSIGNED',assigned_user_id:null,contact_date:new Date().toISOString().slice(0,10),site_country_code:'ES'});

  useEffect(()=>{getActiveCompanies().then(cs=>setCompanyId(cs[0]?.id??null)).catch(e=>setError(e instanceof Error?e.message:'No se pudo obtener la empresa activa.'));},[]);
  useEffect(()=>{if(companyId&&measurementId)load();},[companyId,measurementId]);
  useEffect(()=>{getCustomerSummaries(customerSearch).then(setCustomers).catch(()=>setCustomers([]));},[customerSearch]);
  async function load(){setLoading(true);setError('');try{const d=await getMeasurement(measurementId);setMeasurement(d.measurement);setActivities(d.activities);setDraft(d.measurement);setEditing(false)}catch(e){setError(e instanceof Error?e.message:'No se pudo cargar el expediente.')}finally{setLoading(false)}}
  async function chooseCustomer(id:number){try{const c=await getCustomerById(id);const p=await getPartyById(c.party_id);const draftPatch={customer_id:c.id,customer_name_snapshot:p.trade_name||p.legal_name,customer_tax_id_snapshot:p.tax_id,customer_phone_snapshot:p.phone,customer_mobile_snapshot:null,customer_email_snapshot:p.email};setDraft(v=>({...v,...draftPatch}));setCustomerSearch(p.trade_name||p.legal_name);}catch(e){setError(e instanceof Error?e.message:'No se pudo cargar el cliente.')}}
  function update<K extends keyof Measurement>(key:K,value:Measurement[K]){setDraft(v=>({...v,[key]:value}));}
  async function save(e?:FormEvent){e?.preventDefault();if(!companyId)return;if(!String(draft.customer_name_snapshot||'').trim()){setError('El cliente es obligatorio.');return}if(!draft.contact_date){setError('La fecha de contacto es obligatoria.');return}if(draft.assigned_mode==='USER'&&!draft.assigned_user_id){setError('Debe indicar el medidor asignado.');return}setSaving(true);setError('');try{if(measurementId===0){const id=await createMeasurement(companyId,{reference:draft.reference??null,customer_id:draft.customer_id??null,customer_name_snapshot:draft.customer_name_snapshot??null,customer_tax_id_snapshot:draft.customer_tax_id_snapshot??null,customer_phone_snapshot:draft.customer_phone_snapshot??null,customer_mobile_snapshot:draft.customer_mobile_snapshot??null,customer_email_snapshot:draft.customer_email_snapshot??null,site_street:draft.site_street??null,site_postal_code:draft.site_postal_code??null,site_city:draft.site_city??null,site_region:draft.site_region??null,site_country_code:draft.site_country_code??'ES',site_latitude:null,site_longitude:null,contact_method:draft.contact_method??null,commercial_name:draft.commercial_name??null,assigned_user_id:draft.assigned_user_id??null,assigned_mode:(draft.assigned_mode??'UNASSIGNED') as AssignedMode,status:(draft.status??'PLANNED') as MeasurementStatus,contact_date:draft.contact_date!,measurement_date:draft.measurement_date??null,measurement_time:draft.measurement_time??null,reference_note:draft.reference_note??null,observations:draft.observations??null});navigate(`/gestion/mediciones/${id}`);}else{await updateMeasurement(measurementId,draft,'Expediente actualizado','UPDATED');await load() ;setEditing(false)}}catch(e){setError(e instanceof Error?e.message:'No se pudo guardar el expediente.')}finally{setSaving(false)}}
  async function advance(){if(!measurement)return;const next:Record<MeasurementStatus,MeasurementStatus|undefined>={PLANNED:'ASSIGNED',ASSIGNED:'IN_PROGRESS',IN_PROGRESS:'COMPLETED',COMPLETED:'QUOTED',QUOTED:'CLOSED',CLOSED:undefined,CANCELLED:undefined};const n=next[measurement.status];if(!n)return;const patch=n==='ASSIGNED'&&measurement.assigned_mode==='UNASSIGNED'?{status:n as MeasurementStatus}:{status:n as MeasurementStatus};if(n==='ASSIGNED'&&measurement.assigned_mode==='UNASSIGNED'){setError('Asigna un medidor o selecciona “Medidas propias” antes de continuar.');setEditing(true);return}await updateMeasurement(measurement.id,patch,`Estado cambiado a ${statusMeta[n].label}`,'STATUS_CHANGED');await load()}
  if(loading)return <div className="loading-block">Cargando expediente…</div>;
  if(measurementId!==0&&!measurement)return <div className="inline-error">Expediente no encontrado.</div>;
  const isNew=!measurement;
  const current=measurement??draft as Measurement;
  return <div className="module-page measurement-detail-page">
    <div className="page-head"><div><div className="eyebrow">GESTIÓN / MEDICIONES / {current.code||'NUEVA'}</div><h1>{current.code||'Nueva medición'}</h1><p>{current.customer_name_snapshot||'Expediente de campo'}{current.site_city?` · ${current.site_city}`:''}</p></div><div className="measurement-head-actions"><button className="secondary-button" onClick={()=>navigate('/gestion/mediciones')}><ArrowLeft size={15}/> Volver</button>{measurement&&!editing&&<button className="secondary-button" onClick={()=>setEditing(true)}>Editar expediente</button>}</div></div>
    {error&&<div className="inline-error">{error}</div>}
    <div className="measurement-summary"><div><span>Número</span><strong>{current.code||'Se asignará al guardar'}</strong></div><div><span>Estado</span><StatusBadge status={current.status}/></div><div><span>Próxima acción</span><strong>{statusMeta[current.status].next}</strong></div><div><span>Fecha medición</span><strong>{formatDate(current.measurement_date)}</strong></div></div>
    <div className="measurement-grid">
      <form onSubmit={save} className="measurement-main">
        <section className="panel"><div className="panel-head"><div><h2>Cliente y ubicación</h2><p>La medición conserva una copia de los datos utilizados en la visita.</p></div><User size={19}/></div>
          <div className="form-grid"><label className="wide">Buscar cliente<input value={customerSearch||current.customer_name_snapshot||''} disabled={!editing} onChange={e=>setCustomerSearch(e.target.value)} list="measurement-customer-list" placeholder="Nombre, CIF/NIF o código…"/>
            <datalist id="measurement-customer-list">{customers.slice(0,20).map(c=><option key={c.id} value={c.party.trade_name||c.party.legal_name}>{c.party.tax_id||c.party.code||''}</option>)}</datalist></label>
            <label>Cliente<input readOnly value={current.customer_name_snapshot||''} /></label><label>CIF/NIF<input readOnly value={current.customer_tax_id_snapshot||''}/></label><label>Teléfono<input readOnly value={current.customer_phone_snapshot||''}/></label><label>Móvil<input readOnly value={current.customer_mobile_snapshot||''}/></label><label>Email<input readOnly value={current.customer_email_snapshot||''}/></label>
            <label className="wide">Dirección de medición<input disabled={!editing} value={current.site_street||''} onChange={e=>update('site_street',e.target.value)}/></label><label>CP<input disabled={!editing} value={current.site_postal_code||''} onChange={e=>update('site_postal_code',e.target.value)}/></label><label>Población<input disabled={!editing} value={current.site_city||''} onChange={e=>update('site_city',e.target.value)}/></label><label>Provincia<input disabled={!editing} value={current.site_region||''} onChange={e=>update('site_region',e.target.value)}/></label></div>
        </section>
        <section className="panel"><div className="panel-head"><div><h2>Agenda y asignación</h2><p>La persona que realiza la medición se gestiona por usuario del sistema.</p></div><CalendarDays size={19}/></div>
          <div className="form-grid"><label>Forma de contacto<select disabled={!editing} value={current.contact_method||''} onChange={e=>update('contact_method',e.target.value||null)}><option value="">Seleccionar…</option><option>Recomendado</option><option>Teléfono</option><option>Visita oficina</option><option>Email</option><option>Comerciales</option><option>Presupuesto on-line</option></select></label><label>Comercial<input disabled={!editing} value={current.commercial_name||''} onChange={e=>update('commercial_name',e.target.value||null)} placeholder="Opcional"/></label><label>Fecha de contacto<input type="date" disabled={!editing} value={current.contact_date||''} onChange={e=>update('contact_date',e.target.value)}/></label><label>Fecha de medición<input type="date" disabled={!editing} value={current.measurement_date||''} onChange={e=>update('measurement_date',e.target.value||null)}/></label><label>Hora<input type="time" disabled={!editing} value={current.measurement_time||''} onChange={e=>update('measurement_time',e.target.value||null)}/></label><label>Medidor<select disabled={!editing} value={current.assigned_mode||'UNASSIGNED'} onChange={e=>{const mode=e.target.value as AssignedMode;update('assigned_mode',mode);update('assigned_user_id',mode==='SELF'?user?.id??null:null)}}><option value="UNASSIGNED">Sin asignar</option><option value="SELF">Medidas propias</option><option value="USER">Usuario asignado</option></select></label>{current.assigned_mode==='USER'&&<label>Usuario asignado<input disabled value={current.assigned_user_id||''} placeholder="En una siguiente iteración se seleccionará desde el maestro de usuarios"/></label>}
          </div>
        </section>
        <section className="panel"><div className="panel-head"><div><h2>Observaciones</h2><p>Información libre del expediente.</p></div><FileText size={19}/></div><textarea disabled={!editing} rows={7} value={current.observations||''} onChange={e=>update('observations',e.target.value)} placeholder="Acceso, detalles de la visita, incidencias…"/></section>
        {editing&&<div className="measurement-save-bar"><button type="submit" className="primary-button" disabled={saving}>{saving?'Guardando…':'Guardar expediente'}</button></div>}
      </form>
      <aside className="measurement-side">
        <section className="panel measurement-next"><div className="panel-head"><div><h2>Acción siguiente</h2><p>El expediente guía el trabajo.</p></div><Ruler size={19}/></div>{measurement?.status==='CANCELLED'?<div className="side-action muted">Expediente cancelado.</div>:measurement?.status==='CLOSED'?<div className="side-action muted">Expediente cerrado.</div>:<button className="next-action" onClick={advance}>{measurement?.status==='COMPLETED'?<FileText size={18}/>:measurement?.status==='IN_PROGRESS'?<CheckCircle2 size={18}/>:<Clock3 size={18}/>} {statusMeta[current.status].next}</button>}{measurement&&measurement.status!=='CANCELLED'&&measurement.status!=='CLOSED'&&<button className="danger-button full" onClick={async()=>{await markMeasurementCancelled(measurement.id);await load()}}><XCircle size={16}/> Cancelar medición</button>}</section>
        <section className="panel"><div className="panel-head"><div><h2>Actividad</h2><p>Historial del expediente.</p></div></div><div className="activity-list">{activities.length===0?<span className="secondary">Sin actividad.</span>:activities.map(a=><div key={a.id} className="activity-item"><span className="activity-dot"/><div><strong>{a.message}</strong><div className="secondary">{new Intl.DateTimeFormat('es-ES',{dateStyle:'short',timeStyle:'short'}).format(new Date(a.created_at))}</div></div></div>)}</div></section>
        <section className="panel"><div className="panel-head"><div><h2>Presupuestos</h2><p>Origen para futuros documentos comerciales.</p></div></div><div className="side-placeholder">Todavía no hay presupuesto asociado. El enlace quedará preparado para la siguiente fase.</div></section>
      </aside>
    </div>
  </div>
}
