// Asistente IA para el editor de OTD. Genera una propuesta JSON que el editor valida y muestra para que el usuario decida qué aceptar.
// Proveedor: Google Gemini API. Requiere el secreto GEMINI_API_KEY en Supabase.
// Exige un usuario autenticado y no escribe nada en la base de datos.
import { createClient } from "npm:@supabase/supabase-js@2";
const CORS_HEADERS={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type"};
const MODEL="gemini-2.5-flash-lite";
const ENDPOINT=`https://generativelanguage.googleapis.com/v1beta/models/${MODEL}:generateContent`;
const FUNCTIONS=["CEIL(x)","FLOOR(x)","ROUND(x)","ROUND(x, decimales)","MAX(a,b,...)","MIN(a,b,...)","ABS(x)","SQRT(x)","TRUNC(x)","TO_M(mm)","TO_MM(m)","TO_CM(mm)","TO_DM(mm)","TO_M2(mm2) o TO_M2(mm_ancho, mm_alto)","TO_CM2(...)","TO_MM2(...)","TO_KG(g)","TO_G(kg)"];
const SYSTEM=`Eres un asistente técnico que ayuda a definir OTD (Órdenes Técnicas de Despiece) para un ERP de fabricación de toldos y lonas a medida. Un OTD tiene selections (entradas de oficina), variables (valores numéricos calculados) y components (piezas/materiales). Las fórmulas solo admiten + - * / % y paréntesis. Los identificadores son códigos MAYUSCULAS_CON_GUION_BAJO o funciones ${FUNCTIONS.join(", ")}. Solo puedes referenciar códigos existentes o definidos en tu respuesta. Los códigos deben ser únicos entre selections y variables. selection_type: OPTION, NUMBER, TEXT o BOOLEAN. is_dimension=true solo para medidas físicas. unit_code debe ser uno de los códigos dados o null. component_type: BASIC o IMPROVEMENT. No inventes product_id ni characteristic_id. Devuelve únicamente JSON válido con: selections[{code,name,selection_type,required,is_dimension,unit_code,options[{code,label}]}], variables[{code,name,expression,data_type}], components[{code,description,quantity_expression,component_type,unit_code,dimension_expressions}], notes. Si una lista no aplica, array vacío.`;
const SCHEMA={type:"OBJECT",properties:{selections:{type:"ARRAY",items:{type:"OBJECT",properties:{code:{type:"STRING"},name:{type:"STRING"},selection_type:{type:"STRING",enum:["OPTION","NUMBER","TEXT","BOOLEAN"]},required:{type:"BOOLEAN"},is_dimension:{type:"BOOLEAN"},unit_code:{type:["STRING","NULL"]},options:{type:"ARRAY",items:{type:"OBJECT",properties:{code:{type:"STRING"},label:{type:"STRING"}},required:["code","label"]}}},required:["code","name","selection_type","required","is_dimension","unit_code","options"]}},variables:{type:"ARRAY",items:{type:"OBJECT",properties:{code:{type:"STRING"},name:{type:"STRING"},expression:{type:"STRING"},data_type:{type:"STRING",enum:["NUMBER"]}},required:["code","name","expression","data_type"]}},components:{type:"ARRAY",items:{type:"OBJECT",properties:{code:{type:"STRING"},description:{type:"STRING"},quantity_expression:{type:"STRING"},component_type:{type:"STRING",enum:["BASIC","IMPROVEMENT"]},unit_code:{type:["STRING","NULL"]},dimension_expressions:{type:"OBJECT",additionalProperties:{type:"STRING"}}},required:["code","description","quantity_expression","component_type","unit_code","dimension_expressions"]}},notes:{type:"STRING"}},required:["selections","variables","components","notes"]};
const out=(b:unknown,s=200)=>new Response(JSON.stringify(b),{status:s,headers:{...CORS_HEADERS,"Content-Type":"application/json"}});
Deno.serve(async(req)=>{if(req.method==="OPTIONS")return new Response(null,{headers:CORS_HEADERS});if(req.method!=="POST")return out({error:"Método no permitido."},405);try{const auth=req.headers.get("Authorization");if(!auth)return out({error:"No autenticado."},401);const url=Deno.env.get("SUPABASE_URL"),anon=Deno.env.get("SUPABASE_ANON_KEY");if(!url||!anon)return out({error:"El servidor no tiene configurado Supabase."},500);const sb=createClient(url,anon,{global:{headers:{Authorization:auth}}});const{data,error}=await sb.auth.getUser();if(error||!data?.user)return out({error:"No autenticado."},401);const body=await req.json().catch(()=>null),prompt=typeof body?.prompt==="string"?body.prompt.trim():"";if(!prompt)return out({error:"Falta el prompt."},400);const key=Deno.env.get("GEMINI_API_KEY");if(!key)return out({error:"El servidor no tiene configurada GEMINI_API_KEY."},500);const units=Array.isArray(body?.unitCodes)?body.unitCodes:[],sels=Array.isArray(body?.existingSelections)?body.existingSelections:[],vars=Array.isArray(body?.existingVariables)?body.existingVariables:[];const context=`Unidades disponibles: ${units.length?units.join(", "):"ninguna"}.\nEntradas existentes: ${sels.length?sels.map((x:any)=>x.code).filter(Boolean).join(", "):"ninguna"}.\nVariables existentes: ${vars.length?vars.map((x:any)=>x.code).filter(Boolean).join(", "):"ninguna"}.\n\nPetición del usuario:\n${prompt}`;const r=await fetch(`${ENDPOINT}?key=${encodeURIComponent(key)}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({systemInstruction:{parts:[{text:SYSTEM}]},contents:[{role:"user",parts:[{text:context}]}],generationConfig:{temperature:.2,maxOutputTokens:4096,responseMimeType:"application/json",responseSchema:SCHEMA}})});const j=await r.json().catch(()=>null);if(!r.ok)return out({error:`Error de la API de Gemini: ${j?.error?.message||`HTTP ${r.status}`}`},502);const text=j?.candidates?.[0]?.content?.parts?.find((p:any)=>typeof p?.text==="string")?.text;if(!text)return out({error:"Gemini no ha devuelto una respuesta válida."},502);try{return out(JSON.parse(text))}catch{return out({error:"Gemini no ha devuelto un JSON válido. Prueba a reformular el prompt."},502)}}catch(e){return out({error:e instanceof Error?e.message:"Error inesperado."},500)}});
