-- ONIN: stock dimensional y remanentes.
-- Las características identifican la variante comercial; las dimensiones identifican la pieza física.

create table if not exists public.warehouse_stock_item (
  id bigint generated by default as identity primary key,
  warehouse_stock_id bigint not null references public.warehouse_stock(id),
  product_id bigint not null references public.product(id),
  characteristic_id bigint null references public.product_characteristic(id),
  quantity numeric not null default 1,
  dimension_values jsonb not null default '[]'::jsonb,
  status varchar not null default 'AVAILABLE',
  parent_stock_item_id bigint null references public.warehouse_stock_item(id),
  source_stock_movement_id bigint null references public.stock_movement(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint warehouse_stock_item_quantity_check check (quantity > 0),
  constraint warehouse_stock_item_status_check check (status in ('AVAILABLE','RESERVED','CONSUMED','SCRAP')),
  constraint warehouse_stock_item_dimensions_array_check check (jsonb_typeof(dimension_values) = 'array')
);

create index if not exists idx_warehouse_stock_item_lookup
  on public.warehouse_stock_item (warehouse_stock_id, product_id, characteristic_id, status);

create index if not exists idx_warehouse_stock_item_parent
  on public.warehouse_stock_item (parent_stock_item_id);

create index if not exists idx_warehouse_stock_item_dimensions
  on public.warehouse_stock_item using gin (dimension_values);

alter table public.stock_movement
  add column if not exists dimension_values jsonb not null default '[]'::jsonb;

alter table public.stock_reservation
  add column if not exists dimension_values jsonb not null default '[]'::jsonb;

comment on table public.warehouse_stock_item is
  'Unidad física o lote de stock. Las dimensiones se almacenan en el mismo orden que las dimensiones del Tipo de medida del artículo. Los remanentes se crean como nuevas unidades enlazadas mediante parent_stock_item_id.';
comment on column public.warehouse_stock_item.dimension_values is
  'Dimensiones físicas de la existencia, por ejemplo [600] para un perfil de 600 cm o [500,120] para una lona.';
comment on column public.warehouse_stock_item.parent_stock_item_id is
  'Existencia de origen de la que procede este remanente.';
comment on column public.stock_movement.dimension_values is
  'Dimensiones físicas afectadas por el movimiento de stock.';
comment on column public.stock_reservation.dimension_values is
  'Dimensiones solicitadas/reservadas junto con el artículo y la característica.';
