-- Migration: Add product_family_attribute table for Family Characteristics relation
create table if not exists public.product_family_attribute (
  id bigint generated by default as identity primary key,
  family_id bigint not null references public.product_family(id) on delete cascade,
  attribute_id bigint not null references public.product_attribute(id) on delete cascade,
  required boolean not null default false,
  sort_order integer not null default 0,
  active boolean not null default true,
  deleted_at timestamptz,
  deleted_by uuid,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint product_family_attribute_uk unique(family_id, attribute_id)
);

create index if not exists ix_product_family_attribute_family on public.product_family_attribute(family_id, active, sort_order);
create index if not exists ix_product_family_attribute_attribute on public.product_family_attribute(attribute_id);
