create table if not exists public.customer_family_discount (
  id bigint generated by default as identity primary key,
  company_id bigint not null references public.company(id),
  customer_party_id bigint not null references public.party(id),
  product_family_id bigint not null references public.product_family(id),
  discount_percent numeric not null check (discount_percent >= 0 and discount_percent <= 100),
  active boolean not null default true,
  deleted_at timestamptz null,
  deleted_by uuid null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (company_id, customer_party_id, product_family_id)
);

alter table public.product_customer_discount
  add column if not exists deleted_at timestamptz null,
  add column if not exists deleted_by uuid null;

create index if not exists idx_customer_family_discount_customer
  on public.customer_family_discount(customer_party_id);
create index if not exists idx_customer_family_discount_family
  on public.customer_family_discount(product_family_id);
create index if not exists idx_product_customer_discount_customer
  on public.product_customer_discount(customer_party_id);
create index if not exists idx_product_customer_discount_product
  on public.product_customer_discount(product_id);
create index if not exists idx_product_customer_discount_deleted_at
  on public.product_customer_discount(deleted_at);
