-- ONIN: reserva, consumo y remanentes de stock dimensional.
-- Principio: la reserva selecciona piezas físicas concretas; el consumo transforma una pieza cortable
-- en consumo + remanente (o scrap) de forma atómica.

create table if not exists public.stock_reservation_item (
  id bigint generated by default as identity primary key,
  reservation_id bigint not null references public.stock_reservation(id) on delete cascade,
  stock_item_id bigint not null references public.warehouse_stock_item(id),
  allocated_quantity numeric not null default 1,
  requested_dimension_values jsonb not null default '[]'::jsonb,
  remaining_dimension_values jsonb not null default '[]'::jsonb,
  status varchar not null default 'RESERVED',
  consumed_at timestamptz null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint stock_reservation_item_quantity_check check (allocated_quantity > 0),
  constraint stock_reservation_item_status_check check (status in ('RESERVED','CONSUMED','RELEASED')),
  constraint stock_reservation_item_requested_dims_check check (jsonb_typeof(requested_dimension_values) = 'array'),
  constraint stock_reservation_item_remaining_dims_check check (jsonb_typeof(remaining_dimension_values) = 'array')
);
create index if not exists idx_stock_reservation_item_reservation on public.stock_reservation_item(reservation_id,status);
create index if not exists idx_stock_reservation_item_stock on public.stock_reservation_item(stock_item_id,status);

insert into public.stock_movement_type (company_id,code,name,direction,active)
select c.id,v.code,v.name,v.direction,true
from public.company c
cross join (values
  ('DIMENSIONAL_CONSUMPTION','Consumo de stock dimensional',-1),
  ('DIMENSIONAL_REMNANT','Alta de remanente dimensional',1),
  ('DIMENSIONAL_SCRAP','Merma de corte dimensional',-1)
) v(code,name,direction)
where not exists (
  select 1 from public.stock_movement_type t
  where t.company_id=c.id and t.code=v.code
);

create or replace function public.reserve_dimensional_stock(
  p_company_id bigint,
  p_warehouse_id bigint,
  p_product_id bigint,
  p_quantity numeric,
  p_characteristic_id bigint default null,
  p_dimension_values jsonb default '[]'::jsonb,
  p_reference varchar default null,
  p_notes text default null
) returns bigint
language plpgsql
security invoker
as $$
declare
  v_product public.product%rowtype;
  v_family public.product_family%rowtype;
  v_reservation_id bigint;
  v_needed integer;
  v_allocated integer := 0;
  v_item record;
  v_source_dims jsonb;
  v_source_len numeric;
  v_requested_len numeric;
  v_remaining numeric;
  v_recuttable boolean := false;
  v_minimum_remainder numeric := 0;
begin
  if p_quantity is null or p_quantity <= 0 then raise exception 'La cantidad a reservar debe ser mayor que cero'; end if;
  if p_dimension_values is null or jsonb_typeof(p_dimension_values) <> 'array' then raise exception 'Las dimensiones solicitadas deben ser un array JSON'; end if;

  select * into v_product from public.product where id=p_product_id and company_id=p_company_id and deleted_at is null and active=true;
  if not found then raise exception 'El artículo no existe o no está activo'; end if;
  if not v_product.stock_enabled then raise exception 'El artículo no tiene la gestión de stock activada'; end if;
  if not v_product.include_measurements_in_stock then raise exception 'El artículo no tiene activado el control de stock dimensional'; end if;

  if v_product.family_id is not null then
    select * into v_family from public.product_family where id=v_product.family_id and deleted_at is null;
    if found then
      v_recuttable := coalesce(v_family.recuttable,false);
      v_minimum_remainder := coalesce(v_product.minimum_remainder,v_family.minimum_remainder,0);
    end if;
  end if;

  if p_characteristic_id is not null then
    perform 1 from public.product_characteristic pc where pc.id=p_characteristic_id and pc.product_id=p_product_id and pc.deleted_at is null and pc.active=true;
    if not found then raise exception 'La característica no pertenece al artículo o no está activa'; end if;
  elsif v_product.include_stock_by_color then
    raise exception 'El artículo requiere característica para reservar stock dimensional';
  end if;

  if v_recuttable then
    if jsonb_array_length(p_dimension_values) <> 1 then
      raise exception 'El corte automático de remanentes requiere actualmente un único eje dimensional. Las piezas multidimensionales requieren una regla de corte específica';
    end if;
    v_requested_len := (p_dimension_values->>0)::numeric;
    if v_requested_len <= 0 then raise exception 'La dimensión solicitada debe ser mayor que cero'; end if;
  end if;

  v_needed := ceil(p_quantity);
  if p_quantity <> v_needed then raise exception 'El stock dimensional se reserva por piezas físicas completas'; end if;

  insert into public.stock_reservation(company_id,warehouse_id,product_id,characteristic_id,quantity,reference,notes,status,dimension_values)
  values(p_company_id,p_warehouse_id,p_product_id,p_characteristic_id,p_quantity,p_reference,p_notes,'ACTIVE',p_dimension_values)
  returning id into v_reservation_id;

  if v_recuttable then
    for v_item in
      select wsi.id,wsi.warehouse_stock_id,wsi.product_id,wsi.characteristic_id,wsi.quantity,wsi.dimension_values
      from public.warehouse_stock_item wsi
      join public.warehouse_stock ws on ws.id=wsi.warehouse_stock_id
      where ws.warehouse_id=p_warehouse_id
        and wsi.product_id=p_product_id
        and wsi.characteristic_id is not distinct from p_characteristic_id
        and wsi.status='AVAILABLE'
        and jsonb_array_length(wsi.dimension_values)=1
        and (wsi.dimension_values->>0)::numeric >= v_requested_len
      order by (wsi.dimension_values->>0)::numeric asc,wsi.id
      for update of wsi skip locked
      limit v_needed
    loop
      v_source_dims := v_item.dimension_values;
      v_source_len := (v_source_dims->>0)::numeric;
      v_remaining := v_source_len-v_requested_len;
      insert into public.stock_reservation_item(reservation_id,stock_item_id,allocated_quantity,requested_dimension_values,remaining_dimension_values,status)
      values(v_reservation_id,v_item.id,1,p_dimension_values,case when v_remaining>0 then jsonb_build_array(v_remaining) else '[]'::jsonb end,'RESERVED');
      update public.warehouse_stock_item set status='RESERVED',updated_at=now() where id=v_item.id;
      update public.warehouse_stock set reserved_quantity=reserved_quantity+1,updated_at=now() where id=v_item.warehouse_stock_id;
      v_allocated := v_allocated+1;
    end loop;
  else
    for v_item in
      select wsi.id,wsi.warehouse_stock_id,wsi.product_id,wsi.characteristic_id,wsi.quantity,wsi.dimension_values
      from public.warehouse_stock_item wsi
      join public.warehouse_stock ws on ws.id=wsi.warehouse_stock_id
      where ws.warehouse_id=p_warehouse_id
        and wsi.product_id=p_product_id
        and wsi.characteristic_id is not distinct from p_characteristic_id
        and wsi.status='AVAILABLE'
        and wsi.dimension_values = p_dimension_values
      order by wsi.id
      for update of wsi skip locked
      limit v_needed
    loop
      insert into public.stock_reservation_item(reservation_id,stock_item_id,allocated_quantity,requested_dimension_values,remaining_dimension_values,status)
      values(v_reservation_id,v_item.id,1,p_dimension_values,'[]'::jsonb,'RESERVED');
      update public.warehouse_stock_item set status='RESERVED',updated_at=now() where id=v_item.id;
      update public.warehouse_stock set reserved_quantity=reserved_quantity+1,updated_at=now() where id=v_item.warehouse_stock_id;
      v_allocated := v_allocated+1;
    end loop;
  end if;

  if v_allocated < v_needed then
    update public.warehouse_stock_item wsi
      set status='AVAILABLE',updated_at=now()
      where wsi.id in (select sri.stock_item_id from public.stock_reservation_item sri where sri.reservation_id=v_reservation_id);
    update public.warehouse_stock ws
      set reserved_quantity=greatest(0,ws.reserved_quantity-v_allocated),updated_at=now()
      where ws.id in (select wsi.warehouse_stock_id from public.warehouse_stock_item wsi join public.stock_reservation_item sri on sri.stock_item_id=wsi.id where sri.reservation_id=v_reservation_id);
    delete from public.stock_reservation_item where reservation_id=v_reservation_id;
    update public.stock_reservation set status='RELEASED',updated_at=now() where id=v_reservation_id;
    raise exception 'Stock dimensional insuficiente. Solicitadas: %, asignadas: %',v_needed,v_allocated;
  end if;

  return v_reservation_id;
end;
$$;

create or replace function public.release_dimensional_stock_reservation(p_reservation_id bigint)
returns void
language plpgsql
security invoker
as $$
declare v_res public.stock_reservation%rowtype; v_item record;
begin
  select * into v_res from public.stock_reservation where id=p_reservation_id for update;
  if not found then raise exception 'Reserva no encontrada'; end if;
  if v_res.status<>'ACTIVE' then return; end if;
  for v_item in select sri.stock_item_id,wsi.warehouse_stock_id from public.stock_reservation_item sri join public.warehouse_stock_item wsi on wsi.id=sri.stock_item_id where sri.reservation_id=p_reservation_id and sri.status='RESERVED' for update of wsi loop
    update public.warehouse_stock_item set status='AVAILABLE',updated_at=now() where id=v_item.stock_item_id;
    update public.warehouse_stock set reserved_quantity=greatest(0,reserved_quantity-1),updated_at=now() where id=v_item.warehouse_stock_id;
    update public.stock_reservation_item set status='RELEASED',updated_at=now() where reservation_id=p_reservation_id and stock_item_id=v_item.stock_item_id and status='RESERVED';
  end loop;
  update public.stock_reservation set status='RELEASED',updated_at=now() where id=p_reservation_id;
end;
$$;

create or replace function public.consume_dimensional_stock_reservation(p_reservation_id bigint)
returns void
language plpgsql
security invoker
as $$
declare
  v_res public.stock_reservation%rowtype;
  v_product public.product%rowtype;
  v_family public.product_family%rowtype;
  v_item record;
  v_stock public.warehouse_stock%rowtype;
  v_type public.stock_movement_type%rowtype;
  v_source_dims jsonb;
  v_remaining_dims jsonb;
  v_remaining numeric;
  v_minimum_remainder numeric := 0;
  v_recuttable boolean := false;
  v_new_item_id bigint;
  v_movement_id bigint;
begin
  select * into v_res from public.stock_reservation where id=p_reservation_id for update;
  if not found then raise exception 'Reserva no encontrada'; end if;
  if v_res.status<>'ACTIVE' then return; end if;
  select * into v_product from public.product where id=v_res.product_id and deleted_at is null;
  if not found then raise exception 'El artículo de la reserva no existe'; end if;
  if v_product.family_id is not null then
    select * into v_family from public.product_family where id=v_product.family_id and deleted_at is null;
    if found then
      v_recuttable:=coalesce(v_family.recuttable,false);
      v_minimum_remainder:=coalesce(v_product.minimum_remainder,v_family.minimum_remainder,0);
    end if;
  end if;

  select * into v_type from public.stock_movement_type where company_id=v_res.company_id and code='DIMENSIONAL_CONSUMPTION' and active=true;
  if not found then raise exception 'No existe el tipo de movimiento DIMENSIONAL_CONSUMPTION'; end if;

  for v_item in
    select sri.id sri_id,sri.stock_item_id,sri.requested_dimension_values,sri.remaining_dimension_values,
           wsi.warehouse_stock_id,wsi.product_id,wsi.characteristic_id,wsi.dimension_values,wsi.status
    from public.stock_reservation_item sri
    join public.warehouse_stock_item wsi on wsi.id=sri.stock_item_id
    where sri.reservation_id=p_reservation_id and sri.status='RESERVED'
    for update of sri,wsi
  loop
    if v_item.status<>'RESERVED' then raise exception 'La existencia % ya no está reservada',v_item.stock_item_id; end if;
    v_source_dims:=v_item.dimension_values;
    v_remaining_dims:=v_item.remaining_dimension_values;

    select * into v_stock from public.warehouse_stock where id=v_item.warehouse_stock_id for update;
    if not found then raise exception 'No existe el saldo agregado del stock %',v_item.warehouse_stock_id; end if;

    insert into public.stock_movement(company_id,warehouse_id,product_id,movement_type_id,characteristic_id,quantity,movement_date,reference,notes,dimension_values)
    values(v_res.company_id,v_res.warehouse_id,v_res.product_id,v_type.id,v_res.characteristic_id,1,now(),v_res.reference,coalesce(v_res.notes,'Consumo dimensional'),v_item.requested_dimension_values)
    returning id into v_movement_id;

    update public.warehouse_stock_item set status='CONSUMED',updated_at=now(),source_stock_movement_id=v_movement_id where id=v_item.stock_item_id;
    update public.warehouse_stock set quantity=greatest(0,quantity-1),reserved_quantity=greatest(0,reserved_quantity-1),updated_at=now() where id=v_item.warehouse_stock_id;

    if v_recuttable and jsonb_array_length(v_remaining_dims)=1 then
      v_remaining:=(v_remaining_dims->>0)::numeric;
      if v_remaining >= v_minimum_remainder and v_remaining > 0 then
        insert into public.warehouse_stock_item(warehouse_stock_id,product_id,characteristic_id,quantity,dimension_values,status,parent_stock_item_id,source_stock_movement_id)
        values(v_item.warehouse_stock_id,v_item.product_id,v_item.characteristic_id,1,v_remaining_dims,'AVAILABLE',v_item.stock_item_id,null)
        returning id into v_new_item_id;

        select * into v_type from public.stock_movement_type where company_id=v_res.company_id and code='DIMENSIONAL_REMNANT' and active=true;
        if not found then raise exception 'No existe el tipo de movimiento DIMENSIONAL_REMNANT'; end if;
        insert into public.stock_movement(company_id,warehouse_id,product_id,movement_type_id,characteristic_id,quantity,movement_date,reference,notes,dimension_values)
        values(v_res.company_id,v_res.warehouse_id,v_res.product_id,v_type.id,v_res.characteristic_id,1,now(),v_res.reference,format('Remanente de %s',v_item.stock_item_id),v_remaining_dims)
        returning id into v_movement_id;
        update public.warehouse_stock_item set source_stock_movement_id=v_movement_id where id=v_new_item_id;
        update public.warehouse_stock set quantity=quantity+1,updated_at=now() where id=v_item.warehouse_stock_id;
      else
        select * into v_type from public.stock_movement_type where company_id=v_res.company_id and code='DIMENSIONAL_SCRAP' and active=true;
        if not found then raise exception 'No existe el tipo de movimiento DIMENSIONAL_SCRAP'; end if;
        insert into public.stock_movement(company_id,warehouse_id,product_id,movement_type_id,characteristic_id,quantity,movement_date,reference,notes,dimension_values)
        values(v_res.company_id,v_res.warehouse_id,v_res.product_id,v_type.id,v_res.characteristic_id,1,now(),v_res.reference,format('Scrap de remanente de %s',v_item.stock_item_id),v_remaining_dims);
      end if;
    end if;

    update public.stock_reservation_item set status='CONSUMED',consumed_at=now(),updated_at=now() where id=v_item.sri_id;
  end loop;

  update public.stock_reservation set status='CONSUMED',updated_at=now() where id=p_reservation_id;
end;
$$;
