ALTER TABLE public.otd
  ADD COLUMN IF NOT EXISTS product_id bigint NULL REFERENCES public.product(id);

CREATE INDEX IF NOT EXISTS idx_otd_product_id ON public.otd(product_id);

ALTER TABLE public.otd_breakdown
  ADD COLUMN IF NOT EXISTS component_type varchar(20) NOT NULL DEFAULT 'BASIC',
  ADD COLUMN IF NOT EXISTS price_increment numeric(14,4) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS dimension_expressions jsonb NOT NULL DEFAULT '{}'::jsonb,
  ADD COLUMN IF NOT EXISTS active boolean NOT NULL DEFAULT true;

ALTER TABLE public.otd_breakdown
  DROP CONSTRAINT IF EXISTS chk_otd_breakdown_component_type;
ALTER TABLE public.otd_breakdown
  ADD CONSTRAINT chk_otd_breakdown_component_type CHECK (component_type IN ('BASIC','IMPROVEMENT'));

CREATE INDEX IF NOT EXISTS idx_otd_breakdown_otd_sort ON public.otd_breakdown(otd_id, sort_order);

CREATE TABLE IF NOT EXISTS public.otd_rule (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  otd_id bigint NOT NULL REFERENCES public.otd(id) ON DELETE CASCADE,
  name varchar(160) NOT NULL,
  condition_expression text NOT NULL,
  action_type varchar(40) NOT NULL,
  action_value jsonb NOT NULL DEFAULT '{}'::jsonb,
  sort_order integer NOT NULL DEFAULT 0,
  active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_otd_rule_otd_sort ON public.otd_rule(otd_id, sort_order);

ALTER TABLE public.otd_rule
  DROP CONSTRAINT IF EXISTS chk_otd_rule_action_type;
ALTER TABLE public.otd_rule
  ADD CONSTRAINT chk_otd_rule_action_type CHECK (action_type IN ('ADD_COMPONENT','SET_QUANTITY','SET_PRODUCT','VALIDATE'));
