create table if not exists public.product_control_type (
  id bigint generated by default as identity primary key,
  company_id bigint not null references public.company(id),
  code varchar not null,
  name varchar not null,
  active boolean not null default true,
  deleted_at timestamptz,
  deleted_by uuid,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.product_mounting_type (
  id bigint generated by default as identity primary key,
  company_id bigint not null references public.company(id),
  code varchar not null,
  name varchar not null,
  active boolean not null default true,
  deleted_at timestamptz,
  deleted_by uuid,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.product_family
  add column if not exists product_type_id bigint references public.product_type(id),
  add column if not exists control_type_id bigint references public.product_control_type(id),
  add column if not exists mounting_type_id bigint references public.product_mounting_type(id),
  add column if not exists minimum_remainder numeric,
  add column if not exists recuttable boolean not null default false;

create index if not exists idx_product_control_type_company on public.product_control_type(company_id, active);
create index if not exists idx_product_mounting_type_company on public.product_mounting_type(company_id, active);
create index if not exists idx_product_family_product_type on public.product_family(product_type_id);
create index if not exists idx_product_family_control_type on public.product_family(control_type_id);
create index if not exists idx_product_family_mounting_type on public.product_family(mounting_type_id);
