create table if not exists public.product_line_behavior (
  id bigint generated by default as identity primary key,
  company_id bigint not null references public.company(id),
  code varchar not null,
  name varchar not null,
  description varchar,
  quantity_enabled boolean not null default true,
  price_enabled boolean not null default true,
  discount_enabled boolean not null default true,
  dimensions_enabled boolean not null default false,
  configuration_enabled boolean not null default false,
  cut_calculation_enabled boolean not null default false,
  length_enabled boolean not null default false,
  characteristics_enabled boolean not null default false,
  canvas_cut_enabled boolean not null default false,
  active boolean not null default true,
  deleted_at timestamptz,
  deleted_by uuid,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint uq_product_line_behavior_company_code unique(company_id, code)
);

alter table public.product_family
  add column if not exists line_behavior_id bigint references public.product_line_behavior(id);

create index if not exists idx_product_line_behavior_company on public.product_line_behavior(company_id, active);
create index if not exists idx_product_family_line_behavior on public.product_family(line_behavior_id);
