import { useEffect, useMemo, useState } from 'react';
import { Check, FileText, PackageSearch, Ruler, Scissors, SlidersHorizontal, X, ClipboardCheck, Play } from 'lucide-react';
import { CoreRepositoryError } from '../../services/core/coreRepository';
import { createLonaConfectionWorkSheet, resolveLonaConfectionComponents, type LonaConfectionResult, type LonaConfectionWorkSheet, type LonaStockCandidate } from '../../services/production/lonaConfectionService';
import { findLonaStockCandidates } from '../../services/production/lonaStockSelectionService';
import { executeLonaConfectionWorkSheet } from '../../services/production/lonaConfectionExecutionService';
import { downloadLonaConfectionPdf } from '../../services/production/lonaConfectionPdfService';
import './lona-confection.css';

type Props = { line:any; companyId:number; salesOrderId:number; reference?:string; onClose:()=>void };
type ManualValues={quantity:string;line:string;output:string};
function formatDimension(value:number|null,unit:string|null){return value==null?'—':`${value} ${unit||''}`.trim()}
function formatDimensions(values:number[],units:string[]){return values.map((value,index)=>formatDimension(value,units[index]??null)).join(' × ')}

export function LonaConfectionModal({line,companyId,salesOrderId,reference,onClose}:Props){
 const [result,setResult]=useState<LonaConfectionResult|null>(null);const[loading,setLoading]=useState(true);const[error,setError]=useState('');const[mode,setMode]=useState<'visual'|'manual'>('visual');const[manualValues,setManualValues]=useState<Record<number,ManualValues>>({});const[stockCandidates,setStockCandidates]=useState<Record<number,LonaStockCandidate[]>>({});const[stockLoading,setStockLoading]=useState<Record<number,boolean>>({});const[selectedStock,setSelectedStock]=useState<Record<number,number>>({});const[creating,setCreating]=useState<Record<number,boolean>>({});const[workSheets,setWorkSheets]=useState<Record<number,LonaConfectionWorkSheet>>({});const[createError,setCreateError]=useState<Record<number,string>>({});const[executing,setExecuting]=useState<Record<number,boolean>>({});const[executionError,setExecutionError]=useState<Record<number,string>>({});
 const snapshot=useMemo(()=>line?.specific_data?.configuration_snapshot||line?.specific_data?.otd_snapshot||null,[line]);
 useEffect(()=>{let active=true;setLoading(true);setError('');setMode('visual');setManualValues({});setResult(null);setStockCandidates({});setSelectedStock({});setWorkSheets({});setCreateError({});setExecuting({});setExecutionError({});if(!snapshot){setError('La línea de pedido no tiene un snapshot OTD disponible.');setLoading(false);return()=>{active=false}}resolveLonaConfectionComponents({companyId,orderLineId:Number(line.id),orderLineNo:Number(line.line_no),reference,snapshot}).then(value=>{if(active)setResult(value)}).catch(value=>{if(!active)return;setError(value instanceof CoreRepositoryError||value instanceof Error?value.message:'No se pudo preparar la confección de lona.')}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[companyId,line.id,line.line_no,reference,snapshot]);
 useEffect(()=>{if(!result)return;let active=true;result.components.forEach((component,index)=>{if(component.line==null||component.output==null||component.line<=0||component.output<=0)return;setStockLoading(previous=>({...previous,[index]:true}));findLonaStockCandidates({companyId,productId:component.productId,characteristicCode:component.sourceComponent.characteristic_code?String(component.sourceComponent.characteristic_code):null,requiredLine:component.line,requiredOutput:component.output,requiredLineUnit:component.lineUnit,requiredOutputUnit:component.outputUnit}).then(candidates=>{if(!active)return;setStockCandidates(previous=>({...previous,[index]:candidates}));if(candidates[0])setSelectedStock(previous=>({...previous,[index]:candidates[0].stockItemId}))}).catch(()=>{if(active)setStockCandidates(previous=>({...previous,[index]:[]}))}).finally(()=>{if(active)setStockLoading(previous=>({...previous,[index]:false}))})});return()=>{active=false}},[companyId,result]);
 const getManual=(index:number,component:LonaConfectionResult['components'][number]):ManualValues=>manualValues[index]??{quantity:String(component.quantity),line:component.line==null?'':String(component.line),output:component.output==null?'':String(component.output)};
 const updateManual=(index:number,key:keyof ManualValues,value:string)=>{const component=result?.components[index];if(!component)return;const current=getManual(index,component);setManualValues(previous=>({...previous,[index]:{...current,[key]:value}}))};
 const manualResult=useMemo(()=>{if(!result)return null;return{...result,components:result.components.map((component,index)=>{const values=manualValues[index];if(!values)return component;return{...component,quantity:Number(values.quantity)||0,line:values.line===''?null:Number(values.line),output:values.output===''?null:Number(values.output)}})} satisfies LonaConfectionResult},[manualValues,result]);
 const displayResult=mode==='manual'?manualResult:result;const manualHasErrors=Boolean(displayResult?.components.some(component=>component.quantity<=0||component.line==null||component.line<=0||component.output==null||component.output<=0));
 const createSheet=async(index:number)=>{const component=displayResult?.components[index];const candidates=stockCandidates[index]||[];const candidate=candidates.find(item=>item.stockItemId===selectedStock[index])||candidates[0];if(!component||!candidate)return;setCreating(previous=>({...previous,[index]:true}));setCreateError(previous=>({...previous,[index]:''}));try{const sheet=await createLonaConfectionWorkSheet({companyId,salesOrderId,salesOrderLineId:Number(line.id),salesOrderLineNo:Number(line.line_no),component,candidate,reference,selectionMode:mode==='manual'?'MANUAL':'AUTOMATIC',selectionReason:mode==='manual'?'Selección manual realizada por el usuario.':candidate.reason});setWorkSheets(previous=>({...previous,[index]:sheet}))}catch(value){setCreateError(previous=>({...previous,[index]:value instanceof Error?value.message:'No se pudo generar la hoja de confección.'}))}finally{setCreating(previous=>({...previous,[index]:false}))}};
 const executeSheet=async(index:number)=>{const sheet=workSheets[index];if(!sheet)return;setExecuting(previous=>({...previous,[index]:true}));setExecutionError(previous=>({...previous,[index]:''}));try{await executeLonaConfectionWorkSheet(sheet.id);setWorkSheets(previous=>({...previous,[index]:{...sheet,status:'COMPLETED'}}))}catch(value){setExecutionError(previous=>({...previous,[index]:value instanceof Error?value.message:'No se pudo ejecutar el corte de lona.'}))}finally{setExecuting(previous=>({...previous,[index]:false}))}};
 return <div className="lona-modal-backdrop" role="dialog" aria-modal="true"><div className="lona-modal"><header className="lona-modal-head"><div><span className="lona-eyebrow">FABRICACIÓN / CONFECCIÓN DE LONA</span><h2>Línea {line.line_no} · {line.description||'Confección'}</h2><p>Onin calcula la necesidad desde el OTD y propone automáticamente el material compatible. El modo manual permite cambiar la decisión.</p></div><button type="button" className="lona-close" onClick={onClose} aria-label="Cerrar"><X size={18}/></button></header>
 {loading?<div className="lona-empty">Analizando componentes del OTD…</div>:error?<div className="lona-error">{error}</div>:displayResult?<><div className="lona-toolbar"><div className="lona-mode-switch" role="tablist" aria-label="Modo de confección"><button type="button" className={mode==='visual'?'active':''} onClick={()=>setMode('visual')} role="tab" aria-selected={mode==='visual'}><Ruler size={15}/> Visual</button><button type="button" className={mode==='manual'?'active':''} onClick={()=>setMode('manual')} role="tab" aria-selected={mode==='manual'}><SlidersHorizontal size={15}/> Manual</button></div><div className="lona-auto-status"><Check size={14}/> {mode==='visual'?'Propuesta automática':'Edición manual'}</div></div>
 <div className="lona-summary"><div><span>Pedido</span><strong>{displayResult.reference||'—'}</strong></div><div><span>OTD</span><strong>{displayResult.otdCode||'—'}</strong></div><div><span>Componentes confeccionables</span><strong>{displayResult.components.length}</strong></div></div>
 <div className="lona-content">{displayResult.components.map((component,index)=>{const manual=getManual(index,component);const width=mode==='manual'?(manual.line===''?null:Number(manual.line)):component.line;const height=mode==='manual'?(manual.output===''?null:Number(manual.output)):component.output;const ratio=width&&height?width/height:1;const visualWidth=ratio>=1?360:Math.max(140,360*ratio);const visualHeight=ratio>=1?Math.max(100,360/ratio):260;const lineLabel=component.lineDimensionCode||'Línea';const outputLabel=component.outputDimensionCode||'Salida';const candidates=stockCandidates[index]||[];const chosenId=selectedStock[index]??candidates[0]?.stockItemId;const chosen=candidates.find(candidate=>candidate.stockItemId===chosenId);const materialLoading=Boolean(stockLoading[index]);const sheet=workSheets[index];const isCreating=Boolean(creating[index]);const isExecuting=Boolean(executing[index]);return <section className="lona-cut-card" key={`${component.productId}-${index}`}><div className="lona-cut-info"><div className="lona-cut-title"><div><strong>{component.productCode}</strong><span>{component.productName}</span></div><span className="lona-chip">CONFECCIONABLE</span></div>
 {mode==='visual'?<div className="lona-data-grid"><div><span>Cantidad</span><strong>{component.quantity}</strong></div><div><span>{lineLabel}</span><strong>{formatDimension(width,component.lineUnit)}</strong></div><div><span>{outputLabel}</span><strong>{formatDimension(height,component.outputUnit)}</strong></div><div><span>Característica</span><strong>{component.characteristicName||'—'}</strong></div></div>:<div className="lona-manual-grid"><label><span>Cantidad</span><input inputMode="decimal" value={manual.quantity} onChange={event=>updateManual(index,'quantity',event.target.value)}/></label><label><span>{lineLabel}</span><div className="lona-input-unit"><input inputMode="decimal" value={manual.line} onChange={event=>updateManual(index,'line',event.target.value)}/><em>{component.lineUnit||''}</em></div></label><label><span>{outputLabel}</span><div className="lona-input-unit"><input inputMode="decimal" value={manual.output} onChange={event=>updateManual(index,'output',event.target.value)}/><em>{component.outputUnit||''}</em></div></label><div className="lona-manual-readonly"><span>Característica</span><strong>{component.characteristicName||'—'}</strong></div></div>}
 <div className={`lona-material ${chosen?'ready':''}`}><div className="lona-material-head"><div><span>Material</span><strong>{materialLoading?'Buscando material compatible…':chosen?`${chosen.warehouseCode} · ${formatDimensions(chosen.sourceDimensions,chosen.sourceDimensionUnits)}`:'Sin material compatible'}</strong></div>{chosen&&<span className="lona-material-badge"><Check size={12}/> Recomendado</span>}</div>{chosen?<><div className="lona-material-detail"><span>{chosen.reason}</span><strong>Corte {formatDimensions(chosen.cutDimensions,chosen.cutDimensionUnits)} · Resto {chosen.remainderDimensions?formatDimensions(chosen.remainderDimensions,chosen.remainderDimensionUnits):'—'}</strong></div>{mode==='manual'&&candidates.length>1&&<div className="lona-material-options">{candidates.slice(0,4).map(candidate=><button type="button" key={candidate.stockItemId} className={candidate.stockItemId===chosen.stockItemId?'selected':''} onClick={()=>setSelectedStock(previous=>({...previous,[index]:candidate.stockItemId}))}><PackageSearch size={13}/><span>{candidate.warehouseCode} · {formatDimensions(candidate.sourceDimensions,candidate.sourceDimensionUnits)}</span><small>{candidate.rotated?'Girado':'Directo'}</small></button>)}</div>}</>:!materialLoading&&<span className="lona-material-empty">No hay una existencia dimensional disponible que pueda satisfacer estas dimensiones.</span>}</div>
 {createError[index]&&<div className="lona-error lona-error-inline">{createError[index]}</div>}{executionError[index]&&<div className="lona-error lona-error-inline">{executionError[index]}</div>}
 {sheet?<div className="lona-sheet-ready"><div><ClipboardCheck size={15}/><span>Hoja de confección <strong>{sheet.code}</strong></span></div><small>{sheet.status==='COMPLETED'?'Corte ejecutado y stock actualizado.':'La hoja conserva la propuesta y el material seleccionado. El stock todavía no se consume.'}</small>{sheet.status==='ISSUED'&&<button type="button" className="lona-create-sheet" disabled={isExecuting} onClick={()=>void executeSheet(index)}><Play size={14}/>{isExecuting?'Ejecutando corte…':'Ejecutar corte de lona'}</button>}</div>:<button type="button" className="lona-create-sheet" disabled={!chosen||manualHasErrors||isCreating} onClick={()=>void createSheet(index)}><ClipboardCheck size={15}/>{isCreating?'Generando hoja…':'Generar hoja de confección'}</button>}
 {mode==='manual'&&<div className="lona-manual-note"><Scissors size={14}/> Los cambios afectan a la propuesta y al informe. La generación de la hoja todavía no consume stock.</div>}</div>
 <div className="lona-diagram-wrap"><div className="lona-diagram-label"><Ruler size={13}/> {chosen?'Propuesta de aprovechamiento':mode==='visual'?'Vista previa dimensional':'Previsualización manual'}</div>{width&&height&&Number.isFinite(width)&&Number.isFinite(height)?<div className="lona-diagram-stage"><div className="lona-diagram-piece" style={{width:visualWidth,height:visualHeight}}><span>{formatDimension(width,component.lineUnit)}</span><b>{formatDimension(height,component.outputUnit)}</b></div>{chosen&&<div className="lona-diagram-caption">{chosen.rotated?'Pieza girada para aprovechar el material':'Orientación original'} · resto previsto {chosen.remainderDimensions?formatDimensions(chosen.remainderDimensions,chosen.remainderDimensionUnits):'—'}</div>}</div>:<div className="lona-diagram-empty">Se necesitan dos dimensiones válidas para representar el corte.</div>}</div></section>})}</div>
 <footer className="lona-modal-actions"><button type="button" className="secondary-button" onClick={()=>displayResult&&!manualHasErrors&&downloadLonaConfectionPdf(displayResult)} disabled={manualHasErrors}><FileText size={15}/> Generar informe de corte</button><button type="button" className="primary-button" onClick={onClose}>Cerrar</button></footer></>:null}</div></div>;
}