import { useEffect, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { ArrowLeft, FileText, Scissors, Hammer, Boxes, CheckCircle2, Receipt, Truck, Eye, CalendarClock, Plus } from 'lucide-react';
import { getSalesOrder, type SalesOrder } from '../../services/sales/salesOrderService';
import { CoreRepositoryError, getUserDisplayNames } from '../../services/core/coreRepository';
import { getWorkSheetsBySalesOrderLine, type WorkSheet } from '../../services/production/workSheetService';
import { getLonaConfectionWorkSheetBySalesOrderLine, type LonaConfectionWorkSheet } from '../../services/production/lonaConfectionQueryService';
import { getComponentConsumptionWorkSheetBySalesOrderLine, resolveOrderLineComponents, type ComponentConsumptionWorkSheet } from '../../services/production/componentConsumptionService';
import { checkAndMarkOrderManufactured } from '../../services/production/orderFabricationService';
import {
  INSTALLATION_STATUS_LABEL,
  INSTALLATION_STATUS_TONE,
  listInstallationsBySalesOrder,
  listInstallationTypes,
  listInstallers,
  type Installation,
  type InstallationType,
  type Installer,
} from '../../services/production/installationService';
import { ProfileCutModal } from './ProfileCutModal';
import { isProfileComponent, isFabricOrLonaComponent } from '../../services/catalog/componentClassification';
import { LonaConfectionModal } from './LonaConfectionModal';
import { LonaConfectionViewModal } from './LonaConfectionViewModal';
import { ComponentConsumptionModal } from './ComponentConsumptionModal';
import { OrderFabricationModal } from './OrderFabricationModal';
import { InstallationModal, type InstallableLine } from './InstallationModal';
import { RegisterLineDeliveryModal } from './RegisterLineDeliveryModal';
import { SalesOrderProductionSheetsModal } from './SalesOrderProductionSheetsModal';
import { LineActionsMenu, type LineActionMenuItem } from './LineActionsMenu';
import { SalesOrderLifecycleStepper, SalesOrderLifecycleHistory } from './SalesOrderLifecycle';
import { QuotationLineSnapshotModal } from '../quotations/QuotationLineSnapshotModal';
import { listSalesOrderComments, type SalesOrderComment } from '../../services/sales/salesOrderCommentService';
import { CommentsPanel } from '../quotations/CommentsPanel';
import { getInvoiceBySalesOrderId, createInvoiceFromSalesOrder, type Invoice } from '../../services/sales/invoiceService';
import {
  listDeliveryNotesBySalesOrderId,
  getSalesOrderDeliveryStatus,
  createDeliveryNoteForAllRemainingSimpleLines,
  type DeliveryNote,
  type SalesOrderLineDeliveryStatus,
} from '../../services/sales/deliveryNoteService';
import { SalesOrderDeliveryNoteModal } from './SalesOrderDeliveryNoteModal';
import './sales-order.css';
import './sales-order-cut.css';
import './lona-confection.css';

const statusLabel: Record<string, string> = { PENDING_MANUFACTURING:'Pendiente de fabricación', PREPARED:'Preparado', FABRICATING:'Fabricando', CONFECTIONED:'Confeccionado', MANUFACTURED:'Fabricado', INSTALLATION_SCHEDULED:'Montaje programado', INSTALLED:'Instalado', INVOICED:'Facturado', CANCELLED:'Cancelado' };
const date=(v:string|null)=>(v?new Date(`${v}T00:00:00`).toLocaleDateString('es-ES'):'—');

export function SalesOrderDetail(){
 const{id}=useParams();const[data,setData]=useState<SalesOrder|null>(null);const[loading,setLoading]=useState(true);const[error,setError]=useState('');const[cutLine,setCutLine]=useState<any|null>(null);const[lonaLine,setLonaLine]=useState<any|null>(null);const[lonaViewLine,setLonaViewLine]=useState<any|null>(null);const[componentsLine,setComponentsLine]=useState<any|null>(null);const[cutSheets,setCutSheets]=useState<Record<number,WorkSheet[]>>({});const[lonaSheets,setLonaSheets]=useState<Record<number,LonaConfectionWorkSheet>>({});const[componentSheets,setComponentSheets]=useState<Record<number,ComponentConsumptionWorkSheet>>({});const[otdSnapshot,setOtdSnapshot]=useState<any|null>(null);const[otdLineNo,setOtdLineNo]=useState(1);const[productionSheetsOpen,setProductionSheetsOpen]=useState(false);const[fabricationOpen,setFabricationOpen]=useState(false);const[comments,setComments]=useState<SalesOrderComment[]>([]);const[invoice,setInvoice]=useState<Invoice|null>(null);const[generatingInvoice,setGeneratingInvoice]=useState(false);const[invoiceError,setInvoiceError]=useState('');
 const[installations,setInstallations]=useState<Installation[]>([]);const[installationTypes,setInstallationTypes]=useState<InstallationType[]>([]);const[installers,setInstallers]=useState<Installer[]>([]);const[installationModalTarget,setInstallationModalTarget]=useState<Installation|'new'|null>(null);
 const[deliveryNotes,setDeliveryNotes]=useState<DeliveryNote[]>([]);const[deliveryStatus,setDeliveryStatus]=useState<SalesOrderLineDeliveryStatus[]>([]);const[viewingDeliveryNote,setViewingDeliveryNote]=useState<DeliveryNote|null>(null);const[generatingDelivery,setGeneratingDelivery]=useState(false);const[deliveryError,setDeliveryError]=useState('');const[deliveringLine,setDeliveringLine]=useState<{id:number;lineNo:number;description:string;remaining:number}|null>(null);
 const[creatorNames,setCreatorNames]=useState<Record<string,string>>({});

 const refreshManufacturedStatus=async()=>{if(!data)return;try{const manufactured=await checkAndMarkOrderManufactured(data.id,data.lines||[]);if(manufactured)setData(current=>current?{...current,status:'MANUFACTURED'}:current);}catch{/* no bloquea el flujo si falla la comprobación */}};
 const generateInvoice=async()=>{if(!data)return;setGeneratingInvoice(true);setInvoiceError('');try{const created=await createInvoiceFromSalesOrder(data.id);setInvoice(created);}catch(e){setInvoiceError(e instanceof CoreRepositoryError?e.message:'No se pudo generar la factura.');}finally{setGeneratingInvoice(false);}};

 async function refreshDelivery(orderId:number){
  const[notes,status]=await Promise.all([listDeliveryNotesBySalesOrderId(orderId),getSalesOrderDeliveryStatus(orderId)]);
  setDeliveryNotes(notes);setDeliveryStatus(status);
 }
 async function refreshInstallations(orderId:number){setInstallations(await listInstallationsBySalesOrder(orderId));}

 const generateBulkDelivery=async()=>{if(!data)return;setGeneratingDelivery(true);setDeliveryError('');try{await createDeliveryNoteForAllRemainingSimpleLines(data.id);await refreshDelivery(data.id);}catch(e){setDeliveryError(e instanceof CoreRepositoryError?e.message:'No se pudo generar el albarán.');}finally{setGeneratingDelivery(false);}};

 useEffect(()=>{let active=true;(async()=>{try{const row=await getSalesOrder(Number(id));if(!active)return;if(!row){setData(null);setError('Pedido no encontrado.');return;}setData(row);void listSalesOrderComments(Number(row.id)).then(setComments).catch(()=>{});const companyIdValue=Number((row as any).company_id||0);const lines=row.lines||[];const sheets=await Promise.all(lines.map(async(line:any)=>[Number(line.id),await getWorkSheetsBySalesOrderLine(Number(line.id)).catch(()=>[])] as const));const lonaSheetsResult=await Promise.all(lines.map(async(line:any)=>[Number(line.id),await getLonaConfectionWorkSheetBySalesOrderLine(Number(line.id)).catch(()=>null)] as const));const componentSheetsResult=await Promise.all(lines.map(async(line:any)=>[Number(line.id),await getComponentConsumptionWorkSheetBySalesOrderLine(Number(line.id)).catch(()=>null)] as const));const[installationsResult,installationTypesResult,installersResult,invoiceResult,deliveryNotesResult,deliveryStatusResult]=await Promise.all([listInstallationsBySalesOrder(Number(row.id)).catch(()=>[]),listInstallationTypes(companyIdValue).catch(()=>[]),listInstallers(companyIdValue).catch(()=>[]),getInvoiceBySalesOrderId(Number(row.id)).catch(()=>null),listDeliveryNotesBySalesOrderId(Number(row.id)).catch(()=>[]),getSalesOrderDeliveryStatus(Number(row.id)).catch(()=>[])]);if(active){setCutSheets(Object.fromEntries(sheets.map(([lineId,lineSheets])=>[lineId,lineSheets as WorkSheet[]])));setLonaSheets(Object.fromEntries(lonaSheetsResult.filter(([,sheet])=>sheet).map(([lineId,sheet])=>[lineId,sheet as LonaConfectionWorkSheet])));setComponentSheets(Object.fromEntries(componentSheetsResult.filter(([,sheet])=>sheet).map(([lineId,sheet])=>[lineId,sheet as ComponentConsumptionWorkSheet])));setInstallations(installationsResult);setInstallationTypes(installationTypesResult);setInstallers(installersResult);setInvoice(invoiceResult);setDeliveryNotes(deliveryNotesResult);setDeliveryStatus(deliveryStatusResult);}}catch(e){if(active)setError(e instanceof CoreRepositoryError?e.message:'No se pudo cargar el pedido.');}finally{if(active)setLoading(false);}})();return()=>{active=false};},[id]);

 useEffect(()=>{const ids=[data?.created_by,...Object.values(cutSheets).flat().map(s=>s.created_by),...Object.values(lonaSheets).map(s=>s.createdBy),...Object.values(componentSheets).map(s=>s.createdBy),...installations.flatMap(i=>[i.createdBy,i.completedBy]),invoice?.created_by,...deliveryNotes.map(n=>n.created_by)];getUserDisplayNames(ids).then(setCreatorNames).catch(()=>{});},[data,cutSheets,lonaSheets,componentSheets,installations,invoice,deliveryNotes]);

 if(loading)return <div className="loading-block">Cargando pedido…</div>;if(error||!data)return <div className="module-page"><div className="inline-error">{error||'Pedido no encontrado.'}</div></div>;
 const canInvoice=['MANUFACTURED','INSTALLATION_SCHEDULED','INSTALLED','INVOICED'].includes(data.status);const canDeliver=['MANUFACTURED','INSTALLATION_SCHEDULED','INSTALLED','INVOICED'].includes(data.status);
 const companyId=Number((data as any).company_id||0);const orderWarehouseId=(data as any).warehouse_id==null?null:Number((data as any).warehouse_id);const allCutSheets=Object.values(cutSheets).flat();const allLonaSheets=Object.values(lonaSheets);const allComponentSheets=Object.values(componentSheets);const totalProductionSheets=allCutSheets.length+allLonaSheets.length+allComponentSheets.length;
 const statusByLine=new Map(deliveryStatus.map(s=>[s.salesOrderLineId,s]));
 const pendingSimpleLines=deliveryStatus.filter(s=>!s.isOtd&&s.remainingQuantity>0);
 const pendingDeliveryLines=deliveryStatus.filter(s=>s.remainingQuantity>0).length;
 const coveredLineIds=new Set(installations.filter(i=>i.status!=='CANCELLED').flatMap(i=>i.lineIds));
 const availableInstallLines:InstallableLine[]=deliveryStatus.filter(s=>s.isOtd&&s.remainingQuantity>0&&!coveredLineIds.has(s.salesOrderLineId)).map(s=>{const line=(data.lines||[]).find((l:any)=>Number(l.id)===s.salesOrderLineId);return{id:s.salesOrderLineId,lineNo:s.lineNo,label:line?.description||'Artículo'};});

 return <div className="module-page sales-order-detail-page">
  <div className="quotation-detail-head"><div className="quotation-detail-title"><div className="quotation-detail-nav-row"><Link className="secondary-button" to="/ventas/pedidos"><ArrowLeft size={15}/> Volver a pedidos</Link><span className="quotation-breadcrumb-code">Ventas / Pedidos / <strong>{data.code}</strong></span></div><div className="quotation-title-row"><h1>{data.code}</h1><span className={`quotation-status ${data.status.toLowerCase()}`}>{statusLabel[data.status]||data.status}</span></div><div className="quotation-subtitle-meta"><span>Presupuesto: <Link to={`/ventas/presupuestos/${data.quotation_id}`}>{data.quotation_code||data.quotation_id}</Link></span>{data.measurement_id&&<><span className="dot-sep">·</span><span>Medición: <Link to={`/gestion/mediciones/${data.measurement_id}`}>{data.measurement_id}</Link></span></>}</div></div></div>
  <SalesOrderLifecycleStepper order={data} cutSheets={allCutSheets} lonaSheets={allLonaSheets} componentSheets={allComponentSheets} installations={installations} invoice={invoice} pendingDeliveryLines={pendingDeliveryLines} totalDeliveryLines={deliveryStatus.length} onFabricate={()=>setFabricationOpen(true)} onInstall={()=>{const ongoing=installations.find(i=>i.status==='BLOCKED'||i.status==='IN_PROGRESS'||i.status==='SCHEDULED');setInstallationModalTarget(ongoing??'new');}} onInvoice={generateInvoice} onViewProductionSheets={()=>setProductionSheetsOpen(true)}/>
  <div className="quotation-section-grid"><section className="quotation-card"><h2>Cliente</h2><p className="detail-value">{data.customer_name||'—'}</p><div className="detail-grid"><div><span>Contacto</span><strong>{data.contact_name||'—'}</strong></div><div><span>Email</span><strong>{data.contact_email||'—'}</strong></div><div><span>Teléfono</span><strong>{data.contact_phone||'—'}</strong></div></div></section><section className="quotation-card"><h2>Datos del pedido</h2><div className="detail-grid"><div><span>Fecha</span><strong>{date(data.issue_date)}</strong></div><div><span>Entrega solicitada</span><strong>{date(data.requested_delivery_date)}</strong></div><div><span>Referencia</span><strong>{data.reference||'—'}</strong></div></div></section><section className="quotation-card"><h2>Facturación</h2>{invoiceError&&<div className="inline-error">{invoiceError}</div>}{invoice?<div className="detail-grid"><div><span>Factura</span><strong><Link to={`/facturacion/facturas/${invoice.id}`}>{invoice.code}</Link></strong></div><div><span>Estado</span><strong>Emitida</strong></div></div>:canInvoice?<button type="button" className="primary-button" disabled={generatingInvoice} onClick={generateInvoice}><Receipt size={15}/> {generatingInvoice?'Generando…':'Generar factura'}</button>:<p className="detail-value" style={{fontSize:'13px',color:'var(--muted)'}}>Disponible cuando el pedido esté fabricado.</p>}</section>{comments.some(c=>c.salesOrderLineId===null)&&<section className="quotation-card"><h2>Comentarios</h2><CommentsPanel readOnly comments={comments.filter(c=>c.salesOrderLineId===null).map(c=>({text:c.text,isPublic:c.isPublic}))}/></section>}</div>

  <section className="quotation-card"><h2>Montajes</h2><p className="detail-value" style={{fontSize:'13px',fontWeight:400,color:'var(--muted)',marginBottom:'12px'}}>Un pedido con varios toldos puede instalarse en varias visitas — cada una cubre las líneas que elijas.</p>
   {installations.length===0?<p className="detail-value" style={{fontSize:'13px',color:'var(--muted)'}}>{canDeliver?'Sin visitas programadas todavía.':'Disponible cuando el pedido esté fabricado.'}</p>:<div className="table-panel card-table"><table><thead><tr><th>Estado</th><th>Fecha</th><th>Líneas</th><th></th></tr></thead><tbody>{installations.map(inst=><tr key={inst.id}><td><span className={`status-pill ${INSTALLATION_STATUS_TONE[inst.status]}`}>{INSTALLATION_STATUS_LABEL[inst.status]}</span>{inst.incidents.some(i=>i.status==='OPEN')&&<span className="status-pill danger" style={{marginLeft:6}}>Incidencia abierta</span>}</td><td>{date(inst.scheduledDate)}{inst.startTime?` · ${inst.startTime}`:''}</td><td>{inst.lineIds.length} línea{inst.lineIds.length===1?'':'s'}</td><td><button type="button" className="secondary-button compact" onClick={()=>setInstallationModalTarget(inst)}><Eye size={14}/> {inst.status==='COMPLETED'||inst.status==='CANCELLED'?'Ver':'Gestionar'}</button></td></tr>)}</tbody></table></div>}
   {canDeliver&&availableInstallLines.length>0&&<div style={{marginTop:'12px'}}><button type="button" className="secondary-button" onClick={()=>setInstallationModalTarget('new')}><Plus size={14}/> Programar visita ({availableInstallLines.length} línea{availableInstallLines.length===1?'':'s'} pendiente{availableInstallLines.length===1?'':'s'})</button></div>}
  </section>

  <section className="quotation-card"><h2>Albaranes</h2>{deliveryError&&<div className="inline-error">{deliveryError}</div>}
   {deliveryNotes.length===0?<p className="detail-value" style={{fontSize:'13px',color:'var(--muted)'}}>Sin albaranes generados todavía.</p>:<div className="table-panel card-table"><table><thead><tr><th>Albarán</th><th>Estado</th><th></th></tr></thead><tbody>{deliveryNotes.map(n=><tr key={n.id}><td>{n.code}</td><td>{n.status}</td><td><button type="button" className="secondary-button compact" onClick={()=>setViewingDeliveryNote(n)}><Eye size={14}/> Consultar</button></td></tr>)}</tbody></table></div>}
   {canDeliver&&pendingSimpleLines.length>0&&<div style={{marginTop:'12px'}}><button type="button" className="primary-button" disabled={generatingDelivery} onClick={()=>void generateBulkDelivery()}><Truck size={15}/> {generatingDelivery?'Generando…':`Entregar todo lo pendiente (${pendingSimpleLines.length} línea${pendingSimpleLines.length===1?'':'s'} simple${pendingSimpleLines.length===1?'':'s'})`}</button></div>}
  </section>

  <section className="quotation-card"><h2>Líneas</h2><div className="table-panel card-table"><table><thead><tr><th>#</th><th>Artículo / descripción</th><th>Cantidad</th><th>Entrega</th><th>Acciones</th></tr></thead><tbody>{(data.lines||[]).map((l:any)=>{const snapshot=(l.specific_data?.configuration_snapshot||l.specific_data?.otd_snapshot) as any;const hasOtd=Boolean(snapshot?.otd_code||snapshot?.otd_id||snapshot?.inputs_display||snapshot?.components);const rawComponents=Array.isArray(snapshot?.components)?snapshot.components:[];const profileComponents=rawComponents.filter(isProfileComponent);const totalProfilesInLine=profileComponents.length>0?profileComponents.length:1;const lineSheets=cutSheets[Number(l.id)]||[];const lonaSheet=lonaSheets[Number(l.id)];const isFullyCut=lineSheets.length>0&&lineSheets.length>=totalProfilesInLine;const isPartiallyCut=lineSheets.length>0&&lineSheets.length<totalProfilesInLine;const isLona=Boolean(lonaSheet);const componentSheet=componentSheets[Number(l.id)];const hasComponents=rawComponents.some((c:any)=>c&&c.product_id!=null&&!isProfileComponent(c)&&!isFabricOrLonaComponent(c));const lineMenuItems:LineActionMenuItem[]=[];if(hasOtd)lineMenuItems.push({key:'otd',label:'Detalle OTD',icon:<FileText size={14}/>,title:'Ver configuración específica del OTD',onClick:()=>{setOtdSnapshot(snapshot);setOtdLineNo(Number(l.line_no)||1);}});if(isFullyCut)lineMenuItems.push({key:'cut',label:`Ver corte${totalProfilesInLine>1?'s':''}`,icon:<Hammer size={14}/>,title:'Visualizar los cortes de perfiles realizados',onClick:()=>setCutLine(l)});else lineMenuItems.push({key:'cut',label:'Corte perfil',icon:<Hammer size={14}/>,title:'Preparar corte de perfil',onClick:()=>setCutLine(l)});if(isLona)lineMenuItems.push({key:'lona',label:'Ver confección',icon:<Scissors size={14}/>,title:'Visualizar la confección previamente realizada',onClick:()=>setLonaViewLine(l)});else lineMenuItems.push({key:'lona',label:'Confección lona',icon:<Scissors size={14}/>,title:'Preparar confección de lona',onClick:()=>setLonaLine(l)});if(componentSheet)lineMenuItems.push({key:'components',label:'Ver componentes',icon:<Boxes size={14}/>,title:'Visualizar los componentes descontados',onClick:()=>setComponentsLine(l)});else if(hasComponents)lineMenuItems.push({key:'components',label:'Componentes',icon:<Boxes size={14}/>,title:'Descontar componentes por unidades (soportes, motores…)',onClick:()=>setComponentsLine(l)});
const lineComments=comments.filter(c=>c.salesOrderLineId===Number(l.id));
const delivery=statusByLine.get(Number(l.id));
const coveringInstallation=installations.find(inst=>inst.lineIds.includes(Number(l.id))&&inst.status!=='CANCELLED');
return <tr key={l.id}><td>{l.line_no}</td><td><strong>{l.description||'—'}</strong>{l.product_id&&<div className="muted">Artículo #{l.product_id}</div>}{snapshot?.otd_code&&<div className="muted">OTD: {snapshot.otd_code}</div>}{lineComments.length>0&&<CommentsPanel readOnly compact comments={lineComments.map(c=>({text:c.text,isPublic:c.isPublic}))}/>}</td><td>{l.quantity}</td><td>{!delivery?'—':delivery.remainingQuantity<=0?<span className="line-cut-status"><CheckCircle2 size={13}/> Entregado</span>:delivery.isOtd?coveringInstallation?<span className="line-cut-status partial"><CalendarClock size={13}/> Montaje {coveringInstallation.status==='SCHEDULED'?'programado':coveringInstallation.status}</span>:<span className="muted">Sin montaje asignado</span>:<span className="muted">{delivery.deliveredQuantity>0?`${delivery.deliveredQuantity} de ${delivery.quantity}`:'Pendiente'}</span>}</td><td><div className="quotation-line-actions-cell"><div className="quotation-line-status-badges">{isFullyCut&&<span className="line-cut-status" title={`Corte realizado (${lineSheets.length}/${totalProfilesInLine}): ${lineSheets.map(s=>s.code).join(', ')}`}><CheckCircle2 size={13}/> Cortada{totalProfilesInLine>1?` (${lineSheets.length}/${totalProfilesInLine})`:''}</span>}{isPartiallyCut&&<span className="line-cut-status partial"><Hammer size={13}/> Corte parcial ({lineSheets.length}/{totalProfilesInLine})</span>}{isLona&&<span className="line-cut-status" title={`Confección realizada: ${lonaSheet.code}`}><CheckCircle2 size={13}/> Confeccionada</span>}{componentSheet&&<span className="line-cut-status" title={`Componentes descontados: ${componentSheet.code}`}><CheckCircle2 size={13}/> Componentes</span>}{canDeliver&&delivery&&!delivery.isOtd&&delivery.remainingQuantity>0&&<button type="button" className="icon-link" title="Registrar entrega" onClick={()=>setDeliveringLine({id:Number(l.id),lineNo:Number(l.line_no),description:l.description||'Artículo',remaining:delivery.remainingQuantity})}><Truck size={13}/></button>}</div><LineActionsMenu items={lineMenuItems}/></div></td></tr>;})}</tbody></table></div></section>
  <SalesOrderLifecycleHistory order={data} cutSheets={allCutSheets} lonaSheets={allLonaSheets} componentSheets={allComponentSheets} installations={installations} invoice={invoice} deliveryNotes={deliveryNotes} creatorNames={creatorNames}/>
  {cutLine&&<ProfileCutModal line={cutLine} companyId={companyId} salesOrderId={data.id} reference={`${data.code} · Línea ${cutLine.line_no}`} onClose={async()=>{const lineId=Number(cutLine.id);setCutLine(null);const updatedSheets=await getWorkSheetsBySalesOrderLine(lineId).catch(()=>[]);setCutSheets(current=>({...current,[lineId]:updatedSheets}));await refreshManufacturedStatus();}}/>}
  {lonaLine&&<LonaConfectionModal line={lonaLine} companyId={companyId} salesOrderId={Number(data.id)} reference={`${data.code} · Línea ${lonaLine.line_no}`} onClose={async()=>{setLonaLine(null);const sheet=await getLonaConfectionWorkSheetBySalesOrderLine(Number(lonaLine.id)).catch(()=>null);if(sheet)setLonaSheets(current=>({...current,[Number(lonaLine.id)]:sheet}));await refreshManufacturedStatus();}}/>}
  {lonaViewLine&&<LonaConfectionViewModal line={lonaViewLine} reference={`${data.code} · Línea ${lonaViewLine.line_no}`} onClose={()=>setLonaViewLine(null)}/>}
  {componentsLine&&<ComponentConsumptionModal line={componentsLine} companyId={companyId} salesOrderId={Number(data.id)} orderWarehouseId={orderWarehouseId} reference={`${data.code} · Línea ${componentsLine.line_no}`} onClose={()=>setComponentsLine(null)} onDone={async sheet=>{setComponentSheets(current=>({...current,[Number(componentsLine.id)]:sheet}));await refreshManufacturedStatus();}}/>}
  {productionSheetsOpen&&<SalesOrderProductionSheetsModal orderCode={data.code} reference={data.reference} cutSheets={allCutSheets} lonaSheets={allLonaSheets} componentSheets={allComponentSheets} onClose={()=>setProductionSheetsOpen(false)}/>}
  {fabricationOpen&&<OrderFabricationModal order={data} companyId={companyId} onClose={()=>setFabricationOpen(false)} onDone={({cutSheets:newCut,lonaSheets:newLona,componentSheets:newComponents,orderManufactured})=>{setCutSheets(current=>({...current,...newCut}));setLonaSheets(current=>({...current,...newLona}));setComponentSheets(current=>({...current,...newComponents}));if(orderManufactured)setData(current=>current?{...current,status:'MANUFACTURED'}:current);}}/>}
  {installationModalTarget&&<InstallationModal order={data} companyId={companyId} installation={installationModalTarget==='new'?null:installationModalTarget} availableLines={availableInstallLines} types={installationTypes} installers={installers} onClose={()=>setInstallationModalTarget(null)} onDone={async()=>{await refreshInstallations(data.id);await refreshDelivery(data.id);const refreshedOrder=await getSalesOrder(data.id).catch(()=>null);if(refreshedOrder)setData(refreshedOrder);}} onCancelled={async()=>{await refreshInstallations(data.id);}}/>}
  <QuotationLineSnapshotModal isOpen={Boolean(otdSnapshot)} onClose={()=>setOtdSnapshot(null)} snapshot={otdSnapshot} lineNo={otdLineNo}/>
  {viewingDeliveryNote&&<SalesOrderDeliveryNoteModal note={viewingDeliveryNote} onClose={()=>setViewingDeliveryNote(null)} onStatusChange={updated=>{setViewingDeliveryNote(updated);setDeliveryNotes(current=>current.map(n=>n.id===updated.id?updated:n));}}/>}
  {deliveringLine&&<RegisterLineDeliveryModal line={deliveringLine} onClose={()=>setDeliveringLine(null)} onDone={async()=>{await refreshDelivery(data.id);}}/>}
 </div>;
}
