import { Boxes, Hammer, Printer, Scissors, X } from 'lucide-react';
import type { WorkSheet } from '../../services/production/workSheetService';
import type { LonaConfectionWorkSheet } from '../../services/production/lonaConfectionService';
import type { ComponentConsumptionWorkSheet } from '../../services/production/componentConsumptionService';
import { downloadBatchWorkSheetsPdf } from '../../services/production/workSheetPdfService';
import { downloadLonaWorkSheetsPdf } from '../../services/production/lonaConfectionPdfService';
import './sales-order.css';
import './sales-order-production.css';

type Props = { orderCode:string; reference?:string|null; cutSheets:WorkSheet[]; lonaSheets:LonaConfectionWorkSheet[]; componentSheets?:ComponentConsumptionWorkSheet[]; onClose:()=>void };
const statusLabel=(status:string)=>({ISSUED:'Emitida',IN_PROGRESS:'En curso',COMPLETED:'Completada',CANCELLED:'Cancelada'} as Record<string,string>)[status]||status;
const dimensions=(values:number[],units:string[])=>values.length?values.map((value,index)=>`${value} ${units[index]||''}`.trim()).join(' × '):'—';

export function SalesOrderProductionSheetsModal({orderCode,reference,cutSheets,lonaSheets,componentSheets=[],onClose}:Props){
 const total=cutSheets.length+lonaSheets.length+componentSheets.length;
 return <div className="sales-order-modal-backdrop" role="dialog" aria-modal="true">
   <div className="sales-order-modal production-sheets-modal">
    <header className="sales-order-modal-head"><div><div className="eyebrow">PEDIDO / PRODUCCIÓN</div><h2>Hojas de producción</h2><p>{orderCode}{reference?` · ${reference}`:''} · {total} documento{total===1?'':'s'}</p></div><button type="button" className="icon-link" onClick={onClose} aria-label="Cerrar"><X size={18}/></button></header>
    <div className="production-sheets-toolbar"><div className="production-sheets-summary"><span>Corte de perfil</span><strong>{cutSheets.length}</strong></div><div className="production-sheets-summary"><span>Confección de lona</span><strong>{lonaSheets.length}</strong></div><div className="production-sheets-summary"><span>Componentes</span><strong>{componentSheets.length}</strong></div><div className="production-sheets-actions"><button type="button" className="secondary-button" disabled={!cutSheets.length} onClick={()=>downloadBatchWorkSheetsPdf(cutSheets,`${orderCode} · ${reference||''}`)}><Printer size={14}/> Imprimir cortes</button><button type="button" className="secondary-button" disabled={!lonaSheets.length} onClick={()=>downloadLonaWorkSheetsPdf(lonaSheets,orderCode,reference)}><Printer size={14}/> Imprimir confecciones</button></div></div>
    <div className="production-sheets-body"><section className="production-sheet-group"><div className="production-sheet-group-title"><Hammer size={16}/><div><h3>Hojas de corte de perfil</h3><span>{cutSheets.length} documento{cutSheets.length===1?'':'s'}</span></div></div>{cutSheets.length?cutSheets.map(sheet=><article className="production-sheet-row" key={sheet.id}><div className="production-sheet-icon"><Hammer size={16}/></div><div className="production-sheet-main"><strong>{sheet.code}</strong><span>Línea {sheet.sales_order_line_no??'—'} · {sheet.product_code||'Perfil'}{sheet.characteristic_name?` · ${sheet.characteristic_name}`:''}</span><small>{sheet.quantity} ud. · Necesidad {sheet.required_length} {sheet.unit_symbol||sheet.unit_code||''}</small></div><span className={`work-sheet-status ${sheet.status.toLowerCase()}`}>{statusLabel(sheet.status)}</span></article>):<div className="production-sheet-empty">No hay hojas de corte de perfil para este pedido.</div>}</section><section className="production-sheet-group"><div className="production-sheet-group-title"><Scissors size={16}/><div><h3>Hojas de confección de lona</h3><span>{lonaSheets.length} documento{lonaSheets.length===1?'':'s'}</span></div></div>{lonaSheets.length?lonaSheets.map(sheet=><article className="production-sheet-row" key={sheet.id}><div className="production-sheet-icon"><Scissors size={16}/></div><div className="production-sheet-main"><strong>{sheet.code}</strong><span>Línea {sheet.orderLineId} · {sheet.productCode||'Lona'}{sheet.characteristicName?` · ${sheet.characteristicName}`:''}</span><small>{sheet.quantity} ud. · Necesidad {dimensions(sheet.requiredDimensions,sheet.requiredDimensionUnits)}</small></div><span className={`work-sheet-status ${sheet.status.toLowerCase()}`}>{statusLabel(sheet.status)}</span></article>):<div className="production-sheet-empty">No hay hojas de confección de lona para este pedido.</div>}</section><section className="production-sheet-group"><div className="production-sheet-group-title"><Boxes size={16}/><div><h3>Hojas de componentes</h3><span>{componentSheets.length} documento{componentSheets.length===1?'':'s'}</span></div></div>{componentSheets.length?componentSheets.map(sheet=><article className="production-sheet-row" key={sheet.id}><div className="production-sheet-icon"><Boxes size={16}/></div><div className="production-sheet-main"><strong>{sheet.code}</strong><span>Línea {sheet.salesOrderLineNo??'—'} · {sheet.lines.length} componente{sheet.lines.length===1?'':'s'}</span><small>{sheet.lines.map(l=>`${l.productCode} × ${l.quantity}`).join(', ')}</small></div><span className={`work-sheet-status ${sheet.status.toLowerCase()}`}>{statusLabel(sheet.status)}</span></article>):<div className="production-sheet-empty">No hay hojas de componentes para este pedido.</div>}</section></div>
    <footer className="sales-order-modal-actions"><button type="button" className="primary-button" onClick={onClose}>Cerrar</button></footer>
   </div>
 </div>;
}
