import { useEffect, useState } from 'react';
import { Plus, Save, X } from 'lucide-react';
import { getActiveCompanies } from '../../services/core/coreRepository';
import { listMeasurementTypes, upsertMeasurementType, type MeasurementDimension, type MeasurementType } from '../../services/catalog/measurementTypeRepository';
import './catalog.css';

const emptyDimension = (n: number): MeasurementDimension => ({ dimension_number: n, code: `DIM${n}`, name: `Dimensión ${n}`, unit_id: null, decimals: 2 });
const emptyType = (): MeasurementType => ({ code: '', name: '', dimension_count: 0, result_unit_id: null, result_decimals: 2, calculation_type: '', formula: '', active: true, dimensions: [] });

export function MeasurementTypesV1() {
  const [companyId, setCompanyId] = useState<number | null>(null); const [rows, setRows] = useState<MeasurementType[]>([]); const [form, setForm] = useState<MeasurementType>(emptyType()); const [editing, setEditing] = useState(false); const [saving, setSaving] = useState(false); const [error, setError] = useState('');
  useEffect(() => { getActiveCompanies().then(cs => setCompanyId(cs[0]?.id ?? null)).catch(e => setError(e instanceof Error ? e.message : 'No se pudo obtener la empresa.')); }, []);
  useEffect(() => { if (companyId) load(); }, [companyId]);
  async function load() { if (!companyId) return; try { setRows(await listMeasurementTypes(companyId)); } catch (e) { setError(e instanceof Error ? e.message : 'No se pudieron cargar los tipos de medida.'); } }
  function startNew() { setForm(emptyType()); setEditing(true); setError(''); }
  function startEdit(row: MeasurementType) { setForm({ ...row, dimensions: row.dimensions.map(d => ({ ...d })) }); setEditing(true); setError(''); }
  function changeCount(count: number) { setForm(f => ({ ...f, dimension_count: count, dimensions: Array.from({ length: count }, (_, i) => f.dimensions[i] ?? emptyDimension(i + 1)) })); }
  function updateDimension(index: number, patch: Partial<MeasurementDimension>) { setForm(f => ({ ...f, dimensions: f.dimensions.map((d, i) => i === index ? { ...d, ...patch } : d) })); }
  async function save() { if (!companyId || !form.code.trim() || !form.name.trim()) { setError('Código y nombre son obligatorios.'); return; } if (form.dimensions.some(d => !d.code.trim() || !d.name.trim())) { setError('Todas las dimensiones deben tener código y nombre.'); return; } setSaving(true); setError(''); try { await upsertMeasurementType(companyId, form); setEditing(false); await load(); } catch (e) { setError(e instanceof Error ? e.message : 'No se pudo guardar.'); } finally { setSaving(false); } }
  return <div className="module-page catalog-page">
    <div className="page-head"><div><div className="eyebrow">VENTAS / CONFIGURACIÓN</div><h1>Tipos de medida</h1><p>Define dimensiones, unidades, precisión y cálculo reutilizables por los artículos.</p></div><button className="primary-button" onClick={startNew}><Plus size={16}/> Nuevo tipo de medida</button></div>
    {error && <div className="inline-error">{error}</div>}
    <div className="catalog-layout"><section className="panel"><div className="panel-head"><div><h2>Tipos de medida</h2><p>Configuraciones dimensionales independientes de familias y artículos.</p></div></div><div className="catalog-table-wrap"><table className="catalog-table"><thead><tr><th>Código</th><th>Nombre</th><th>Dimensiones</th><th>Cálculo</th><th>Resultado</th><th></th></tr></thead><tbody>{rows.map(r => <tr key={r.id}><td>{r.code}</td><td>{r.name}</td><td>{r.dimensions.map(d => d.name).join(' · ') || 'Sin dimensiones'}</td><td>{r.calculation_type || '—'}</td><td>{r.result_unit_id ? `Unidad #${r.result_unit_id} · ${r.result_decimals} dec.` : `${r.result_decimals} dec.`}</td><td><button className="icon-action" title="Editar" onClick={() => startEdit(r)}>Editar</button></td></tr>)}{rows.length === 0 && <tr><td colSpan={6}><div className="empty-state">No hay tipos de medida definidos.</div></td></tr>}</tbody></table></div></section>
      {editing && <aside className="panel catalog-editor"><div className="panel-head"><div><h2>{form.id ? 'Editar' : 'Nuevo'} tipo de medida</h2></div><button className="icon-action" onClick={() => setEditing(false)} title="Cancelar"><X size={17}/></button></div>
        <div className="form-grid"><label>Código *<input value={form.code} onChange={e => setForm({ ...form, code: e.target.value })}/></label><label>Nombre *<input value={form.name} onChange={e => setForm({ ...form, name: e.target.value })}/></label><label>Nº dimensiones<select value={form.dimension_count} onChange={e => changeCount(Number(e.target.value))}>{[0,1,2,3,4,5].map(n => <option key={n} value={n}>{n}</option>)}</select></label><label>Decimales resultado<input type="number" min={0} max={6} value={form.result_decimals} onChange={e => setForm({ ...form, result_decimals: Number(e.target.value) })}/></label>
          <div className="wide"><div className="form-section-title">Dimensiones</div>{form.dimensions.map((d, i) => <div key={d.dimension_number} className="form-grid" style={{ marginBottom: 10 }}><label>#{i + 1} Código<input value={d.code} onChange={e => updateDimension(i, { code: e.target.value })}/></label><label>Nombre<input value={d.name} onChange={e => updateDimension(i, { name: e.target.value })}/></label><label>Unidad (ID)<input type="number" min={0} value={d.unit_id ?? ''} onChange={e => updateDimension(i, { unit_id: e.target.value ? Number(e.target.value) : null })}/></label><label>Decimales<input type="number" min={0} max={6} value={d.decimals} onChange={e => updateDimension(i, { decimals: Number(e.target.value) })}/></label></div>)}</div>
          <label>Tipo de cálculo<input value={form.calculation_type ?? ''} onChange={e => setForm({ ...form, calculation_type: e.target.value })} placeholder="Ej. SUPERFICIE"/></label><label>Fórmula<input value={form.formula ?? ''} onChange={e => setForm({ ...form, formula: e.target.value })} placeholder="Ej. DIM1 * DIM2"/></label><label>Unidad resultado (ID)<input type="number" min={0} value={form.result_unit_id ?? ''} onChange={e => setForm({ ...form, result_unit_id: e.target.value ? Number(e.target.value) : null })}/></label>
        </div><div className="editor-actions"><button className="secondary-button" onClick={() => setEditing(false)}>Cancelar</button><button className="primary-button" disabled={saving} onClick={save}><Save size={15}/> {saving ? 'Guardando...' : 'Guardar'}</button></div>
      </aside>}
    </div>
  </div>;
}
