import { supabase } from '../../lib/supabase';
import { CoreRepositoryError } from '../core/coreRepository';
import { evaluateFormula, resolveOtdVariables, type FormulaEvaluationContext, type OtdVariableDefinition } from './formulaEngine';
import { resolveProductUnitPrice, round2 } from '../catalog/productPricingService';
import { listOtdScales, resolveOtdBasePriceFromScales, type OtdScaleRow } from './otdScaleRepository';
import { resolveComponentProduct } from './otdArticleResolutionService';
import type { Product, ProductCharacteristic } from '../catalog/productRepository';
import type { ProductScaleRow } from '../catalog/productCommercialRepository';

export type OtdModel={id:number;company_id:number;code:string;name:string;template_type:string|null;active:boolean;product_id?:number|null;version?:number};
export type OtdDimensionDef={code:string;name:string;dimension_number:number;unit_id:number|null;decimals:number};
export type OtdScale=ProductScaleRow&{product_id:number};
export type OtdSelectionOption={id:number;selection_id:number;code:string;label:string;value:string|null;sort_order:number;product_id:number|null;product:Product|null};
export type OtdSelection={id:number;otd_id:number;code:string;name:string;selection_type:'NUMBER'|'OPTION'|'TEXT'|'BOOLEAN';required:boolean;is_dimension?:boolean;unit_id?:number|null;sort_order:number;options:OtdSelectionOption[]};
export type OtdVariable=OtdVariableDefinition&{id:number;otd_id:number;name:string;min_value:number|null;max_value:number|null;sort_order:number};
export type OtdComponentDef={id:number;otd_id:number;code:string;product_id:number|null;product_selection_code:string|null;description:string|null;component_type:'BASIC'|'IMPROVEMENT';quantity_expression:string|null;dimension_expressions:Record<string,string>;characteristic_id:number|null;characteristic_expression:string|null;price_increment:number;price_increment_type:'FIXED'|'PERCENTAGE';active:boolean;sort_order:number;product?:Product|null;dimensions?:OtdDimensionDef[];scales?:OtdScale[];characteristics?:ProductCharacteristic[]};
export type OtdRuntimeData={otd:OtdModel;selections:OtdSelection[];variables:OtdVariable[];components:OtdComponentDef[];scales:OtdScaleRow[];productsMap:Map<number,Product>;productDimensionsMap:Map<number,OtdDimensionDef[]>;loadedAt:string};
export type OtdCalculatedComponent={id:number;code:string;description:string;product_id:number|null;product_code:string;product_name:string;product_resolution_source:'FIXED'|'OPTION'|'MISSING';product_selection_code:string|null;component_type:'BASIC'|'IMPROVEMENT';quantity:number;quantity_expression:string|null;dimensions:Record<string,number>;dimension_expressions:Record<string,string>;dimension_list:Array<{code:string;name:string;value:number}>;characteristic_id:number|null;characteristic_code:string|null;characteristic_name:string|null;characteristic_expression:string|null;pricing_source:'base'|'characteristic'|'scale'|'scale_characteristic'|'manual';scale_step_used:{dimension_1:number;dimension_2:number|null;price:number}|null;base_price:number;price_increment:number;price_increment_type:'FIXED'|'PERCENTAGE';increment_amount:number;unit_price:number;total_price:number;ok:boolean;formula_error?:string};
export type OtdCalculationResult={inputs:Record<string,string|number|boolean|null>;resolvedVariables:FormulaEvaluationContext;components:OtdCalculatedComponent[];otdBasePrice:number;otdScaleStepUsed:{dimension_1:number;dimension_2:number|null;price:number}|null;totalIncrements:number;totalAmount:number;isValid:boolean;requiredMissing:string[];errors:string[]};
export type OtdSnapshotComponent=OtdCalculatedComponent&{is_missing_price:boolean;missing_reason?:string};
export type OtdConfigurationSnapshot={snapshot_version:'1.0';created_at:string;otd_id:number;otd_code:string;otd_name:string;template_type:string|null;inputs:Record<string,string|number|boolean|null>;inputs_display:Array<{code:string;name:string;value:string|number|boolean|null;display_value:string;is_dimension?:boolean}>;variables:Record<string,number>;variables_display:Array<{code:string;name:string;value:number;expression:string|null}>;otd_base_price:number;otd_scale_step_used:{dimension_1:number;dimension_2:number|null;price:number}|null;total_increments:number;components:OtdSnapshotComponent[];total_amount:number;notes?:string};

const db=()=>{if(!supabase)throw new CoreRepositoryError('Supabase no está inicializado.');return supabase;};
const normalizeScales=(rows:any[],pid:number):OtdScale[]=>rows.map(r=>({...r,product_id:pid,dimension_values:Array.isArray(r.dimension_values)&&r.dimension_values.length?r.dimension_values:[Number(r.dimension_1),...(r.dimension_2==null?[]:[Number(r.dimension_2)])],attribute_values:r.attribute_values&&typeof r.attribute_values==='object'?r.attribute_values:{}}));

export async function loadOtdRuntimeData(otdId:number):Promise<OtdRuntimeData>{
 const c=db();const [o,s,v,co,os]=await Promise.all([c.from('otd').select('*').eq('id',otdId).single(),c.from('otd_selection').select('*,otd_selection_option(*)').eq('otd_id',otdId).order('sort_order'),c.from('otd_variable').select('*').eq('otd_id',otdId).eq('active',true).order('sort_order'),c.from('otd_component').select('*').eq('otd_id',otdId).eq('active',true).order('sort_order'),listOtdScales(otdId)]);if(o.error)throw new CoreRepositoryError(o.error.message);
 const rawS:any[]=s.data??[],rawC:any[]=co.data??[];const pids=[...new Set([...rawC.map(x=>x.product_id),...rawS.flatMap(x=>(x.otd_selection_option??[]).map((z:any)=>z.product_id))].filter(x=>Number.isFinite(Number(x))).map(Number)];
 let products:Product[]=[];let scales:any[]=[];let chars:ProductCharacteristic[]=[];let dims:any[]=[];let familyMap:Record<number,any>={};
 if(pids.length){const pr=await c.from('product').select('*').in('id',pids);if(pr.error)throw new CoreRepositoryError(pr.error.message);products=(pr.data??[]) as Product[];const fids=[...new Set(products.map(p=>p.family_id).filter((x):x is number=>Number.isFinite(x)))];if(fids.length){const f=await c.from('product_family').select('id,measurement_type_id').in('id',fids);familyMap=Object.fromEntries((f.data??[]).map((x:any)=>[x.id,x]));}const mtids=[...new Set(products.map(p=>Number.isFinite(p.measurement_type_id)?p.measurement_type_id:familyMap[p.family_id!]?.measurement_type_id).filter((x):x is number=>Number.isFinite(x)))];if(mtids.length){const d=await c.from('measurement_type_dimension').select('measurement_type_id,dimension_number,code,name,unit_id,decimals').in('measurement_type_id',mtids).order('dimension_number');dims=d.data??[];}const [sr,cr]=await Promise.all([c.from('product_scale').select('id,product_id,dimension_values,dimension_1,dimension_2,price,characteristic_id,attribute_values,deleted_at,deleted_by').in('product_id',pids).is('deleted_at',null).order('dimension_1').order('dimension_2'),c.from('product_characteristic').select('*').in('product_id',pids).eq('active',true).is('deleted_at',null).order('code')]);scales=sr.data??[];chars=(cr.data??[]) as ProductCharacteristic[];}
 const pm=new Map(products.map(p=>[Number(p.id),p]));const dm=new Map<number,OtdDimensionDef[]>();for(const p of products){const mt=Number.isFinite(p.measurement_type_id)?p.measurement_type_id:familyMap[p.family_id!]?.measurement_type_id;dm.set(Number(p.id),dims.filter((d:any)=>Number(d.measurement_type_id)===Number(mt)).map((d:any)=>({code:String(d.code),name:String(d.name),dimension_number:Number(d.dimension_number),unit_id:d.unit_id==null?null:Number(d.unit_id),decimals:Number(d.decimals??0)})));}
 const sm=new Map<number,OtdScale[]>();for(const r of scales){const pid=Number(r.product_id);sm.set(pid,[...(sm.get(pid)??[]),...normalizeScales([r],pid)]);}const cm=new Map<number,ProductCharacteristic[]>();for(const ch of chars){const pid=Number(ch.product_id);cm.set(pid,[...(cm.get(pid)??[]),ch]);}
 const selections:OtdSelection[]=rawS.map(x=>({id:Number(x.id),otd_id:Number(x.otd_id),code:String(x.code||''),name:String(x.name||x.code||''),selection_type:x.selection_type||'NUMBER',required:Boolean(x.required),is_dimension:Boolean(x.is_dimension),unit_id:x.unit_id==null?null:Number(x.unit_id),sort_order:Number(x.sort_order??0),options:(x.otd_selection_option??[]).map((z:any)=>({id:Number(z.id),selection_id:Number(z.selection_id),code:String(z.code||''),label:String(z.label||z.code||''),value:z.value==null?null:String(z.value),sort_order:Number(z.sort_order??0),product_id:z.product_id==null?null:Number(z.product_id),product:z.product_id?pm.get(Number(z.product_id))??null:null}))}));
 const variables:OtdVariable[]=(v.data??[]).map((x:any)=>({id:Number(x.id),otd_id:Number(x.otd_id),code:String(x.code||''),name:String(x.name||x.code||''),expression:x.expression||null,data_type:x.data_type||'NUMBER',min_value:x.min_value==null?null:Number(x.min_value),max_value:x.max_value==null?null:Number(x.max_value),sort_order:Number(x.sort_order??0),active:Boolean(x.active)}));
 const components:OtdComponentDef[]=rawC.map(x=>{const p=x.product_id?pm.get(Number(x.product_id))??null:null;return{id:Number(x.id),otd_id:Number(x.otd_id),code:String(x.code||''),product_id:x.product_id==null?null:Number(x.product_id),product_selection_code:x.product_selection_code||null,description:x.description||null,component_type:x.component_type==='IMPROVEMENT'?'IMPROVEMENT':'BASIC',quantity_expression:x.quantity_expression||null,dimension_expressions:x.dimension_expressions&&typeof x.dimension_expressions==='object'?x.dimension_expressions:{},characteristic_id:x.characteristic_id?Number(x.characteristic_id):null,characteristic_expression:x.characteristic_expression||null,price_increment:Number(x.price_increment??0),price_increment_type:x.price_increment_type==='PERCENTAGE'?'PERCENTAGE':'FIXED',active:Boolean(x.active),sort_order:Number(x.sort_order??0),product:p,dimensions:p?dm.get(Number(p.id))??[]:[],scales:p?sm.get(Number(p.id))??[]:[],characteristics:p?cm.get(Number(p.id))??[]:[]};});
 return{otd:o.data as OtdModel,selections,variables,components,scales:os,productsMap:pm,productDimensionsMap:dm,loadedAt:new Date().toISOString()};
}

export async function fetchProductForOtdComponent(productId:number){const c=db();const {data:p,error}=await c.from('product').select('*').eq('id',productId).single();if(error||!p)throw new CoreRepositoryError(error?.message||'Producto no encontrado');let mt:any=(p as any).measurement_type_id??null;if(!mt&&(p as any).family_id){const f=await c.from('product_family').select('measurement_type_id').eq('id',(p as any).family_id).single();mt=f.data?.measurement_type_id??null;}let dimensions:OtdDimensionDef[]=[];if(mt){const d=await c.from('measurement_type_dimension').select('measurement_type_id,dimension_number,code,name,unit_id,decimals').eq('measurement_type_id',mt).order('dimension_number');dimensions=(d.data??[]).map((x:any)=>({code:String(x.code),name:String(x.name),dimension_number:Number(x.dimension_number),unit_id:x.unit_id==null?null:Number(x.unit_id),decimals:Number(x.decimals??0)}));}const [sr,cr]=await Promise.all([c.from('product_scale').select('id,product_id,dimension_values,dimension_1,dimension_2,price,characteristic_id,attribute_values,deleted_at,deleted_by').eq('product_id',productId).is('deleted_at',null).order('dimension_1').order('dimension_2'),c.from('product_characteristic').select('*').eq('product_id',productId).eq('active',true).is('deleted_at',null).order('code')]);return{product:p as Product,dimensions,scales:normalizeScales(sr.data??[],productId),characteristics:(cr.data??[]) as ProductCharacteristic[]};}

export function calculateOtdRuntime(rd:OtdRuntimeData,raw:Record<string,string|number|boolean|null>):OtdCalculationResult{
 const numeric:FormulaEvaluationContext={};const inputs:Record<string,string|number|boolean|null>={};const missing:string[]=[];const errors:string[]=[];const dims:number[]=[];
 for(const s of rd.selections){const v=raw[s.code];const present=v!=null&&String(v).trim()!=='';if(s.required&&!present)missing.push(s.name||s.code);if(s.selection_type==='NUMBER'){const n=Number(v);inputs[s.code]=Number.isFinite(n)?n:null;if(Number.isFinite(n)){numeric[s.code]=n;if(s.is_dimension)dims.push(n);}}else if(s.selection_type==='BOOLEAN'){const b=v===true||v==='true'||v==='1'||v===1;inputs[s.code]=b;numeric[s.code]=b?1:0;}else if(s.selection_type==='OPTION'){inputs[s.code]=present?String(v):null;const o=s.options.find(x=>(x.value!=null&&String(x.value).trim()===String(v).trim())||x.code===String(v)||x.label===String(v));for(const q of [o?.value,o?.code,v]){const n=Number(q);if(Number.isFinite(n)){numeric[s.code]=n;break;}}}else{inputs[s.code]=present?String(v):null;const n=Number(v);if(Number.isFinite(n))numeric[s.code]=n;}}
 let vars:FormulaEvaluationContext={...numeric};try{vars=resolveOtdVariables(rd.variables,numeric);}catch(e:any){errors.push(`Error al resolver variables: ${e?.message||e}`);}
 let base=0;let baseStep:{dimension_1:number;dimension_2:number|null;price:number}|null=null;if(rd.scales.length){const r=resolveOtdBasePriceFromScales(rd.scales,dims);if(r.found){base=r.basePrice;baseStep=r.scaleStep;}else if(dims.length)errors.push('No se encontró escalón de precio en la matriz del OTD para las medidas seleccionadas.');}
 const result:OtdCalculatedComponent[]=[];
 for(const c of rd.components){if(!c.active)continue;const res=resolveComponentProduct(c,rd.selections,raw,rd.productsMap);const p=res.product;const name=p?.commercial_description||p?.technical_description||c.description||c.code;try{const qty=Math.max(0,evaluateFormula(c.quantity_expression||'1',vars).value);const dmap:Record<string,number>={};const dlist:Array<{code:string;name:string;value:number}>=[];const defs=p?rd.productDimensionsMap.get(Number(p.id))??[]:c.dimensions??[];for(const [code,expr] of Object.entries(c.dimension_expressions??{})){if(!expr?.trim())continue;const val=Math.max(0,evaluateFormula(expr,vars).value);dmap[code]=val;const d=defs.find(x=>x.code===code);dlist.push({code,name:d?.name||code,value:val});}const ordered=defs.map(d=>dmap[d.code]??null);let ch:ProductCharacteristic|null=null;if(c.characteristic_id)ch=(c.characteristics??[]).find(x=>x.id===c.characteristic_id)??null;else if(c.characteristic_expression?.trim()){const q=inputs[c.characteristic_expression.trim()]??raw[c.characteristic_expression.trim()]??c.characteristic_expression.trim();const qs=String(q).toUpperCase();ch=(c.characteristics??[]).find(x=>String(x.id)===qs||x.code.toUpperCase()===qs||(x.description??'').toUpperCase()===qs)??null;}
 let price=0;let source:'base'|'characteristic'|'scale'|'scale_characteristic'|'manual'='base';let step:{dimension_1:number;dimension_2:number|null;price:number}|null=null;let ok=true;let err:string|undefined;if(!p){ok=false;source='manual';err=c.product_selection_code?`La entrada '${c.product_selection_code}' no tiene artículo para la opción seleccionada.`:'El componente no tiene un artículo asignado en el catálogo.';}else if(rd.scales.length){source='manual';}else{const pr=resolveProductUnitPrice({product:p,characteristic:ch,dimension1:ordered[0]??null,dimension2:ordered[1]??null,scales:c.scales??[],selectedAttributeValues:{}});price=pr.price;source=pr.source;if(pr.scale)step={dimension_1:Number(pr.scale.dimension_1),dimension_2:pr.scale.dimension_2==null?null:Number(pr.scale.dimension_2),price:Number(pr.scale.price)};if(pr.missing){ok=false;err=pr.missingReason||'No se encontró escalado o precio para el artículo.';}}
 let inc=0;let unit=price;const iv=Number(c.price_increment||0);if(iv>0){if(c.price_increment_type==='PERCENTAGE'){inc=round2((rd.scales.length?base:price)*iv/100);unit=round2(price+inc);}else{inc=iv;unit=round2(price+inc);}}const total=round2(unit*qty);result.push({id:c.id,code:c.code,description:c.description||name,product_id:res.product_id,product_code:p?.code||c.code,product_name:name,product_resolution_source:res.source,product_selection_code:c.product_selection_code,component_type:c.component_type,quantity:qty,quantity_expression:c.quantity_expression,dimensions:dmap,dimension_expressions:c.dimension_expressions,dimension_list:dlist,characteristic_id:ch?.id??c.characteristic_id??null,characteristic_code:ch?.code??null,characteristic_name:ch?.description??null,characteristic_expression:c.characteristic_expression,pricing_source:source,scale_step_used:step,base_price:price,price_increment:iv,price_increment_type:c.price_increment_type,increment_amount:inc,unit_price:unit,total_price:total,ok,formula_error:err});}catch(e:any){result.push({id:c.id,code:c.code,description:c.description||name,product_id:res.product_id,product_code:p?.code||c.code,product_name:name,product_resolution_source:res.source,product_selection_code:c.product_selection_code,component_type:c.component_type,quantity:0,quantity_expression:c.quantity_expression,dimensions:{},dimension_expressions:c.dimension_expressions,dimension_list:[],characteristic_id:null,characteristic_code:null,characteristic_name:null,characteristic_expression:c.characteristic_expression,pricing_source:'manual',scale_step_used:null,base_price:0,price_increment:0,price_increment_type:'FIXED',increment_amount:0,unit_price:0,total_price:0,ok:false,formula_error:e?.message||'Error en el cálculo del componente'});}}
 const increments=rd.scales.length?round2(result.reduce((s,c)=>s+(c.ok?c.total_price:0),0)):0;const total=rd.scales.length?round2(base+increments):round2(result.reduce((s,c)=>s+(c.ok?c.total_price:0),0));const valid=missing.length===0&&errors.length===0&&(rd.scales.length===0||base>0||rd.scales.some(s=>s.price===0))&&result.every(c=>c.ok);return{inputs,resolvedVariables:vars,components:result,otdBasePrice:base,otdScaleStepUsed:baseStep,totalIncrements:increments,totalAmount:total,isValid:valid,requiredMissing:missing,errors};
}

export function buildOtdConfigurationSnapshot(rd:OtdRuntimeData,calc:OtdCalculationResult,notes?:string):OtdConfigurationSnapshot{const inputs_display=rd.selections.map(s=>{const v=calc.inputs[s.code];let display=v==null?'—':String(v);if(s.selection_type==='OPTION'){const o=s.options.find(x=>(x.value??x.code)===String(v));if(o)display=o.label||o.code;}else if(s.selection_type==='BOOLEAN')display=v?'Sí':'No';return{code:s.code,name:s.name||s.code,value:v??null,display_value:display,is_dimension:s.is_dimension};});return{snapshot_version:'1.0',created_at:new Date().toISOString(),otd_id:rd.otd.id,otd_code:rd.otd.code,otd_name:rd.otd.name,template_type:rd.otd.template_type,inputs:calc.inputs,inputs_display,variables:calc.resolvedVariables,variables_display:rd.variables.map(v=>({code:v.code,name:v.name||v.code,value:calc.resolvedVariables[v.code]??0,expression:v.expression})),otd_base_price:calc.otdBasePrice,otd_scale_step_used:calc.otdScaleStepUsed,total_increments:calc.totalIncrements,components:calc.components.map(c=>({...c,is_missing_price:!c.ok,missing_reason:c.formula_error})),total_amount:calc.totalAmount,notes};}
