import { supabase } from '../../lib/supabase';
import { CoreRepositoryError } from '../core/coreRepository';
import { evaluateFormula, resolveOtdVariables, type FormulaEvaluationContext, type OtdVariableDefinition } from './formulaEngine';
import { resolveProductUnitPrice, round2 } from '../catalog/productPricingService';
import { listOtdScales, resolveOtdBasePriceFromScales, type OtdScaleRow } from './otdScaleRepository';
import { resolveComponentProduct } from './otdArticleResolutionService';
import type { Product, ProductCharacteristic } from '../catalog/productRepository';
import type { ProductScaleRow } from '../catalog/productCommercialRepository';

export type OtdModel = { id:number; company_id:number; code:string; name:string; template_type:string|null; active:boolean; product_id?:number|null; version?:number };
export type OtdDimensionDef = { code:string; name:string; dimension_number:number; unit_id:number|null; decimals:number };
export type OtdScale = ProductScaleRow & { product_id:number };
export type OtdSelectionOption = { id:number; selection_id:number; code:string; label:string; value:string|null; sort_order:number; product_id:number|null; product:Product|null };
export type OtdSelection = { id:number; otd_id:number; code:string; name:string; selection_type:'NUMBER'|'OPTION'|'TEXT'|'BOOLEAN'; required:boolean; is_dimension?:boolean; unit_id?:number|null; sort_order:number; options:OtdSelectionOption[] };
export type OtdVariable = OtdVariableDefinition & { id:number; otd_id:number; name:string; min_value:number|null; max_value:number|null; sort_order:number };
export type OtdComponentDef = { id:number; otd_id:number; code:string; product_id:number|null; product_selection_code?:string|null; description:string|null; component_type:'BASIC'|'IMPROVEMENT'; quantity_expression:string|null; dimension_expressions:Record<string,string>; characteristic_id:number|null; characteristic_expression:string|null; price_increment:number; price_increment_type:'FIXED'|'PERCENTAGE'; active:boolean; sort_order:number; product?:Product|null; dimensions?:OtdDimensionDef[]; scales?:OtdScale[]; characteristics?:ProductCharacteristic[] };
export type OtdRuntimeData = { otd:OtdModel; selections:OtdSelection[]; variables:OtdVariable[]; components:OtdComponentDef[]; scales:OtdScaleRow[]; productsMap:Map<number,Product>; productDimensionsMap:Map<number,OtdDimensionDef[]>; loadedAt:string };
export type OtdCalculatedComponent = { id:number; code:string; description:string; product_id:number|null; product_code:string; product_name:string; product_resolution_source:'FIXED'|'OPTION'|'MISSING'; product_selection_code:string|null; component_type:'BASIC'|'IMPROVEMENT'; quantity:number; quantity_expression:string|null; dimensions:Record<string,number>; dimension_expressions:Record<string,string>; dimension_list:Array<{code:string;name:string;value:number}>; characteristic_id:number|null; characteristic_code:string|null; characteristic_name:string|null; characteristic_expression:string|null; pricing_source:'base'|'characteristic'|'scale'|'scale_characteristic'|'manual'; scale_step_used:{dimension_1:number;dimension_2:number|null;price:number}|null; base_price:number; price_increment:number; price_increment_type:'FIXED'|'PERCENTAGE'; increment_amount:number; unit_price:number; total_price:number; ok:boolean; formula_error?:string };
export type OtdCalculationResult = { inputs:Record<string,string|number|boolean|null>; resolvedVariables:FormulaEvaluationContext; components:OtdCalculatedComponent[]; otdBasePrice:number; otdScaleStepUsed:{dimension_1:number;dimension_2:number|null;price:number}|null; totalIncrements:number; totalAmount:number; isValid:boolean; requiredMissing:string[]; errors:string[] };
export type OtdSnapshotComponent = OtdCalculatedComponent & { is_missing_price:boolean; missing_reason?:string };
export type OtdConfigurationSnapshot = { snapshot_version:'1.0'; created_at:string; otd_id:number; otd_code:string; otd_name:string; template_type:string|null; inputs:Record<string,string|number|boolean|null>; inputs_display:Array<{code:string;name:string;value:string|number|boolean|null;display_value:string;is_dimension?:boolean}>; variables:Record<string,number>; variables_display:Array<{code:string;name:string;value:number;expression:string|null}>; otd_base_price:number; otd_scale_step_used:{dimension_1:number;dimension_2:number|null;price:number}|null; total_increments:number; components:OtdSnapshotComponent[]; total_amount:number; notes?:string };

function client(){ if(!supabase) throw new CoreRepositoryError('Supabase no está inicializado.'); return supabase; }
function normalizeScales(rows:any[],productId:number):OtdScale[]{ return rows.map(r=>({...r,product_id:productId,dimension_values:Array.isArray(r.dimension_values)&&r.dimension_values.length?r.dimension_values:[Number(r.dimension_1),...(r.dimension_2==null?[]:[Number(r.dimension_2)])],attribute_values:r.attribute_values&&typeof r.attribute_values==='object'?r.attribute_values:{}})); }

export async function loadOtdRuntimeData(otdId:number):Promise<OtdRuntimeData>{
 const c=client();
 const [otdRes,selRes,varRes,compRes,otdScales]=await Promise.all([
  c.from('otd').select('*').eq('id',otdId).single(),
  c.from('otd_selection').select('*,otd_selection_option(*)').eq('otd_id',otdId).order('sort_order'),
  c.from('otd_variable').select('*').eq('otd_id',otdId).eq('active',true).order('sort_order'),
  c.from('otd_component').select('*').eq('otd_id',otdId).eq('active',true).order('sort_order'),
  listOtdScales(otdId),
 ]);
 if(otdRes.error) throw new CoreRepositoryError(otdRes.error.message);
 const rawSelections:any[]=selRes.data??[]; const rawComponents:any[]=compRes.data??[];
 const rawProductIds:any[]=[...rawComponents.map(x=>x.product_id),...rawSelections.flatMap(x=>(x.otd_selection_option??[]).map((o:any)=>o.product_id))];
 const productIds=Array.from(new Set(rawProductIds.filter(x=>Number.isFinite(Number(x))).map(Number)));
 let products:Product[]=[]; let productScales:any[]=[]; let characteristics:ProductCharacteristic[]=[]; let dimensions:any[]=[]; let familyMap:Record<number,any>={};
 if(productIds.length){
  const pRes=await c.from('product').select('*').in('id',productIds); if(pRes.error)throw new CoreRepositoryError(pRes.error.message); products=(pRes.data??[]) as Product[];
  const familyIds=Array.from(new Set(products.map(p=>p.family_id).filter((x):x is number=>Number.isFinite(x))));
  if(familyIds.length){const fRes=await c.from('product_family').select('id,measurement_type_id').in('id',familyIds);familyMap=Object.fromEntries((fRes.data??[]).map((x:any)=>[x.id,x]));}
  const measurementTypeIds=Array.from(new Set(products.map(p=>Number.isFinite(p.measurement_type_id)?p.measurement_type_id:familyMap[p.family_id!]?.measurement_type_id).filter((x):x is number=>Number.isFinite(x))));
  if(measurementTypeIds.length){const dRes=await c.from('measurement_type_dimension').select('measurement_type_id,dimension_number,code,name,unit_id,decimals').in('measurement_type_id',measurementTypeIds).order('dimension_number');dimensions=dRes.data??[];}
  const[scaleRes,charRes]=await Promise.all([
   c.from('product_scale').select('id,product_id,dimension_values,dimension_1,dimension_2,price,characteristic_id,attribute_values,deleted_at,deleted_by').in('product_id',productIds).is('deleted_at',null).order('dimension_1').order('dimension_2'),
   c.from('product_characteristic').select('*').in('product_id',productIds).eq('active',true).is('deleted_at',null).order('code'),
  ]);
  productScales=scaleRes.data??[]; characteristics=(charRes.data??[]) as ProductCharacteristic[];
 }
 const productsMap=new Map<number,Product>(products.map(p=>[Number(p.id),p]));
 const productDimensionsMap=new Map<number,OtdDimensionDef[]>();
 for(const p of products){
  const mt=Number.isFinite(p.measurement_type_id)?p.measurement_type_id:familyMap[p.family_id!]?.measurement_type_id;
  productDimensionsMap.set(Number(p.id),dimensions.filter((d:any)=>Number(d.measurement_type_id)===Number(mt)).map((d:any)=>({code:String(d.code),name:String(d.name),dimension_number:Number(d.dimension_number),unit_id:d.unit_id==null?null:Number(d.unit_id),decimals:Number(d.decimals??0)})));
 }
 const scalesByProduct=new Map<number,OtdScale[]>(); for(const row of productScales){const pid=Number(row.product_id);scalesByProduct.set(pid,[...(scalesByProduct.get(pid)??[]),...normalizeScales([row],pid)]);}
 const charsByProduct=new Map<number,ProductCharacteristic[]>(); for(const ch of characteristics){const pid=Number(ch.product_id);charsByProduct.set(pid,[...(charsByProduct.get(pid)??[]),ch]);}
 const selections:OtdSelection[]=rawSelections.map((s:any)=>({id:Number(s.id),otd_id:Number(s.otd_id),code:String(s.code||''),name:String(s.name||s.code||''),selection_type:s.selection_type||'NUMBER',required:Boolean(s.required),is_dimension:Boolean(s.is_dimension),unit_id:s.unit_id==null?null:Number(s.unit_id),sort_order:Number(s.sort_order??0),options:(s.otd_selection_option??[]).map((o:any)=>({id:Number(o.id),selection_id:Number(o.selection_id),code:String(o.code||''),label:String(o.label||o.code||''),value:o.value==null?null:String(o.value),sort_order:Number(o.sort_order??0),product_id:o.product_id==null?null:Number(o.product_id),product:o.product_id?productsMap.get(Number(o.product_id))??null:null}))}));
 const variables:OtdVariable[]=(varRes.data??[]).map((v:any)=>({id:Number(v.id),otd_id:Number(v.otd_id),code:String(v.code||''),name:String(v.name||v.code||''),expression:v.expression||null,data_type:v.data_type||'NUMBER',min_value:v.min_value==null?null:Number(v.min_value),max_value:v.max_value==null?null:Number(v.max_value),sort_order:Number(v.sort_order??0),active:Boolean(v.active)}));
 const components:OtdComponentDef[]=rawComponents.map((x:any)=>{const p=x.product_id?productsMap.get(Number(x.product_id))??null:null;const pid=p?Number(p.id):null;return{id:Number(x.id),otd_id:Number(x.otd_id),code:String(x.code||''),product_id:x.product_id==null?null:Number(x.product_id),product_selection_code:x.product_selection_code||null,description:x.description||null,component_type:x.component_type==='IMPROVEMENT'?'IMPROVEMENT':'BASIC',quantity_expression:x.quantity_expression||null,dimension_expressions:x.dimension_expressions&&typeof x.dimension_expressions==='object'?x.dimension_expressions:{},characteristic_id:x.characteristic_id?Number(x.characteristic_id):null,characteristic_expression:x.characteristic_expression||null,price_increment:Number(x.price_increment??0),price_increment_type:x.price_increment_type==='PERCENTAGE'?'PERCENTAGE':'FIXED',active:Boolean(x.active),sort_order:Number(x.sort_order??0),product:p,dimensions:pid?productDimensionsMap.get(pid)??[]:[],scales:pid?scalesByProduct.get(pid)??[]:[],characteristics:pid?charsByProduct.get(pid)??[]:[]};});
 return{otd:otdRes.data as OtdModel,selections,variables,components,scales:otdScales,productsMap,productDimensionsMap,loadedAt:new Date().toISOString()};
}

export async function fetchProductForOtdComponent(productId:number){
 const c=client();const{data:product,error}=await c.from('product').select('*').eq('id',productId).single();if(error||!product)throw new CoreRepositoryError(error?.message||'Producto no encontrado');
 let measurementTypeId:any=(product as any).measurement_type_id??null;if(!measurementTypeId&&(product as any).family_id){const f=await c.from('product_family').select('measurement_type_id').eq('id',(product as any).family_id).single();measurementTypeId=f.data?.measurement_type_id??null;}
 let dimensions:OtdDimensionDef[]=[];if(measurementTypeId){const d=await c.from('measurement_type_dimension').select('measurement_type_id,dimension_number,code,name,unit_id,decimals').eq('measurement_type_id',measurementTypeId).order('dimension_number');dimensions=(d.data??[]).map((x:any)=>({code:String(x.code),name:String(x.name),dimension_number:Number(x.dimension_number),unit_id:x.unit_id==null?null:Number(x.unit_id),decimals:Number(x.decimals??0)}));}
 const[scalesRes,charsRes]=await Promise.all([c.from('product_scale').select('id,product_id,dimension_values,dimension_1,dimension_2,price,characteristic_id,attribute_values,deleted_at,deleted_by').eq('product_id',productId).is('deleted_at',null).order('dimension_1').order('dimension_2'),c.from('product_characteristic').select('*').eq('product_id',productId).eq('active',true).is('deleted_at',null).order('code')]);
 return{product:product as Product,dimensions,scales:normalizeScales(scalesRes.data??[],productId),characteristics:(charsRes.data??[]) as ProductCharacteristic[]};
}

export function calculateOtdRuntime(data:OtdRuntimeData,rawValues:Record<string,string|number|boolean|null>):OtdCalculationResult{
 const numericInputs:FormulaEvaluationContext={};const inputs:Record<string,string|number|boolean|null>={};const requiredMissing:string[]=[];const errors:string[]=[];const dimensionInputs:number[]=[];
 for(const selection of data.selections){
  const raw=rawValues[selection.code];const present=raw!==null&&raw!==undefined&&String(raw).trim()!=='';if(selection.required&&!present)requiredMissing.push(selection.name||selection.code);
  if(selection.selection_type==='NUMBER'){const n=Number(raw);inputs[selection.code]=Number.isFinite(n)?n:null;if(Number.isFinite(n)){numericInputs[selection.code]=n;if(selection.is_dimension)dimensionInputs.push(n);}}
  else if(selection.selection_type==='BOOLEAN'){const b=raw===true||raw==='true'||raw==='1'||raw===1;inputs[selection.code]=b;numericInputs[selection.code]=b?1:0;}
  else if(selection.selection_type==='OPTION'){inputs[selection.code]=present?String(raw):null;const option=selection.options.find(o=>(o.value!=null&&String(o.value).trim()===String(raw).trim())||String(o.code)===String(raw)||String(o.label)===String(raw));for(const candidate of[option?.value,option?.code,raw]){const n=Number(candidate);if(Number.isFinite(n)){numericInputs[selection.code]=n;break;}}}
  else{inputs[selection.code]=present?String(raw):null;const n=Number(raw);if(Number.isFinite(n))numericInputs[selection.code]=n;}
 }
 let resolvedVariables:FormulaEvaluationContext={...numericInputs};try{resolvedVariables=resolveOtdVariables(data.variables,numericInputs);}catch(e:any){errors.push(`Error al resolver variables: ${e?.message||e}`);}
 let otdBasePrice=0;let otdScaleStepUsed:{dimension_1:number;dimension_2:number|null;price:number}|null=null;if(data.scales.length){const resolution=resolveOtdBasePriceFromScales(data.scales,dimensionInputs);if(resolution.found){otdBasePrice=resolution.basePrice;otdScaleStepUsed=resolution.scaleStep;}else if(dimensionInputs.length)errors.push('No se encontró escalón de precio en la matriz del OTD para las medidas seleccionadas.');}
 const calculated:OtdCalculatedComponent[]=[];
 for(const component of data.components){if(!component.active)continue;const resolved=resolveComponentProduct(component,data.selections,rawValues,data.productsMap);const product=resolved.product;const productName=product?.commercial_description||product?.technical_description||component.description||component.code;try{
  const quantity=Math.max(0,evaluateFormula(component.quantity_expression||'1',resolvedVariables).value);const dimensions:Record<string,number>={};const dimensionList:Array<{code:string;name:string;value:number}>=[];const dimensionDefs=product?data.productDimensionsMap.get(Number(product.id))??[]:component.dimensions??[];
  for(const[code,expression]of Object.entries(component.dimension_expressions??{})){if(!expression?.trim())continue;const value=Math.max(0,evaluateFormula(expression,resolvedVariables).value);dimensions[code]=value;const definition=dimensionDefs.find(d=>d.code===code);dimensionList.push({code,name:definition?.name||code,value});}
  const orderedDimensions=dimensionDefs.map(d=>dimensions[d.code]??null);let characteristic:ProductCharacteristic|null=null;if(component.characteristic_id)characteristic=(component.characteristics??[]).find(c=>c.id===component.characteristic_id)??null;else if(component.characteristic_expression?.trim()){const value=inputs[component.characteristic_expression.trim()]??rawValues[component.characteristic_expression.trim()]??component.characteristic_expression.trim();const key=String(value).toUpperCase();characteristic=(component.characteristics??[]).find(c=>String(c.id)===key||c.code.toUpperCase()===key||(c.description??'').toUpperCase()===key)??null;}
  let basePrice=0;let pricingSource:'base'|'characteristic'|'scale'|'scale_characteristic'|'manual'='base';let scaleStepUsed:{dimension_1:number;dimension_2:number|null;price:number}|null=null;let ok=true;let formulaError:string|undefined;
  if(!product){ok=false;pricingSource='manual';formulaError=component.product_selection_code?`La entrada '${component.product_selection_code}' no tiene artículo para la opción seleccionada.`:'El componente no tiene un artículo asignado en el catálogo.';}
  else if(data.scales.length){pricingSource='manual';}
  else{const pricing=resolveProductUnitPrice({product,characteristic,dimension1:orderedDimensions[0]??null,dimension2:orderedDimensions[1]??null,scales:component.scales??[],selectedAttributeValues:{}});basePrice=pricing.price;pricingSource=pricing.source;if(pricing.scale)scaleStepUsed={dimension_1:Number(pricing.scale.dimension_1),dimension_2:pricing.scale.dimension_2==null?null:Number(pricing.scale.dimension_2),price:Number(pricing.scale.price)};if(pricing.missing){ok=false;formulaError=pricing.missingReason||'No se encontró escalado o precio para el artículo.';}}
  let incrementAmount=0;let unitPrice=basePrice;const increment=Number(component.price_increment||0);if(increment>0){if(component.price_increment_type==='PERCENTAGE'){incrementAmount=round2((data.scales.length?otdBasePrice:basePrice)*(increment/100));unitPrice=round2(basePrice+incrementAmount);}else{incrementAmount=increment;unitPrice=round2(basePrice+incrementAmount);}}
  calculated.push({id:component.id,code:component.code,description:component.description||productName,product_id:resolved.product_id,product_code:product?.code||component.code,product_name:productName,product_resolution_source:resolved.source,product_selection_code:component.product_selection_code??null,component_type:component.component_type,quantity,quantity_expression:component.quantity_expression,dimensions,dimension_expressions:component.dimension_expressions,dimension_list:dimensionList,characteristic_id:characteristic?.id??component.characteristic_id??null,characteristic_code:characteristic?.code??null,characteristic_name:characteristic?.description??null,characteristic_expression:component.characteristic_expression,pricing_source:pricingSource,scale_step_used:scaleStepUsed,base_price:basePrice,price_increment:increment,price_increment_type:component.price_increment_type,increment_amount:incrementAmount,unit_price:unitPrice,total_price:round2(unitPrice*quantity),ok,formula_error:formulaError});
 }catch(e:any){calculated.push({id:component.id,code:component.code,description:component.description||productName,product_id:resolved.product_id,product_code:product?.code||component.code,product_name:productName,product_resolution_source:resolved.source,product_selection_code:component.product_selection_code??null,component_type:component.component_type,quantity:0,quantity_expression:component.quantity_expression,dimensions:{},dimension_expressions:component.dimension_expressions,dimension_list:[],characteristic_id:null,characteristic_code:null,characteristic_name:null,characteristic_expression:component.characteristic_expression,pricing_source:'manual',scale_step_used:null,base_price:0,price_increment:0,price_increment_type:'FIXED',increment_amount:0,unit_price:0,total_price:0,ok:false,formula_error:e?.message||'Error en el cálculo del componente'});}
 }
 const totalIncrements=data.scales.length?round2(calculated.reduce((sum,item)=>sum+(item.ok?item.total_price:0),0)):0;const totalAmount=data.scales.length?round2(otdBasePrice+totalIncrements):round2(calculated.reduce((sum,item)=>sum+(item.ok?item.total_price:0),0));const isValid=requiredMissing.length===0&&errors.length===0&&(data.scales.length===0||otdBasePrice>0||data.scales.some(s=>s.price===0))&&calculated.every(item=>item.ok);return{inputs,resolvedVariables,components:calculated,otdBasePrice,otdScaleStepUsed,totalIncrements,totalAmount,isValid,requiredMissing,errors};
}

export function buildOtdConfigurationSnapshot(data:OtdRuntimeData,result:OtdCalculationResult,notes?:string):OtdConfigurationSnapshot{
 const inputsDisplay=data.selections.map(selection=>{const value=result.inputs[selection.code];let display=value==null?'—':String(value);if(selection.selection_type==='OPTION'){const option=selection.options.find(o=>(o.value??o.code)===String(value));if(option)display=option.label||option.code;}else if(selection.selection_type==='BOOLEAN')display=value?'Sí':'No';else if(selection.selection_type==='NUMBER'&&typeof value==='number')display=value.toLocaleString('es-ES');return{code:selection.code,name:selection.name||selection.code,value:value??null,display_value:display,is_dimension:selection.is_dimension};});
 return{snapshot_version:'1.0',created_at:new Date().toISOString(),otd_id:data.otd.id,otd_code:data.otd.code,otd_name:data.otd.name,template_type:data.otd.template_type,inputs:result.inputs,inputs_display:inputsDisplay,variables:result.resolvedVariables,variables_display:data.variables.map(v=>({code:v.code,name:v.name||v.code,value:result.resolvedVariables[v.code]??0,expression:v.expression})),otd_base_price:result.otdBasePrice,otd_scale_step_used:result.otdScaleStepUsed,total_increments:result.totalIncrements,components:result.components.map(c=>({...c,is_missing_price:!c.ok,missing_reason:c.formula_error})),total_amount:result.totalAmount,notes};
}
