import { FormEvent, useEffect, useState } from 'react';
import { KeyRound, Plus, Save, UserCog } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { listUsers, createUser, updateUserAccount, type UserAccount, type UserRole } from '../../services/core/userRepository';
import { getActiveCompanies } from '../../services/core/coreRepository';
import { useAuth } from '../../auth/AuthContext';
import { MessageLog } from '../../components/ui/MessageLog';
import './users.css';

const roleLabels:Record<UserRole,string>={ADMIN:'Administrador',OFFICE:'Oficina',WORKSHOP:'Taller',CONFECTION:'Confección',INSTALLER:'Montador'};
const emptyNew={username:'',display_name:'',email:'',password:'',role_code:'OFFICE' as UserRole,can_measure:false};

export function UserList(){
 const navigate=useNavigate(); const {user}=useAuth();
 const [rows,setRows]=useState<UserAccount[]>([]);const [search,setSearch]=useState('');const [status,setStatus]=useState<'active'|'inactive'|'all'>('active');const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [newUser,setNewUser]=useState(false);const [form,setForm]=useState(emptyNew);const [saving,setSaving]=useState(false);
 async function load(){setLoading(true);setError('');try{setRows(await listUsers(search,status));}catch(e){setError(e instanceof Error?e.message:'No se pudieron cargar los usuarios.')}finally{setLoading(false)}}
 useEffect(()=>{const t=setTimeout(()=>void load(),180);return()=>clearTimeout(t)},[search,status]);
 async function saveNew(e:FormEvent){e.preventDefault();setSaving(true);setError('');try{const companies=await getActiveCompanies();await createUser({...form,company_id:companies[0]?.id??null});setNewUser(false);setForm(emptyNew);await load();}catch(e){setError(e instanceof Error?e.message:'No se pudo crear el usuario.')}finally{setSaving(false)}}
 async function patch(id:number,changes:Partial<UserAccount>){setError('');try{await updateUserAccount(id,changes);await load();}catch(e){setError(e instanceof Error?e.message:'No se pudo actualizar el usuario.')}}
 return <div className="module-page users-page">
   <div className="page-head"><div><div className="eyebrow">CONFIGURACIÓN / USUARIOS</div><h1>Usuarios</h1><p>Usuarios de acceso a ONIN, perfiles operativos y capacidad para realizar mediciones.</p></div><button className="primary-button" onClick={()=>setNewUser(true)}><Plus size={17}/> Nuevo usuario</button></div>
   <MessageLog error={error}/>
   <div className="toolbar"><div className="search-box"><KeyRound size={17}/><input autoFocus value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar por usuario, nombre o email…" aria-label="Buscar usuarios"/></div><select value={status} onChange={e=>setStatus(e.target.value as typeof status)} aria-label="Estado"><option value="active">Activos</option><option value="inactive">Inactivos</option><option value="all">Todos</option></select><span className="result-count">{rows.length} usuarios</span></div>
   {newUser&&<form className="panel user-create-panel" onSubmit={saveNew}><div className="panel-head"><div><h2>Nuevo usuario</h2><p>La cuenta se crea con acceso por email y contraseña.</p></div></div><div className="form-grid"><label>Usuario *<input value={form.username} onChange={e=>setForm({...form,username:e.target.value})} required maxLength={120}/></label><label>Nombre *<input value={form.display_name} onChange={e=>setForm({...form,display_name:e.target.value})} required maxLength={120}/></label><label>Email *<input type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})} required/></label><label>Contraseña temporal *<input type="password" value={form.password} onChange={e=>setForm({...form,password:e.target.value})} minLength={8} required/></label><label>Rol<select value={form.role_code} onChange={e=>setForm({...form,role_code:e.target.value as UserRole})}>{Object.entries(roleLabels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label className="checkbox-field"><span>Puede realizar mediciones</span><input type="checkbox" checked={form.can_measure} onChange={e=>setForm({...form,can_measure:e.target.checked})}/></label></div><div className="form-footer"><button type="button" className="secondary-button" onClick={()=>setNewUser(false)}>Cancelar</button><button type="submit" className="primary-button" disabled={saving}><Save size={15}/>{saving?'Creando…':'Crear usuario'}</button></div></form>}
   <div className="table-panel"><table><thead><tr><th>Usuario</th><th>Nombre</th><th>Email</th><th>Rol</th><th>Medidor</th><th>Estado</th><th></th></tr></thead><tbody>{loading?<tr><td colSpan={7}>Cargando…</td></tr>:rows.length===0?<tr><td colSpan={7}><div className="empty-state"><UserCog size={28}/><strong>No hay usuarios</strong><span>Crea un usuario o cambia el filtro.</span></div></td></tr>:rows.map(r=><tr key={r.id} className="clickable-row" onDoubleClick={()=>navigate(`/configuracion/usuarios/${r.id}`)}><td><button type="button" className="table-link" onClick={()=>navigate(`/configuracion/usuarios/${r.id}`)}><strong>{r.username}</strong></button></td><td>{r.display_name}</td><td>{r.email}</td><td><span className="user-role">{roleLabels[r.role_code]}</span></td><td><button type="button" className={`measure-toggle ${r.can_measure?'on':''}`} onClick={(e)=>{e.stopPropagation();void patch(r.id,{can_measure:!r.can_measure})}}>{r.can_measure?'Sí':'No'}</button></td><td><span className={`status-pill ${r.active?'active':'inactive'}`}>{r.active?'Activo':'Inactivo'}</span></td><td>{r.auth_user_id===user?.id?<span className="secondary">Sesión actual</span>:<button className="icon-btn" title={r.active?'Desactivar':'Activar'} onClick={(e)=>{e.stopPropagation();void patch(r.id,{active:!r.active})}}>{r.active?'Desactivar':'Activar'}</button>}</td></tr>)}</tbody></table></div>
 </div>
}
