import { supabase } from '../../lib/supabase';
import { CoreRepositoryError } from './coreRepository';
import type { Address, Contact, CustomerSummary, Party } from '../../domain/core/types';
import type { AddressForm, ContactForm, CustomerDetails, CustomerForm } from '../../modules/customers/types';

function client(){ if(!supabase) throw new CoreRepositoryError('Supabase no está configurado.'); return supabase; }
export async function listCustomers(search='',status:'active'|'inactive'|'all'='active'):Promise<CustomerSummary[]>{ const c=client(); let q=c.from('customer').select('id,party_id,party!inner(id,code,legal_name,trade_name,tax_id,email,phone,active)').order('id'); if(status==='active') q=q.eq('party.active',true); if(status==='inactive') q=q.eq('party.active',false); const term=search.trim().replace(/[%_]/g,''); if(term) q=q.or(`legal_name.ilike.%${term}%,trade_name.ilike.%${term}%,tax_id.ilike.%${term}%,code.ilike.%${term}%`,{referencedTable:'party'}); const {data,error}=await q; if(error) throw new CoreRepositoryError(error.message); return (data??[]) as unknown as CustomerSummary[]; }
export async function getCustomerDetails(customerId:number):Promise<CustomerDetails>{ const c=client(); const {data:customer,error:ce}=await c.from('customer').select('id,party_id').eq('id',customerId).single(); if(ce) throw new CoreRepositoryError(ce.message); const {data:partyRow,error:pe}=await c.from('party').select('id,company_id,code,legal_name,trade_name,tax_id,email,phone,active').eq('id',customer.party_id).single(); if(pe) throw new CoreRepositoryError(pe.message); const [addresses,contacts]=await Promise.all([getAddresses(customer.party_id),getContacts(customer.party_id)]); return {customer,party:partyRow as Party,addresses,contacts}; }
export async function getAddresses(partyId:number):Promise<Address[]>{ const c=client(); const {data,error}=await c.from('address').select('*').eq('party_id',partyId).order('id'); if(error) throw new CoreRepositoryError(error.message); return (data??[]) as Address[]; }
export async function getContacts(partyId:number):Promise<Contact[]>{ const c=client(); const {data,error}=await c.from('contact').select('*').eq('party_id',partyId).order('id'); if(error) throw new CoreRepositoryError(error.message); return (data??[]) as Contact[]; }
export async function createCustomer(input:CustomerForm,companyId:number):Promise<number>{ const c=client(); const {data,error}=await c.rpc('create_customer',{p_company_id:companyId,p_legal_name:input.legal_name.trim(),p_trade_name:input.trade_name.trim()||null,p_tax_id:input.tax_id.trim().toUpperCase(),p_email:input.email.trim()||null,p_phone:input.phone.trim()||null,p_active:input.active,p_notes:input.notes.trim()||null}); if(error) throw new CoreRepositoryError(error.message); return Number(data); }
export async function deleteCustomer(customerId:number):Promise<void>{ const c=client(); const {error}=await c.rpc('delete_customer',{p_customer_id:customerId}); if(error) throw new CoreRepositoryError(error.message); }
export async function updateCustomer(customerId:number,input:CustomerForm):Promise<void>{ const c=client(); const {data,error}=await c.from('customer').select('party_id').eq('id',customerId).single(); if(error) throw new CoreRepositoryError(error.message); const {error:pe}=await c.from('party').update({legal_name:input.legal_name.trim(),trade_name:input.trade_name.trim()||null,tax_id:input.tax_id.trim().toUpperCase(),email:input.email.trim()||null,phone:input.phone.trim()||null,active:input.active}).eq('id',data.party_id); if(pe) throw new CoreRepositoryError(pe.message); }
export async function setCustomerActive(customerId:number,active:boolean):Promise<void>{ const c=client(); const {data,error}=await c.from('customer').select('party_id').eq('id',customerId).single(); if(error) throw new CoreRepositoryError(error.message); const {error:pe}=await c.from('party').update({active}).eq('id',data.party_id); if(pe) throw new CoreRepositoryError(pe.message); }
export async function createAddress(partyId:number,input:AddressForm):Promise<void>{const c=client();const {error}=await c.from('address').insert({party_id:partyId,...input});if(error)throw new CoreRepositoryError(error.message)}
export async function updateAddress(id:number,input:AddressForm):Promise<void>{const c=client();const {error}=await c.from('address').update(input).eq('id',id);if(error)throw new CoreRepositoryError(error.message)}
export async function deleteAddress(id:number):Promise<void>{const c=client();const {error}=await c.from('address').delete().eq('id',id);if(error)throw new CoreRepositoryError(error.message)}
export async function createContact(partyId:number,input:ContactForm):Promise<void>{const c=client();const {error}=await c.from('contact').insert({party_id:partyId,...input});if(error)throw new CoreRepositoryError(error.message)}
export async function updateContact(id:number,input:ContactForm):Promise<void>{const c=client();const {error}=await c.from('contact').update(input).eq('id',id);if(error)throw new CoreRepositoryError(error.message)}
export async function deleteContact(id:number):Promise<void>{const c=client();const {error}=await c.from('contact').delete().eq('id',id);if(error)throw new CoreRepositoryError(error.message)}
