import { FormEvent, useEffect, useState } from 'react';
import { useNavigate, useParams, useSearchParams } from 'react-router-dom';
import { ArrowLeft, Edit3, Package, Plus, RotateCcw, Search, Trash2, Undo2 } from 'lucide-react';
import { getActiveCompanies } from '../../services/core/coreRepository';
import { createProduct, createProductDraft, getProduct, getProductReferences, listProducts, markProductForDeletion, restoreProduct, updateProduct, type Product, type ProductForm, type ProductListRow, type ProductStatus } from '../../services/catalog/productRepository';
import { EntitySearchHelp } from './ProductCommercialPanel';
import './product.css';
import './product-fixes.css';

type ReferenceData=Awaited<ReturnType<typeof getProductReferences>>;
type ProductV2Props={onEditModeChange?:(editing:boolean)=>void;onScaledChange?:(scaled:boolean)=>void};

const emptyProduct=():ProductForm=>({
  code:'',technical_description:'',commercial_description:'',family_id:null,product_type_id:null,base_unit_id:null,
  sales_price:null,purchase_price:null,stock_enabled:false,allow_negative_stock:false,active:true,notes:'',cod_arb:null,
  price_increment:0,upc:0,ptc:0,stock_minimum:0,discarded_size:null,minimum_remainder:null,smooth_cut:false,monochrome:false,
  usage_status:'ACTIVE',iva_percent:null,default_supplier_party_id:null,include_measurements_in_stock:false,include_stock_by_color:false,
  scaled:false,scaled_by_characteristic:false,deleted_at:null,deleted_by:null,
});

function ProductStatusBadge({product}:{product:Pick<Product,'active'|'deleted_at'>}){
  const deleted=!!product.deleted_at;
  return <span className={`status ${deleted||!product.active?'inactive':'active'}`}>{deleted?'Marcado para borrado':product.active?'Activo':'Inactivo'}</span>;
}

export function ProductV2({onEditModeChange,onScaledChange}:ProductV2Props){
  const { id }=useParams<{id:string}>();
  const [searchParams]=useSearchParams();
  const navigate=useNavigate();
  const isNew=id==='nuevo';
  const isDraft=searchParams.get('draft')==='1';
  const [companyId,setCompanyId]=useState<number|null>(null);
  const [rows,setRows]=useState<ProductListRow[]>([]);
  const [refs,setRefs]=useState<ReferenceData|null>(null);
  const [search,setSearch]=useState('');
  const [status,setStatus]=useState<ProductStatus>('active');
  const [loading,setLoading]=useState(true);
  const [creatingDraft,setCreatingDraft]=useState(false);
  const [error,setError]=useState('');

  useEffect(()=>{getActiveCompanies().then(cs=>setCompanyId(cs[0]?.id??null)).catch(e=>setError(e instanceof Error?e.message:'No se pudo obtener la empresa activa.'));},[]);
  useEffect(()=>{if(!companyId||id)return; loadList();},[companyId,status]);
  async function loadList(){if(!companyId)return;setLoading(true);setError('');try{const [r,ref]=await Promise.all([listProducts(companyId,search,status),getProductReferences(companyId)]);setRows(r);setRefs(ref);}catch(e){setError(e instanceof Error?e.message:'No se pudo cargar el listado de artículos.')}finally{setLoading(false)}}
  async function startNew(){if(!companyId||creatingDraft)return;setCreatingDraft(true);setError('');try{const draftId=await createProductDraft(companyId);navigate(`/ventas/articulos/${draftId}?draft=1`);}catch(e){setError(e instanceof Error?e.message:'No se pudo preparar el nuevo artículo.')}finally{setCreatingDraft(false)}}
  if(id) return <ProductEditor companyId={companyId} productId={isNew?null:Number(id)} draftMode={isDraft} error={error} setError={setError} refs={refs} onSaved={()=>navigate('/ventas/articulos')} onEditModeChange={onEditModeChange} onScaledChange={onScaledChange} />;
  return <div className="module-page product-page">
    <div className="page-head"><div><div className="eyebrow">VENTAS / ARTÍCULOS</div><h1>Listado de Artículos</h1><p>Consulta y gestión del maestro de artículos.</p></div><div className="product-head-actions"><button className="secondary-button" type="button" onClick={()=>navigate('/ventas/articulos/catalogos')}><Package size={16}/> Catálogos</button><button className="primary-button" type="button" onClick={()=>void startNew()} disabled={creatingDraft}><Plus size={16}/> {creatingDraft?'Preparando…':'Nuevo artículo'}</button></div></div>
    <div className="toolbar"><div className="search-box"><Search size={17}/><input value={search} onChange={e=>setSearch(e.target.value)} onKeyDown={e=>e.key==='Enter'&&loadList()} placeholder="Buscar por código o descripción…" aria-label="Buscar artículo"/></div><select value={status} onChange={e=>setStatus(e.target.value as ProductStatus)} aria-label="Estado"><option value="active">Activos</option><option value="inactive">Inactivos</option><option value="deleted">Marcados para borrado</option><option value="all">Todos</option></select><button className="secondary-button" onClick={loadList}><RotateCcw size={15}/> Actualizar</button><span className="result-count">{rows.length} artículos</span></div>
    {error&&<div className="inline-error">{error}</div>}
    <div className="table-panel product-table"><table><thead><tr><th>Código</th><th>Descripción</th><th>Familia</th><th>Tipo</th><th>Unidad</th><th>PVP</th><th>Stock</th><th>Estado</th></tr></thead><tbody>{loading?<tr><td colSpan={8}>Cargando…</td></tr>:rows.length===0?<tr><td colSpan={8}><div className="empty-state"><Package size={28}/><strong>No hay artículos</strong><span>Prueba otra búsqueda o crea un nuevo artículo.</span></div></td></tr>:rows.map(r=><tr key={r.id} className="clickable-row"><td><button type="button" className="link-button primary-link" onClick={()=>navigate(`/ventas/articulos/${r.id}`)}>{r.code}</button></td><td><button type="button" className="link-button" onClick={()=>navigate(`/ventas/articulos/${r.id}`)}>{r.commercial_description||r.technical_description||'—'}</button></td><td>{r.family?.name||'—'}</td><td>{r.productType?.name||'—'}</td><td>{r.unit?.name||'—'}</td><td>{r.sales_price==null?'—':Number(r.sales_price).toFixed(2)+' €'}</td><td>{r.stock_enabled?<><span className="stock-dot">●</span> Gestionado</>:'No gestionado'}</td><td><ProductStatusBadge product={r}/></td></tr>)}</tbody></table></div>
  </div>;
}

function ProductEditor({companyId,productId,draftMode,error,setError,refs:initialRefs,onSaved,onEditModeChange,onScaledChange}:{companyId:number|null;productId:number|null;draftMode:boolean;error:string;setError:(v:string)=>void;refs:ReferenceData|null;onSaved:()=>void;onEditModeChange?:(editing:boolean)=>void;onScaledChange?:(scaled:boolean)=>void}){
  const navigate=useNavigate();
  const [product,setProduct]=useState<Product|null>(null);
  const [refs,setRefs]=useState<ReferenceData|null>(initialRefs);
  const [form,setForm]=useState<ProductForm>(emptyProduct());
  const [editing,setEditing]=useState(productId===null||draftMode);
  const [loading,setLoading]=useState(true);
  const [saving,setSaving]=useState(false);
  const isDeleted=!!product?.deleted_at;

  useEffect(()=>{onEditModeChange?.(editing);},[editing,onEditModeChange]);
  useEffect(()=>{onScaledChange?.(!!form.scaled);},[form.scaled,onScaledChange]);
  useEffect(()=>{if(companyId)load();},[companyId,productId]);
  async function load(){if(!companyId)return;setLoading(true);setError('');try{const referenceData=await getProductReferences(companyId);setRefs(referenceData);if(productId!==null){const d=await getProduct(companyId,productId);setProduct(d.product);setForm(toForm(d.product));setEditing(draftMode||false)}}catch(e){setError(e instanceof Error?e.message:'No se pudo cargar el artículo.')}finally{setLoading(false)}}
  function toForm(p:Product):ProductForm{const {id,company_id,...rest}=p;return rest;}
  function update<K extends keyof ProductForm>(key:K,value:ProductForm[K]){setForm(prev=>({...prev,[key]:value}));}
  async function save(e?:FormEvent){e?.preventDefault();if(!companyId)return;if(!form.code.trim()||form.code.startsWith('__DRAFT__')){setError('El código de artículo es obligatorio.');return}if(!form.commercial_description?.trim()&&!form.technical_description?.trim()){setError('Introduce al menos una descripción del artículo.');return}setSaving(true);setError('');try{if(productId===null){await createProduct(companyId,{...form,code:form.code.trim()});onSaved()}else if(draftMode){await updateProduct(companyId,productId,{...form,code:form.code.trim(),active:true,usage_status:'ACTIVE',deleted_at:null,deleted_by:null});navigate('/ventas/articulos')}else{await updateProduct(companyId,productId,{...form,code:form.code.trim()});setEditing(false);await load();onSaved()} }catch(e){setError(e instanceof Error?e.message:'No se pudo guardar el artículo.')}finally{setSaving(false)}}
  async function mark(){if(!companyId||!productId)return;if(!window.confirm(`¿Marcar el artículo ${product?.code||''} para borrado? No se eliminará físicamente y podrá recuperarse.`))return;try{await markProductForDeletion(companyId,productId);await load();if(draftMode)navigate('/ventas/articulos')}catch(e){setError(e instanceof Error?e.message:'No se pudo marcar el artículo para borrado.')}}
  async function cancel(){if(draftMode&&companyId&&productId){try{await markProductForDeletion(companyId,productId);}catch(e){setError(e instanceof Error?e.message:'No se pudo cancelar el borrador.')}}navigate('/ventas/articulos');}
  async function restore(){if(!companyId||!productId)return;try{await restoreProduct(companyId,productId);await load()}catch(e){setError(e instanceof Error?e.message:'No se pudo recuperar el artículo.')}}
  if(loading)return <div className="loading-block">{draftMode?'Preparando nuevo artículo…':'Cargando artículo…'}</div>;
  if(productId!==null&&!product)return <div className="inline-error">Artículo no encontrado.</div>;
  const readOnly=(!editing||isDeleted)&&!draftMode;
  return <div className="module-page product-page"><div className="page-head"><div><div className="eyebrow">VENTAS / ARTÍCULOS / {draftMode?'NUEVO':productId??'NUEVO'}</div><h1>{draftMode?'Nuevo artículo':productId===null?'Nuevo artículo':`Artículo ${product?.code||productId}`}</h1><p>{draftMode?'Alta del artículo; puedes configurar características y escalados antes de guardar.':productId===null?'Alta del maestro de artículos.':(product?.commercial_description||product?.technical_description||'')}</p></div><div className="product-head-actions"><button className="secondary-button" type="button" onClick={draftMode?cancel:()=>navigate('/ventas/articulos')}><ArrowLeft size={15}/> Cancelar</button>{productId!==null&&!draftMode&&!isDeleted&&!editing&&<button className="primary-button" type="button" onClick={()=>setEditing(true)}><Edit3 size={15}/> Editar</button>}{productId!==null&&!draftMode&&(isDeleted?<button className="secondary-button" type="button" onClick={restore}><Undo2 size={15}/> Recuperar</button>:!editing?<button className="danger-button" type="button" onClick={mark}><Trash2 size={15}/> Marcar para borrado</button>:null)}</div></div>
    {error&&<div className="inline-error">{error}</div>}{isDeleted&&!draftMode&&<div className="soft-delete-banner">Este artículo está marcado para borrado. Se conserva para mantener la trazabilidad y no puede utilizarse en nuevos documentos.</div>}{draftMode&&<div className="soft-delete-banner">Borrador: puedes definir características, proveedores y escalados antes de guardar definitivamente el artículo.</div>}
    <form id="product-profile-form" onSubmit={save} className="product-detail-grid">
      <section id="producto-datos-generales" className="panel product-profile-anchor"><div className="panel-head"><div><h2>Datos generales</h2><p>Identificación y clasificación del artículo.</p></div>{product&&!draftMode&&<ProductStatusBadge product={product}/>}</div><div className="form-grid"><label>ID<input value={product?.id??'—'} readOnly/></label><label>Código *<input value={draftMode&&form.code.startsWith('__DRAFT__')?'':form.code} readOnly={readOnly} onChange={e=>update('code',e.target.value)}/></label><label className="wide">Descripción comercial<input value={form.commercial_description??''} readOnly={readOnly} onChange={e=>update('commercial_description',e.target.value)}/></label><label className="wide">Descripción técnica<input value={form.technical_description??''} readOnly={readOnly} onChange={e=>update('technical_description',e.target.value)}/></label><label>Familia<select disabled={readOnly} value={form.family_id??''} onChange={e=>update('family_id',e.target.value?Number(e.target.value):null)}><option value="">Sin familia</option>{refs?.families.map(x=><option key={x.id} value={x.id}>{x.code} · {x.name}</option>)}</select></label><label>Tipo de producto<select disabled={readOnly} value={form.product_type_id??''} onChange={e=>update('product_type_id',e.target.value?Number(e.target.value):null)}><option value="">Sin tipo</option>{refs?.types.map(x=><option key={x.id} value={x.id}>{x.code} · {x.name}</option>)}</select></label><label>Unidad base<select disabled={readOnly} value={form.base_unit_id??''} onChange={e=>update('base_unit_id',e.target.value?Number(e.target.value):null)}><option value="">Sin unidad</option>{refs?.units.map(x=><option key={x.id} value={x.id}>{x.code} · {x.name}</option>)}</select></label><label>Proveedor habitual<EntitySearchHelp title="Buscar proveedor" placeholder="Seleccionar proveedor…" items={refs?.suppliers??[]} value={form.default_supplier_party_id} onChange={id=>update('default_supplier_party_id',id)} labelOf={item=>{const supplier=refs?.suppliers.find(x=>x.id===item.id);return supplier?.name??`Proveedor ${item.id}`;}} /></label><label>Estado<select disabled={readOnly} value={form.active?'1':'0'} onChange={e=>update('active',e.target.value==='1')}><option value="1">Activo</option><option value="0">Inactivo</option></select></label></div></section>
      <section id="producto-comercial" className="panel product-profile-anchor"><div className="panel-head"><div><h2>Información comercial</h2><p>Precios y datos comerciales básicos; la gestión avanzada de precios queda para la siguiente fase.</p></div></div><div className="form-grid"><label>Precio venta<input type="number" step="0.01" readOnly={readOnly} value={form.sales_price??''} onChange={e=>update('sales_price',e.target.value===''?null:Number(e.target.value))}/></label><label>Precio compra<input type="number" step="0.01" readOnly={readOnly} value={form.purchase_price??''} onChange={e=>update('purchase_price',e.target.value===''?null:Number(e.target.value))}/></label><label>IVA (%)<input type="number" step="0.01" readOnly={readOnly} value={form.iva_percent??''} onChange={e=>update('iva_percent',e.target.value===''?null:Number(e.target.value))}/></label><label>Incremento de precio<input type="number" step="0.01" readOnly={readOnly} value={form.price_increment??0} onChange={e=>update('price_increment',Number(e.target.value))}/></label><label>UPC<input type="number" step="0.01" readOnly={readOnly} value={form.upc??0} onChange={e=>update('upc',Number(e.target.value))}/></label><label>PTC<input type="number" step="0.01" readOnly={readOnly} value={form.ptc??0} onChange={e=>update('ptc',Number(e.target.value))}/></label></div></section>
      <section id="producto-stock" className="panel product-profile-anchor"><div className="panel-head"><div><h2>Gestión de stock</h2><p>Configuración del artículo; las existencias y movimientos se implementarán en la fase de Stock.</p></div></div><div className="form-grid"><label className="check-card"><input type="checkbox" checked={form.stock_enabled} disabled={readOnly} onChange={e=>update('stock_enabled',e.target.checked)}/><span><strong>Actualizar stock</strong><small>El artículo participa en la gestión de existencias.</small></span></label><label>Stock mínimo<input type="number" step="1" min="0" readOnly={readOnly||!form.stock_enabled} value={form.stock_minimum??0} onChange={e=>update('stock_minimum',Number(e.target.value))}/></label><label className="check-card"><input type="checkbox" checked={form.allow_negative_stock} disabled={readOnly||!form.stock_enabled} onChange={e=>update('allow_negative_stock',e.target.checked)}/><span><strong>Permitir stock negativo</strong><small>Disponible sólo cuando se gestiona stock.</small></span></label><label className="check-card"><input type="checkbox" checked={form.include_measurements_in_stock} disabled={readOnly||!form.stock_enabled} onChange={e=>update('include_measurements_in_stock',e.target.checked)}/><span><strong>Incluir medidas en stock</strong></span></label><label className="check-card"><input type="checkbox" checked={form.include_stock_by_color} disabled={readOnly||!form.stock_enabled} onChange={e=>update('include_stock_by_color',e.target.checked)}/><span><strong>Incluir stock por color</strong></span></label><label className="check-card"><input type="checkbox" checked={form.scaled} disabled={readOnly} onChange={e=>update('scaled',e.target.checked)}/><span><strong>Escalado</strong><small>Las relaciones de escalado se habilitan inmediatamente al activar esta opción.</small></span></label><label className="check-card"><input type="checkbox" checked={form.scaled_by_characteristic} disabled={readOnly||!form.scaled} onChange={e=>update('scaled_by_characteristic',e.target.checked)}/><span><strong>Escalado por característica</strong><small>Requiere escalado.</small></span></label><label className="check-card"><input type="checkbox" checked={form.smooth_cut} disabled={readOnly} onChange={e=>update('smooth_cut',e.target.checked)}/><span><strong>Corte liso</strong></span></label><label className="check-card"><input type="checkbox" checked={form.monochrome} disabled={readOnly} onChange={e=>update('monochrome',e.target.checked)}/><span><strong>Monocromo</strong></span></label></div></section>
      <section className="panel"><div className="panel-head"><div><h2>Observaciones</h2></div></div><label className="wide-label">Notas<textarea readOnly={readOnly} value={form.notes??''} onChange={e=>update('notes',e.target.value||null)}/></label></section>
    </form>
  </div>;
}
