import './otd-increment.css';

type FormulaVariable = { code:string; name:string };
type FormulaHost = { input:HTMLInputElement; editor:HTMLDivElement; suggestions:HTMLDivElement; lastValue:string; variableSignature:string; selectedIndex:number };

const formulaPlaceholders = new Set(['Expresión técnica (opcional)','Ej. 1','Ej. COLOR_CLIENTE','Ej. ANCHO_UTIL']);
const hosts = new WeakMap<HTMLInputElement,FormulaHost>();

function escape(value:string){return value.replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]??c));}
function currentVariableCode(input:HTMLInputElement){return input.closest('.otd-rule-line')?.querySelector<HTMLInputElement>('input[placeholder="Código"]')?.value.trim()??'';}
function collectVariables(selector:string):FormulaVariable[]{return [...document.querySelectorAll<HTMLInputElement>(selector)].map(codeInput=>({code:codeInput.value.trim(),name:codeInput.parentElement?.querySelector<HTMLInputElement>('input[placeholder="Nombre"]')?.value.trim()??''})).filter(v=>Boolean(v.code));}
function getOfficeVariables():FormulaVariable[]{const card=[...document.querySelectorAll<HTMLElement>('.otd-card')].find(x=>x.querySelector('.otd-card-head h2')?.textContent?.trim()==='Entradas para oficina');if(!card)return [];return [...card.querySelectorAll<HTMLInputElement>('input[placeholder="Código"]')].filter(input=>!input.closest('.option-list')).map(codeInput=>({code:codeInput.value.trim(),name:codeInput.parentElement?.querySelector<HTMLInputElement>('input[placeholder="Nombre"]')?.value.trim()??''})).filter(v=>Boolean(v.code));}
function getVariableCandidates(excludeCode=''):FormulaVariable[]{const calculated=collectVariables('.otd-rule-line input[placeholder="Código"]');const office=getOfficeVariables();const seen=new Set<string>();return [...office,...calculated].filter(v=>v.code!==excludeCode&&!seen.has(v.code)&&seen.add(v.code));}
function variableSignature(){return getVariableCandidates().map(v=>`${v.code}::${v.name}`).join('|');}
function tokenRegex(variables:FormulaVariable[]){const codes=variables.map(v=>v.code).sort((a,b)=>b.length-a.length).map(x=>x.replace(/[.*+?^${}()|[\]\\]/g,'\\$&'));return codes.length?new RegExp(`(${codes.join('|')})`,'g'):null;}
function render(value:string,variables:FormulaVariable[]){const codes=variables.map(v=>v.code);const re=tokenRegex(variables);if(!re)return escape(value);return value.split(re).map(part=>codes.includes(part)?`<span class="formula-token" data-token="${escape(part)}" contenteditable="false">${escape(part)}</span>`:escape(part)).join('');}
function read(root:HTMLElement){let out='';root.childNodes.forEach(n=>{if(n.nodeType===Node.ELEMENT_NODE&&(n as HTMLElement).dataset.token)out+=(n as HTMLElement).dataset.token;else out+=n.textContent??''});return out;}
function currentQuery(root:HTMLElement){const sel=window.getSelection();if(sel&&sel.rangeCount&&root.contains(sel.anchorNode)){const range=sel.getRangeAt(0);if(range.collapsed&&range.startContainer.nodeType===Node.TEXT_NODE)return(range.startContainer.textContent??'').slice(0,range.startOffset).match(/[A-Za-z_][A-Za-z0-9_]*$/)?.[0]??''}return read(root).match(/[A-Za-z_][A-Za-z0-9_]*$/)?.[0]??'';}
function filteredCandidates(host:FormulaHost){const query=currentQuery(host.editor).toLowerCase();if(!query)return [];return getVariableCandidates(currentVariableCode(host.input)).filter(v=>v.code.toLowerCase().includes(query)||v.name.toLowerCase().includes(query)).slice(0,8);}
function setSelectedIndex(host:FormulaHost,index:number){const buttons=[...host.suggestions.querySelectorAll<HTMLButtonElement>('button')];host.selectedIndex=Math.max(0,Math.min(index,buttons.length-1));buttons.forEach((b,i)=>b.classList.toggle('is-selected',i===host.selectedIndex));buttons[host.selectedIndex]?.scrollIntoView({block:'nearest'});}
function deleteCurrentQuery(root:HTMLElement){const query=currentQuery(root);if(!query)return;const sel=window.getSelection();if(!sel?.rangeCount)return;const range=sel.getRangeAt(0);if(range.collapsed&&range.startContainer.nodeType===Node.TEXT_NODE){const start=range.startOffset-query.length;if(start>=0){range.setStart(range.startContainer,start);range.deleteContents();}}}
function insertTokenAtCaret(root:HTMLElement,code:string){const sel=window.getSelection();const range=sel?.rangeCount?sel.getRangeAt(0):null;if(range&&root.contains(range.commonAncestorContainer))deleteCurrentQuery(root);const activeRange=sel?.rangeCount?sel.getRangeAt(0):null;const token=document.createElement('span');token.className='formula-token';token.dataset.token=code;token.contentEditable='false';token.textContent=code;const space=document.createTextNode(' ');if(activeRange&&root.contains(activeRange.commonAncestorContainer)){activeRange.insertNode(token);token.after(space);activeRange.setStartAfter(space);activeRange.collapse(true);sel?.removeAllRanges();sel?.addRange(activeRange)}else root.append(token,space);}
function refreshSuggestions(host:FormulaHost){host.suggestions.innerHTML='';const candidates=filteredCandidates(host);host.selectedIndex=0;if(!candidates.length){host.suggestions.classList.remove('visible');return;}candidates.forEach((v,i)=>{const button=document.createElement('button');button.type='button';button.classList.toggle('is-selected',i===0);button.innerHTML=`<span class="formula-token-suggestion-chip">${escape(v.code)}</span><span><strong>${escape(v.name||v.code)}</strong></span>`;button.addEventListener('mousedown',e=>e.preventDefault());button.addEventListener('click',()=>selectCandidate(host,v));host.suggestions.appendChild(button)});host.suggestions.classList.add('visible');}
function selectCandidate(host:FormulaHost,candidate:FormulaVariable){host.editor.focus();insertTokenAtCaret(host.editor,candidate.code);const value=read(host.editor);host.lastValue=value;host.input.value=value;host.input.dispatchEvent(new Event('input',{bubbles:true}));host.suggestions.classList.remove('visible');host.selectedIndex=0;}
function enhance(input:HTMLInputElement){if(hosts.has(input))return;const wrapper=document.createElement('div');wrapper.className='formula-token-editor';const editor=document.createElement('div');editor.className='formula-token-input';editor.contentEditable='true';editor.dataset.placeholder=input.placeholder||'Escribe una fórmula…';const suggestions=document.createElement('div');suggestions.className='formula-token-suggestions';wrapper.append(editor,suggestions);input.style.display='none';input.parentElement?.insertBefore(wrapper,input);const host:FormulaHost={input,editor,suggestions,lastValue:input.value,variableSignature:variableSignature(),selectedIndex:0};hosts.set(input,host);editor.innerHTML=render(input.value,getVariableCandidates(currentVariableCode(input)));editor.addEventListener('focus',()=>refreshSuggestions(host));editor.addEventListener('blur',()=>setTimeout(()=>suggestions.classList.remove('visible'),150));editor.addEventListener('input',()=>{const value=read(editor);host.lastValue=value;input.value=value;input.dispatchEvent(new Event('input',{bubbles:true}));refreshSuggestions(host)});editor.addEventListener('keydown',event=>{const buttons=suggestions.querySelectorAll('button');if(!suggestions.classList.contains('visible')||!buttons.length)return;if(event.key==='ArrowDown'){event.preventDefault();setSelectedIndex(host,host.selectedIndex+1)}else if(event.key==='ArrowUp'){event.preventDefault();setSelectedIndex(host,host.selectedIndex-1)}else if(event.key==='Enter'){event.preventDefault();const candidate=filteredCandidates(host)[host.selectedIndex];if(candidate)selectCandidate(host,candidate)}else if(event.key==='Escape'){event.preventDefault();suggestions.classList.remove('visible')}});const localObserver=new MutationObserver(()=>{const signature=variableSignature();if(signature===host.variableSignature)return;host.variableSignature=signature;const vars=getVariableCandidates(currentVariableCode(input));if(document.activeElement!==editor)editor.innerHTML=render(host.lastValue,vars);if(document.activeElement===editor)refreshSuggestions(host)});localObserver.observe(document.querySelector('.otd-card')||document.body,{subtree:true,childList:true,characterData:true});}

function enhanceComponentIncrement(root:HTMLElement){if(root.dataset.incrementEnhanced==='true')return;const labels=[...root.querySelectorAll<HTMLLabelElement>('label')];const label=labels.find(x=>x.textContent?.trim().startsWith('Incremento'));const input=label?.querySelector<HTMLInputElement>('input[type="number"]');if(!label||!input)return;root.dataset.incrementEnhanced='true';const wrapper=document.createElement('div');wrapper.className='otd-increment-type';const select=document.createElement('select');select.innerHTML='<option value="FIXED">Importe fijo (€)</option><option value="PERCENTAGE">Porcentaje (%)</option>';select.value=Number(input.value)<0?'PERCENTAGE':'FIXED';const sync=()=>{const percentage=select.value==='PERCENTAGE';const numeric=Math.abs(Number(input.value)||0);input.value=percentage?String(-numeric):String(numeric);input.dispatchEvent(new Event('input',{bubbles:true}));const textNode=[...label.childNodes].find(n=>n.nodeType===Node.TEXT_NODE);if(textNode)textNode.textContent=percentage?'Incremento (%)':'Incremento (€)';};select.addEventListener('change',sync);wrapper.appendChild(select);label.parentElement?.insertBefore(wrapper,label);};
function scanComponents(){document.querySelectorAll<HTMLElement>('.otd-row-card').forEach(enhanceComponentIncrement);}
function scan(){document.querySelectorAll<HTMLInputElement>('.otd-page input').forEach(input=>{if(formulaPlaceholders.has(input.placeholder)||input.classList.contains('formula-input'))enhance(input)});scanComponents();}
const observer=new MutationObserver(scan);observer.observe(document.body,{subtree:true,childList:true});if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',scan);else scan();
