import { useEffect, useState } from 'react';
import { ArrowLeft } from 'lucide-react';
import { useNavigate, useParams } from 'react-router-dom';
import { supabase } from '../../lib/supabase';
import { CoreRepositoryError } from '../../services/core/coreRepository';
import './quotation.css';

type Detail = { id:number; code:string; issue_date:string; valid_until:string|null; status:string; reference:string|null; notes:string|null; net_amount:number; discount_amount:number; tax_amount:number; total_amount:number; customer:any; commercial:any; warehouse:any; payment_method:any; payment_term:any; lines:any[] };
const money=(n:number)=>n.toLocaleString('es-ES',{style:'currency',currency:'EUR'});
const statusLabel=(s:string)=>({DRAFT:'Borrador',SENT:'Enviado',ACCEPTED:'Aceptado',REJECTED:'Rechazado',EXPIRED:'Caducado'} as Record<string,string>)[s]||s;
const partyName=(p:any)=>p?.party?.trade_name||p?.party?.legal_name||'Sin asignar';

export function QuotationDetail(){
 const {id}=useParams(); const nav=useNavigate(); const [data,setData]=useState<Detail|null>(null); const [loading,setLoading]=useState(true); const [error,setError]=useState('');
 useEffect(()=>{let active=true;(async()=>{try{if(!supabase)throw new CoreRepositoryError('Supabase no está configurado.');const {data:{user},error:ue}=await supabase.auth.getUser();if(ue||!user)throw new CoreRepositoryError('No hay un usuario autenticado.');const {data:ua,error:uae}=await supabase.from('user_account').select('company_id').eq('auth_user_id',user.id).maybeSingle();if(uae)throw new CoreRepositoryError(uae.message);if(ua?.company_id==null)throw new CoreRepositoryError('El usuario no tiene empresa asignada.');const {data:q,error:qe}=await supabase.from('quotation').select('id,code,issue_date,valid_until,status,reference,notes,net_amount,discount_amount,tax_amount,total_amount,customer:customer_id(party:party_id(legal_name,trade_name)),commercial:commercial_id(party:party_id(legal_name,trade_name)),warehouse:warehouse_id(code,name),payment_method:payment_method_id(code,name),payment_term:payment_term_id(code,name),lines:quotation_line(id,line_no,description,quantity,unit_price,discount_percent,tax_percent,net_amount,tax_amount,total_amount,product:product_id(code,commercial_description,technical_description))').eq('company_id',ua.company_id).eq('id',Number(id)).maybeSingle();if(qe)throw new CoreRepositoryError(qe.message);if(!q)throw new CoreRepositoryError('Presupuesto no encontrado.');if(active)setData(q as unknown as Detail);}catch(e){if(active)setError(e instanceof Error?e.message:'No se pudo cargar el presupuesto.');}finally{if(active)setLoading(false);}})();return()=>{active=false};},[id]);
 if(loading)return <div className="module-page"><p>Cargando presupuesto…</p></div>;
 if(error||!data)return <div className="module-page"><div className="page-head"><div><button type="button" className="button secondary" onClick={()=>nav('/ventas/presupuestos')}><ArrowLeft size={16}/>Presupuestos</button><h1>Presupuesto</h1></div></div><div className="inline-error">{error||'Presupuesto no encontrado.'}</div></div>;
 return <div className="module-page quotation-page"><div className="page-head"><div><button type="button" className="button secondary" onClick={()=>nav('/ventas/presupuestos')}><ArrowLeft size={16}/>Presupuestos</button><div className="eyebrow">VENTAS / PRESUPUESTOS</div><h1>{data.code}</h1><p>{partyName(data.customer)} · {new Date(`${data.issue_date}T00:00:00`).toLocaleDateString('es-ES')}</p></div><span className={`quotation-status ${data.status.toLowerCase()}`}>{statusLabel(data.status)}</span></div><section className="panel"><div className="panel-head"><div><h2>Datos del presupuesto</h2><p>Información comercial y condiciones.</p></div></div><div className="form-grid"><div><small>Cliente</small><strong>{partyName(data.customer)}</strong></div><div><small>Comercial</small><strong>{partyName(data.commercial)}</strong></div><div><small>Almacén</small><strong>{data.warehouse?.code?`${data.warehouse.code} · ${data.warehouse.name}`:data.warehouse?.name||'Sin asignar'}</strong></div><div><small>Forma de pago</small><strong>{data.payment_method?.code?`${data.payment_method.code} · ${data.payment_method.name}`:data.payment_method?.name||'Sin especificar'}</strong></div><div><small>Condiciones de pago</small><strong>{data.payment_term?.code?`${data.payment_term.code} · ${data.payment_term.name}`:data.payment_term?.name||'Sin especificar'}</strong></div><div><small>Referencia</small><strong>{data.reference||'—'}</strong></div></div></section><section className="panel"><div className="panel-head"><div><h2>Líneas</h2><p>Detalle del presupuesto.</p></div></div><div className="table-panel"><table><thead><tr><th>#</th><th>Artículo</th><th>Descripción</th><th>Cantidad</th><th>Precio</th><th>Dto.</th><th>IVA</th><th className="numeric">Total</th></tr></thead><tbody>{(data.lines||[]).sort((a,b)=>a.line_no-b.line_no).map(l=><tr key={l.id}><td>{l.line_no}</td><td>{l.product?.code||'Manual'}</td><td>{l.description}</td><td>{Number(l.quantity).toLocaleString('es-ES')}</td><td>{money(Number(l.unit_price||0))}</td><td>{Number(l.discount_percent||0)}%</td><td>{Number(l.tax_percent||0)}%</td><td className="numeric"><strong>{money(Number(l.total_amount||0))}</strong></td></tr>)}</tbody></table></div><div className="quote-totals"><span>Neto <strong>{money(Number(data.net_amount||0))}</strong></span><span>Descuento <strong>{money(Number(data.discount_amount||0))}</strong></span><span>IVA <strong>{money(Number(data.tax_amount||0))}</strong></span><span>Total <strong>{money(Number(data.total_amount||0))}</strong></span></div></section>{data.notes&&<section className="panel"><div className="panel-head"><div><h2>Observaciones</h2></div></div><p>{data.notes}</p></section>}</div>;
}
