import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { createPortal } from 'react-dom';
import { ArrowLeft, ChevronDown, ChevronUp, Plus, Search, Trash2, X } from 'lucide-react';
import { Link, useNavigate } from 'react-router-dom';
import { CoreRepositoryError } from '../../services/core/coreRepository';
import { createQuotation, customerAddresses, customerProductDiscount, quotationOptions, type ProductLineBehavior } from '../../services/sales/quotationCreationRepository';
import { MessageLog } from '../../components/ui/MessageLog';
import { ProfileSaveBar } from '../../components/ui/ProfileSaveBar';
import { Toast } from '../../components/ui/Toast';
import { effectiveLineBehavior } from './QuotationLineBehavior';
import './quotation-create.css';

const today=()=>new Date().toISOString().slice(0,10);
const money=(n:number)=>n.toLocaleString('es-ES',{style:'currency',currency:'EUR'});
type LineDimension={code:string;name:string;value:string;unit:string};
type LineSpecific={length:string;line:string;exit:string;cutType:string;hem:string;overlap:string;selectedWidth:string;configuration:string};
type Line={product_id:number|null;description:string;quantity:number;unit_price:number;discount_percent:number;line_behavior:ProductLineBehavior|null;dimensions:LineDimension[];characteristics:string;specific:LineSpecific};
const emptySpecific=():LineSpecific=>({length:'',line:'',exit:'',cutType:'',hem:'',overlap:'',selectedWidth:'',configuration:''});
const blank=():Line=>({product_id:null,description:'',quantity:1,unit_price:0,discount_percent:0,line_behavior:null,dimensions:[],characteristics:'',specific:emptySpecific()});
type Option={id:number;label:string;code?:string;price?:number;lineBehavior?:ProductLineBehavior|null};
type AddressDraft={source_id:number|null;label:string;street:string;postal_code:string;city:string;region:string};
const emptyAddress=():AddressDraft=>({source_id:null,label:'',street:'',postal_code:'',city:'',region:''});
const addressDraft=(a:any):AddressDraft=>({source_id:a?.id??null,label:a?.label||({FACTURACION:'Facturación',FISCAL:'Fiscal',INSTALACION:'Instalación'} as Record<string,string>)[String(a?.address_type||'').toUpperCase()]||'Dirección',street:a?.street||'',postal_code:a?.postal_code||'',city:a?.city||'',region:a?.region||''});

export function QuotationCreate(){
 const nav=useNavigate();
 const [opts,setOpts]=useState<any>(); const [addresses,setAddresses]=useState<any[]>([]); const [customerId,setCustomerId]=useState<number|null>(null);
 const [commercialId,setCommercialId]=useState<number|null>(null); const [warehouseId,setWarehouseId]=useState<number|null>(null); const [billingId,setBillingId]=useState<number|null>(null);
 const [installationId,setInstallationId]=useState<number|null>(null); const [billingAddress,setBillingAddress]=useState<AddressDraft>(emptyAddress()); const [installationAddress,setInstallationAddress]=useState<AddressDraft>(emptyAddress());
 const [paymentMethodId,setPaymentMethodId]=useState<number|null>(null); const [paymentTermId,setPaymentTermId]=useState<number|null>(null);
 const [taxRateId,setTaxRateId]=useState<number|null>(null); const [taxPercent,setTaxPercent]=useState(0); const [issueDate,setIssueDate]=useState(today()); const [validUntil,setValidUntil]=useState('');
 const [reference,setReference]=useState(''); const [notes,setNotes]=useState(''); const [lines,setLines]=useState<Line[]>([blank()]); const [error,setError]=useState(''); const [toast,setToast]=useState('');
 const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [headerCollapsed,setHeaderCollapsed]=useState(false); const [expandedLines,setExpandedLines]=useState<Set<number>>(new Set()); const [pendingCustomerId,setPendingCustomerId]=useState<number|null>(null); const [changingCustomer,setChangingCustomer]=useState(false);
 useEffect(()=>{void quotationOptions().then(setOpts).catch(e=>setError(e instanceof Error?e.message:'No se pudieron cargar los datos.')).finally(()=>setLoading(false));},[]);
 const totals=useMemo(()=>lines.reduce((a,l)=>{const gross=Math.max(0,l.quantity*l.unit_price);const net=Math.max(0,gross*(1-l.discount_percent/100));return{gross:a.gross,discount:a.discount+(gross-net),net:a.net+net,tax:a.tax+net*taxPercent/100,total:a.total+net*(1+taxPercent/100)};},{gross:0,discount:0,net:0,tax:0,total:0}),[lines,taxPercent]);
 const change=(i:number,key:keyof Line,value:string)=>setLines(xs=>xs.map((l,j)=>j===i?{...l,[key]:key==='description'?value:Number(value)}:l));
 const updateLine=(i:number,patch:Partial<Line>)=>setLines(xs=>xs.map((l,j)=>j===i?{...l,...patch}:l));
 const product=async(i:number,id:number|null)=>{const p=opts?.products?.find((x:any)=>x.id===id);if(id===null){updateLine(i,{product_id:null,description:'',unit_price:0,discount_percent:0,line_behavior:null,dimensions:[],characteristics:'',specific:emptySpecific()});return;}try{const discount=customerId?await customerProductDiscount(customerId,id):null;const behavior=p?.lineBehavior??null;updateLine(i,{product_id:id,description:p?.label||'',unit_price:p?.price??0,discount_percent:discount?.discount_percent??0,line_behavior:behavior});setExpandedLines(s=>new Set(s).add(i));if(discount)setToast(`El cliente tiene descuentos aplicados (${discount.level==='article'?'artículo':'familia'}: ${discount.discount_percent}%).`);}catch(e){setError(e instanceof Error?e.message:'No se pudo recuperar el descuento del cliente.');}};
 const closeToast=useCallback(()=>setToast(''),[]);
 const requestCustomerChange=(id:number|null)=>{if(id===customerId)return;setPendingCustomerId(id);};
 const cancelCustomerChange=()=>setPendingCustomerId(null);
 const applyCustomerAddresses=(rows:any[])=>{setAddresses(rows);const billing=rows.find((a:any)=>['FACTURACION','FISCAL'].includes(String(a.address_type).toUpperCase()));const installation=rows.find((a:any)=>String(a.address_type).toUpperCase()==='INSTALACION');setBillingId(billing?.id??null);setInstallationId(installation?.id??null);setBillingAddress(addressDraft(billing));setInstallationAddress(addressDraft(installation));};
 const confirmCustomerChange=async()=>{const id=pendingCustomerId;setPendingCustomerId(null);if(id===customerId)return;setChangingCustomer(true);setError('');try{setCustomerId(id);if(id===null){setAddresses([]);setBillingId(null);setInstallationId(null);setBillingAddress(emptyAddress());setInstallationAddress(emptyAddress());setLines(xs=>xs.map(l=>({...l,discount_percent:0})));return;}const rows=await customerAddresses(id);applyCustomerAddresses(rows);const discounted=await Promise.all(lines.map(async l=>l.product_id?customerProductDiscount(id,l.product_id):null));setLines(xs=>xs.map((l,i)=>({...l,discount_percent:discounted[i]?.discount_percent??0})));if(discounted.some(Boolean))setToast('El cliente tiene descuentos aplicados.');}catch(e){setError(e instanceof Error?e.message:'No se pudieron recalcular los datos asociados al cliente.');}finally{setChangingCustomer(false);}};
 useEffect(()=>{if(!customerId){setAddresses([]);setBillingId(null);setInstallationId(null);setBillingAddress(emptyAddress());setInstallationAddress(emptyAddress());return;}void customerAddresses(customerId).then(applyCustomerAddresses).catch(e=>setError(e instanceof Error?e.message:'No se pudieron cargar las direcciones del cliente.'));},[customerId]);
 const toggleLine=(i:number)=>setExpandedLines(s=>{const next=new Set(s);if(next.has(i))next.delete(i);else next.add(i);return next;});
 const updateDimension=(i:number,d:number,key:'name'|'value'|'unit',value:string)=>setLines(xs=>xs.map((l,j)=>j===i?{...l,dimensions:l.dimensions.map((x,k)=>k===d?{...x,[key]:value}:x)}:l));
 const addDimension=(i:number)=>setLines(xs=>xs.map((l,j)=>j===i?{...l,dimensions:[...l.dimensions,{code:`DIM_${l.dimensions.length+1}`,name:'',value:'',unit:''}]}:l));
 const removeDimension=(i:number,d:number)=>setLines(xs=>xs.map((l,j)=>j===i?{...l,dimensions:l.dimensions.filter((_,k)=>k!==d)}:l));
 async function save(e?:React.FormEvent){e?.preventDefault();setError('');if(!customerId){setError('Selecciona un cliente.');return;}setSaving(true);try{await createQuotation({customer_id:customerId,commercial_id:commercialId,warehouse_id:warehouseId,billing_address_id:billingId,installation_address_id:installationId,billing_address:billingAddress,installation_address:installationAddress,payment_method_id:paymentMethodId,payment_term_id:paymentTermId,measurement_id:null,tax_rate_id:taxRateId,tax_percent:taxPercent,issue_date:issueDate,valid_until:validUntil||null,reference,notes,lines:lines.map(({line_behavior:_,dimensions:__,characteristics:___,specific:____,...line})=>line)});nav('/ventas/presupuestos');}catch(e){setError(e instanceof CoreRepositoryError?e.message:e instanceof Error?e.message:'No se pudo guardar el presupuesto.');}finally{setSaving(false);}}
 if(loading)return <div className="module-page"><div className="page-head"><div><div className="eyebrow">VENTAS / PRESUPUESTOS / NUEVO</div><h1>Nuevo presupuesto</h1></div></div><p>Cargando datos…</p></div>;
 return <div className="module-page quotation-create">
  <div className="page-head"><div><div className="eyebrow">VENTAS / PRESUPUESTOS / NUEVO</div><h1>Nuevo presupuesto</h1><p>Crear presupuesto en estado borrador.</p></div><Link className="secondary-button" to="/ventas/presupuestos"><ArrowLeft size={15}/>Volver a presupuestos</Link></div>
  <MessageLog error={error}/>{toast&&<Toast message={toast} onClose={closeToast}/>} 
  <form id="quotation-create-form" className="detail-grid" onSubmit={save}>
   <section className="panel quotation-header-panel">
    <div className="panel-head"><div><h2>Datos generales</h2><p>Cliente, condiciones comerciales y direcciones del presupuesto.</p></div><button type="button" className="secondary-button" onClick={()=>setHeaderCollapsed(v=>!v)}>{headerCollapsed?<><ChevronDown size={15}/>Mostrar cabecera</>:<><ChevronUp size={15}/>Contraer cabecera</>}</button></div>
    {!headerCollapsed&&<div className="form-grid">
     <label className="quotation-reference-field">Referencia<input value={reference} onChange={e=>setReference(e.target.value)} /></label>
     <LookupSelect label="Cliente" required options={opts.customers} value={customerId} onChange={requestCustomerChange} placeholder="Buscar cliente por nombre…" />
     <label>Comercial<select value={commercialId??''} onChange={e=>setCommercialId(e.target.value?Number(e.target.value):null)}><option value="">Sin asignar</option>{opts.commercials.map((x:any)=><option key={x.id} value={x.id}>{x.label}</option>)}</select></label>
     <label>Almacén<select value={warehouseId??''} onChange={e=>setWarehouseId(e.target.value?Number(e.target.value):null)}><option value="">Sin asignar</option>{opts.warehouses.map((x:any)=><option key={x.id} value={x.id}>{x.label}</option>)}</select></label>
     <label className="date-field">Fecha de Documento<input type="date" value={issueDate} onChange={e=>setIssueDate(e.target.value)} required/></label><label className="date-field">Válido hasta<input type="date" value={validUntil} onChange={e=>setValidUntil(e.target.value)}/></label>
     <label>Forma de pago<select value={paymentMethodId??''} onChange={e=>setPaymentMethodId(e.target.value?Number(e.target.value):null)}><option value="">Sin especificar</option>{opts.paymentMethods.map((x:any)=><option key={x.id} value={x.id}>{x.label}</option>)}</select></label>
     <label>Condiciones de pago<select value={paymentTermId??''} onChange={e=>setPaymentTermId(e.target.value?Number(e.target.value):null)}><option value="">Sin especificar</option>{opts.paymentTerms.map((x:any)=><option key={x.id} value={x.id}>{x.label}</option>)}</select></label>
     <label>IVA<select value={taxRateId??''} onChange={e=>{const id=e.target.value?Number(e.target.value):null;const t=opts.taxRates.find((x:any)=>x.id===id);setTaxRateId(id);setTaxPercent(Number(t?.rate??0));}}><option value="">Sin IVA</option>{opts.taxRates.map((t:any)=><option key={t.id} value={t.id}>{t.rate}% · {t.label}</option>)}</select></label>
     <AddressEditor title="Dirección de facturación" addresses={addresses} value={billingAddress} onChange={setBillingAddress} onSourceChange={id=>setBillingId(id)} />
     <AddressEditor title="Dirección de instalación" addresses={addresses} value={installationAddress} onChange={setInstallationAddress} onSourceChange={id=>setInstallationId(id)} />
    </div>}
   </section>
   <section className="panel quotation-lines-panel">
    <div className="panel-head"><div><h2>Líneas del presupuesto</h2><p>El comportamiento de cada línea se determina por el artículo y su familia.</p></div><div className="panel-actions"><button type="button" className="primary-button" onClick={()=>setLines(xs=>[...xs,blank()])}><Plus size={15}/>Añadir línea</button></div></div>
    <div className="table-panel quotation-lines-table"><table><thead><tr><th>Artículo</th><th>Descripción</th><th>Cant.</th><th>Precio</th><th>Dto.</th><th className="numeric">Total</th><th></th></tr></thead><tbody>{lines.map((l,i)=>{const behavior=effectiveLineBehavior(l.line_behavior);const total=Math.max(0,l.quantity*l.unit_price*(1-l.discount_percent/100))*(1+taxPercent/100);const advanced=hasAdvancedBehavior(behavior);const expanded=expandedLines.has(i);return <><tr key={`line-${i}`} className={expanded?'line-expanded':''}><td className="article-cell"><LookupSelect compact options={opts.products} value={l.product_id} onChange={id=>void product(i,id)} placeholder="Buscar artículo por código o descripción…" />{advanced&&<button type="button" className="line-config-trigger" onClick={()=>toggleLine(i)} aria-expanded={expanded}>{expanded?<><ChevronUp size={14}/>Ocultar configuración</>:<><ChevronDown size={14}/>Configurar línea</>}</button>}</td><td className="description-cell"><input value={l.description} onChange={e=>change(i,'description',e.target.value)} required /></td><td className="quantity-cell"><input type="number" min="0.01" step="0.01" value={l.quantity} disabled={!behavior.quantity_enabled} onChange={e=>change(i,'quantity',e.target.value)} /></td><td className="price-cell"><input type="number" min="0" step="0.01" value={l.unit_price} disabled={!behavior.price_enabled} onChange={e=>change(i,'unit_price',e.target.value)} /></td><td className="discount-cell"><input type="number" min="0" max="100" step="0.01" value={l.discount_percent} disabled={!behavior.discount_enabled} onChange={e=>change(i,'discount_percent',e.target.value)} /></td><td className="numeric">{money(total)}</td><td><button type="button" className="icon-button" aria-label="Eliminar línea" disabled={lines.length===1} onClick={()=>setLines(xs=>xs.filter((_,j)=>j!==i))}><Trash2 size={16}/></button></td></tr>{expanded&&<tr key={`details-${i}`} className="line-details-row"><td colSpan={7}><QuotationLineDetails line={l} behavior={behavior} onAddDimension={()=>addDimension(i)} onRemoveDimension={d=>removeDimension(i,d)} onDimensionChange={(d,k,v)=>updateDimension(i,d,k,v)} onCharacteristicsChange={v=>updateLine(i,{characteristics:v})} onSpecificChange={patch=>updateLine(i,{specific:{...l.specific,...patch}})}/></td></tr>}</>})}</tbody></table></div>
    <div className="quote-totals"><span>Base imponible <strong>{money(totals.net)}</strong></span><span>Descuentos <strong>{money(totals.discount)}</strong></span><span>Impuestos ({taxPercent}%) <strong>{money(totals.tax)}</strong></span><span>Total <strong>{money(totals.total)}</strong></span></div>
   </section>
   <section className="panel quotation-notes-panel"><label className="wide-field"><span className="sr-only">Observaciones</span><textarea aria-label="Observaciones" placeholder="Observaciones" rows={5} value={notes} onChange={e=>setNotes(e.target.value)} /></label></section>
  </form>
  <ProfileSaveBar onSave={()=>{const formElement=document.getElementById('quotation-create-form') as HTMLFormElement|null;formElement?.requestSubmit();}} saving={saving} label="Crear presupuesto" />
  {pendingCustomerId!==null&&<ConfirmationDialog title="Cambiar cliente" message="Al cambiar el cliente se recalcularán las direcciones y los descuentos aplicados a las líneas del presupuesto. ¿Quieres continuar?" confirmLabel="Cambiar cliente" busy={changingCustomer} onCancel={cancelCustomerChange} onConfirm={confirmCustomerChange}/>} 
 </div>;
}

function hasAdvancedBehavior(b:ProductLineBehavior){return b.dimensions_enabled||b.configuration_enabled||b.cut_calculation_enabled||b.length_enabled||b.characteristics_enabled||b.canvas_cut_enabled;}

function QuotationLineDetails({line,behavior,onAddDimension,onRemoveDimension,onDimensionChange,onCharacteristicsChange,onSpecificChange}:{line:Line;behavior:ProductLineBehavior;onAddDimension:()=>void;onRemoveDimension:(i:number)=>void;onDimensionChange:(i:number,k:'name'|'value'|'unit',v:string)=>void;onCharacteristicsChange:(v:string)=>void;onSpecificChange:(p:Partial<LineSpecific>)=>void}){
 const dimensionEnabled=behavior.dimensions_enabled; const profile=behavior.length_enabled||behavior.cut_calculation_enabled; const canvas=behavior.canvas_cut_enabled;
 return <div className="quotation-line-details">
  <div className="line-details-head"><div><strong>{behavior.name}</strong><span>{behavior.description||'Configuración específica de la línea'}</span></div><div className="line-capability-list">{[dimensionEnabled&&'Dimensiones',behavior.configuration_enabled&&'Configuración',behavior.cut_calculation_enabled&&'Cálculo de corte',behavior.length_enabled&&'Longitud',behavior.characteristics_enabled&&'Características',canvas&&'Corte de lona'].filter(Boolean).map(x=><span key={String(x)}>{x}</span>)}</div></div>
  {dimensionEnabled&&<div className="line-detail-section"><div className="line-detail-title"><span>Dimensiones</span><button type="button" className="secondary-button compact-action" onClick={onAddDimension}><Plus size={13}/>Añadir dimensión</button></div>{line.dimensions.length===0?<div className="line-detail-empty">Añade solo las dimensiones necesarias para este artículo.</div>:<div className="dimension-grid">{line.dimensions.map((d,i)=><div className="dimension-item" key={`${d.code}-${i}`}><label>Nombre<input value={d.name} onChange={e=>onDimensionChange(i,'name',e.target.value)} placeholder="Ej. Ancho"/></label><label>Valor<input type="number" step="0.01" value={d.value} onChange={e=>onDimensionChange(i,'value',e.target.value)}/></label><label>Unidad<input value={d.unit} onChange={e=>onDimensionChange(i,'unit',e.target.value)} placeholder="mm"/></label><button type="button" className="icon-button" aria-label="Eliminar dimensión" onClick={()=>onRemoveDimension(i)}><Trash2 size={14}/></button></div>)}</div>}</div>}
  {profile&&<div className="line-detail-section"><div className="line-detail-title"><span>Datos de perfil y corte</span></div><div className="specific-grid"><label>Longitud<input type="number" step="0.01" value={line.specific.length} onChange={e=>onSpecificChange({length:e.target.value})}/></label><label>Línea<input type="number" step="0.01" value={line.specific.line} onChange={e=>onSpecificChange({line:e.target.value})}/></label><label>Salida<input type="number" step="0.01" value={line.specific.exit} onChange={e=>onSpecificChange({exit:e.target.value})}/></label><label>Tipo de corte<input value={line.specific.cutType} onChange={e=>onSpecificChange({cutType:e.target.value})}/></label></div></div>}
  {canvas&&<div className="line-detail-section"><div className="line-detail-title"><span>Datos de lona</span></div><div className="specific-grid"><label>Línea<input type="number" step="0.01" value={line.specific.line} onChange={e=>onSpecificChange({line:e.target.value})}/></label><label>Salida<input type="number" step="0.01" value={line.specific.exit} onChange={e=>onSpecificChange({exit:e.target.value})}/></label><label>Tipo de corte<input value={line.specific.cutType} onChange={e=>onSpecificChange({cutType:e.target.value})}/></label><label>Dobladillo<input type="number" step="0.01" value={line.specific.hem} onChange={e=>onSpecificChange({hem:e.target.value})}/></label><label>Solape<input type="number" step="0.01" value={line.specific.overlap} onChange={e=>onSpecificChange({overlap:e.target.value})}/></label><label>Ancho seleccionado<input type="number" step="0.01" value={line.specific.selectedWidth} onChange={e=>onSpecificChange({selectedWidth:e.target.value})}/></label></div></div>}
  {behavior.configuration_enabled&&<div className="line-detail-section"><div className="line-detail-title"><span>Configuración</span></div><textarea rows={3} value={line.specific.configuration} onChange={e=>onSpecificChange({configuration:e.target.value})} placeholder="Configuración del artículo…"/></div>}
  {behavior.characteristics_enabled&&<div className="line-detail-section"><div className="line-detail-title"><span>Características</span></div><textarea rows={3} value={line.characteristics} onChange={e=>onCharacteristicsChange(e.target.value)} placeholder="Características seleccionadas…"/></div>}
 </div>;
}

function AddressEditor({title,addresses,value,onChange,onSourceChange}:{title:string;addresses:any[];value:AddressDraft;onChange:(value:AddressDraft)=>void;onSourceChange:(id:number|null)=>void}){const set=(key:keyof AddressDraft,next:string)=>onChange({...value,[key]:next});const selectSource=(id:number|null)=>{const source=addresses.find(a=>a.id===id);onSourceChange(id);onChange(source?addressDraft(source):{...value,source_id:id});};return <fieldset className="address-editor"><legend>{title}</legend><label className="address-source">Cargar desde cliente<select value={value.source_id??''} onChange={e=>selectSource(e.target.value?Number(e.target.value):null)}><option value="">Sin dirección de cliente</option>{addresses.map(a=><option key={a.id} value={a.id}>{addressLabel(a)}</option>)}</select></label><div className="address-editor-grid"><label className="address-street">Dirección<input value={value.street} onChange={e=>set('street',e.target.value)}/></label><label>Código Postal<input value={value.postal_code} onChange={e=>set('postal_code',e.target.value)}/></label><label>Localidad<input value={value.city} onChange={e=>set('city',e.target.value)}/></label><label>Provincia<input value={value.region} onChange={e=>set('region',e.target.value)}/></label></div></fieldset>}
function addressLabel(a:any){return [a.label||({FACTURACION:'Facturación',FISCAL:'Fiscal',INSTALACION:'Instalación'} as Record<string,string>)[String(a.address_type).toUpperCase()]||'Dirección',a.street,a.postal_code,a.city].filter(Boolean).join(' · ');}
function LookupSelect({label,required=false,compact=false,options,value,onChange,placeholder}:{label?:string;required?:boolean;compact?:boolean;options:Option[];value:number|null;onChange:(id:number|null)=>void;placeholder:string}){const [query,setQuery]=useState('');const [open,setOpen]=useState(false);const [rect,setRect]=useState<DOMRect|null>(null);const inputRef=useRef<HTMLInputElement|null>(null);const selected=options.find(x=>x.id===value);const filtered=useMemo(()=>{const q=query.trim().toLocaleLowerCase();if(!q)return options.slice(0,10);return options.filter(x=>`${x.code??''} ${x.label}`.toLocaleLowerCase().includes(q)).slice(0,10);},[options,query]);const reposition=()=>{if(inputRef.current)setRect(inputRef.current.closest('.lookup-control')?.getBoundingClientRect()??inputRef.current.getBoundingClientRect());};useEffect(()=>{if(!open)return;reposition();const onScroll=()=>reposition();window.addEventListener('scroll',onScroll,true);window.addEventListener('resize',onScroll);return()=>{window.removeEventListener('scroll',onScroll,true);window.removeEventListener('resize',onScroll);};},[open]);return <div className={`lookup-field ${compact?'lookup-field-compact':''}`}>{label&&<span className="field-label">{label}{required?' *':''}</span>}<div className="lookup-control"><Search size={15}/><input ref={inputRef} required={required&&!value} value={open?query:(selected?.label??'')} placeholder={placeholder} onFocus={()=>{setOpen(true);if(selected)setQuery(selected.label);}} onChange={e=>{setQuery(e.target.value);setOpen(true);if(value!==null)onChange(null);}}/>{selected&&<button type="button" className="lookup-clear" aria-label="Limpiar selección" onClick={()=>{setQuery('');onChange(null);setOpen(false);}}><X size={14}/></button>}</div>{open&&rect&&createPortal(<div className="lookup-portal"><button type="button" className="lookup-dismiss" aria-label="Cerrar resultados" onClick={()=>setOpen(false)}/><div className="lookup-results" style={{top:rect.bottom+4,left:rect.left,width:Math.max(rect.width,280)}}>{filtered.length===0?<small>No se han encontrado resultados.</small>:filtered.map(x=><button type="button" key={x.id} onMouseDown={e=>e.preventDefault()} onClick={()=>{onChange(x.id);setQuery('');setOpen(false);}}><strong>{x.code?`${x.code} · `:''}{x.label}</strong></button>)}</div></div>,document.body)}</div>}
function ConfirmationDialog({title,message,confirmLabel,busy,onCancel,onConfirm}:{title:string;message:string;confirmLabel:string;busy:boolean;onCancel:()=>void;onConfirm:()=>void}){return createPortal(<div className="confirmation-overlay" role="presentation"><div className="confirmation-dialog" role="dialog" aria-modal="true" aria-labelledby="confirmation-title"><h2 id="confirmation-title">{title}</h2><p>{message}</p><div className="confirmation-actions"><button type="button" className="secondary-button" onClick={onCancel} disabled={busy}>Cancelar</button><button type="button" className="primary-button" onClick={onConfirm} disabled={busy}>{busy?'Recalculando…':confirmLabel}</button></div></div></div>,document.body)}
