import { useEffect, useMemo, useState, type FormEvent } from 'react';
import { ArrowLeft, Plus, Trash2 } from 'lucide-react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { MessageLog } from '../../components/ui/MessageLog';
import { CoreRepositoryError } from '../../services/core/coreRepository';
import { quotationForEdit, quotationOptions, updateQuotation, type QuotationEditData, type QuotationEditLine } from '../../services/sales/quotationEditRepository';
import type { QuotationLineCharacteristicDraft, QuotationLineDimensionDraft } from '../../services/sales/quotationCreationRepository';
import './quotation-create.css';
import './quotation.css';

const money=(n:number)=>n.toLocaleString('es-ES',{style:'currency',currency:'EUR'});
type Address={label:string;street:string;postal_code:string;city:string;region:string};
type EditLine=QuotationEditLine;
function blankLine():EditLine{return{id:0,line_no:0,product_id:null,description:'',quantity:1,unit_price:0,discount_percent:0,tax_rate_id:null,tax_percent:0,line_behavior_id:null,line_behavior_snapshot:null,dimensions:[],characteristics:[],specific_data:{}};}

export function QuotationEdit(){
 const {id}=useParams(); const nav=useNavigate();
 const [data,setData]=useState<QuotationEditData|null>(null); const [opts,setOpts]=useState<any>(null); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [error,setError]=useState('');
 const [customerId,setCustomerId]=useState<number|null>(null); const [commercialId,setCommercialId]=useState<number|null>(null); const [warehouseId,setWarehouseId]=useState<number|null>(null); const [billingId,setBillingId]=useState<number|null>(null); const [installationId,setInstallationId]=useState<number|null>(null);
 const [billingAddress,setBillingAddress]=useState<Address>({label:'',street:'',postal_code:'',city:'',region:''}); const [installationAddress,setInstallationAddress]=useState<Address>({label:'',street:'',postal_code:'',city:'',region:''});
 const [paymentMethodId,setPaymentMethodId]=useState<number|null>(null); const [paymentTermId,setPaymentTermId]=useState<number|null>(null); const [taxRateId,setTaxRateId]=useState<number|null>(null); const [taxPercent,setTaxPercent]=useState(0);
 const [issueDate,setIssueDate]=useState(''); const [validUntil,setValidUntil]=useState(''); const [reference,setReference]=useState(''); const [notes,setNotes]=useState(''); const [lines,setLines]=useState<EditLine[]>([]);

 useEffect(()=>{let active=true;(async()=>{try{const [o,q]=await Promise.all([quotationOptions(),quotationForEdit(Number(id))]);if(!active)return;setOpts(o);setData(q);setCustomerId(q.customer_id);setCommercialId(q.commercial_id);setWarehouseId(q.warehouse_id);setBillingId(q.billing_address_id);setInstallationId(q.installation_address_id);setBillingAddress(q.billing_address);setInstallationAddress(q.installation_address);setPaymentMethodId(q.payment_method_id);setPaymentTermId(q.payment_term_id);setTaxRateId(q.tax_rate_id);setTaxPercent(q.tax_percent);setIssueDate(q.issue_date);setValidUntil(q.valid_until||'');setReference(q.reference);setNotes(q.notes);setLines(q.lines);}catch(e){if(active)setError(e instanceof Error?e.message:'No se pudo cargar el presupuesto.');}finally{if(active)setLoading(false);}})();return()=>{active=false};},[id]);
 const totals=useMemo(()=>lines.reduce((a,l)=>{const gross=Math.max(0,l.quantity*l.unit_price);const discount=Math.max(0,gross*(l.discount_percent/100));const net=Math.max(0,gross-discount);const tax=net*taxPercent/100;return{gross:a.gross,discount:a.discount+discount,net:a.net+net,tax:a.tax+tax,total:a.total+net+tax};},{gross:0,discount:0,net:0,tax:0,total:0}),[lines,taxPercent]);
 const updateLine=(i:number,patch:Partial<EditLine>)=>setLines(xs=>xs.map((line,j)=>j===i?{...line,...patch}:line));
 const updateDimension=(i:number,d:number,patch:Partial<QuotationLineDimensionDraft>)=>setLines(xs=>xs.map((line,j)=>j===i?{...line,dimensions:line.dimensions.map((dim,k)=>k===d?{...dim,...patch}:dim)}:line));
 const updateCharacteristic=(i:number,c:number,patch:Partial<QuotationLineCharacteristicDraft>)=>setLines(xs=>xs.map((line,j)=>j===i?{...line,characteristics:line.characteristics.map((ch,k)=>k===c?{...ch,...patch}:ch)}:line));
 const addDimension=(i:number)=>setLines(xs=>xs.map((line,j)=>j===i?{...line,dimensions:[...line.dimensions,{code:`DIM_${line.dimensions.length+1}`,name:'',value:null,unit_id:null,sort_order:line.dimensions.length}]}:line));
 const addCharacteristic=(i:number)=>setLines(xs=>xs.map((line,j)=>j===i?{...line,characteristics:[...line.characteristics,{attribute_id:null,attribute_value_id:null,value_text:null,value_number:null,value_boolean:null}]}:line));

 async function save(e:FormEvent){e.preventDefault();setError('');if(!customerId){setError('Selecciona un cliente.');return;}if(lines.some(l=>l.quantity<=0)){setError('La cantidad debe ser mayor que cero.');return;}setSaving(true);try{await updateQuotation({id:Number(id),customer_id:customerId,commercial_id:commercialId,warehouse_id:warehouseId,billing_address_id:billingId,installation_address_id:installationId,billing_address:billingAddress,installation_address:installationAddress,payment_method_id:paymentMethodId,payment_term_id:paymentTermId,tax_rate_id:taxRateId,tax_percent:taxPercent,issue_date:issueDate,valid_until:validUntil||null,reference,notes,lines});nav(`/ventas/presupuestos/${id}`);}catch(e){setError(e instanceof CoreRepositoryError?e.message:e instanceof Error?e.message:'No se pudo guardar el presupuesto.');}finally{setSaving(false);}}

 if(loading)return <div className="module-page"><div className="page-head"><div><div className="eyebrow">VENTAS / PRESUPUESTOS / EDITAR</div><h1>Editando presupuesto</h1></div></div><p>Cargando datos…</p></div>;
 if(error&&!data)return <div className="module-page"><div className="page-head"><div><div className="eyebrow">VENTAS / PRESUPUESTOS</div><h1>Editar presupuesto</h1></div></div><MessageLog error={error}/></div>;
 if(!data||!opts)return null;
 return <div className="module-page quotation-create">
  <div className="page-head"><div><div className="eyebrow">VENTAS / PRESUPUESTOS / EDITAR</div><h1>{data.code}</h1><p>Edita cabecera, líneas, dimensiones y características sin crear un nuevo presupuesto.</p></div><Link className="secondary-button" to={`/ventas/presupuestos/${data.id}`}><ArrowLeft size={15}/>Volver al presupuesto</Link></div>
  <MessageLog error={error}/>
  <form className="detail-grid" onSubmit={save}>
   <section className="panel quotation-header-panel"><div className="panel-head"><div><h2>Datos generales</h2><p>Condiciones comerciales y datos del documento.</p></div></div><div className="form-grid">
    <label className="quotation-reference-field">Referencia<input value={reference} onChange={e=>setReference(e.target.value)}/></label>
    <label>Cliente<select value={customerId??''} onChange={e=>setCustomerId(e.target.value?Number(e.target.value):null)} required><option value="">Selecciona cliente</option>{opts.customers.map((x:any)=><option key={x.id} value={x.id}>{x.label}</option>)}</select></label>
    <label>Comercial<select value={commercialId??''} onChange={e=>setCommercialId(e.target.value?Number(e.target.value):null)}><option value="">Sin asignar</option>{opts.commercials.map((x:any)=><option key={x.id} value={x.id}>{x.label}</option>)}</select></label>
    <label>Almacén<select value={warehouseId??''} onChange={e=>setWarehouseId(e.target.value?Number(e.target.value):null)}><option value="">Sin asignar</option>{opts.warehouses.map((x:any)=><option key={x.id} value={x.id}>{x.label}</option>)}</select></label>
    <label>Fecha de documento<input type="date" value={issueDate} onChange={e=>setIssueDate(e.target.value)} required/></label><label>Válido hasta<input type="date" value={validUntil} onChange={e=>setValidUntil(e.target.value)}/></label>
    <label>Forma de pago<select value={paymentMethodId??''} onChange={e=>setPaymentMethodId(e.target.value?Number(e.target.value):null)}><option value="">Sin especificar</option>{opts.paymentMethods.map((x:any)=><option key={x.id} value={x.id}>{x.label}</option>)}</select></label>
    <label>Condiciones de pago<select value={paymentTermId??''} onChange={e=>setPaymentTermId(e.target.value?Number(e.target.value):null)}><option value="">Sin especificar</option>{opts.paymentTerms.map((x:any)=><option key={x.id} value={x.id}>{x.label}</option>)}</select></label>
    <label>IVA<select value={taxRateId??''} onChange={e=>{const next=e.target.value?Number(e.target.value):null;const rate=opts.taxRates.find((x:any)=>x.id===next);setTaxRateId(next);setTaxPercent(Number(rate?.rate??0));}}><option value="">Sin IVA</option>{opts.taxRates.map((x:any)=><option key={x.id} value={x.id}>{x.rate}% · {x.label}</option>)}</select></label>
   </div></section>

   <section className="panel quotation-lines-panel"><div className="panel-head"><div><h2>Líneas del presupuesto</h2><p>Modifica artículos, cantidades, precios, descuentos y datos de confección/recorte.</p></div><button type="button" className="primary-button" onClick={()=>setLines(xs=>[...xs,blankLine()])}><Plus size={15}/>Añadir línea</button></div>
    <div className="table-panel quotation-lines-table"><table><thead><tr><th>#</th><th>Artículo</th><th>Descripción</th><th>Cantidad</th><th>Precio</th><th>Dto.</th><th className="numeric">Total</th><th></th></tr></thead><tbody>{lines.map((line,i)=>{const total=Math.max(0,line.quantity*line.unit_price*(1-line.discount_percent/100))*(1+taxPercent/100);return <tr key={`${line.id}-${i}`}><td>{i+1}</td><td><select value={line.product_id??''} onChange={e=>{const pid=e.target.value?Number(e.target.value):null;const p=opts.products.find((x:any)=>x.id===pid);updateLine(i,{product_id:pid,description:pid?(p?.label||p?.code||''):line.description,unit_price:pid?Number(p?.price??0):0,line_behavior_id:pid?(p?.lineBehavior?.id??null):null,line_behavior_snapshot:pid?(p?.lineBehavior??null):null});}}><option value="">Manual</option>{opts.products.map((p:any)=><option key={p.id} value={p.id}>{p.code} · {p.label}</option>)}</select></td><td><input value={line.description} onChange={e=>updateLine(i,{description:e.target.value})} required/></td><td><input type="number" min="0.01" step="0.01" value={line.quantity} onChange={e=>updateLine(i,{quantity:Number(e.target.value)})}/></td><td><input type="number" min="0" step="0.01" value={line.unit_price} onChange={e=>updateLine(i,{unit_price:Number(e.target.value)})}/></td><td><input type="number" min="0" max="100" step="0.01" value={line.discount_percent} onChange={e=>updateLine(i,{discount_percent:Number(e.target.value)})}/></td><td className="numeric"><strong>{money(total)}</strong></td><td><button type="button" className="icon-button" disabled={lines.length===1} aria-label="Eliminar línea" onClick={()=>setLines(xs=>xs.filter((_,j)=>j!==i))}><Trash2 size={16}/></button></td></tr>})}</tbody></table></div>

    {lines.map((line,i)=><div key={`advanced-${line.id}-${i}`} className="panel quotation-line-editor-card"><div className="panel-head"><div><h3>Línea {i+1}: {line.description||'Sin descripción'}</h3><p>{line.product_id?`Artículo ${opts.products.find((p:any)=>p.id===line.product_id)?.code||line.product_id}`:'Línea manual'}</p></div></div>
      <div className="form-grid"><div className="quotation-edit-subsection"><div className="quotation-section-head"><div><h4>Dimensiones</h4><p>Datos usados en artículos confeccionables y recortables.</p></div><button type="button" className="secondary-button" onClick={()=>addDimension(i)}><Plus size={14}/>Añadir dimensión</button></div>{line.dimensions.length===0&&<p className="muted">Sin dimensiones almacenadas.</p>}{line.dimensions.map((d,di)=><div className="form-grid quotation-inline-grid" key={`${d.code}-${di}`}><label>Código<input value={d.code} onChange={e=>updateDimension(i,di,{code:e.target.value})}/></label><label>Nombre<input value={d.name} onChange={e=>updateDimension(i,di,{name:e.target.value})}/></label><label>Valor<input type="number" step="0.01" value={d.value??''} onChange={e=>updateDimension(i,di,{value:e.target.value===''?null:Number(e.target.value)})}/></label><label>Unidad ID<input type="number" value={d.unit_id??''} onChange={e=>updateDimension(i,di,{unit_id:e.target.value?Number(e.target.value):null})}/></label><button type="button" className="icon-button" aria-label="Eliminar dimensión" onClick={()=>setLines(xs=>xs.map((l,j)=>j===i?{...l,dimensions:l.dimensions.filter((_,k)=>k!==di)}:l))}><Trash2 size={15}/></button></div>)}</div>
      <div className="quotation-edit-subsection"><div className="quotation-section-head"><div><h4>Características</h4><p>Se conservan y permiten editar los valores almacenados en la línea.</p></div><button type="button" className="secondary-button" onClick={()=>addCharacteristic(i)}><Plus size={14}/>Añadir característica</button></div>{line.characteristics.length===0&&<p className="muted">Sin características almacenadas.</p>}{line.characteristics.map((ch,ci)=><div className="form-grid quotation-inline-grid" key={`${ci}-${ch.attribute_id}`}><label>Atributo ID<input type="number" value={ch.attribute_id??''} onChange={e=>updateCharacteristic(i,ci,{attribute_id:e.target.value?Number(e.target.value):null})}/></label><label>Valor opción ID<input type="number" value={ch.attribute_value_id??''} onChange={e=>updateCharacteristic(i,ci,{attribute_value_id:e.target.value?Number(e.target.value):null})}/></label><label>Texto<input value={ch.value_text??''} onChange={e=>updateCharacteristic(i,ci,{value_text:e.target.value||null})}/></label><label>Número<input type="number" step="0.01" value={ch.value_number??''} onChange={e=>updateCharacteristic(i,ci,{value_number:e.target.value===''?null:Number(e.target.value)})}/></label><button type="button" className="icon-button" aria-label="Eliminar característica" onClick={()=>setLines(xs=>xs.map((l,j)=>j===i?{...l,characteristics:l.characteristics.filter((_,k)=>k!==ci)}:l))}><Trash2 size={15}/></button></div>)}</div></div>
    </div>)}
    <div className="quote-totals"><span>Base imponible <strong>{money(totals.net)}</strong></span><span>Descuentos <strong>{money(totals.discount)}</strong></span><span>Impuestos ({taxPercent}%) <strong>{money(totals.tax)}</strong></span><span>Total <strong>{money(totals.total)}</strong></span></div>
   </section>

   <section className="panel"><div className="panel-head"><div><h2>Observaciones</h2><p>Notas internas o información adicional del presupuesto.</p></div></div><textarea value={notes} onChange={e=>setNotes(e.target.value)} rows={5}/></section>
   <div className="profile-save-bar"><Link className="secondary-button" to={`/ventas/presupuestos/${data.id}`}>Cancelar</Link><button className="primary-button" type="submit" disabled={saving}>{saving?'Guardando…':'Guardar cambios'}</button></div>
  </form>
 </div>;
}
