import { useEffect, useMemo, useState, type FormEvent } from 'react';
import { ArrowLeft, Plus, Trash2 } from 'lucide-react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { MessageLog } from '../../components/ui/MessageLog';
import { CoreRepositoryError } from '../../services/core/coreRepository';
import { getProductLineDefinition, type ProductLineDefinition } from '../../services/catalog/productDefinitionRepository';
import { quotationForEdit, quotationOptions, updateQuotation, type QuotationEditData, type QuotationEditLine } from '../../services/sales/quotationEditRepository';
import type { QuotationLineCharacteristicDraft } from '../../services/sales/quotationCreationRepository';
import './quotation-create.css';
import './quotation.css';

const money=(n:number)=>n.toLocaleString('es-ES',{style:'currency',currency:'EUR'});
type Address={label:string;street:string;postal_code:string;city:string;region:string};
type EditLine=QuotationEditLine;
function blankLine():EditLine{return{id:0,line_no:0,product_id:null,description:'',quantity:1,unit_price:0,discount_percent:0,tax_rate_id:null,tax_percent:0,line_behavior_id:null,line_behavior_snapshot:null,product_definition_snapshot:null,dimensions:[],characteristics:[],specific_data:{}};}
function clone<T>(v:T):T{return JSON.parse(JSON.stringify(v));}
function dimensionsFromDefinition(definition:ProductLineDefinition,old:EditLine['dimensions']){const values=new Map(old.map(v=>[v.code,v.value]));return definition.dimensions.map((d,i)=>({code:d.code,name:d.name,value:values.get(d.code)??null,unit_id:d.unit_id,sort_order:i}));}
function characteristicsFromDefinition(definition:ProductLineDefinition,old:EditLine['characteristics']){const values=new Map(old.filter(v=>v.attribute_id!=null).map(v=>[Number(v.attribute_id),v]));return definition.characteristics.map(c=>{const v=values.get(c.attribute_id);return{attribute_id:c.attribute_id,attribute_value_id:v?.attribute_value_id??null,value_text:v?.value_text??null,value_number:v?.value_number??null,value_boolean:v?.value_boolean??null};});}

export function QuotationEdit(){
 const {id}=useParams();const nav=useNavigate();
 const [data,setData]=useState<QuotationEditData|null>(null);const [opts,setOpts]=useState<any>(null);const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const [error,setError]=useState('');const [loadingDefinition,setLoadingDefinition]=useState<number|null>(null);
 const [customerId,setCustomerId]=useState<number|null>(null);const [commercialId,setCommercialId]=useState<number|null>(null);const [warehouseId,setWarehouseId]=useState<number|null>(null);const [billingId,setBillingId]=useState<number|null>(null);const [installationId,setInstallationId]=useState<number|null>(null);
 const [billingAddress,setBillingAddress]=useState<Address>({label:'',street:'',postal_code:'',city:'',region:''});const [installationAddress,setInstallationAddress]=useState<Address>({label:'',street:'',postal_code:'',city:'',region:''});
 const [paymentMethodId,setPaymentMethodId]=useState<number|null>(null);const [paymentTermId,setPaymentTermId]=useState<number|null>(null);const [taxRateId,setTaxRateId]=useState<number|null>(null);const [taxPercent,setTaxPercent]=useState(0);const [issueDate,setIssueDate]=useState('');const [validUntil,setValidUntil]=useState('');const [reference,setReference]=useState('');const [notes,setNotes]=useState('');const [lines,setLines]=useState<EditLine[]>([]);
 useEffect(()=>{let active=true;(async()=>{try{const[o,q]=await Promise.all([quotationOptions(),quotationForEdit(Number(id))]);if(!active)return;setOpts(o);setData(q);setCustomerId(q.customer_id);setCommercialId(q.commercial_id);setWarehouseId(q.warehouse_id);setBillingId(q.billing_address_id);setInstallationId(q.installation_address_id);setBillingAddress(q.billing_address);setInstallationAddress(q.installation_address);setPaymentMethodId(q.payment_method_id);setPaymentTermId(q.payment_term_id);setTaxRateId(q.tax_rate_id);setTaxPercent(q.tax_percent);setIssueDate(q.issue_date);setValidUntil(q.valid_until||'');setReference(q.reference);setNotes(q.notes);setLines(q.lines);}catch(e){if(active)setError(e instanceof Error?e.message:'No se pudo cargar el presupuesto.');}finally{if(active)setLoading(false);}})();return()=>{active=false};},[id]);
 const totals=useMemo(()=>lines.reduce((a,l)=>{const gross=Math.max(0,l.quantity*l.unit_price);const discount=Math.max(0,gross*l.discount_percent/100);const net=Math.max(0,gross-discount);const tax=net*taxPercent/100;return{discount:a.discount+discount,net:a.net+net,tax:a.tax+tax,total:a.total+net+tax};},{discount:0,net:0,tax:0,total:0}),[lines,taxPercent]);
 const updateLine=(i:number,patch:Partial<EditLine>)=>setLines(xs=>xs.map((l,j)=>j===i?{...l,...patch}:l));
 const updateDimensionValue=(i:number,d:number,value:number|null)=>setLines(xs=>xs.map((l,j)=>j===i?{...l,dimensions:l.dimensions.map((x,k)=>k===d?{...x,value}:x)}:l));
 const updateCharacteristic=(i:number,c:number,patch:Partial<QuotationLineCharacteristicDraft>)=>setLines(xs=>xs.map((l,j)=>j===i?{...l,characteristics:l.characteristics.map((x,k)=>k===c?{...x,...patch}:x)}:l));
 const selectProduct=async(i:number,pid:number|null)=>{if(pid===null){updateLine(i,{product_id:null,description:'',unit_price:0,line_behavior_id:null,line_behavior_snapshot:null,product_definition_snapshot:null,dimensions:[],characteristics:[]});return;}const p=opts.products.find((x:any)=>x.id===pid);setLoadingDefinition(pid);setError('');try{const definition=await getProductLineDefinition(pid);updateLine(i,{product_id:pid,description:p?.label||p?.code||'',unit_price:Number(p?.price??0),line_behavior_id:p?.lineBehavior?.id??null,line_behavior_snapshot:p?.lineBehavior??null,product_definition_snapshot:clone(definition),dimensions:dimensionsFromDefinition(definition,[]),characteristics:characteristicsFromDefinition(definition,[])});}catch(e){setError(e instanceof Error?e.message:'No se pudo cargar la definición del artículo.');}finally{setLoadingDefinition(null);}};
 async function save(e:FormEvent){e.preventDefault();setError('');if(!customerId){setError('Selecciona un cliente.');return;}if(lines.some(l=>l.quantity<=0)){setError('La cantidad debe ser mayor que cero.');return;}setSaving(true);try{await updateQuotation({id:Number(id),customer_id:customerId,commercial_id:commercialId,warehouse_id:warehouseId,billing_address_id:billingId,installation_address_id:installationId,billing_address:billingAddress,installation_address:installationAddress,payment_method_id:paymentMethodId,payment_term_id:paymentTermId,tax_rate_id:taxRateId,tax_percent:taxPercent,issue_date:issueDate,valid_until:validUntil||null,reference,notes,lines});nav(`/ventas/presupuestos/${id}`);}catch(e){setError(e instanceof CoreRepositoryError?e.message:e instanceof Error?e.message:'No se pudo guardar el presupuesto.');}finally{setSaving(false);}}
 if(loading)return <div className="module-page"><div className="page-head"><div><div className="eyebrow">VENTAS / PRESUPUESTOS / EDITAR</div><h1>Editando presupuesto</h1></div></div><p>Cargando datos…</p></div>;
 if(error&&!data)return <div className="module-page"><div className="page-head"><div><div className="eyebrow">VENTAS / PRESUPUESTOS</div><h1>Editar presupuesto</h1></div></div><MessageLog error={error}/></div>;
 if(!data||!opts)return null;
 return <div className="module-page quotation-create">
  <div className="page-head"><div><div className="eyebrow">VENTAS / PRESUPUESTOS / EDITAR</div><h1>{data.code}</h1><p>Modifica los datos del documento y los valores de cada línea sin alterar la definición del artículo.</p></div><Link className="secondary-button" to={`/ventas/presupuestos/${data.id}`}><ArrowLeft size={15}/>Volver al presupuesto</Link></div>
  <MessageLog error={error}/>
  <form className="detail-grid" onSubmit={save}>
   <section className="panel quotation-header-panel"><div className="panel-head"><div><h2>Datos generales</h2><p>Condiciones comerciales y datos del documento.</p></div></div><div className="form-grid">
    <label className="quotation-reference-field">Referencia<input value={reference} onChange={e=>setReference(e.target.value)}/></label>
    <label>Cliente<select value={customerId??''} onChange={e=>setCustomerId(e.target.value?Number(e.target.value):null)} required><option value="">Selecciona cliente</option>{opts.customers.map((x:any)=><option key={x.id} value={x.id}>{x.label}</option>)}</select></label>
    <label>Comercial<select value={commercialId??''} onChange={e=>setCommercialId(e.target.value?Number(e.target.value):null)}><option value="">Sin asignar</option>{opts.commercials.map((x:any)=><option key={x.id} value={x.id}>{x.label}</option>)}</select></label>
    <label>Almacén<select value={warehouseId??''} onChange={e=>setWarehouseId(e.target.value?Number(e.target.value):null)}><option value="">Sin asignar</option>{opts.warehouses.map((x:any)=><option key={x.id} value={x.id}>{x.label}</option>)}</select></label>
    <label>Fecha de documento<input type="date" value={issueDate} onChange={e=>setIssueDate(e.target.value)} required/></label><label>Válido hasta<input type="date" value={validUntil} onChange={e=>setValidUntil(e.target.value)}/></label>
    <label>Forma de pago<select value={paymentMethodId??''} onChange={e=>setPaymentMethodId(e.target.value?Number(e.target.value):null)}><option value="">Sin especificar</option>{opts.paymentMethods.map((x:any)=><option key={x.id} value={x.id}>{x.label}</option>)}</select></label>
    <label>Condiciones de pago<select value={paymentTermId??''} onChange={e=>setPaymentTermId(e.target.value?Number(e.target.value):null)}><option value="">Sin especificar</option>{opts.paymentTerms.map((x:any)=><option key={x.id} value={x.id}>{x.label}</option>)}</select></label>
    <label>IVA<select value={taxRateId??''} onChange={e=>{const next=e.target.value?Number(e.target.value):null;const rate=opts.taxRates.find((x:any)=>x.id===next);setTaxRateId(next);setTaxPercent(Number(rate?.rate??0));}}><option value="">Sin IVA</option>{opts.taxRates.map((x:any)=><option key={x.id} value={x.id}>{x.rate}% · {x.label}</option>)}</select></label>
   </div></section>
   <section className="panel quotation-lines-panel"><div className="panel-head"><div><h2>Líneas del presupuesto</h2><p>Modifica artículo, cantidad, precio, descuento y valores de configuración.</p></div><button type="button" className="primary-button" onClick={()=>setLines(xs=>[...xs,blankLine()])}><Plus size={15}/>Añadir línea</button></div>
    <div className="table-panel quotation-lines-table"><table><thead><tr><th>#</th><th>Artículo</th><th>Descripción</th><th>Cantidad</th><th>Precio</th><th>Dto.</th><th className="numeric">Total</th><th></th></tr></thead><tbody>{lines.map((line,i)=>{const total=Math.max(0,line.quantity*line.unit_price*(1-line.discount_percent/100))*(1+taxPercent/100);return <tr key={`${line.id}-${i}`}><td>{i+1}</td><td><select value={line.product_id??''} disabled={loadingDefinition===line.product_id} onChange={e=>{void selectProduct(i,e.target.value?Number(e.target.value):null);}}><option value="">Manual</option>{opts.products.map((p:any)=><option key={p.id} value={p.id}>{p.code} · {p.label}</option>)}</select></td><td><input value={line.description} onChange={e=>updateLine(i,{description:e.target.value})} required/></td><td><input type="number" min="0.01" step="0.01" value={line.quantity} onChange={e=>updateLine(i,{quantity:Number(e.target.value)})}/></td><td><input type="number" min="0" step="0.01" value={line.unit_price} onChange={e=>updateLine(i,{unit_price:Number(e.target.value)})}/></td><td><input type="number" min="0" max="100" step="0.01" value={line.discount_percent} onChange={e=>updateLine(i,{discount_percent:Number(e.target.value)})}/></td><td className="numeric"><strong>{money(total)}</strong></td><td><button type="button" className="icon-button" disabled={lines.length===1} aria-label="Eliminar línea" onClick={()=>setLines(xs=>xs.filter((_,j)=>j!==i))}><Trash2 size={16}/></button></td></tr>})}</tbody></table></div>
    {lines.map((line,i)=><div key={`advanced-${line.id}-${i}`} className="panel quotation-line-editor-card"><div className="panel-head"><div><h3>Línea {i+1}: {line.description||'Sin descripción'}</h3><p>{line.product_id?`Artículo ${opts.products.find((p:any)=>p.id===line.product_id)?.code||line.product_id}`:'Línea manual'}</p></div></div>
      {line.product_id&&line.product_definition_snapshot&&<div className="quotation-definition-summary"><div><strong>Definición del artículo</strong><span>{line.product_definition_snapshot.dimensions.length} dimensión(es) · {line.product_definition_snapshot.characteristics.length} característica(s)</span></div><span className="definition-badge">Definición bloqueada</span></div>}
      {line.product_id&&line.product_definition_snapshot&&<div className="form-grid">
       {line.product_definition_snapshot.dimensions.length>0&&<div className="quotation-edit-subsection"><div className="quotation-section-head"><div><h4>Dimensiones</h4><p>Solo se modifica el valor. Nombre, unidad, código y orden pertenecen a la definición.</p></div></div>{line.dimensions.map((d,di)=><div className="quotation-instance-row" key={`${d.code}-${di}`}><div><strong>{d.name}</strong><span>{d.code}{d.unit_id!=null?` · unidad ${d.unit_id}`:''}</span></div><input aria-label={`Valor ${d.name}`} type="number" step={1/(10**Math.max(0,Number(line.product_definition_snapshot?.dimensions[di]?.decimals??2)))} value={d.value??''} onChange={e=>updateDimensionValue(i,di,e.target.value===''?null:Number(e.target.value))}/></div>)}</div>}
       {line.product_definition_snapshot.characteristics.length>0&&<div className="quotation-edit-subsection"><div className="quotation-section-head"><div><h4>Características</h4><p>El atributo y sus valores posibles pertenecen a la definición del artículo.</p></div></div>{line.product_definition_snapshot.characteristics.map((c,ci)=>{const current=line.characteristics[ci]??{attribute_id:c.attribute_id,attribute_value_id:null,value_text:null,value_number:null,value_boolean:null};return <div className="quotation-instance-row" key={c.assignment_id}><div><strong>{c.attribute_name||c.attribute_code}</strong><span>{c.attribute_code}{c.required?' · obligatorio':''}</span></div>{c.values.length>0?<select value={current.attribute_value_id??''} onChange={e=>updateCharacteristic(i,ci,{attribute_id:c.attribute_id,attribute_value_id:e.target.value?Number(e.target.value):null,value_text:null,value_number:null,value_boolean:null})}><option value="">Selecciona…</option>{c.values.map(v=><option key={v.id} value={v.id}>{v.code} · {v.name}</option>)}</select>:c.data_type==='NUMBER'?<input type="number" step="0.01" value={current.value_number??''} onChange={e=>updateCharacteristic(i,ci,{attribute_id:c.attribute_id,attribute_value_id:null,value_text:null,value_number:e.target.value===''?null:Number(e.target.value),value_boolean:null})}/>:c.data_type==='BOOLEAN'?<input type="checkbox" checked={current.value_boolean===true} onChange={e=>updateCharacteristic(i,ci,{attribute_id:c.attribute_id,attribute_value_id:null,value_text:null,value_number:null,value_boolean:e.target.checked})}/>:<input value={current.value_text??''} onChange={e=>updateCharacteristic(i,ci,{attribute_id:c.attribute_id,attribute_value_id:null,value_text:e.target.value||null,value_number:null,value_boolean:null})}/>}</div>})}</div>}
       {line.product_definition_snapshot.dimensions.length===0&&line.product_definition_snapshot.characteristics.length===0&&<p className="muted">Este artículo no tiene datos de configuración definidos.</p>}
      </div>}
      {!line.product_id&&<p className="muted">Línea manual: no hay definición de artículo ni datos de configuración.</p>}
    </div>)}
    <div className="quote-totals"><span>Base imponible <strong>{money(totals.net)}</strong></span><span>Descuentos <strong>{money(totals.discount)}</strong></span><span>Impuestos ({taxPercent}%) <strong>{money(totals.tax)}</strong></span><span>Total <strong>{money(totals.total)}</strong></span></div>
   </section>
   <section className="panel"><div className="panel-head"><div><h2>Observaciones</h2><p>Notas internas o información adicional del presupuesto.</p></div></div><textarea value={notes} onChange={e=>setNotes(e.target.value)} rows={5}/></section>
   <div className="profile-save-bar"><Link className="secondary-button" to={`/ventas/presupuestos/${data.id}`}>Cancelar</Link><button className="primary-button" type="submit" disabled={saving||loadingDefinition!==null}>{saving?'Guardando…':'Guardar cambios'}</button></div>
  </form>
 </div>;
}
