import { useEffect, useMemo, useRef, useState } from 'react';
import { createPortal } from 'react-dom';
import { ArrowLeft, ChevronDown, ChevronUp, Plus, Search, Trash2, X } from 'lucide-react';
import { Link, useNavigate } from 'react-router-dom';
import { CoreRepositoryError } from '../../services/core/coreRepository';
import { getProductLineDefinition, type ProductLineDefinition } from '../../services/catalog/productDefinitionRepository';
import { createQuotation, customerAddresses, customerProductDiscount, quotationOptions, type ProductLineBehavior, type QuotationLineCharacteristicDraft, type QuotationLineDimensionDraft } from '../../services/sales/quotationCreationRepository';
import { calculateQuotationLineByProductId } from '../../services/sales/quotationLineCalculationService';
import { MessageLog } from '../../components/ui/MessageLog';
import { ProfileSaveBar } from '../../components/ui/ProfileSaveBar';
import { Toast } from '../../components/ui/Toast';
import './quotation-create.css';

const today=()=>new Date().toISOString().slice(0,10);
const money=(n:number)=>n.toLocaleString('es-ES',{style:'currency',currency:'EUR'});
type AddressDraft={source_id:number|null;label:string;street:string;postal_code:string;city:string;region:string};
type Line={product_id:number|null;description:string;quantity:number;unit_price:number;discount_percent:number;line_behavior:ProductLineBehavior|null;product_definition_snapshot:ProductLineDefinition|null;dimensions:QuotationLineDimensionDraft[];characteristics:QuotationLineCharacteristicDraft[];specific_data:Record<string,unknown>};
const emptyAddress=():AddressDraft=>({source_id:null,label:'',street:'',postal_code:'',city:'',region:''});
const blank=():Line=>({product_id:null,description:'',quantity:1,unit_price:0,discount_percent:0,line_behavior:null,product_definition_snapshot:null,dimensions:[],characteristics:[],specific_data:{}});
type Option={id:number;label:string;code?:string;price?:number;lineBehavior?:ProductLineBehavior|null};

function clone<T>(value:T):T{return JSON.parse(JSON.stringify(value));}
function dimensionsFromDefinition(definition:ProductLineDefinition,old:QuotationLineDimensionDraft[]=[]){const values=new Map(old.map(v=>[v.code,v.value]));return definition.dimensions.map((d,i)=>({code:d.code,name:d.name,value:values.get(d.code)??null,unit_id:d.unit_id,sort_order:i}));}
function characteristicsFromDefinition(definition:ProductLineDefinition,old:QuotationLineCharacteristicDraft[]=[]){const values=new Map(old.filter(v=>v.attribute_id!=null).map(v=>[Number(v.attribute_id),v]));return definition.characteristics.map(c=>{const v=values.get(c.attribute_id);return{attribute_id:c.attribute_id,attribute_value_id:v?.attribute_value_id??null,value_text:v?.value_text??null,value_number:v?.value_number??null,value_boolean:v?.value_boolean??null};});}
function hasDefinitionData(line:Line){return !!line.product_definition_snapshot&&(line.product_definition_snapshot.dimensions.length>0||line.product_definition_snapshot.characteristics.length>0);}
function hasRequiredCharacteristicValues(line:Line){return (line.product_definition_snapshot?.characteristics??[]).every((c,i)=>!c.required||[line.characteristics[i]?.attribute_value_id,line.characteristics[i]?.value_text,line.characteristics[i]?.value_number,line.characteristics[i]?.value_boolean].some(v=>v!==null&&v!==undefined&&v!==''));}

export function QuotationCreate(){
 const nav=useNavigate();
 const [opts,setOpts]=useState<any>();const [addresses,setAddresses]=useState<any[]>([]);const [customerId,setCustomerId]=useState<number|null>(null);
 const [commercialId,setCommercialId]=useState<number|null>(null);const [warehouseId,setWarehouseId]=useState<number|null>(null);const [billingId,setBillingId]=useState<number|null>(null);const [installationId,setInstallationId]=useState<number|null>(null);
 const [billingAddress,setBillingAddress]=useState<AddressDraft>(emptyAddress());const [installationAddress,setInstallationAddress]=useState<AddressDraft>(emptyAddress());
 const [paymentMethodId,setPaymentMethodId]=useState<number|null>(null);const [paymentTermId,setPaymentTermId]=useState<number|null>(null);const [taxRateId,setTaxRateId]=useState<number|null>(null);const [taxPercent,setTaxPercent]=useState(0);
 const [issueDate,setIssueDate]=useState(today());const [validUntil,setValidUntil]=useState('');const [reference,setReference]=useState('');const [notes,setNotes]=useState('');const [lines,setLines]=useState<Line[]>([blank()]);
 const [error,setError]=useState('');const [toast,setToast]=useState('');const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const [headerCollapsed,setHeaderCollapsed]=useState(false);const [expandedLines,setExpandedLines]=useState<Set<number>>(new Set());const [pendingCustomerId,setPendingCustomerId]=useState<number|null>(null);const [changingCustomer,setChangingCustomer]=useState(false);const [loadingDefinition,setLoadingDefinition]=useState<number|null>(null);
 const calculationRequests=useRef<Record<number,number>>({});
 useEffect(()=>{void quotationOptions().then(setOpts).catch(e=>setError(e instanceof Error?e.message:'No se pudieron cargar los datos.')).finally(()=>setLoading(false));},[]);
 const totals=useMemo(()=>lines.reduce((a,l)=>{const gross=Math.max(0,l.quantity*l.unit_price);const discount=Math.max(0,gross*l.discount_percent/100);const net=Math.max(0,gross-discount);const tax=net*taxPercent/100;return{discount:a.discount+discount,net:a.net+net,tax:a.tax+tax,total:a.total+net+tax};},{discount:0,net:0,tax:0,total:0}),[lines,taxPercent]);
 const updateLine=(i:number,patch:Partial<Line>)=>setLines(xs=>xs.map((l,j)=>j===i?{...l,...patch}:l));
 const recalculateLine=async(i:number,productId:number|null,dimensions:QuotationLineDimensionDraft[],silent=true)=>{if(productId===null)return;const request=(calculationRequests.current[i]??0)+1;calculationRequests.current[i]=request;try{const result=await calculateQuotationLineByProductId({productId,dimensions});if(calculationRequests.current[i]===request)updateLine(i,{unit_price:result.unit_price});}catch(e){if(!silent&&calculationRequests.current[i]===request)setError(e instanceof Error?e.message:'No se pudo recalcular el precio del artículo.');}};
 const selectProduct=async(i:number,id:number|null)=>{if(id===null){calculationRequests.current[i]=(calculationRequests.current[i]??0)+1;updateLine(i,blank());return;}const p=opts?.products?.find((x:any)=>x.id===id);setLoadingDefinition(id);setError('');try{const definition=await getProductLineDefinition(id);const discount=customerId?await customerProductDiscount(customerId,id):null;const lineBehavior=p?.lineBehavior??null;const line:Line={product_id:id,description:p?.label||p?.code||'',quantity:1,unit_price:Number(p?.price??0),discount_percent:discount?.discount_percent??0,line_behavior:lineBehavior,product_definition_snapshot:clone(definition),dimensions:dimensionsFromDefinition(definition),characteristics:characteristicsFromDefinition(definition),specific_data:{}};updateLine(i,line);setExpandedLines(s=>new Set(s).add(i));void recalculateLine(i,id,line.dimensions,true);if(discount)setToast(`El cliente tiene descuentos aplicados (${discount.level==='article'?'artículo':'familia'}: ${discount.discount_percent}%).`);}catch(e){setError(e instanceof Error?e.message:'No se pudo cargar la definición del artículo.');}finally{setLoadingDefinition(null);}};
 const updateDimensionValue=(i:number,d:number,value:number|null)=>{const line=lines[i];if(!line)return;const dimensions=line.dimensions.map((x,k)=>k===d?{...x,value}:x);updateLine(i,{dimensions});if(line.product_id!==null)void recalculateLine(i,line.product_id,dimensions,false);};
 const updateCharacteristic=(i:number,c:number,patch:Partial<QuotationLineCharacteristicDraft>)=>setLines(xs=>xs.map((l,j)=>j===i?{...l,characteristics:l.characteristics.map((x,k)=>k===c?{...x,...patch}:x)}:l));
 const toggleLine=(i:number)=>setExpandedLines(s=>{const next=new Set(s);if(next.has(i))next.delete(i);else next.add(i);return next;});
 const applyCustomerAddresses=(rows:any[])=>{setAddresses(rows);const billing=rows.find((a:any)=>['FACTURACION','FISCAL'].includes(String(a.address_type).toUpperCase()));const installation=rows.find((a:any)=>String(a.address_type).toUpperCase()==='INSTALACION');setBillingId(billing?.id??null);setInstallationId(installation?.id??null);setBillingAddress(addressDraft(billing));setInstallationAddress(addressDraft(installation));};
 useEffect(()=>{if(!customerId){setAddresses([]);setBillingId(null);setInstallationId(null);setBillingAddress(emptyAddress());setInstallationAddress(emptyAddress());return;}void customerAddresses(customerId).then(applyCustomerAddresses).catch(e=>setError(e instanceof Error?e.message:'No se pudieron cargar las direcciones del cliente.'));},[customerId]);
 const requestCustomerChange=(id:number|null)=>{if(id===customerId)return;setPendingCustomerId(id);};
 const cancelCustomerChange=()=>setPendingCustomerId(null);
 const confirmCustomerChange=async()=>{const id=pendingCustomerId;setPendingCustomerId(null);if(id===customerId)return;setChangingCustomer(true);setError('');try{setCustomerId(id);if(id===null){setLines(xs=>xs.map(l=>({...l,discount_percent:0})));return;}const rows=await customerAddresses(id);applyCustomerAddresses(rows);const discounted=await Promise.all(lines.map(async l=>l.product_id?customerProductDiscount(id,l.product_id):null));setLines(xs=>xs.map((l,index)=>({...l,discount_percent:discounted[index]?.discount_percent??0})));if(discounted.some(Boolean))setToast('El cliente tiene descuentos aplicados.');}catch(e){setError(e instanceof Error?e.message:'No se pudieron recalcular los datos asociados al cliente.');}finally{setChangingCustomer(false);}};
 const save=async(e:React.FormEvent)=>{e.preventDefault();setError('');if(!customerId){setError('Selecciona un cliente.');return;}if(lines.some(l=>!l.description.trim())){setError('Todas las líneas deben tener descripción.');return;}if(lines.some(l=>!hasRequiredCharacteristicValues(l))){setError('Completa las características obligatorias de los artículos configurables.');return;}setSaving(true);try{await createQuotation({customer_id:customerId,commercial_id:commercialId,warehouse_id:warehouseId,billing_address_id:billingId,installation_address_id:installationId,billing_address:billingAddress,installation_address:installationAddress,payment_method_id:paymentMethodId,payment_term_id:paymentTermId,measurement_id:null,tax_rate_id:taxRateId,tax_percent:taxPercent,issue_date:issueDate,valid_until:validUntil||null,reference,notes,lines:lines.map(l=>({product_id:l.product_id,description:l.description,quantity:l.quantity,unit_price:l.unit_price,discount_percent:l.discount_percent,dimensions:l.dimensions,characteristics:l.characteristics,specific_data:l.specific_data}))});nav('/ventas/presupuestos');}catch(e){setError(e instanceof CoreRepositoryError?e.message:e instanceof Error?e.message:'No se pudo guardar el presupuesto.');}finally{setSaving(false);}};
 if(loading)return <div className="module-page"><div className="page-head"><div><div className="eyebrow">VENTAS / PRESUPUESTOS / NUEVO</div><h1>Nuevo presupuesto</h1></div></div><p>Cargando datos…</p></div>;
 return <div className="module-page quotation-create">
  <div className="page-head"><div><div className="eyebrow">VENTAS / PRESUPUESTOS / NUEVO</div><h1>Nuevo presupuesto</h1><p>Crear presupuesto en estado borrador.</p></div><Link className="secondary-button" to="/ventas/presupuestos"><ArrowLeft size={15}/>Volver a presupuestos</Link></div>
  <MessageLog error={error}/>{toast&&<Toast message={toast} onClose={()=>setToast('')}/>} 
  <form id="quotation-create-form" className="detail-grid" onSubmit={save}>
   <section className="panel quotation-header-panel"><div className="panel-head"><div><h2>Datos generales</h2><p>Cliente, condiciones comerciales y direcciones del presupuesto.</p></div><button type="button" className="secondary-button" onClick={()=>setHeaderCollapsed(v=>!v)}>{headerCollapsed?<><ChevronDown size={15}/>Mostrar cabecera</>:<><ChevronUp size={15}/>Contraer cabecera</>}</button></div>{!headerCollapsed&&<div className="form-grid">
    <label className="quotation-reference-field">Referencia<input value={reference} onChange={e=>setReference(e.target.value)}/></label>
    <LookupSelect label="Cliente" required options={opts.customers} value={customerId} onChange={requestCustomerChange} placeholder="Buscar cliente por nombre…" />
    <label>Comercial<select value={commercialId??''} onChange={e=>setCommercialId(e.target.value?Number(e.target.value):null)}><option value="">Sin asignar</option>{opts.commercials.map((x:any)=><option key={x.id} value={x.id}>{x.label}</option>)}</select></label>
    <label>Almacén<select value={warehouseId??''} onChange={e=>setWarehouseId(e.target.value?Number(e.target.value):null)}><option value="">Sin asignar</option>{opts.warehouses.map((x:any)=><option key={x.id} value={x.id}>{x.label}</option>)}</select></label>
    <label>Fecha de documento<input type="date" value={issueDate} onChange={e=>setIssueDate(e.target.value)} required/></label><label>Válido hasta<input type="date" value={validUntil} onChange={e=>setValidUntil(e.target.value)}/></label>
    <label>Forma de pago<select value={paymentMethodId??''} onChange={e=>setPaymentMethodId(e.target.value?Number(e.target.value):null)}><option value="">Sin especificar</option>{opts.paymentMethods.map((x:any)=><option key={x.id} value={x.id}>{x.label}</option>)}</select></label>
    <label>Condiciones de pago<select value={paymentTermId??''} onChange={e=>setPaymentTermId(e.target.value?Number(e.target.value):null)}><option value="">Sin especificar</option>{opts.paymentTerms.map((x:any)=><option key={x.id} value={x.id}>{x.label}</option>)}</select></label>
    <label>IVA<select value={taxRateId??''} onChange={e=>{const id=e.target.value?Number(e.target.value):null;const t=opts.taxRates.find((x:any)=>x.id===id);setTaxRateId(id);setTaxPercent(Number(t?.rate??0));}}><option value="">Sin IVA</option>{opts.taxRates.map((t:any)=><option key={t.id} value={t.id}>{t.rate}% · {t.label}</option>)}</select></label>
    <AddressEditor title="Dirección de facturación" addresses={addresses} value={billingAddress} onChange={setBillingAddress} onSourceChange={setBillingId}/><AddressEditor title="Dirección de instalación" addresses={addresses} value={installationAddress} onChange={setInstallationAddress} onSourceChange={setInstallationId}/>
   </div>}</section>
   <section className="panel quotation-lines-panel"><div className="panel-head"><div><h2>Líneas del presupuesto</h2><p>La definición de dimensiones y características viene del artículo. Aquí solo se informan sus valores.</p></div><button type="button" className="primary-button" onClick={()=>setLines(xs=>[...xs,blank()])}><Plus size={15}/>Añadir línea</button></div>
    <div className="table-panel quotation-lines-table"><table><thead><tr><th>#</th><th>Artículo</th><th>Descripción</th><th>Cantidad</th><th>Precio</th><th>Dto.</th><th className="numeric">Total</th><th></th></tr></thead><tbody>{lines.map((line,i)=>{const total=Math.max(0,line.quantity*line.unit_price*(1-line.discount_percent/100))*(1+taxPercent/100);const expanded=expandedLines.has(i);return <tr key={`line-${i}`}><td>{i+1}</td><td><LookupSelect compact options={opts.products} value={line.product_id} onChange={id=>void selectProduct(i,id)} placeholder="Buscar artículo…"/>{line.product_id&&<button type="button" className="line-config-trigger" onClick={()=>toggleLine(i)} aria-expanded={expanded}>{expanded?<><ChevronUp size={14}/>Ocultar configuración</>:<><ChevronDown size={14}/>Configurar línea</>}</button>}</td><td><input value={line.description} onChange={e=>updateLine(i,{description:e.target.value})} required/></td><td><input type="number" min="0.01" step="0.01" value={line.quantity} onChange={e=>updateLine(i,{quantity:Number(e.target.value)})}/></td><td><input type="number" min="0" step="0.01" value={line.unit_price} onChange={e=>updateLine(i,{unit_price:Number(e.target.value)})}/></td><td><input type="number" min="0" max="100" step="0.01" value={line.discount_percent} onChange={e=>updateLine(i,{discount_percent:Number(e.target.value)})}/></td><td className="numeric"><strong>{money(total)}</strong></td><td><button type="button" className="icon-button" disabled={lines.length===1} aria-label="Eliminar línea" onClick={()=>setLines(xs=>xs.filter((_,j)=>j!==i))}><Trash2 size={16}/></button></td></tr>})}</tbody></table></div>
    {lines.map((line,i)=>line.product_id&&line.product_definition_snapshot&&expandedLines.has(i)?<QuotationLineInstanceEditor key={`editor-${i}`} line={line} lineIndex={i} onDimensionChange={updateDimensionValue} onCharacteristicChange={updateCharacteristic}/>:null)}
    <div className="quote-totals"><span>Base imponible <strong>{money(totals.net)}</strong></span><span>Descuentos <strong>{money(totals.discount)}</strong></span><span>Impuestos ({taxPercent}%) <strong>{money(totals.tax)}</strong></span><span>Total <strong>{money(totals.total)}</strong></span></div>
   </section>
   <section className="panel quotation-notes-panel"><label className="wide-field"><span className="sr-only">Observaciones</span><textarea aria-label="Observaciones" placeholder="Observaciones" rows={5} value={notes} onChange={e=>setNotes(e.target.value)}/></label></section>
  </form>
  <ProfileSaveBar onSave={()=>{const formElement=document.getElementById('quotation-create-form') as HTMLFormElement|null;formElement?.requestSubmit();}} saving={saving} label="Crear presupuesto"/>
  {pendingCustomerId!==null&&<ConfirmationDialog title="Cambiar cliente" message="Al cambiar el cliente se recalcularán las direcciones y los descuentos aplicados a las líneas del presupuesto. ¿Quieres continuar?" confirmLabel="Cambiar cliente" busy={changingCustomer} onCancel={cancelCustomerChange} onConfirm={confirmCustomerChange}/>} 
 </div>;
}

function QuotationLineInstanceEditor({line,lineIndex,onDimensionChange,onCharacteristicChange}:{line:Line;lineIndex:number;onDimensionChange:(line:number,dimension:number,value:number|null)=>void;onCharacteristicChange:(line:number,characteristic:number,patch:Partial<QuotationLineCharacteristicDraft>)=>void}){
 const definition=line.product_definition_snapshot; if(!definition)return null;
 return <div className="panel quotation-line-editor-card"><div className="panel-head"><div><h3>Línea {lineIndex+1}: {line.description||'Sin descripción'}</h3><p>Artículo {line.product_id}</p></div></div>
  <div className="quotation-definition-summary"><div><strong>Definición del artículo</strong><span>{definition.dimensions.length} dimensión(es) · {definition.characteristics.length} característica(s)</span></div><span className="definition-badge">Definición bloqueada</span></div>
  <div className="form-grid">
   {definition.dimensions.length>0&&<div className="quotation-edit-subsection"><div className="quotation-section-head"><div><h4>Dimensiones</h4><p>Nombre, unidad, código y orden vienen del artículo. Solo se informa el valor.</p></div></div>{line.dimensions.map((d,di)=><div className="quotation-instance-row" key={`${d.code}-${di}`}><div><strong>{d.name}</strong><span>{d.code}{d.unit_id!=null?` · unidad ${d.unit_id}`:''}</span></div><input aria-label={`Valor ${d.name}`} type="number" step={1/(10**Math.max(0,Number(definition.dimensions[di]?.decimals??2)))} value={d.value??''} onChange={e=>onDimensionChange(lineIndex,di,e.target.value===''?null:Number(e.target.value))}/></div>)}</div>}
   {definition.characteristics.length>0&&<div className="quotation-edit-subsection"><div className="quotation-section-head"><div><h4>Características</h4><p>Solo aparecen las características asociadas al artículo y sus valores permitidos.</p></div></div>{definition.characteristics.map((c,ci)=>{const current=line.characteristics[ci]??{attribute_id:c.attribute_id,attribute_value_id:null,value_text:null,value_number:null,value_boolean:null};return <div className="quotation-instance-row" key={c.assignment_id}><div><strong>{c.attribute_name||c.attribute_code}</strong><span>{c.attribute_code}{c.required?' · obligatorio':''}</span></div>{c.values.length>0?<select value={current.attribute_value_id??''} onChange={e=>onCharacteristicChange(lineIndex,ci,{attribute_id:c.attribute_id,attribute_value_id:e.target.value?Number(e.target.value):null,value_text:null,value_number:null,value_boolean:null})}><option value="">Selecciona…</option>{c.values.map(v=><option key={v.id} value={v.id}>{v.code} · {v.name}</option>)}</select>:c.data_type==='NUMBER'?<input type="number" step="0.01" value={current.value_number??''} onChange={e=>onCharacteristicChange(lineIndex,ci,{attribute_id:c.attribute_id,attribute_value_id:null,value_text:null,value_number:e.target.value===''?null:Number(e.target.value),value_boolean:null})}/>:c.data_type==='BOOLEAN'?<input type="checkbox" checked={current.value_boolean===true} onChange={e=>onCharacteristicChange(lineIndex,ci,{attribute_id:c.attribute_id,attribute_value_id:null,value_text:null,value_number:null,value_boolean:e.target.checked})}/>:<input value={current.value_text??''} onChange={e=>onCharacteristicChange(lineIndex,ci,{attribute_id:c.attribute_id,attribute_value_id:null,value_text:e.target.value||null,value_number:null,value_boolean:null})}/>}</div>})}</div>}
   {definition.dimensions.length===0&&definition.characteristics.length===0&&<p className="muted">Este artículo no tiene datos de configuración definidos.</p>}
  </div>
 </div>;
}

function AddressEditor({title,addresses,value,onChange,onSourceChange}:{title:string;addresses:any[];value:AddressDraft;onChange:(value:AddressDraft)=>void;onSourceChange:(id:number|null)=>void}){const set=(key:keyof AddressDraft,next:string)=>onChange({...value,[key]:next});const selectSource=(id:number|null)=>{const source=addresses.find(a=>a.id===id);onSourceChange(id);onChange(source?addressDraft(source):{...value,source_id:id});};return <fieldset className="address-editor"><legend>{title}</legend><label className="address-source">Cargar desde cliente<select value={value.source_id??''} onChange={e=>selectSource(e.target.value?Number(e.target.value):null)}><option value="">Sin dirección de cliente</option>{addresses.map(a=><option key={a.id} value={a.id}>{addressLabel(a)}</option>)}</select></label><div className="address-editor-grid"><label className="address-street">Dirección<input value={value.street} onChange={e=>set('street',e.target.value)}/></label><label>Código Postal<input value={value.postal_code} onChange={e=>set('postal_code',e.target.value)}/></label><label>Localidad<input value={value.city} onChange={e=>set('city',e.target.value)}/></label><label>Provincia<input value={value.region} onChange={e=>set('region',e.target.value)}/></div></fieldset>}
function addressDraft(a:any):AddressDraft{return{source_id:a?.id??null,label:a?.label||({FACTURACION:'Facturación',FISCAL:'Fiscal',INSTALACION:'Instalación'} as Record<string,string>)[String(a?.address_type||'').toUpperCase()]||'Dirección',street:a?.street||'',postal_code:a?.postal_code||'',city:a?.city||'',region:a?.region||''};}
function addressLabel(a:any){return [a.label||({FACTURACION:'Facturación',FISCAL:'Fiscal',INSTALACION:'Instalación'} as Record<string,string>)[String(a.address_type).toUpperCase()]||'Dirección',a.street,a.postal_code,a.city].filter(Boolean).join(' · ');}
function LookupSelect({label,required=false,compact=false,options,value,onChange,placeholder}:{label?:string;required?:boolean;compact?:boolean;options:Option[];value:number|null;onChange:(id:number|null)=>void;placeholder:string}){const [query,setQuery]=useState('');const [open,setOpen]=useState(false);const [rect,setRect]=useState<DOMRect|null>(null);const inputRef=useRef<HTMLInputElement|null>(null);const selected=options.find(x=>x.id===value);const filtered=useMemo(()=>{const q=query.trim().toLocaleLowerCase();if(!q)return options.slice(0,10);return options.filter(x=>`${x.code??''} ${x.label}`.toLocaleLowerCase().includes(q)).slice(0,10);},[options,query]);const reposition=()=>{if(inputRef.current)setRect(inputRef.current.closest('.lookup-control')?.getBoundingClientRect()??inputRef.current.getBoundingClientRect());};useEffect(()=>{if(!open)return;reposition();const onScroll=()=>reposition();window.addEventListener('scroll',onScroll,true);window.addEventListener('resize',onScroll);return()=>{window.removeEventListener('scroll',onScroll,true);window.removeEventListener('resize',onScroll);};},[open]);return <div className={`lookup-field ${compact?'lookup-field-compact':''}`}>{label&&<span className="field-label">{label}{required?' *':''}</span>}<div className="lookup-control"><Search size={15}/><input ref={inputRef} required={required&&!value} value={open?query:(selected?.label??'')} placeholder={placeholder} onFocus={()=>{setOpen(true);if(selected)setQuery(selected.label);}} onChange={e=>{setQuery(e.target.value);setOpen(true);if(value!==null)onChange(null);}}/>{selected&&<button type="button" className="lookup-clear" aria-label="Limpiar selección" onClick={()=>{setQuery('');onChange(null);setOpen(false);}}><X size={14}/></button>}</div>{open&&rect&&createPortal(<div className="lookup-portal"><button type="button" className="lookup-dismiss" aria-label="Cerrar resultados" onClick={()=>setOpen(false)}/><div className="lookup-results" style={{top:rect.bottom+4,left:rect.left,width:Math.max(rect.width,280)}}>{filtered.length===0?<small>No se han encontrado resultados.</small>:filtered.map(x=><button type="button" key={x.id} onMouseDown={e=>e.preventDefault()} onClick={()=>{onChange(x.id);setQuery('');setOpen(false);}}><strong>{x.code?`${x.code} · `:''}{x.label}</strong></button>)}</div></div>,document.body)}</div>}
function ConfirmationDialog({title,message,confirmLabel,busy,onCancel,onConfirm}:{title:string;message:string;confirmLabel:string;busy:boolean;onCancel:()=>void;onConfirm:()=>void}){return createPortal(<div className="confirmation-overlay" role="presentation"><div className="confirmation-dialog" role="dialog" aria-modal="true" aria-labelledby="confirmation-title"><h2 id="confirmation-title">{title}</h2><p>{message}</p><div className="confirmation-actions"><button type="button" className="secondary-button" onClick={onCancel} disabled={busy}>Cancelar</button><button type="button" className="primary-button" onClick={onConfirm} disabled={busy}>{busy?'Recalculando…':confirmLabel}</button></div></div></div>,document.body)}
