import React, { useCallback, useEffect, useMemo, useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { ArrowLeft, ChevronDown, ChevronUp, Maximize2, Minimize2, Plus, Trash2 } from 'lucide-react';
import { CoreRepositoryError } from '../../services/core/coreRepository';
import { createQuotation, customerAddresses, customerProductDiscount, quotationOptions } from '../../services/sales/quotationCreationRepository';
import { LookupSelect } from '../../components/LookupSelect';
import { MessageLog } from '../../components/ui/MessageLog';
import { Toast } from '../../components/ui/Toast';
import './quotation-create.css';

type Line={product_id:number|null;description:string;quantity:number;unit_price:number;discount_percent:number};
const blank=():Line=>({product_id:null,description:'',quantity:1,unit_price:0,discount_percent:0});
const money=(n:number)=>new Intl.NumberFormat('es-ES',{style:'currency',currency:'EUR'}).format(n);

export function QuotationCreate(){
 const nav=useNavigate();
 const [opts,setOpts]=useState<any>({customers:[],commercials:[],warehouses:[],paymentMethods:[],paymentTerms:[],taxRates:[],products:[]});
 const [loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(''),[toast,setToast]=useState('');
 const [customerId,setCustomerId]=useState<number|null>(null),[commercialId,setCommercialId]=useState<number|null>(null),[warehouseId,setWarehouseId]=useState<number|null>(null),[paymentMethodId,setPaymentMethodId]=useState<number|null>(null),[paymentTermId,setPaymentTermId]=useState<number|null>(null),[taxRateId,setTaxRateId]=useState<number|null>(null),[taxPercent,setTaxPercent]=useState(0);
 const [issueDate,setIssueDate]=useState(new Date().toISOString().slice(0,10)),[validUntil,setValidUntil]=useState(''),[reference,setReference]=useState(''),[notes,setNotes]=useState('');
 const [addresses,setAddresses]=useState<any[]>([]),[billingId,setBillingId]=useState<number|null>(null),[installationId,setInstallationId]=useState<number|null>(null);
 const [lines,setLines]=useState<Line[]>([blank()]),[linesExpanded,setLinesExpanded]=useState(false),[headerCollapsed,setHeaderCollapsed]=useState(false),[pendingCustomerId,setPendingCustomerId]=useState<number|null>(null),[changingCustomer,setChangingCustomer]=useState(false);
 const addressLabel=(a:any)=>[a.name,a.address_line1,a.city].filter(Boolean).join(' · ');
 useEffect(()=>{quotationOptions().then(setOpts).catch((e:any)=>setError(e instanceof Error?e.message:'No se pudieron cargar las opciones.')).finally(()=>setLoading(false));},[]);
 const totals=useMemo(()=>lines.reduce((a,l)=>{const gross=Math.max(0,l.quantity*l.unit_price);const net=Math.max(0,gross*(1-l.discount_percent/100));return{discount:a.discount+(gross-net),net:a.net+net,tax:a.tax+net*taxPercent/100,total:a.total+net*(1+taxPercent/100)};},{discount:0,net:0,tax:0,total:0}),[lines,taxPercent]);
 const closeToast=useCallback(()=>setToast(''),[]);
 const requestCustomerChange=(id:number|null)=>{if(id===customerId)return;setPendingCustomerId(id);};
 const cancelCustomerChange=()=>setPendingCustomerId(null);
 const confirmCustomerChange=async()=>{const id=pendingCustomerId;setPendingCustomerId(null);if(id===customerId)return;setChangingCustomer(true);setError('');try{setCustomerId(id);if(id===null){setAddresses([]);setBillingId(null);setInstallationId(null);setLines(xs=>xs.map(l=>({...l,discount_percent:0})));return;}const rows=await customerAddresses(id);setAddresses(rows);const billing=rows.find((a:any)=>['FACTURACION','FISCAL'].includes(String(a.address_type).toUpperCase()));const installation=rows.find((a:any)=>String(a.address_type).toUpperCase()==='INSTALACION');setBillingId(billing?.id??null);setInstallationId(installation?.id??null);const discounted=await Promise.all(lines.map(async l=>l.product_id?customerProductDiscount(id,l.product_id):null));setLines(xs=>xs.map((l,i)=>({...l,discount_percent:discounted[i]?.discount_percent??0})));if(discounted.some(Boolean))setToast('El cliente tiene descuentos aplicados.');}catch(e){setError(e instanceof Error?e.message:'No se pudieron recalcular los datos asociados al cliente.');}finally{setChangingCustomer(false);}};
 useEffect(()=>{if(!customerId){setAddresses([]);setBillingId(null);setInstallationId(null);return;}void customerAddresses(customerId).then((rows:any[])=>{setAddresses(rows);const billing=rows.find((a:any)=>['FACTURACION','FISCAL'].includes(String(a.address_type).toUpperCase()));const installation=rows.find((a:any)=>String(a.address_type).toUpperCase()==='INSTALACION');setBillingId(billing?.id??null);setInstallationId(installation?.id??null);}).catch((e:any)=>setError(e instanceof Error?e.message:'No se pudieron cargar las direcciones del cliente.'));},[customerId]);
 async function save(e?:React.FormEvent){e?.preventDefault();setError('');if(!customerId){setError('Selecciona un cliente.');return;}setSaving(true);try{await createQuotation({customer_id:customerId,commercial_id:commercialId,warehouse_id:warehouseId,billing_address_id:billingId,installation_address_id:installationId,payment_method_id:paymentMethodId,payment_term_id:paymentTermId,measurement_id:null,tax_rate_id:taxRateId,tax_percent:taxPercent,issue_date:issueDate,valid_until:validUntil||null,reference,notes,lines});nav('/ventas/presupuestos');}catch(e){setError(e instanceof CoreRepositoryError?e.message:e instanceof Error?e.message:'No se pudo guardar el presupuesto.');}finally{setSaving(false);}}
 if(loading)return <div className="module-page"><div className="page-head"><div><div className="eyebrow">VENTAS / PRESUPUESTOS / NUEVO</div><h1>Nuevo presupuesto</h1></div></div><p>Cargando datos…</p></div>;
 const product=async(i:number,id:number|null)=>{const p=opts.products.find((x:any)=>x.id===id);if(id===null){setLines(xs=>xs.map((l,j)=>j===i?{...l,product_id:null,description:'',unit_price:0,discount_percent:0}:l));return;}try{const discount=customerId?await customerProductDiscount(customerId,id):null;setLines(xs=>xs.map((l,j)=>j===i?{...l,product_id:id,description:p?.label||'',unit_price:p?.price??0,discount_percent:discount?.discount_percent??0}:l));if(discount)setToast(`El cliente tiene descuentos aplicados (${discount.level==='article'?'artículo':'familia'}: ${discount.discount_percent}%).`);}catch(e){setError(e instanceof Error?e.message:'No se pudo recuperar el descuento del cliente.');}};
 const change=(i:number,k:keyof Line,v:string)=>setLines(xs=>xs.map((l,j)=>j===i?{...l,[k]:k==='description'?v:Number(v)}:l));
 return <div className={`module-page quotation-create ${linesExpanded?'quotation-lines-expanded':''}`}>
  <div className="page-head"><div><div className="eyebrow">VENTAS / PRESUPUESTOS / NUEVO</div><h1>Nuevo presupuesto</h1><p>Crear presupuesto en estado borrador.</p></div><Link className="secondary-button" to="/ventas/presupuestos"><ArrowLeft size={15}/>Volver a presupuestos</Link></div>
  <MessageLog error={error}/>{toast&&<Toast message={toast} onClose={closeToast}/>} 
  <form id="quotation-create-form" className="detail-grid" onSubmit={save}>
   <section className="panel quotation-header-panel">
    <div className="panel-head"><div><h2>Datos generales</h2><p>Cliente, condiciones comerciales y direcciones del presupuesto.</p></div><button type="button" className="secondary-button" onClick={()=>setHeaderCollapsed(v=>!v)}>{headerCollapsed?<><ChevronDown size={15}/>Mostrar cabecera</>:<><ChevronUp size={15}/>Contraer cabecera</>}</button></div>
    {!headerCollapsed&&<div className="form-grid">
     <label className="quotation-reference-field">Referencia<input value={reference} onChange={e=>setReference(e.target.value)} /></label>
     <LookupSelect label="Cliente" required options={opts.customers} value={customerId} onChange={requestCustomerChange} placeholder="Buscar cliente por nombre…" />
     <label>Comercial<select value={commercialId??''} onChange={e=>setCommercialId(e.target.value?Number(e.target.value):null)}><option value="">Sin asignar</option>{opts.commercials.map((x:any)=><option key={x.id} value={x.id}>{x.label}</option>)}</select></label>
     <label>Almacén<select value={warehouseId??''} onChange={e=>setWarehouseId(e.target.value?Number(e.target.value):null)}><option value="">Sin asignar</option>{opts.warehouses.map((x:any)=><option key={x.id} value={x.id}>{x.label}</option>)}</select></label>
     <label className="date-field">Fecha de Documento<input type="date" value={issueDate} onChange={e=>setIssueDate(e.target.value)} required/></label><label className="date-field">Válido hasta<input type="date" value={validUntil} onChange={e=>setValidUntil(e.target.value)}/></label>
     <label>Forma de pago<select value={paymentMethodId??''} onChange={e=>setPaymentMethodId(e.target.value?Number(e.target.value):null)}><option value="">Sin especificar</option>{opts.paymentMethods.map((x:any)=><option key={x.id} value={x.id}>{x.label}</option>)}</select></label>
     <label>Condiciones de pago<select value={paymentTermId??''} onChange={e=>setPaymentTermId(e.target.value?Number(e.target.value):null)}><option value="">Sin especificar</option>{opts.paymentTerms.map((x:any)=><option key={x.id} value={x.id}>{x.label}</option>)}</select></label>
     <label>IVA<select value={taxRateId??''} onChange={e=>{const id=e.target.value?Number(e.target.value):null;const t=opts.taxRates.find((x:any)=>x.id===id);setTaxRateId(id);setTaxPercent(Number(t?.rate??0));}}><option value="">Sin IVA</option>{opts.taxRates.map((t:any)=><option key={t.id} value={t.id}>{t.rate}% · {t.label}</option>)}</select></label>
     <label className="address-field">Dirección de facturación<select value={billingId??''} onChange={e=>setBillingId(e.target.value?Number(e.target.value):null)}><option value="">Sin especificar</option>{addresses.map((a:any)=><option key={a.id} value={a.id}>{addressLabel(a)}</option>)}</select></label>
     <label className="address-field">Dirección de instalación<select value={installationId??''} onChange={e=>setInstallationId(e.target.value?Number(e.target.value):null)}><option value="">Sin especificar</option>{addresses.map((a:any)=><option key={a.id} value={a.id}>{addressLabel(a)}</option>)}</select></label>
    </div>}
   </section>
   <section className={`panel quotation-lines-panel ${linesExpanded?'expanded':''}`}>
    <div className="panel-head"><div><h2>Líneas del presupuesto</h2><p>Añade artículos, cantidades, precios y descuentos.</p></div><div className="panel-actions"><button type="button" className="secondary-button" onClick={()=>setLinesExpanded(v=>!v)}>{linesExpanded?<><Minimize2 size={15}/>Reducir espacio</>:<><Maximize2 size={15}/>Ampliar espacio</>}</button><button type="button" className="primary-button" onClick={()=>setLines(xs=>[...xs,blank()])}><Plus size={15}/>Añadir línea</button></div></div>
    <div className="table-panel quotation-lines-table"><table><thead><tr><th>Artículo</th><th>Descripción</th><th>Cant.</th><th>Precio</th><th>Dto.</th><th className="numeric">Total</th><th></th></tr></thead><tbody>{lines.map((l,i)=>{const total=Math.max(0,l.quantity*l.unit_price*(1-l.discount_percent/100))*(1+taxPercent/100);return <tr key={i}><td><LookupSelect compact options={opts.products} value={l.product_id} onChange={(id:number|null)=>void product(i,id)} placeholder="Buscar artículo por código o descripción…" /></td><td className="description-cell"><input value={l.description} onChange={e=>change(i,'description',e.target.value)} required /></td><td className="quantity-cell"><input type="number" min="0.01" step="0.01" value={l.quantity} onChange={e=>change(i,'quantity',e.target.value)} /></td><td className="price-cell"><input type="number" min="0" step="0.01" value={l.unit_price} onChange={e=>change(i,'unit_price',e.target.value)} /></td><td className="discount-cell"><input type="number" min="0" max="100" step="0.01" value={l.discount_percent} onChange={e=>change(i,'discount_percent',e.target.value)} /></td><td className="numeric">{money(total)}</td><td><button type="button" className="icon-button" aria-label="Eliminar línea" disabled={lines.length===1} onClick={()=>setLines(xs=>xs.filter((_,j)=>j!==i))}><Trash2 size={16}/></button></td></tr>})}</tbody></table></div>
    <div className="quote-totals"><span>Base imponible <strong>{money(totals.net)}</strong></span><span>Descuentos <strong>{money(totals.discount)}</strong></span><span>Impuestos ({taxPercent}%) <strong>{money(totals.tax)}</strong></span><span>Total <strong>{money(totals.total)}</strong></span></div>
   </section>
   <section className="panel"><div className="panel-head"><div><h2>Notas</h2><p>Información adicional del presupuesto.</p></div></div><textarea value={notes} onChange={e=>setNotes(e.target.value)} rows={4}/><div className="form-actions"><button type="button" className="secondary-button" onClick={()=>nav('/ventas/presupuestos')}>Cancelar</button><button type="submit" className="primary-button" disabled={saving||changingCustomer}>{saving?'Guardando…':'Guardar presupuesto'}</button></div></section>
  </form>
  {pendingCustomerId!==null&&<div className="confirmation-overlay"><div className="confirmation-dialog"><h2>Cambiar cliente</h2><p>Al cambiar el cliente se recalcularán las direcciones y los descuentos asociados a sus líneas.</p><div className="confirmation-actions"><button type="button" className="secondary-button" onClick={cancelCustomerChange}>Cancelar</button><button type="button" className="primary-button" onClick={()=>void confirmCustomerChange()}>Continuar</button></div></div></div>}
 </div>;
}
