import { FormEvent, useEffect, useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { Save } from 'lucide-react';
import { getActiveCompanies } from '../../services/core/coreRepository';
import { createCustomer } from '../../services/core/customerRepository';
import type { CustomerForm } from './types';
import { validateEmail, validatePhone, validateSpanishTaxId } from './validation';

export function CustomerCreate(){
  const navigate=useNavigate(); const [companyId,setCompanyId]=useState<number|null>(null); const [form,setForm]=useState<CustomerForm>({legal_name:'',trade_name:'',tax_id:'',email:'',phone:'',active:true,notes:''}); const [saving,setSaving]=useState(false); const [error,setError]=useState('');
  useEffect(()=>{getActiveCompanies().then(cs=>setCompanyId(cs[0]?.id??null)).catch(e=>setError(e instanceof Error?e.message:'No se pudo obtener la empresa activa.'))},[]);
  async function submit(e:FormEvent){e.preventDefault();const errors=[validateSpanishTaxId(form.tax_id),validateEmail(form.email),validatePhone(form.phone)].filter(Boolean) as string[];if(!form.legal_name.trim())errors.unshift('La razón social es obligatoria.');if(!companyId)errors.unshift('No hay una empresa activa configurada.');if(errors.length){setError(errors[0]);return;}setSaving(true);setError('');try{const id=await createCustomer(form,companyId!);navigate(`/ventas/clientes/${id}`)}catch(e){setError(e instanceof Error?e.message:'No se pudo crear el cliente.')}finally{setSaving(false)}}
  return <div className="module-page"><div className="page-head"><div><div className="eyebrow">VENTAS / CLIENTES / NUEVO</div><h1>Nuevo cliente</h1><p>Alta de cliente con ID generado automáticamente.</p></div><Link className="secondary-button" to="/ventas/clientes">← Volver al listado</Link></div>{error&&<div className="inline-error">{error}</div>}<form className="detail-grid" onSubmit={submit}><section className="panel"><div className="panel-head"><div><h2>Datos generales</h2><p>El código y el ID no se introducen manualmente.</p></div></div><div className="form-grid"><label>Razón social *<input autoFocus value={form.legal_name} onChange={e=>setForm({...form,legal_name:e.target.value})} maxLength={200}/></label><label>Nombre comercial<input value={form.trade_name} onChange={e=>setForm({...form,trade_name:e.target.value})} maxLength={200}/></label><label>CIF/NIF *<input value={form.tax_id} onChange={e=>setForm({...form,tax_id:e.target.value.toUpperCase()})} maxLength={32}/></label><label>Email<input type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})} maxLength={254}/></label><label>Teléfono<input type="tel" value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})} maxLength={40}/></label><label>Estado<select value={form.active?'1':'0'} onChange={e=>setForm({...form,active:e.target.value==='1'})}><option value="1">Activo</option><option value="0">Inactivo</option></select></label><label className="wide">Observaciones<textarea value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></label></div><div className="actions"><button className="primary-button" disabled={saving}><Save size={16}/>{saving?'Creando…':'Crear cliente'}</button></div></section></form></div>
}
