import { supabase } from '../../lib/supabase';
import { loadMasterProductConfiguration } from '../catalog/productConfigurationService';
import type { MasterProductConfiguration } from '../catalog/productConfigurationService';
import { CoreRepositoryError } from '../core/coreRepository';

export type LonaConfectionComponent = { index:number; productId:number; productCode:string; productName:string; characteristicName:string|null; quantity:number; line:number|null; output:number|null; lineUnit:string|null; outputUnit:string|null; lineDimensionCode:string|null; outputDimensionCode:string|null; sourceComponent:OtdComponentSnapshot; productConfiguration:MasterProductConfiguration; };
export type LonaCutGeometry = { width:number; height:number; widthLabel:string; heightLabel:string };
export type LonaStockCandidate = { stockItemId:number; warehouseId:number; warehouseCode:string; warehouseName:string; productId:number; characteristicId:number|null; characteristicCode:string|null; quantity:number; sourceDimensions:number[]; sourceDimensionUnits:string[]; cutDimensions:[number,number]; cutDimensionUnits:string[]; remainderDimensions:[number,number]|null; remainderDimensionUnits:string[]; rotated:boolean; score:number; reason:string; };
export type LonaConfectionResult = { orderLineId:number; orderLineNo:number; reference:string|null; otdCode:string|null; components:LonaConfectionComponent[]; };
export type LonaConfectionWorkSheet = { id:number; code:string; issueDate:string; status:string; orderLineId:number; productCode:string|null; productName:string|null; characteristicName:string|null; quantity:number; requiredDimensions:number[]; requiredDimensionUnits:string[]; unitSymbol:string|null; selectionMode:string|null; selectionReason:string|null; lines:Array<{id:number;lineNo:number;warehouseCode:string|null;warehouseName:string|null;stockItemId:number|null;sourceDimensions:number[];sourceDimensionUnits:string[];cutDimensions:number[];cutDimensionUnits:string[];quantity:number;remainderDimensions:number[];remainderDimensionUnits:string[]}>; };

type OtdDimensionSnapshot={code?:string|null;name?:string|null;value?:unknown;unit_id?:number|null;unit_symbol?:string|null;unit_code?:string|null};
type OtdComponentSnapshot={product_id?:unknown;product_code?:unknown;product_name?:unknown;characteristic_name?:unknown;characteristic_code?:unknown;quantity?:unknown;dimension_list?:OtdDimensionSnapshot[];dimensions?:Record<string,unknown>};
type OtdSnapshot={otd_code?:unknown;components?:OtdComponentSnapshot[];dimensions?:OtdDimensionSnapshot[]};
type DimensionValue=OtdDimensionSnapshot;
type StockHeaderRow={id:number;warehouse_id:number};
type CharacteristicRow={id:number;code:string|null};
type WarehouseRow={id:number;code:string|null;name:string|null};
type StockItemRow={id:number;product_id:number;warehouse_stock_id:number;characteristic_id:number|null;quantity:number;dimension_values:unknown;dimension_units:unknown;status:string};

function client(){if(!supabase)throw new CoreRepositoryError('Supabase no está configurado.');return supabase}
function numeric(value:unknown):number|null{const n=Number(value);return Number.isFinite(n)?n:null}
function unitText(dimension:DimensionValue|undefined,configuration:MasterProductConfiguration):string|null{if(!dimension)return null;if(dimension.unit_symbol)return String(dimension.unit_symbol);if(dimension.unit_code)return String(dimension.unit_code);if(dimension.unit_id!=null){const unit=configuration.unitsMap.get(Number(dimension.unit_id));if(unit)return unit.code||unit.name}const definition=configuration.dimensions.find(candidate=>(dimension.code&&candidate.code===dimension.code)||(dimension.name&&candidate.name===dimension.name));if(definition?.unit_id!=null){const unit=configuration.unitsMap.get(Number(definition.unit_id));if(unit)return unit.code||unit.name}return null}
function dimensionText(dimension:DimensionValue|undefined):string{return`${dimension?.code??''} ${dimension?.name??''}`.trim().toLowerCase()}
function componentDimensions(component:OtdComponentSnapshot,snapshot:OtdSnapshot):DimensionValue[]{if(Array.isArray(component.dimension_list)&&component.dimension_list.length)return component.dimension_list;if(component.dimensions&&typeof component.dimensions==='object'){const entries=Object.entries(component.dimensions).map(([code,value])=>({code,value} as OtdDimensionSnapshot));if(entries.length)return entries}return Array.isArray(snapshot.dimensions)?snapshot.dimensions:[]}
function resolveCutDimensions(dimensions:DimensionValue[]):{line:DimensionValue|undefined;output:DimensionValue|undefined}{if(dimensions.length<2)return{line:dimensions[0],output:undefined};const lineIndex=dimensions.findIndex(d=>(/(^|\b)(linea|línea|ancho|width)(\b|$)/i).test(dimensionText(d)));const outputIndex=dimensions.findIndex(d=>(/(^|\b)(salida|alto|altura|height)(\b|$)/i).test(dimensionText(d)));if(lineIndex>=0&&outputIndex>=0&&lineIndex!==outputIndex)return{line:dimensions[lineIndex],output:dimensions[outputIndex]};return{line:dimensions[0],output:dimensions[1]}}
function getGeometry(component:LonaConfectionComponent):LonaCutGeometry|null{const dimensions=component.sourceComponent.dimension_list?.length?component.sourceComponent.dimension_list:Object.entries(component.sourceComponent.dimensions??{}).map(([code,value])=>({code,value} as OtdDimensionSnapshot));const{line,output}=resolveCutDimensions(dimensions);const width=numeric(line?.value);const height=numeric(output?.value);if(width==null||height==null||width<=0||height<=0)return null;return{width,height,widthLabel:`${line?.code??line?.name??'Línea'}${component.lineUnit?` (${component.lineUnit})`:''}`,heightLabel:`${output?.code??output?.name??'Salida'}${component.outputUnit?` (${component.outputUnit})`:''}`}}
export function getLonaCutGeometry(component:LonaConfectionComponent):LonaCutGeometry|null{return getGeometry(component)}

const LENGTH_FACTORS_MM:Record<string,number>={mm:1,millimeter:1,millimetre:1,cm:10,centimeter:10,centimetre:10,m:1000,meter:1000,metre:1000};
function normalizeLength(value:number,unit:string|null):number|null{if(!unit)return null;const factor=LENGTH_FACTORS_MM[unit.trim().toLowerCase()];return factor==null?null:value*factor}
function asStringArray(value:unknown):string[]{return Array.isArray(value)?value.map(v=>String(v??'')):[]}

export async function listLonaStockCandidates(input:{companyId:number;productId:number;characteristicCode?:string|null;requiredLine:number;requiredOutput:number;requiredLineUnit?:string|null;requiredOutputUnit?:string|null}):Promise<LonaStockCandidate[]>{
 const c=client();
 const {data:itemData,error:itemError}=await c.from('warehouse_stock_item').select('id,product_id,warehouse_stock_id,characteristic_id,quantity,dimension_values,dimension_units,status').eq('product_id',input.productId).gt('quantity',0).eq('status','AVAILABLE').order('created_at',{ascending:true}).limit(500);
 if(itemError)throw new CoreRepositoryError(itemError.message);
 const items=(itemData??[]) as StockItemRow[];
 const stockIds=[...new Set(items.map(row=>Number(row.warehouse_stock_id)).filter(Number.isFinite))];
 const characteristicIds=[...new Set(items.map(row=>row.characteristic_id==null?null:Number(row.characteristic_id)).filter((id):id is number=>id!=null))];
 const [stocksResult,characteristicsResult]=await Promise.all([stockIds.length?c.from('warehouse_stock').select('id,warehouse_id').in('id',stockIds):Promise.resolve({data:[],error:null}),characteristicIds.length?c.from('product_characteristic').select('id,code').in('id',characteristicIds):Promise.resolve({data:[],error:null})]);
 if(stocksResult.error)throw new CoreRepositoryError(stocksResult.error.message);if(characteristicsResult.error)throw new CoreRepositoryError(characteristicsResult.error.message);
 const stocks=(stocksResult.data??[]) as StockHeaderRow[];const characteristics=(characteristicsResult.data??[]) as CharacteristicRow[];const warehouseIds=[...new Set(stocks.map(row=>Number(row.warehouse_id)).filter(Number.isFinite))];const warehousesResult=warehouseIds.length?await c.from('warehouse').select('id,code,name').in('id',warehouseIds):{data:[],error:null};if(warehousesResult.error)throw new CoreRepositoryError(warehousesResult.error.message);
 const stockById=new Map(stocks.map(row=>[Number(row.id),row]));const characteristicById=new Map(characteristics.map(row=>[Number(row.id),row]));const warehouseById=new Map(((warehousesResult.data??[]) as WarehouseRow[]).map(row=>[Number(row.id),row]));const requestedCharacteristic=input.characteristicCode??null;
 const requiredLineMm=normalizeLength(input.requiredLine,input.requiredLineUnit??null);const requiredOutputMm=normalizeLength(input.requiredOutput,input.requiredOutputUnit??null);if(requiredLineMm==null||requiredOutputMm==null)throw new CoreRepositoryError('No se puede comparar el material porque falta una unidad de longitud compatible.');
 const result:LonaStockCandidate[]=[];
 for(const row of items){
   const characteristicId=row.characteristic_id==null?null:Number(row.characteristic_id);const characteristicCode=characteristicId==null?null:characteristicById.get(characteristicId)?.code??null;if(characteristicCode!==requestedCharacteristic)continue;
   const dimensions=Array.isArray(row.dimension_values)?row.dimension_values.map(Number).filter(Number.isFinite):[];const units=asStringArray(row.dimension_units);if(dimensions.length<2||units.length!==dimensions.length)continue;
   const d0=normalizeLength(dimensions[0],units[0]);const d1=normalizeLength(dimensions[1],units[1]);if(d0==null||d1==null)continue;
   const direct=d0>=requiredLineMm&&d1>=requiredOutputMm;const rotated=d0>=requiredOutputMm&&d1>=requiredLineMm;if(!direct&&!rotated)continue;const useRotated=!direct&&rotated;
   const cut:[number,number]=useRotated?[input.requiredOutput,input.requiredLine]:[input.requiredLine,input.requiredOutput];const cutDimensionUnits=[useRotated?(input.requiredOutputUnit??''):(input.requiredLineUnit??''),useRotated?(input.requiredLineUnit??''):(input.requiredOutputUnit??'')];const cutMm:[number,number]=useRotated?[requiredOutputMm,requiredLineMm]:[requiredLineMm,requiredOutputMm];
   const remainderMm:[number,number]=[Math.max(0,d0-cutMm[0]),Math.max(0,d1-cutMm[1])];const factor0=LENGTH_FACTORS_MM[units[0].trim().toLowerCase()]??1;const factor1=LENGTH_FACTORS_MM[units[1].trim().toLowerCase()]??1;const remainder:[number,number]=[remainderMm[0]/factor0,remainderMm[1]/factor1];const waste=remainderMm[0]*remainderMm[1];
   const stock=stockById.get(Number(row.warehouse_stock_id));if(!stock)continue;const warehouse=warehouseById.get(Number(stock.warehouse_id));if(!warehouse)continue;
   result.push({stockItemId:Number(row.id),warehouseId:Number(stock.warehouse_id),warehouseCode:warehouse.code??'—',warehouseName:warehouse.name??'—',productId:Number(row.product_id),characteristicId,characteristicCode,quantity:Number(row.quantity||0),sourceDimensions:dimensions,sourceDimensionUnits:units,cutDimensions:cut,cutDimensionUnits,remainderDimensions:remainder,remainderDimensionUnits:[units[0],units[1]],rotated:useRotated,score:(useRotated?100000:0)+waste,reason:useRotated?'Material compatible girando la pieza.':'Material compatible en la orientación original.'});
 }
 return result.sort((a,b)=>a.score-b.score||a.sourceDimensions.reduce((x,y)=>x+y,0)-b.sourceDimensions.reduce((x,y)=>x+y,0));
}

export async function resolveLonaConfectionComponents(input:{companyId:number;orderLineId:number;orderLineNo:number;reference?:string|null;snapshot:OtdSnapshot}):Promise<LonaConfectionResult>{const snapshot=input.snapshot??{};const rawComponents=Array.isArray(snapshot.components)?snapshot.components:[];const candidates=rawComponents.map((component,index)=>({component,index})).filter(({component})=>Number(component.product_id)>0);const resolved=(await Promise.all(candidates.map(async({component,index})=>{const productId=Number(component.product_id);const configuration=await loadMasterProductConfiguration(productId,input.companyId);if(!configuration.family?.confectionable)return null;const dimensions=componentDimensions(component,snapshot);const{line,output}=resolveCutDimensions(dimensions);return{index,productId,productCode:String(component.product_code??configuration.product.code??''),productName:String(component.product_name??configuration.product.commercial_description??configuration.product.technical_description??''),characteristicName:component.characteristic_name?String(component.characteristic_name):null,quantity:numeric(component.quantity)??0,line:numeric(line?.value),output:numeric(output?.value),lineUnit:unitText(line,configuration),outputUnit:unitText(output,configuration),lineDimensionCode:line?.code??null,outputDimensionCode:output?.code??null,sourceComponent:component,productConfiguration:configuration} satisfies LonaConfectionComponent;}))).filter((component):component is LonaConfectionComponent=>component!==null);if(resolved.length===0)throw new CoreRepositoryError('La línea de pedido no contiene componentes confeccionables.');return{orderLineId:input.orderLineId,orderLineNo:input.orderLineNo,reference:input.reference??null,otdCode:snapshot.otd_code?String(snapshot.otd_code):null,components:resolved}}

export async function createLonaConfectionWorkSheet(input:{companyId:number;salesOrderId:number;salesOrderLineId:number;salesOrderLineNo:number;component:LonaConfectionComponent;candidate:LonaStockCandidate;reference?:string|null;selectionMode?:'AUTOMATIC'|'MANUAL';selectionReason?:string|null}):Promise<LonaConfectionWorkSheet>{const c=client();if(input.component.line==null||input.component.output==null)throw new CoreRepositoryError('La pieza no tiene dimensiones válidas para generar la hoja de confección.');const cut=input.candidate.cutDimensions;const source=input.candidate.sourceDimensions;const remainder=input.candidate.remainderDimensions??[];const{data,error}=await c.rpc('create_lona_confection_work_sheet',{p_company_id:input.companyId,p_sales_order_id:input.salesOrderId,p_sales_order_line_id:input.salesOrderLineId,p_sales_order_line_no:input.salesOrderLineNo,p_product_id:input.component.productId,p_product_code:input.component.productCode,p_product_name:input.component.productName,p_characteristic_id:input.candidate.characteristicId,p_characteristic_code:input.candidate.characteristicCode,p_characteristic_name:input.component.characteristicName,p_required_dimension_values:[input.component.line,input.component.output],p_required_dimension_units:[input.component.lineUnit,input.component.outputUnit],p_quantity:input.component.quantity,p_unit_symbol:input.component.lineUnit,p_unit_code:input.component.outputUnit,p_reference:input.reference??null,p_notes:'Hoja de confección generada a partir del OTD. Pendiente de ejecución de consumo dimensional 2D.',p_selection_mode:input.selectionMode??'AUTOMATIC',p_selection_reason:input.selectionReason??input.candidate.reason,p_selections:[{stock_item_id:input.candidate.stockItemId,warehouse_id:input.candidate.warehouseId,source_dimension_values:source,source_dimension_units:input.candidate.sourceDimensionUnits,cut_dimension_values:cut,cut_dimension_units:input.candidate.cutDimensionUnits,remainder_dimension_values:remainder,remainder_dimension_units:input.candidate.remainderDimensionUnits,quantity:input.component.quantity}]});if(error)throw new CoreRepositoryError(error.message);const sheet=await getLonaConfectionWorkSheet(Number(data));if(!sheet)throw new CoreRepositoryError('La hoja de confección se ha creado pero no se ha podido recuperar.');return sheet}

export async function getLonaConfectionWorkSheet(id:number):Promise<LonaConfectionWorkSheet|null>{const c=client();const{data,error}=await c.from('production_work_sheet').select('id,code,issue_date,status,sales_order_line_id,product_code,product_name,characteristic_name,quantity,required_dimension_values,required_dimension_units,unit_symbol,selection_mode,selection_reason,lines:production_work_sheet_line(id,line_no,warehouse_code,warehouse_name,stock_item_id,source_dimension_values,source_dimension_units,cut_dimension_values,cut_dimension_units,quantity,remainder_dimension_values,remainder_dimension_units)').eq('id',id).eq('document_type','LONA_CONFECTION').maybeSingle();if(error)throw new CoreRepositoryError(error.message);if(!data)return null;return{id:Number(data.id),code:data.code,issueDate:data.issue_date,status:data.status,orderLineId:Number(data.sales_order_line_id),productCode:data.product_code??null,productName:data.product_name??null,characteristicName:data.characteristic_name??null,quantity:Number(data.quantity||0),requiredDimensions:Array.isArray(data.required_dimension_values)?data.required_dimension_values.map(Number):[],requiredDimensionUnits:asStringArray(data.required_dimension_units),unitSymbol:data.unit_symbol??null,selectionMode:data.selection_mode??null,selectionReason:data.selection_reason??null,lines:(data.lines??[]).map((line:any)=>({id:Number(line.id),lineNo:Number(line.line_no),warehouseCode:line.warehouse_code??null,warehouseName:line.warehouse_name??null,stockItemId:line.stock_item_id==null?null:Number(line.stock_item_id),sourceDimensions:Array.isArray(line.source_dimension_values)?line.source_dimension_values.map(Number):[],sourceDimensionUnits:asStringArray(line.source_dimension_units),cutDimensions:Array.isArray(line.cut_dimension_values)?line.cut_dimension_values.map(Number):[],cutDimensionUnits:asStringArray(line.cut_dimension_units),quantity:Number(line.quantity||0),remainderDimensions:Array.isArray(line.remainder_dimension_values)?line.remainder_dimension_values.map(Number):[],remainderDimensionUnits:asStringArray(line.remainder_dimension_units)}))};}
