-- Formas de pago y condiciones de pago (base para Facturación / Cobros).
--
-- Los presupuestos y pedidos ya guardaban payment_method_id / payment_term_id
-- (columnas bigint sin FK, igual que commercial_id/warehouse_id en sales_order)
-- y QuotationCreate/QuotationEdit ya consultan c.from('payment_method') /
-- c.from('payment_term') para sus desplegables — pero esas tablas nunca
-- llegaron a crearse. Esta migración las da de alta.
--
-- payment_term no replica el diseño del legacy Toldos (FormaPago con 10
-- plazos como columnas fijas importep1..10/cobrado1..10/fechap1..10): en su
-- lugar, cada condición de pago es una cabecera con N líneas de plazo
-- (payment_term_installment), cada una con su % del importe y los días desde
-- la fecha de referencia (factura/pedido). Así "Contado", "30 días" o
-- "50% anticipo + 50% entrega" son solo distinto número de líneas, y esta
-- misma tabla sirve de base para calcular vencimientos reales cuando se
-- aborde Cobros.

create table if not exists public.payment_method (
  id bigint generated by default as identity primary key,
  company_id bigint not null references public.company(id),
  code varchar(30),
  name varchar(120) not null,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint payment_method_company_name_uk unique (company_id, name)
);

create table if not exists public.payment_term (
  id bigint generated by default as identity primary key,
  company_id bigint not null references public.company(id),
  code varchar(30),
  name varchar(120) not null,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint payment_term_company_name_uk unique (company_id, name)
);

create table if not exists public.payment_term_installment (
  id bigint generated by default as identity primary key,
  payment_term_id bigint not null references public.payment_term(id) on delete cascade,
  sequence integer not null,
  percentage numeric(6,3) not null,
  days_offset integer not null default 0,
  description text,
  constraint payment_term_installment_seq_uk unique (payment_term_id, sequence),
  constraint payment_term_installment_percentage_ck check (percentage > 0 and percentage <= 100),
  constraint payment_term_installment_days_ck check (days_offset >= 0)
);
create index if not exists ix_payment_term_installment_term on public.payment_term_installment(payment_term_id);

alter table public.payment_method enable row level security;
alter table public.payment_term enable row level security;
alter table public.payment_term_installment enable row level security;

drop policy if exists payment_method_company_select on public.payment_method;
create policy payment_method_company_select on public.payment_method for select using (
  company_id = (select company_id from public.user_account where auth_user_id = auth.uid())
);
drop policy if exists payment_method_company_insert on public.payment_method;
create policy payment_method_company_insert on public.payment_method for insert with check (
  company_id = (select company_id from public.user_account where auth_user_id = auth.uid())
);
drop policy if exists payment_method_company_update on public.payment_method;
create policy payment_method_company_update on public.payment_method for update using (
  company_id = (select company_id from public.user_account where auth_user_id = auth.uid())
) with check (
  company_id = (select company_id from public.user_account where auth_user_id = auth.uid())
);

drop policy if exists payment_term_company_select on public.payment_term;
create policy payment_term_company_select on public.payment_term for select using (
  company_id = (select company_id from public.user_account where auth_user_id = auth.uid())
);
drop policy if exists payment_term_company_insert on public.payment_term;
create policy payment_term_company_insert on public.payment_term for insert with check (
  company_id = (select company_id from public.user_account where auth_user_id = auth.uid())
);
drop policy if exists payment_term_company_update on public.payment_term;
create policy payment_term_company_update on public.payment_term for update using (
  company_id = (select company_id from public.user_account where auth_user_id = auth.uid())
) with check (
  company_id = (select company_id from public.user_account where auth_user_id = auth.uid())
);

drop policy if exists payment_term_installment_company_select on public.payment_term_installment;
create policy payment_term_installment_company_select on public.payment_term_installment for select using (
  exists(select 1 from public.payment_term t where t.id = payment_term_id and t.company_id = (select company_id from public.user_account where auth_user_id = auth.uid()))
);
drop policy if exists payment_term_installment_company_insert on public.payment_term_installment;
create policy payment_term_installment_company_insert on public.payment_term_installment for insert with check (
  exists(select 1 from public.payment_term t where t.id = payment_term_id and t.company_id = (select company_id from public.user_account where auth_user_id = auth.uid()))
);
drop policy if exists payment_term_installment_company_update on public.payment_term_installment;
create policy payment_term_installment_company_update on public.payment_term_installment for update using (
  exists(select 1 from public.payment_term t where t.id = payment_term_id and t.company_id = (select company_id from public.user_account where auth_user_id = auth.uid()))
) with check (
  exists(select 1 from public.payment_term t where t.id = payment_term_id and t.company_id = (select company_id from public.user_account where auth_user_id = auth.uid()))
);
drop policy if exists payment_term_installment_company_delete on public.payment_term_installment;
create policy payment_term_installment_company_delete on public.payment_term_installment for delete using (
  exists(select 1 from public.payment_term t where t.id = payment_term_id and t.company_id = (select company_id from public.user_account where auth_user_id = auth.uid()))
);
