create table if not exists public.measurement_sequence (
  company_id bigint not null references public.company(id) on delete cascade,
  year integer not null,
  last_number bigint not null default 0,
  primary key(company_id, year)
);

create table if not exists public.measurement (
  id bigint generated by default as identity primary key,
  company_id bigint not null references public.company(id),
  number bigint not null,
  year integer not null,
  code varchar not null,
  reference varchar,
  customer_id bigint references public.customer(id),
  customer_name_snapshot varchar,
  customer_tax_id_snapshot varchar,
  customer_phone_snapshot varchar,
  customer_mobile_snapshot varchar,
  customer_email_snapshot varchar,
  site_street varchar,
  site_postal_code varchar,
  site_city varchar,
  site_region varchar,
  site_country_code varchar not null default 'ES',
  site_latitude numeric(10,7),
  site_longitude numeric(10,7),
  contact_method varchar,
  commercial_name varchar,
  assigned_user_id uuid references auth.users(id),
  assigned_mode varchar not null default 'UNASSIGNED',
  status varchar not null default 'PLANNED',
  contact_date date not null default current_date,
  measurement_date date,
  measurement_time time,
  reference_note text,
  observations text,
  deleted_at timestamptz,
  created_at timestamptz not null default now(),
  created_by uuid references auth.users(id),
  updated_at timestamptz not null default now(),
  updated_by uuid references auth.users(id),
  constraint measurement_company_number_uk unique(company_id, year, number),
  constraint measurement_company_code_uk unique(company_id, code),
  constraint measurement_status_ck check(status in ('PLANNED','ASSIGNED','IN_PROGRESS','COMPLETED','QUOTED','CLOSED','CANCELLED')),
  constraint measurement_assigned_mode_ck check(assigned_mode in ('UNASSIGNED','SELF','USER'))
);

create table if not exists public.measurement_activity (
  id bigint generated by default as identity primary key,
  measurement_id bigint not null references public.measurement(id) on delete cascade,
  event_type varchar not null,
  message text not null,
  created_at timestamptz not null default now(),
  created_by uuid references auth.users(id)
);

create index if not exists ix_measurement_company_status on public.measurement(company_id, status, deleted_at);
create index if not exists ix_measurement_customer on public.measurement(customer_id);
create index if not exists ix_measurement_measurement_date on public.measurement(company_id, measurement_date);
create index if not exists ix_measurement_activity_measurement on public.measurement_activity(measurement_id, created_at desc);

create or replace function public.create_measurement(
  p_company_id bigint,
  p_reference varchar,
  p_customer_id bigint,
  p_customer_name varchar,
  p_customer_tax_id varchar,
  p_customer_phone varchar,
  p_customer_mobile varchar,
  p_customer_email varchar,
  p_site_street varchar,
  p_site_postal_code varchar,
  p_site_city varchar,
  p_site_region varchar,
  p_site_country_code varchar,
  p_contact_method varchar,
  p_commercial_name varchar,
  p_assigned_user_id uuid,
  p_assigned_mode varchar,
  p_status varchar,
  p_contact_date date,
  p_measurement_date date,
  p_measurement_time time,
  p_observations text
) returns bigint
language plpgsql
security invoker
as $$
declare
  v_year integer := extract(year from coalesce(p_measurement_date,p_contact_date,current_date));
  v_number bigint;
  v_id bigint;
  v_user uuid := auth.uid();
begin
  if coalesce(trim(p_customer_name),'') = '' then raise exception 'El cliente es obligatorio'; end if;
  if p_contact_date is null then raise exception 'La fecha de contacto es obligatoria'; end if;
  if p_assigned_mode = 'USER' and p_assigned_user_id is null then raise exception 'Debe indicar el medidor asignado'; end if;

  insert into public.measurement_sequence(company_id, year, last_number)
  values(p_company_id, v_year, 1)
  on conflict(company_id, year) do update set last_number=public.measurement_sequence.last_number+1
  returning last_number into v_number;

  insert into public.measurement(
    company_id, number, year, code, reference, customer_id,
    customer_name_snapshot, customer_tax_id_snapshot, customer_phone_snapshot, customer_mobile_snapshot, customer_email_snapshot,
    site_street, site_postal_code, site_city, site_region, site_country_code,
    contact_method, commercial_name, assigned_user_id, assigned_mode, status,
    contact_date, measurement_date, measurement_time, observations, created_by, updated_by
  ) values(
    p_company_id, v_number, v_year, 'M-'||v_year||'-'||lpad(v_number::text,6,'0'), nullif(trim(p_reference),''), p_customer_id,
    nullif(trim(p_customer_name),''), nullif(trim(p_customer_tax_id),''), nullif(trim(p_customer_phone),''), nullif(trim(p_customer_mobile),''), nullif(trim(p_customer_email),''),
    nullif(trim(p_site_street),''), nullif(trim(p_site_postal_code),''), nullif(trim(p_site_city),''), nullif(trim(p_site_region),''), coalesce(nullif(trim(p_site_country_code),''),'ES'),
    nullif(trim(p_contact_method),''), nullif(trim(p_commercial_name),''), p_assigned_user_id, coalesce(p_assigned_mode,'UNASSIGNED'), coalesce(p_status,'PLANNED'),
    p_contact_date, p_measurement_date, p_measurement_time, nullif(trim(p_observations),''), v_user, v_user
  ) returning id into v_id;

  insert into public.measurement_activity(measurement_id,event_type,message,created_by)
  values(v_id,'CREATED','Medición creada',v_user);

  return v_id;
end;
$$;

alter table public.measurement enable row level security;
alter table public.measurement_activity enable row level security;
alter table public.measurement_sequence enable row level security;

create policy measurement_authenticated_select on public.measurement for select to authenticated using(auth.uid() is not null);
create policy measurement_authenticated_insert on public.measurement for insert to authenticated with check(auth.uid() is not null);
create policy measurement_authenticated_update on public.measurement for update to authenticated using(auth.uid() is not null) with check(auth.uid() is not null);
create policy measurement_activity_authenticated_select on public.measurement_activity for select to authenticated using(auth.uid() is not null);
create policy measurement_activity_authenticated_insert on public.measurement_activity for insert to authenticated with check(auth.uid() is not null);
create policy measurement_sequence_authenticated_select on public.measurement_sequence for select to authenticated using(auth.uid() is not null);
create policy measurement_sequence_authenticated_insert on public.measurement_sequence for insert to authenticated with check(auth.uid() is not null);
create policy measurement_sequence_authenticated_update on public.measurement_sequence for update to authenticated using(auth.uid() is not null) with check(auth.uid() is not null);
