-- Cuadrillas de instalación (fase 1 de la Agenda de instalaciones).
--
-- Hasta ahora installation.installers es una lista de instaladores elegida a mano
-- en cada montaje, sin ningún concepto de equipo estable en el tiempo. Para poder
-- planificar una agenda semanal por equipo hace falta una cuadrilla con nombre y
-- color propios; installers sigue existiendo y sigue siendo la lista real de quién
-- va a esa visita en concreto (se autorrellena desde la cuadrilla, pero se puede
-- seguir ajustando a mano si un día falta alguien).
--
-- Las mediciones NO ganan cuadrilla: measurement.assigned_user_id sigue siendo una
-- única persona, porque medir es un trabajo individual (a diferencia del montaje,
-- que suele necesitar varias manos). La futura Agenda combinará ambos tipos de
-- visita en la misma pantalla, pero agrupará montajes por cuadrilla y mediciones
-- por la persona asignada — son dos formas de agrupar, no una tabla común.
--
-- Los miembros de una cuadrilla se pueden elegir de cualquier usuario activo que
-- haga trabajo de campo (role_code='INSTALLER' o can_measure=true), no solo
-- instaladores puros, porque en una pyme de este tamaño es habitual que la misma
-- persona mida e instale.

create table if not exists public.installation_crew (
  id bigint generated by default as identity primary key,
  company_id bigint not null references public.company(id),
  name text not null,
  member_ids jsonb not null default '[]'::jsonb,
  color text not null default '#3f6f8f',
  active boolean not null default true,
  deleted_at timestamptz,
  deleted_by uuid,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint installation_crew_company_name_uk unique (company_id, name),
  constraint installation_crew_member_ids_ck check (jsonb_typeof(member_ids) = 'array'),
  constraint installation_crew_color_ck check (color ~ '^#[0-9a-fA-F]{3,8}$')
);

create index if not exists ix_installation_crew_company
  on public.installation_crew (company_id)
  where deleted_at is null;

alter table public.installation_crew enable row level security;

drop policy if exists installation_crew_company_select on public.installation_crew;
drop policy if exists installation_crew_company_insert on public.installation_crew;
drop policy if exists installation_crew_company_update on public.installation_crew;

create policy installation_crew_company_select on public.installation_crew
  for select using (company_id = public.current_company_id());
create policy installation_crew_company_insert on public.installation_crew
  for insert with check (company_id = public.current_company_id());
create policy installation_crew_company_update on public.installation_crew
  for update using (company_id = public.current_company_id())
  with check (company_id = public.current_company_id());

alter table public.installation add column if not exists crew_id bigint references public.installation_crew(id);

create index if not exists ix_installation_crew_id
  on public.installation (crew_id)
  where crew_id is not null;
