-- Colores de característica de sistema (fase 0 del modelo Sistema -> Familia -> Artículo).
--
-- product_attribute es el catálogo de características a nivel de sistema (Acabado,
-- Accionamiento, Color…), gestionado en Configuración de artículos -> Características.
-- Hasta ahora no tenía ninguna relación con el catálogo color. attribute_color es la
-- tabla puente que asocia colores del sistema a una característica; product_family_attribute
-- y product_attribute_assignment (familia y artículo) heredarán este conjunto en fases
-- posteriores, con exclusiones propias en cada nivel.
--
-- De paso, corrige un bug latente: color no tenía columnas deleted_at/deleted_by pese a
-- que la pestaña "Colores" del catálogo genérico (ProductCatalogV1 -> catalogRepository)
-- ya las asume (upsertCatalog, markForDeletion, restoreFromDeletion son genéricos y las
-- usan para cualquier tabla del catálogo) — crear o borrar un color desde esa pantalla
-- fallaba porque la columna no existía.

alter table public.color add column if not exists deleted_at timestamptz;
alter table public.color add column if not exists deleted_by uuid;

create table if not exists public.attribute_color (
  id bigint generated by default as identity primary key,
  attribute_id bigint not null references public.product_attribute(id),
  color_id bigint not null references public.color(id),
  active boolean not null default true,
  deleted_at timestamptz,
  deleted_by uuid,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint attribute_color_uk unique (attribute_id, color_id)
);

create index if not exists ix_attribute_color_attribute
  on public.attribute_color (attribute_id)
  where deleted_at is null;

create index if not exists ix_attribute_color_color
  on public.attribute_color (color_id)
  where deleted_at is null;

alter table public.attribute_color enable row level security;

drop policy if exists attribute_color_company_access on public.attribute_color;
create policy attribute_color_company_access on public.attribute_color
  for all using (
    exists (
      select 1 from public.product_attribute pa
      where pa.id = attribute_id and pa.company_id = public.current_company_id()
    )
  )
  with check (
    exists (
      select 1 from public.product_attribute pa
      where pa.id = attribute_id and pa.company_id = public.current_company_id()
    )
  );

comment on table public.attribute_color is
  'Colores del catálogo de sistema asociados a una característica (product_attribute). Familia y artículo heredarán este conjunto con exclusiones propias en fases posteriores.';
