-- Maestro de Colores (fase 1): biblioteca de referencia RAL Classic + catálogo
-- de acabados + composición sobre `color`, según lo acordado en el análisis
-- "Maestro de Colores" (artifact de esta sesión).
--
-- No toca ninguna fila de las tablas que ya usan color_id como unidad física
-- (attribute_color, warehouse_stock, stock_movement, production_work_sheet,
-- otd_component): color.id no cambia. Solo se añade de dónde puede componerse
-- una fila de `color` y una biblioteca de referencia global de la que
-- elegir en vez de teclear a mano.
--
-- Fase 0 (investigación previa): se comprobó contra datos reales que hoy no
-- hay ningún product_id/color_id repartido en más de una fila de
-- warehouse_stock por estar asociado a distinta Característica — el riesgo
-- de fragmentación de stock descrito en el análisis es, por ahora, teórico.
-- No se actúa sobre ello en esta migración.

-- 1. Biblioteca de referencia cromática (global, no por empresa). Solo
--    contiene sistemas con datos redistribuibles en bloque — por eso arranca
--    únicamente con RAL Classic; Pantone/NCS quedan fuera por licencia (ver
--    el análisis) y se dan de alta a mano por color, sin biblioteca.
create table if not exists public.color_reference_library (
  id bigint generated by default as identity primary key,
  standard varchar not null,
  code varchar not null,
  name varchar not null,
  hex varchar(7) not null,
  created_at timestamptz not null default now(),
  constraint color_reference_library_standard_ck check (standard in ('RAL_CLASSIC', 'RAL_DESIGN', 'RAL_EFFECT')),
  constraint color_reference_library_uk unique (standard, code)
);

create index if not exists ix_color_reference_library_search
  on public.color_reference_library (standard, code);

alter table public.color_reference_library enable row level security;

drop policy if exists color_reference_library_authenticated_select on public.color_reference_library;
create policy color_reference_library_authenticated_select on public.color_reference_library
  for select to authenticated using (true);

comment on table public.color_reference_library is
  'Biblioteca de referencia cromática global (no por empresa) para dar de alta colores del Maestro de Onin por búsqueda en vez de a mano. Ver artifact "Maestro de Colores" de esta sesión para el análisis completo.';

-- 2. Catálogo de acabados (global, ~6 filas fijas). Eje independiente del
--    color: el mismo RAL 7016 puede existir liso, texturado, mate...
create table if not exists public.color_finish (
  id bigint generated by default as identity primary key,
  code varchar not null,
  name varchar not null,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  constraint color_finish_code_uk unique (code)
);

alter table public.color_finish enable row level security;

drop policy if exists color_finish_authenticated_select on public.color_finish;
create policy color_finish_authenticated_select on public.color_finish
  for select to authenticated using (true);

comment on table public.color_finish is
  'Acabados superficiales (Liso, Mate, Texturado...) que componen, junto a color_reference_library, la identidad de una fila de color. No sustituye a product_attribute: un acabado no es una Característica comercial, es una dimensión de identidad del color.';

-- 3. Composición sobre `color`: de dónde sale su identidad, en vez de
--    escribirla a mano. Todas las columnas nullable — nada de lo que ya
--    existe se ve afectado, y un color personalizado/textil sin estándar
--    sigue siendo válido con todas ellas a NULL.
alter table public.color add column if not exists hex varchar(7);
alter table public.color add column if not exists base_reference_id bigint references public.color_reference_library(id);
alter table public.color add column if not exists finish_id bigint references public.color_finish(id);
alter table public.color add column if not exists standard varchar;
alter table public.color add column if not exists supplier_code varchar;

comment on column public.color.hex is 'Representación visual (swatch en pantalla/PDF) — nunca la identidad del color. Copiado de la referencia al añadir desde la biblioteca, o introducido a mano con un selector visual para colores personalizados.';
comment on column public.color.base_reference_id is 'Identidad cromática pura (p. ej. RAL 7016) vía color_reference_library. NULL si el color es personalizado, de fabricante o de catálogo textil sin biblioteca de referencia.';
comment on column public.color.finish_id is 'Proceso superficial (Texturado, Mate...) vía color_finish. NULL = acabado estándar/no diferenciado.';
comment on column public.color.standard is 'Denormalizado desde base_reference_id (RAL_CLASSIC/RAL_DESIGN/RAL_EFFECT), o FABRICANTE/PERSONALIZADO/TEXTIL_CATALOGO/PANTONE/NCS cuando no hay base_reference_id. Evita un join para listados.';
comment on column public.color.supplier_code is 'Código o nombre tal como lo da el proveedor cuando no hay estándar público — "Blanco Gaviota", una referencia Sauleda, un Pantone dictado por un cliente.';

-- 4. Seed: acabados.
insert into public.color_finish (code, name, sort_order) values
  ('LISO', 'Liso', 0),
  ('MATE', 'Mate', 1),
  ('SATINADO', 'Satinado', 2),
  ('TEXTURADO', 'Texturado', 3),
  ('ANODIZADO', 'Anodizado', 4),
  ('FORJA', 'Forja', 5)
on conflict (code) do nothing;

-- 5. Seed: RAL Classic (216 colores). Código, nombre en español y HEX de
--    referencia comunitaria (no valores oficiales de RAL gGmbH) — ver nota
--    de licencia en el artifact "Maestro de Colores".
insert into public.color_reference_library (standard, code, name, hex) values
  ('RAL_CLASSIC','1000','Beige verdoso','#CDBA88'),
  ('RAL_CLASSIC','1001','Beige','#D0B084'),
  ('RAL_CLASSIC','1002','Amarillo arena','#D2AA6D'),
  ('RAL_CLASSIC','1003','Amarillo señales','#F9A900'),
  ('RAL_CLASSIC','1004','Amarillo oro','#E49E00'),
  ('RAL_CLASSIC','1005','Amarillo miel','#CB8F00'),
  ('RAL_CLASSIC','1006','Amarillo maíz','#E19000'),
  ('RAL_CLASSIC','1007','Amarillo narciso','#E88C00'),
  ('RAL_CLASSIC','1011','Beige pardo','#AF8050'),
  ('RAL_CLASSIC','1012','Amarillo limón','#DDAF28'),
  ('RAL_CLASSIC','1013','Blanco perla','#E3D9C7'),
  ('RAL_CLASSIC','1014','Marfil','#DDC49B'),
  ('RAL_CLASSIC','1015','Marfil claro','#E6D2B5'),
  ('RAL_CLASSIC','1016','Amarillo azufre','#F1DD39'),
  ('RAL_CLASSIC','1017','Amarillo azafrán','#F6A951'),
  ('RAL_CLASSIC','1018','Amarillo de zinc','#FACA31'),
  ('RAL_CLASSIC','1019','Beige agrisado','#A48F7A'),
  ('RAL_CLASSIC','1020','Amarillo oliva','#A08F65'),
  ('RAL_CLASSIC','1021','Amarillo colza','#F6B600'),
  ('RAL_CLASSIC','1023','Amarillo tráfico','#F7B500'),
  ('RAL_CLASSIC','1024','Amarillo ocre','#BA8F4C'),
  ('RAL_CLASSIC','1026','Amarillo brillante','#FFFF00'),
  ('RAL_CLASSIC','1027','Amarillo curry','#A77F0F'),
  ('RAL_CLASSIC','1028','Amarillo melón','#FF9C00'),
  ('RAL_CLASSIC','1032','Amarillo retama','#E2A300'),
  ('RAL_CLASSIC','1033','Amarillo dalia','#F99A1D'),
  ('RAL_CLASSIC','1034','Amarillo pastel','#EB9C52'),
  ('RAL_CLASSIC','1035','Beige perlado','#8F8370'),
  ('RAL_CLASSIC','1036','Oro perlado','#806440'),
  ('RAL_CLASSIC','1037','Amarillo sol','#F09200'),
  ('RAL_CLASSIC','2000','Amarillo naranja','#DA6E00'),
  ('RAL_CLASSIC','2001','Rojo anaranjado','#BA481C'),
  ('RAL_CLASSIC','2002','Naranja sanguíneo','#BF3922'),
  ('RAL_CLASSIC','2003','Naranja pálido','#F67829'),
  ('RAL_CLASSIC','2004','Naranja puro','#E25304'),
  ('RAL_CLASSIC','2005','Naranja brillante','#FF4D08'),
  ('RAL_CLASSIC','2007','Naranja claro brillante','#FFB200'),
  ('RAL_CLASSIC','2008','Rojo claro anaranjado','#EC6B22'),
  ('RAL_CLASSIC','2009','Naranja tráfico','#DE5308'),
  ('RAL_CLASSIC','2010','Naranja señales','#D05D29'),
  ('RAL_CLASSIC','2011','Naranja intenso','#E26E0F'),
  ('RAL_CLASSIC','2012','Naranja salmón','#D5654E'),
  ('RAL_CLASSIC','2013','Naranja perlado','#923E25'),
  ('RAL_CLASSIC','2017','Naranja RAL','#FC5500'),
  ('RAL_CLASSIC','3000','Rojo vivo','#A72920'),
  ('RAL_CLASSIC','3001','Rojo señales','#9B2423'),
  ('RAL_CLASSIC','3002','Rojo carmin','#9B2321'),
  ('RAL_CLASSIC','3003','Rojo rubí','#861A22'),
  ('RAL_CLASSIC','3004','Rojo púrpura','#6B1C23'),
  ('RAL_CLASSIC','3005','Rojo vino','#59191F'),
  ('RAL_CLASSIC','3007','Rojo negruzco','#3E2022'),
  ('RAL_CLASSIC','3009','Rojo óxido','#6D342D'),
  ('RAL_CLASSIC','3011','Rojo pardo','#782423'),
  ('RAL_CLASSIC','3012','Rojo beige','#C5856D'),
  ('RAL_CLASSIC','3013','Rojo tomate','#972E25'),
  ('RAL_CLASSIC','3014','Rojo viejo','#CB7375'),
  ('RAL_CLASSIC','3015','Rosa claro','#D8A0A6'),
  ('RAL_CLASSIC','3016','Rojo coral','#A63D30'),
  ('RAL_CLASSIC','3017','Rosa','#CA555D'),
  ('RAL_CLASSIC','3018','Rojo fresa','#C63F4A'),
  ('RAL_CLASSIC','3020','Rojo tráfico','#BB1F11'),
  ('RAL_CLASSIC','3022','Rojo salmón','#CF6955'),
  ('RAL_CLASSIC','3024','Rojo brillante','#FF2D21'),
  ('RAL_CLASSIC','3026','Rojo claro brillante','#FF2A1C'),
  ('RAL_CLASSIC','3027','Rojo frambuesa','#AB273C'),
  ('RAL_CLASSIC','3028','Rojo puro','#CC2C24'),
  ('RAL_CLASSIC','3031','Rojo oriente','#A63437'),
  ('RAL_CLASSIC','3032','Rojo rubí perlado','#701D24'),
  ('RAL_CLASSIC','3033','Rosa perlado','#A53A2E'),
  ('RAL_CLASSIC','4001','Rojo lila','#816183'),
  ('RAL_CLASSIC','4002','Rojo violeta','#8D3C4B'),
  ('RAL_CLASSIC','4003','Violeta érica','#C4618C'),
  ('RAL_CLASSIC','4004','Burdeos','#651E38'),
  ('RAL_CLASSIC','4005','Lila azulado','#76689A'),
  ('RAL_CLASSIC','4006','Púrpura tráfico','#903373'),
  ('RAL_CLASSIC','4007','Violeta púrpura','#47243C'),
  ('RAL_CLASSIC','4008','Violeta señales','#844C82'),
  ('RAL_CLASSIC','4009','Violeta pastel','#9D8692'),
  ('RAL_CLASSIC','4010','Magenta tele','#BB4077'),
  ('RAL_CLASSIC','4011','Violeta perlado','#6E6387'),
  ('RAL_CLASSIC','4012','Morado perlado','#6A6B7F'),
  ('RAL_CLASSIC','5000','Azul violeta','#304F6E'),
  ('RAL_CLASSIC','5001','Azul verdoso','#0E4C64'),
  ('RAL_CLASSIC','5002','Azul ultramar','#00387A'),
  ('RAL_CLASSIC','5003','Azul zafiro','#1F3855'),
  ('RAL_CLASSIC','5004','Azul negruzco','#191E28'),
  ('RAL_CLASSIC','5005','Azul señales','#005387'),
  ('RAL_CLASSIC','5007','Azul brillante','#376B8C'),
  ('RAL_CLASSIC','5008','Azul grisáceo','#2B3A44'),
  ('RAL_CLASSIC','5009','Azul azur','#215F78'),
  ('RAL_CLASSIC','5010','Azul genciana','#004F7C'),
  ('RAL_CLASSIC','5011','Azul acero','#1A2B3C'),
  ('RAL_CLASSIC','5012','Azul luminoso','#0089B6'),
  ('RAL_CLASSIC','5013','Azul cobalto','#193153'),
  ('RAL_CLASSIC','5014','Azul colombino','#637D96'),
  ('RAL_CLASSIC','5015','Azul celeste','#007CAF'),
  ('RAL_CLASSIC','5017','Azul tráfico','#005B8C'),
  ('RAL_CLASSIC','5018','Azul turquesa','#048B8C'),
  ('RAL_CLASSIC','5019','Azul capri','#005E83'),
  ('RAL_CLASSIC','5020','Azul océano','#00414B'),
  ('RAL_CLASSIC','5021','Azul agua','#007577'),
  ('RAL_CLASSIC','5022','Azul noche','#222D5A'),
  ('RAL_CLASSIC','5023','Azul lejanía','#41698C'),
  ('RAL_CLASSIC','5024','Azul pastel','#6093AC'),
  ('RAL_CLASSIC','5025','Gencian perlado','#20697C'),
  ('RAL_CLASSIC','5026','Azul noche perlado','#0F3052'),
  ('RAL_CLASSIC','6000','Verde patina','#3C7460'),
  ('RAL_CLASSIC','6001','Verde esmeralda','#366735'),
  ('RAL_CLASSIC','6002','Verde hoja','#325928'),
  ('RAL_CLASSIC','6003','Verde oliva','#50533C'),
  ('RAL_CLASSIC','6004','Verde azulado','#024442'),
  ('RAL_CLASSIC','6005','Verde musgo','#114232'),
  ('RAL_CLASSIC','6006','Oliva grisáceo','#3C392E'),
  ('RAL_CLASSIC','6007','Verde botella','#2C3222'),
  ('RAL_CLASSIC','6008','Verde parduzco','#36342A'),
  ('RAL_CLASSIC','6009','Verde abeto','#27352A'),
  ('RAL_CLASSIC','6010','Verde hierba','#4D6F39'),
  ('RAL_CLASSIC','6011','Verde reseda','#6B7C59'),
  ('RAL_CLASSIC','6012','Verde negruzco','#2F3D3A'),
  ('RAL_CLASSIC','6013','Verde caña','#7C765A'),
  ('RAL_CLASSIC','6014','Amarillo oliva','#474135'),
  ('RAL_CLASSIC','6015','Oliva negruzco','#3D3D36'),
  ('RAL_CLASSIC','6016','Verde turquesa','#00694C'),
  ('RAL_CLASSIC','6017','Verde mayo','#587F40'),
  ('RAL_CLASSIC','6018','Verde amarillento','#60993B'),
  ('RAL_CLASSIC','6019','Verde blanquecino','#B9CEAC'),
  ('RAL_CLASSIC','6020','Verde cromo','#37422F'),
  ('RAL_CLASSIC','6021','Verde pálido','#8A9977'),
  ('RAL_CLASSIC','6022','Oliva parduzco','#3A3327'),
  ('RAL_CLASSIC','6024','Verde tráfico','#008351'),
  ('RAL_CLASSIC','6025','Verde helecho','#5E6E3B'),
  ('RAL_CLASSIC','6026','Verde ópalo','#005F4E'),
  ('RAL_CLASSIC','6027','Verde luminoso','#7EBAB5'),
  ('RAL_CLASSIC','6028','Verde pino','#315442'),
  ('RAL_CLASSIC','6029','Verde menta','#006F3D'),
  ('RAL_CLASSIC','6032','Verde señales','#237F52'),
  ('RAL_CLASSIC','6033','Turquesa menta','#45877F'),
  ('RAL_CLASSIC','6034','Turquesa pastel','#7AADAC'),
  ('RAL_CLASSIC','6035','Verde perlado','#194D25'),
  ('RAL_CLASSIC','6036','Verde ópalo perlado','#04574B'),
  ('RAL_CLASSIC','6037','Verde puro','#008B29'),
  ('RAL_CLASSIC','6038','Verde brillante','#00B51B'),
  ('RAL_CLASSIC','6039','Verde fibra','#B3C43E'),
  ('RAL_CLASSIC','7000','Gris ardilla','#7A888E'),
  ('RAL_CLASSIC','7001','Gris plata','#8C979C'),
  ('RAL_CLASSIC','7002','Gris oliva','#817863'),
  ('RAL_CLASSIC','7003','Gris musgo','#797669'),
  ('RAL_CLASSIC','7004','Gris señales','#9A9B9B'),
  ('RAL_CLASSIC','7005','Gris ratón','#6B6E6B'),
  ('RAL_CLASSIC','7006','Gris beige','#766A5E'),
  ('RAL_CLASSIC','7008','Gris caqui','#745F3D'),
  ('RAL_CLASSIC','7009','Gris verdoso','#5D6058'),
  ('RAL_CLASSIC','7010','Gris lona','#585C56'),
  ('RAL_CLASSIC','7011','Gris hierro','#52595D'),
  ('RAL_CLASSIC','7012','Gris basalto','#575D5E'),
  ('RAL_CLASSIC','7013','Gris parduzco','#575044'),
  ('RAL_CLASSIC','7015','Gris pizarra','#4F5358'),
  ('RAL_CLASSIC','7016','Gris antracita','#383E42'),
  ('RAL_CLASSIC','7021','Gris negruzco','#2F3234'),
  ('RAL_CLASSIC','7022','Gris sombra','#4C4A44'),
  ('RAL_CLASSIC','7023','Gris hormigón','#808076'),
  ('RAL_CLASSIC','7024','Gris grafita','#45494E'),
  ('RAL_CLASSIC','7026','Gris granito','#374345'),
  ('RAL_CLASSIC','7030','Gris piedra','#928E85'),
  ('RAL_CLASSIC','7031','Gris azulado','#5B686D'),
  ('RAL_CLASSIC','7032','Gris guijarro','#B5B0A1'),
  ('RAL_CLASSIC','7033','Gris cemento','#7F8274'),
  ('RAL_CLASSIC','7034','Gris amarillento','#92886F'),
  ('RAL_CLASSIC','7035','Gris luminoso','#C5C7C4'),
  ('RAL_CLASSIC','7036','Gris platino','#979392'),
  ('RAL_CLASSIC','7037','Gris polvo','#7A7B7A'),
  ('RAL_CLASSIC','7038','Gris ágata','#B0B0A9'),
  ('RAL_CLASSIC','7039','Gris cuarzo','#6B665E'),
  ('RAL_CLASSIC','7040','Gris ventana','#989EA1'),
  ('RAL_CLASSIC','7042','Gris tráfico A','#8E9291'),
  ('RAL_CLASSIC','7043','Gris tráfico B','#4F5250'),
  ('RAL_CLASSIC','7044','Gris seda','#B7B3A8'),
  ('RAL_CLASSIC','7045','Gris tele 1','#8D9295'),
  ('RAL_CLASSIC','7046','Gris tele 2','#7E868A'),
  ('RAL_CLASSIC','7047','Gris tele 4','#C8C8C7'),
  ('RAL_CLASSIC','7048','Gris musgo perlado','#817B73'),
  ('RAL_CLASSIC','8000','Pardo verdoso','#89693F'),
  ('RAL_CLASSIC','8001','Pardo ocre','#9D622B'),
  ('RAL_CLASSIC','8002','Marrón señales','#794D3E'),
  ('RAL_CLASSIC','8003','Pardo arcilla','#7E4B27'),
  ('RAL_CLASSIC','8004','Pardo cobre','#8D4931'),
  ('RAL_CLASSIC','8007','Pardo corzo','#70462B'),
  ('RAL_CLASSIC','8008','Pardo oliva','#724A25'),
  ('RAL_CLASSIC','8011','Pardo nuez','#5A3827'),
  ('RAL_CLASSIC','8012','Pardo rojo','#66332B'),
  ('RAL_CLASSIC','8014','Sepia','#4A3526'),
  ('RAL_CLASSIC','8015','Castaño','#5E2F26'),
  ('RAL_CLASSIC','8016','Caoba','#4C2B20'),
  ('RAL_CLASSIC','8017','Chocolate','#442F29'),
  ('RAL_CLASSIC','8019','Pardo grisáceo','#3D3635'),
  ('RAL_CLASSIC','8022','Pardo negruzco','#1A1719'),
  ('RAL_CLASSIC','8023','Pardo anaranjado','#A45729'),
  ('RAL_CLASSIC','8024','Pardo beige','#795038'),
  ('RAL_CLASSIC','8025','Pardo pálido','#755847'),
  ('RAL_CLASSIC','8028','Marrón tierra','#513A2A'),
  ('RAL_CLASSIC','8029','Cobre perlado','#7F4031'),
  ('RAL_CLASSIC','9001','Blanco crema','#E9E0D2'),
  ('RAL_CLASSIC','9002','Blanco grisáceo','#D6D5CB'),
  ('RAL_CLASSIC','9003','Blanco señales','#ECECE7'),
  ('RAL_CLASSIC','9004','Negro señales','#2B2B2C'),
  ('RAL_CLASSIC','9005','Negro intenso','#0E0E10'),
  ('RAL_CLASSIC','9006','Aluminio blanco','#A1A1A0'),
  ('RAL_CLASSIC','9007','Aluminio gris','#868581'),
  ('RAL_CLASSIC','9010','Blanco puro','#F1EDE1'),
  ('RAL_CLASSIC','9011','Negro grafito','#27292B'),
  ('RAL_CLASSIC','9012','Blanco sala blanca','#F8F2E1'),
  ('RAL_CLASSIC','9016','Blanco tráfico','#F1F1EA'),
  ('RAL_CLASSIC','9017','Negro tráfico','#29292A'),
  ('RAL_CLASSIC','9018','Blanco papiro','#C8CBC4'),
  ('RAL_CLASSIC','9022','Gris claro perlado','#858583'),
  ('RAL_CLASSIC','9023','Gris oscuro perlado','#787B7A')
on conflict (standard, code) do nothing;
