-- Log de auditoría: qué usuario hizo qué sobre los documentos transaccionales
-- y los datos sensibles de seguridad (permisos, usuarios, clientes). Fase 1:
-- no incluye catálogo/precios ni stock_movement (éste ya es en sí mismo un
-- log de eventos, no necesita un meta-log encima).
--
-- Diseño: una única tabla genérica alimentada por un trigger genérico
-- (to_jsonb(NEW)/to_jsonb(OLD) + diff de claves), en vez de una tabla y un
-- trigger por módulo — así una tabla nueva en el alcance es una línea en el
-- array de abajo, no una migración nueva.

create table if not exists public.audit_log (
  id bigint generated by default as identity primary key,
  company_id bigint references public.company(id),
  table_name text not null,
  record_id bigint,
  action text not null check (action in ('INSERT', 'UPDATE', 'DELETE')),
  changed_by uuid,
  changed_at timestamptz not null default now(),
  changed_fields text[],
  old_data jsonb,
  new_data jsonb
);
create index if not exists ix_audit_log_company_date on public.audit_log (company_id, changed_at desc);
create index if not exists ix_audit_log_record on public.audit_log (table_name, record_id);
create index if not exists ix_audit_log_user on public.audit_log (changed_by);

alter table public.audit_log enable row level security;

-- Solo lectura, solo ADMIN, y solo de su propia empresa. Nadie escribe aquí
-- directamente (ni siquiera un ADMIN): la única vía de escritura es el
-- trigger, que corre en modo SECURITY DEFINER y por tanto no pasa por estas
-- políticas. Sin políticas de insert/update/delete = denegado por defecto.
drop policy if exists audit_log_admin_select on public.audit_log;
create policy audit_log_admin_select on public.audit_log for select using (
  public.is_admin() and company_id = public.admin_company_id()
);

-- Trigger genérico: compara NEW/OLD completos vía jsonb, sin necesitar
-- conocer las columnas de cada tabla. Ignora updates donde lo único que
-- cambió es updated_at (no aportan nada a un histórico de auditoría).
-- company_id se resuelve de la propia fila cuando la tabla lo tiene; para
-- las dos tablas del alcance que no lo tienen directamente (invoice_installment,
-- user_module_permission) se resuelve vía su tabla padre, para no dejar
-- filas con company_id null que se saltarían el filtrado por empresa de la
-- política de arriba.
create or replace function public.audit_log_row() returns trigger
language plpgsql security definer set search_path = public as $$
declare
  v_old jsonb;
  v_new jsonb;
  v_changed text[];
  v_company bigint;
  v_record bigint;
begin
  if tg_op = 'INSERT' then
    v_new := to_jsonb(NEW);
    v_record := (v_new->>'id')::bigint;
    v_company := nullif(v_new->>'company_id', '')::bigint;
  elsif tg_op = 'UPDATE' then
    v_old := to_jsonb(OLD);
    v_new := to_jsonb(NEW);
    v_record := (v_new->>'id')::bigint;
    v_company := nullif(v_new->>'company_id', '')::bigint;
    select array_agg(n.key order by n.key) into v_changed
    from jsonb_each(v_new) n
    where n.key <> 'updated_at' and n.value is distinct from (v_old -> n.key);
    if v_changed is null then
      return NEW;
    end if;
  else
    v_old := to_jsonb(OLD);
    v_record := (v_old->>'id')::bigint;
    v_company := nullif(v_old->>'company_id', '')::bigint;
  end if;

  if v_company is null then
    if tg_table_name = 'invoice_installment' then
      select company_id into v_company from public.invoice
      where id = coalesce((v_new->>'invoice_id')::bigint, (v_old->>'invoice_id')::bigint);
    elsif tg_table_name = 'user_module_permission' then
      select company_id into v_company from public.user_account
      where id = coalesce((v_new->>'user_account_id')::bigint, (v_old->>'user_account_id')::bigint);
    end if;
  end if;

  insert into public.audit_log (company_id, table_name, record_id, action, changed_by, changed_fields, old_data, new_data)
  values (v_company, tg_table_name, v_record, tg_op, auth.uid(), v_changed, v_old, v_new);

  if tg_op = 'DELETE' then
    return OLD;
  end if;
  return NEW;
end;
$$;
revoke all on function public.audit_log_row() from public;

do $$
declare
  t text;
begin
  foreach t in array array[
    'quotation', 'sales_order', 'invoice', 'invoice_installment',
    'production_work_sheet', 'delivery_note', 'installation',
    'customer', 'user_account', 'user_module_permission'
  ]
  loop
    execute format('drop trigger if exists audit_log_trg on public.%I', t);
    execute format(
      'create trigger audit_log_trg after insert or update or delete on public.%I for each row execute function public.audit_log_row()',
      t
    );
  end loop;
end;
$$;
