-- ONIN: gestión de montajes (instalación en casa del cliente), última etapa del pedido.
--
-- En Toldos (legacy) la programación de un montaje NO estaba bloqueada por el estado
-- "Fabricado" del pedido — el menú "Montaje" solo comprobaba que el documento
-- estuviera guardado. Además, el campo MONTADO nunca llegaba a marcarse "S" en
-- ningún camino del código: el formulario de cierre ("finalizador") exigía rellenar
-- hora de fin y duración real, pero seguía grabando MONTADO='N' siempre. La pantalla
-- de listado coloreaba en naranja las filas vencidas infiriendo el estado a partir de
-- si esos campos estaban rellenos, no del propio flag.
--
-- Aquí se corrigen ambas cosas: el montaje pasa a llamarse "installation", solo se
-- puede programar cuando el pedido ya está MANUFACTURED (o INSTALLED, para permitir
-- reprogramaciones), y sí existe un estado real (SCHEDULED/COMPLETED/CANCELLED) que se
-- actualiza de verdad. Al completarse, el pedido pasa automáticamente a INSTALLED,
-- cerrando el ciclo de estados que ya existía en sales_order pero que nada activaba.
--
-- Los instaladores se seleccionan de user_account (ya existe el rol 'INSTALLER' en el
-- tipo UserRole del cliente) en vez del texto libre unido con guiones de Toldos.

create table if not exists public.installation_type (
  id bigint generated by default as identity primary key,
  company_id bigint not null references public.company(id),
  description text not null,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  constraint installation_type_company_description_uk unique (company_id, description)
);

create table if not exists public.installation (
  id bigint generated by default as identity primary key,
  company_id bigint not null references public.company(id),
  sales_order_id bigint not null references public.sales_order(id),
  installation_type_id bigint references public.installation_type(id),
  scheduled_date date,
  start_time varchar(10),
  end_time varchar(10),
  estimated_duration varchar(20),
  actual_duration varchar(20),
  installers jsonb not null default '[]'::jsonb,
  notes text,
  status varchar(20) not null default 'SCHEDULED',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint installation_status_ck check (status in ('SCHEDULED', 'COMPLETED', 'CANCELLED')),
  constraint installation_installers_ck check (jsonb_typeof(installers) = 'array')
);

-- Como mucho una programación activa (no cancelada) por pedido, igual que Toldos
-- gestionaba un único montaje por pedido vía obtenerMontajeByPedido.
create unique index if not exists ux_installation_order_active
  on public.installation (sales_order_id)
  where status <> 'CANCELLED';

create index if not exists ix_installation_company_date
  on public.installation (company_id, scheduled_date);
create index if not exists ix_installation_status
  on public.installation (company_id, status);

alter table public.installation_type enable row level security;
alter table public.installation enable row level security;

create policy installation_type_company_select on public.installation_type for select using (company_id = (select company_id from public.user_account where auth_user_id = auth.uid()));
create policy installation_type_company_insert on public.installation_type for insert with check (company_id = (select company_id from public.user_account where auth_user_id = auth.uid()));
create policy installation_type_company_update on public.installation_type for update using (company_id = (select company_id from public.user_account where auth_user_id = auth.uid())) with check (company_id = (select company_id from public.user_account where auth_user_id = auth.uid()));

create policy installation_company_select on public.installation for select using (company_id = (select company_id from public.user_account where auth_user_id = auth.uid()));
create policy installation_company_insert on public.installation for insert with check (company_id = (select company_id from public.user_account where auth_user_id = auth.uid()));
create policy installation_company_update on public.installation for update using (company_id = (select company_id from public.user_account where auth_user_id = auth.uid())) with check (company_id = (select company_id from public.user_account where auth_user_id = auth.uid()));

-- Bloquea la programación hasta que el pedido esté fabricado (o ya instalado, para
-- permitir reprogramar). A diferencia de Toldos, esto sí se aplica de verdad.
create or replace function public.check_installation_order_manufactured()
returns trigger
language plpgsql
as $$
declare
  v_status varchar;
begin
  select status into v_status from public.sales_order where id = new.sales_order_id;
  if v_status is null then
    raise exception 'El pedido de la instalación no existe';
  end if;
  if v_status not in ('MANUFACTURED', 'INSTALLED') then
    raise exception 'El pedido debe estar fabricado antes de programar el montaje';
  end if;
  return new;
end;
$$;

drop trigger if exists trg_check_installation_order_manufactured on public.installation;
create trigger trg_check_installation_order_manufactured
before insert on public.installation
for each row execute function public.check_installation_order_manufactured();

-- Completa la instalación (exige hora de fin y duración real, como el modo
-- "finalizador" de Toldos) y, a diferencia de Toldos, sí marca el pedido como
-- instalado.
create or replace function public.complete_installation(
  p_installation_id bigint,
  p_end_time varchar,
  p_actual_duration varchar
)
returns void
language plpgsql
security invoker
as $$
declare
  v_order_id bigint;
begin
  if p_end_time is null or trim(p_end_time) = '' or trim(p_end_time) = '00:00' then
    raise exception 'Debe indicar la hora de finalización';
  end if;
  if p_actual_duration is null or trim(p_actual_duration) = '' or trim(p_actual_duration) = '0' then
    raise exception 'Debe indicar la duración real';
  end if;

  update public.installation
     set status = 'COMPLETED', end_time = p_end_time, actual_duration = p_actual_duration, updated_at = now()
   where id = p_installation_id and status = 'SCHEDULED'
   returning sales_order_id into v_order_id;

  if v_order_id is null then
    raise exception 'La instalación no existe o ya no está programada';
  end if;

  update public.sales_order
     set status = 'INSTALLED', updated_at = now()
   where id = v_order_id and status not in ('INSTALLED', 'CANCELLED');
end;
$$;

grant execute on function public.complete_installation(bigint, varchar, varchar) to authenticated;

insert into public.installation_type (company_id, description, active)
select c.id, 'Instalación estándar', true
from public.company c
where not exists (
  select 1 from public.installation_type t where t.company_id = c.id
);
