-- Onin V2: personalización de características heredadas de Familia a nivel de Artículo.
-- El artículo puede añadir características propias mediante product_attribute_assignment
-- y excluir características heredadas de su Familia mediante esta tabla.
create table if not exists public.product_family_attribute_exclusion (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.product(id) on delete cascade,
  attribute_id bigint not null references public.product_attribute(id) on delete cascade,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint product_family_attribute_exclusion_uk unique(product_id, attribute_id)
);

create index if not exists ix_product_family_attribute_exclusion_product
  on public.product_family_attribute_exclusion(product_id, attribute_id);

comment on table public.product_family_attribute_exclusion is
  'Exclusiones de características heredadas de la Familia para un Artículo concreto.';
