-- Corrige en Supabase la versión de "huecos" ya aplicada anteriormente
-- (otd_id + medidas directamente en measurement_opening, un único producto
-- por hueco) al modelo final, que permite varios productos por hueco
-- (measurement_opening_product). Escrita para poder ejecutarse tal cual
-- tanto si solo se llegó a aplicar la primera versión (product_family_id /
-- measurement_type_id) como si ya se había corregido a otd_id.

create table if not exists public.measurement_opening_product (
  id bigint generated by default as identity primary key,
  opening_id bigint not null references public.measurement_opening(id) on delete cascade,
  sort_order integer not null default 0,
  otd_id bigint references public.otd(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists ix_measurement_opening_product_opening
  on public.measurement_opening_product(opening_id, sort_order);

comment on table public.measurement_opening_product is
  'Un producto (OTD) dentro de un hueco — un hueco puede tener más de un toldo/pérgola.';
comment on column public.measurement_opening_product.otd_id is
  'OTD sugerido por quien mide, in situ. Selección manual, no automática. Define qué selecciones/dimensiones aplican (otd_selection con is_dimension = true).';

-- Si measurement_opening todavía tiene otd_id (versión intermedia ya
-- aplicada), migrar cada hueco a su primer/único producto y retirarlo.
do $$
begin
  if exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'measurement_opening' and column_name = 'otd_id'
  ) then
    insert into public.measurement_opening_product (opening_id, sort_order, otd_id, created_at, updated_at)
    select o.id, 1, o.otd_id, now(), now()
    from public.measurement_opening o
    where not exists (select 1 from public.measurement_opening_product p where p.opening_id = o.id);

    alter table public.measurement_opening drop column otd_id;
  end if;
end $$;

-- Columnas de la primera versión (familia/tipo de medida), ya sin uso en
-- ninguna variante del modelo actual.
alter table public.measurement_opening drop column if exists product_family_id;
alter table public.measurement_opening drop column if exists measurement_type_id;

-- measurement_opening_dimension: pasar de colgar de opening_id a colgar de
-- opening_product_id (un producto puede tener sus propias medidas).
do $$
begin
  if exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'measurement_opening_dimension' and column_name = 'opening_id'
  ) then
    alter table public.measurement_opening_dimension
      add column if not exists opening_product_id bigint references public.measurement_opening_product(id) on delete cascade;

    -- Huecos con medidas pero sin producto todavía (medidas sin OTD decidido
    -- en la versión anterior): crear un producto "sin decidir" para no
    -- perder las medidas ya capturadas.
    insert into public.measurement_opening_product (opening_id, sort_order, otd_id, created_at, updated_at)
    select distinct d.opening_id, 1, null::bigint, now(), now()
    from public.measurement_opening_dimension d
    where d.opening_product_id is null
      and not exists (select 1 from public.measurement_opening_product p where p.opening_id = d.opening_id);

    update public.measurement_opening_dimension d
    set opening_product_id = p.id
    from public.measurement_opening_product p
    where d.opening_product_id is null
      and d.opening_id = p.opening_id;

    alter table public.measurement_opening_dimension
      drop constraint if exists measurement_opening_dimension_opening_code_uk;
    alter table public.measurement_opening_dimension
      alter column opening_product_id set not null;
    alter table public.measurement_opening_dimension
      drop column opening_id;
  end if;
end $$;

alter table public.measurement_opening_dimension
  drop constraint if exists measurement_opening_dimension_product_code_uk;
alter table public.measurement_opening_dimension
  add constraint measurement_opening_dimension_product_code_uk unique(opening_product_id, code);

create index if not exists ix_measurement_opening_dimension_product
  on public.measurement_opening_dimension(opening_product_id, sort_order);

alter table public.measurement_opening_product enable row level security;

drop policy if exists measurement_opening_product_company_access on public.measurement_opening_product;
create policy measurement_opening_product_company_access on public.measurement_opening_product for all
  using (exists(select 1 from public.measurement_opening o join public.measurement m on m.id=o.measurement_id where o.id=opening_id and m.company_id=public.current_company_id()))
  with check (exists(select 1 from public.measurement_opening o join public.measurement m on m.id=o.measurement_id where o.id=opening_id and m.company_id=public.current_company_id()));

drop policy if exists measurement_opening_dimension_company_access on public.measurement_opening_dimension;
create policy measurement_opening_dimension_company_access on public.measurement_opening_dimension for all
  using (exists(select 1 from public.measurement_opening_product p join public.measurement_opening o on o.id=p.opening_id join public.measurement m on m.id=o.measurement_id where p.id=opening_product_id and m.company_id=public.current_company_id()))
  with check (exists(select 1 from public.measurement_opening_product p join public.measurement_opening o on o.id=p.opening_id join public.measurement m on m.id=o.measurement_id where p.id=opening_product_id and m.company_id=public.current_company_id()));
