ALTER TABLE public.warehouse_stock ADD COLUMN IF NOT EXISTS characteristic_id bigint REFERENCES public.product_characteristic(id);
ALTER TABLE public.stock_movement ADD COLUMN IF NOT EXISTS characteristic_id bigint REFERENCES public.product_characteristic(id);
ALTER TABLE public.stock_movement ADD COLUMN IF NOT EXISTS transfer_group_id uuid;

CREATE UNIQUE INDEX IF NOT EXISTS uq_warehouse_stock_item
  ON public.warehouse_stock (warehouse_id, product_id, COALESCE(characteristic_id, 0));
CREATE INDEX IF NOT EXISTS idx_warehouse_stock_product_characteristic
  ON public.warehouse_stock (product_id, characteristic_id);
CREATE INDEX IF NOT EXISTS idx_stock_movement_item_date
  ON public.stock_movement (warehouse_id, product_id, characteristic_id, movement_date DESC);
CREATE INDEX IF NOT EXISTS idx_stock_movement_transfer_group
  ON public.stock_movement (transfer_group_id)
  WHERE transfer_group_id IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS uq_stock_movement_type_company_code
  ON public.stock_movement_type (company_id, code);

CREATE TABLE IF NOT EXISTS public.stock_reservation (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id bigint NOT NULL REFERENCES public.company(id),
  warehouse_id bigint NOT NULL REFERENCES public.warehouse(id),
  product_id bigint NOT NULL REFERENCES public.product(id),
  characteristic_id bigint NULL REFERENCES public.product_characteristic(id),
  quantity numeric NOT NULL CHECK (quantity > 0),
  reference varchar NULL,
  notes text NULL,
  status varchar NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE','RELEASED','CONSUMED')),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_stock_reservation_lookup
  ON public.stock_reservation (company_id, warehouse_id, product_id, characteristic_id, status);

INSERT INTO public.stock_movement_type (company_id, code, name, direction, active)
SELECT c.id, v.code, v.name, v.direction, true
FROM public.company c
CROSS JOIN (VALUES
  ('INITIAL','Stock inicial',1),
  ('PURCHASE','Entrada por compra',1),
  ('SALE','Salida por venta',-1),
  ('RETURN_SALE','Devolución de venta',1),
  ('RETURN_PURCHASE','Devolución de compra',-1),
  ('ADJUSTMENT_IN','Ajuste positivo',1),
  ('ADJUSTMENT_OUT','Ajuste negativo',-1),
  ('TRANSFER_IN','Entrada por traspaso',1),
  ('TRANSFER_OUT','Salida por traspaso',-1)
) v(code,name,direction)
WHERE NOT EXISTS (
  SELECT 1 FROM public.stock_movement_type t
  WHERE t.company_id = c.id AND t.code = v.code
);

CREATE OR REPLACE FUNCTION public.register_stock_movement(
  p_company_id bigint,
  p_warehouse_id bigint,
  p_product_id bigint,
  p_quantity numeric,
  p_movement_type_code varchar,
  p_characteristic_id bigint DEFAULT NULL,
  p_reference varchar DEFAULT NULL,
  p_notes text DEFAULT NULL,
  p_movement_date timestamptz DEFAULT now(),
  p_transfer_group_id uuid DEFAULT NULL
) RETURNS bigint
LANGUAGE plpgsql
SECURITY INVOKER
AS $$
DECLARE
  v_product public.product%ROWTYPE;
  v_warehouse public.warehouse%ROWTYPE;
  v_type public.stock_movement_type%ROWTYPE;
  v_stock public.warehouse_stock%ROWTYPE;
  v_signed numeric;
  v_movement_id bigint;
BEGIN
  IF p_quantity IS NULL OR p_quantity <= 0 THEN
    RAISE EXCEPTION 'La cantidad debe ser mayor que cero';
  END IF;
  SELECT * INTO v_product FROM public.product WHERE id = p_product_id AND company_id = p_company_id AND deleted_at IS NULL;
  IF NOT FOUND THEN RAISE EXCEPTION 'El artículo no existe para la empresa indicada'; END IF;
  IF NOT v_product.stock_enabled THEN RAISE EXCEPTION 'El artículo % no tiene la gestión de stock activada', v_product.code; END IF;
  SELECT * INTO v_warehouse FROM public.warehouse WHERE id = p_warehouse_id AND company_id = p_company_id AND deleted_at IS NULL;
  IF NOT FOUND THEN RAISE EXCEPTION 'El almacén no existe para la empresa indicada'; END IF;
  IF NOT v_warehouse.active THEN RAISE EXCEPTION 'El almacén está inactivo'; END IF;
  SELECT * INTO v_type FROM public.stock_movement_type WHERE company_id = p_company_id AND code = p_movement_type_code AND active = true;
  IF NOT FOUND THEN RAISE EXCEPTION 'Tipo de movimiento no válido: %', p_movement_type_code; END IF;
  IF p_characteristic_id IS NOT NULL THEN
    PERFORM 1 FROM public.product_characteristic pc WHERE pc.id = p_characteristic_id AND pc.product_id = p_product_id AND pc.deleted_at IS NULL AND pc.active = true;
    IF NOT FOUND THEN RAISE EXCEPTION 'La característica no pertenece al artículo o no está activa'; END IF;
  ELSIF v_product.include_stock_by_color THEN
    RAISE EXCEPTION 'El artículo requiere característica para gestionar stock por color';
  END IF;
  v_signed := p_quantity * v_type.direction;
  SELECT * INTO v_stock FROM public.warehouse_stock WHERE warehouse_id = p_warehouse_id AND product_id = p_product_id AND characteristic_id IS NOT DISTINCT FROM p_characteristic_id FOR UPDATE;
  IF NOT FOUND THEN
    INSERT INTO public.warehouse_stock (warehouse_id, product_id, characteristic_id, quantity, reserved_quantity) VALUES (p_warehouse_id, p_product_id, p_characteristic_id, 0, 0) RETURNING * INTO v_stock;
  END IF;
  IF v_signed < 0 AND NOT v_product.allow_negative_stock AND (v_stock.quantity + v_signed) < 0 THEN
    RAISE EXCEPTION 'Stock insuficiente. Disponible físico: %', v_stock.quantity;
  END IF;
  UPDATE public.warehouse_stock SET quantity = quantity + v_signed, updated_at = now() WHERE id = v_stock.id;
  INSERT INTO public.stock_movement (company_id, warehouse_id, product_id, movement_type_id, characteristic_id, quantity, movement_date, reference, notes, transfer_group_id)
  VALUES (p_company_id, p_warehouse_id, p_product_id, v_type.id, p_characteristic_id, p_quantity, p_movement_date, p_reference, p_notes, p_transfer_group_id)
  RETURNING id INTO v_movement_id;
  RETURN v_movement_id;
END;
$$;

CREATE OR REPLACE FUNCTION public.register_stock_transfer(
  p_company_id bigint,
  p_source_warehouse_id bigint,
  p_target_warehouse_id bigint,
  p_product_id bigint,
  p_quantity numeric,
  p_characteristic_id bigint DEFAULT NULL,
  p_reference varchar DEFAULT NULL,
  p_notes text DEFAULT NULL,
  p_movement_date timestamptz DEFAULT now()
) RETURNS uuid
LANGUAGE plpgsql SECURITY INVOKER AS $$
DECLARE v_group uuid := gen_random_uuid();
BEGIN
  IF p_source_warehouse_id = p_target_warehouse_id THEN RAISE EXCEPTION 'El almacén origen y destino deben ser distintos'; END IF;
  PERFORM public.register_stock_movement(p_company_id,p_source_warehouse_id,p_product_id,p_quantity,'TRANSFER_OUT',p_characteristic_id,p_reference,p_notes,p_movement_date,v_group);
  PERFORM public.register_stock_movement(p_company_id,p_target_warehouse_id,p_product_id,p_quantity,'TRANSFER_IN',p_characteristic_id,p_reference,p_notes,p_movement_date,v_group);
  RETURN v_group;
END;
$$;

CREATE OR REPLACE FUNCTION public.reserve_stock(
  p_company_id bigint,
  p_warehouse_id bigint,
  p_product_id bigint,
  p_quantity numeric,
  p_characteristic_id bigint DEFAULT NULL,
  p_reference varchar DEFAULT NULL,
  p_notes text DEFAULT NULL
) RETURNS bigint
LANGUAGE plpgsql SECURITY INVOKER AS $$
DECLARE v_product public.product%ROWTYPE; v_warehouse public.warehouse%ROWTYPE; v_stock public.warehouse_stock%ROWTYPE; v_id bigint;
BEGIN
  IF p_quantity IS NULL OR p_quantity <= 0 THEN RAISE EXCEPTION 'La cantidad a reservar debe ser mayor que cero'; END IF;
  SELECT * INTO v_product FROM public.product WHERE id=p_product_id AND company_id=p_company_id AND deleted_at IS NULL;
  IF NOT FOUND THEN RAISE EXCEPTION 'El artículo no existe'; END IF;
  IF NOT v_product.stock_enabled THEN RAISE EXCEPTION 'El artículo no tiene la gestión de stock activada'; END IF;
  SELECT * INTO v_warehouse FROM public.warehouse WHERE id=p_warehouse_id AND company_id=p_company_id AND deleted_at IS NULL AND active=true;
  IF NOT FOUND THEN RAISE EXCEPTION 'El almacén no existe o está inactivo'; END IF;
  IF p_characteristic_id IS NOT NULL THEN
    PERFORM 1 FROM public.product_characteristic pc WHERE pc.id=p_characteristic_id AND pc.product_id=p_product_id AND pc.deleted_at IS NULL AND pc.active=true;
    IF NOT FOUND THEN RAISE EXCEPTION 'Característica no válida para el artículo'; END IF;
  ELSIF v_product.include_stock_by_color THEN RAISE EXCEPTION 'El artículo requiere característica para reservar stock'; END IF;
  SELECT * INTO v_stock FROM public.warehouse_stock WHERE warehouse_id=p_warehouse_id AND product_id=p_product_id AND characteristic_id IS NOT DISTINCT FROM p_characteristic_id FOR UPDATE;
  IF NOT FOUND THEN
    INSERT INTO public.warehouse_stock (warehouse_id,product_id,characteristic_id,quantity,reserved_quantity) VALUES (p_warehouse_id,p_product_id,p_characteristic_id,0,0) RETURNING * INTO v_stock;
  END IF;
  IF (v_stock.quantity-v_stock.reserved_quantity)<p_quantity AND NOT v_product.allow_negative_stock THEN
    RAISE EXCEPTION 'Stock disponible insuficiente. Disponible: %',(v_stock.quantity-v_stock.reserved_quantity);
  END IF;
  UPDATE public.warehouse_stock SET reserved_quantity=reserved_quantity+p_quantity,updated_at=now() WHERE id=v_stock.id;
  INSERT INTO public.stock_reservation (company_id,warehouse_id,product_id,characteristic_id,quantity,reference,notes) VALUES (p_company_id,p_warehouse_id,p_product_id,p_characteristic_id,p_quantity,p_reference,p_notes) RETURNING id INTO v_id;
  RETURN v_id;
END;
$$;

CREATE OR REPLACE FUNCTION public.release_stock_reservation(p_reservation_id bigint) RETURNS void LANGUAGE plpgsql SECURITY INVOKER AS $$
DECLARE v_res public.stock_reservation%ROWTYPE;
BEGIN
  SELECT * INTO v_res FROM public.stock_reservation WHERE id=p_reservation_id FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'Reserva no encontrada'; END IF;
  IF v_res.status<>'ACTIVE' THEN RETURN; END IF;
  UPDATE public.warehouse_stock SET reserved_quantity=GREATEST(0,reserved_quantity-v_res.quantity),updated_at=now()
  WHERE warehouse_id=v_res.warehouse_id AND product_id=v_res.product_id AND characteristic_id IS NOT DISTINCT FROM v_res.characteristic_id;
  UPDATE public.stock_reservation SET status='RELEASED',updated_at=now() WHERE id=p_reservation_id;
END;
$$;

CREATE OR REPLACE FUNCTION public.consume_stock_reservation(p_reservation_id bigint) RETURNS void LANGUAGE plpgsql SECURITY INVOKER AS $$
DECLARE v_res public.stock_reservation%ROWTYPE;
BEGIN
  SELECT * INTO v_res FROM public.stock_reservation WHERE id=p_reservation_id FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'Reserva no encontrada'; END IF;
  IF v_res.status<>'ACTIVE' THEN RETURN; END IF;
  UPDATE public.warehouse_stock SET reserved_quantity=GREATEST(0,reserved_quantity-v_res.quantity),updated_at=now()
  WHERE warehouse_id=v_res.warehouse_id AND product_id=v_res.product_id AND characteristic_id IS NOT DISTINCT FROM v_res.characteristic_id;
  UPDATE public.stock_reservation SET status='CONSUMED',updated_at=now() WHERE id=p_reservation_id;
END;
$$;
