create table if not exists public.measurement_type (
  id bigint generated by default as identity primary key,
  company_id bigint not null references public.company(id),
  code varchar not null,
  name varchar not null,
  dimension_count integer not null default 0,
  result_unit_id bigint references public.unit(id),
  result_decimals integer not null default 2,
  calculation_type varchar,
  formula text,
  active boolean not null default true,
  deleted_at timestamptz,
  deleted_by uuid,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint measurement_type_company_code_uk unique(company_id, code),
  constraint measurement_type_dimension_count_ck check (dimension_count between 0 and 5),
  constraint measurement_type_result_decimals_ck check (result_decimals between 0 and 6)
);

create table if not exists public.measurement_type_dimension (
  id bigint generated by default as identity primary key,
  measurement_type_id bigint not null references public.measurement_type(id) on delete cascade,
  dimension_number integer not null,
  code varchar not null,
  name varchar not null,
  unit_id bigint references public.unit(id),
  decimals integer not null default 2,
  constraint measurement_type_dimension_number_ck check (dimension_number between 1 and 5),
  constraint measurement_type_dimension_decimals_ck check (decimals between 0 and 6),
  constraint measurement_type_dimension_number_uk unique(measurement_type_id, dimension_number),
  constraint measurement_type_dimension_code_uk unique(measurement_type_id, code)
);

create index if not exists ix_measurement_type_company_active on public.measurement_type(company_id, active);
create index if not exists ix_measurement_type_dimension_type on public.measurement_type_dimension(measurement_type_id, dimension_number);

alter table public.measurement_type enable row level security;
alter table public.measurement_type_dimension enable row level security;

create policy measurement_type_authenticated_select on public.measurement_type for select to authenticated using(auth.uid() is not null);
create policy measurement_type_authenticated_insert on public.measurement_type for insert to authenticated with check(auth.uid() is not null);
create policy measurement_type_authenticated_update on public.measurement_type for update to authenticated using(auth.uid() is not null) with check(auth.uid() is not null);
create policy measurement_type_dimension_authenticated_select on public.measurement_type_dimension for select to authenticated using(auth.uid() is not null);
create policy measurement_type_dimension_authenticated_insert on public.measurement_type_dimension for insert to authenticated with check(auth.uid() is not null);
create policy measurement_type_dimension_authenticated_update on public.measurement_type_dimension for update to authenticated using(auth.uid() is not null) with check(auth.uid() is not null);
create policy measurement_type_dimension_authenticated_delete on public.measurement_type_dimension for delete to authenticated using(auth.uid() is not null);
