-- Fase 2 del modelo Sistema -> Familia -> Artículo: precio y colores por
-- característica a nivel de FAMILIA.
--
-- Colores: la familia hereda el conjunto de colores de la característica de
-- sistema (attribute_color) y puede excluir los que no le apliquen — modelo
-- "excluir", no "incluir desde cero": mientras no haya fila de exclusión, el
-- color sigue disponible para la familia.
--
-- Precio: puede ser plano (product_family_attribute.pvp) o escalado por
-- cantidad (product_family_attribute_scale, mismo patrón dimension_1/
-- dimension_2/price que product_scale), decidido característica a
-- característica dentro de la misma familia mediante el flag "scaled" — no
-- es un flag global de familia, porque una familia puede tener una
-- característica con escalado y otra con precio plano al mismo tiempo.

alter table public.product_family_attribute add column if not exists scaled boolean not null default false;
alter table public.product_family_attribute add column if not exists pvp numeric;

comment on column public.product_family_attribute.scaled is
  'Si es true, el precio de esta característica para la familia se resuelve por tramos (product_family_attribute_scale) en vez del valor plano (pvp).';

create table if not exists public.product_family_attribute_scale (
  id bigint generated by default as identity primary key,
  family_attribute_id bigint not null references public.product_family_attribute(id) on delete cascade,
  dimension_1 numeric not null,
  dimension_2 numeric,
  price numeric not null,
  deleted_at timestamptz,
  deleted_by uuid,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint product_family_attribute_scale_price_ck check (price > 0),
  constraint product_family_attribute_scale_dim1_ck check (dimension_1 >= 0)
);

create index if not exists ix_product_family_attribute_scale_lookup
  on public.product_family_attribute_scale (family_attribute_id, dimension_1, dimension_2)
  where deleted_at is null;

alter table public.product_family_attribute_scale enable row level security;

drop policy if exists product_family_attribute_scale_company_access on public.product_family_attribute_scale;
create policy product_family_attribute_scale_company_access on public.product_family_attribute_scale
  for all using (
    exists (
      select 1 from public.product_family_attribute pfa
      join public.product_family f on f.id = pfa.family_id
      where pfa.id = family_attribute_id and f.company_id = public.current_company_id()
    )
  )
  with check (
    exists (
      select 1 from public.product_family_attribute pfa
      join public.product_family f on f.id = pfa.family_id
      where pfa.id = family_attribute_id and f.company_id = public.current_company_id()
    )
  );

create table if not exists public.product_family_attribute_color_exclusion (
  id bigint generated by default as identity primary key,
  family_attribute_id bigint not null references public.product_family_attribute(id) on delete cascade,
  color_id bigint not null references public.color(id),
  created_at timestamptz not null default now(),
  constraint product_family_attribute_color_exclusion_uk unique (family_attribute_id, color_id)
);

create index if not exists ix_product_family_attribute_color_exclusion_lookup
  on public.product_family_attribute_color_exclusion (family_attribute_id);

alter table public.product_family_attribute_color_exclusion enable row level security;

drop policy if exists product_family_attribute_color_exclusion_company_access on public.product_family_attribute_color_exclusion;
create policy product_family_attribute_color_exclusion_company_access on public.product_family_attribute_color_exclusion
  for all using (
    exists (
      select 1 from public.product_family_attribute pfa
      join public.product_family f on f.id = pfa.family_id
      where pfa.id = family_attribute_id and f.company_id = public.current_company_id()
    )
  )
  with check (
    exists (
      select 1 from public.product_family_attribute pfa
      join public.product_family f on f.id = pfa.family_id
      where pfa.id = family_attribute_id and f.company_id = public.current_company_id()
    )
  );

comment on table public.product_family_attribute_color_exclusion is
  'Colores heredados de attribute_color que esta familia excluye para esta característica concreta. Ausencia de fila = color disponible.';
