-- Creación de la tabla de escalado directo para OTD (artículos compuestos)
create table if not exists public.otd_scale (
  id bigint generated by default as identity primary key,
  otd_id bigint not null references public.otd(id) on delete cascade,
  dimension_1 numeric(15, 4) not null,
  dimension_2 numeric(15, 4),
  dimension_values jsonb not null default '[]'::jsonb,
  price numeric(15, 2) not null check (price >= 0),
  attribute_values jsonb not null default '{}'::jsonb,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  deleted_at timestamp with time zone,
  deleted_by bigint
);

create index if not exists idx_otd_scale_otd_id on public.otd_scale(otd_id) where deleted_at is null;
create index if not exists idx_otd_scale_dims on public.otd_scale(otd_id, dimension_1, dimension_2) where deleted_at is null;

comment on table public.otd_scale is 'Matriz de escalado de precios base para el producto compuesto OTD.';
comment on column public.otd_scale.dimension_values is 'Array con los valores dimensionales del escalón en el orden de las dimensiones OTD marcadas como is_dimension.';
