alter table public.measurement add column if not exists year integer;
alter table public.measurement add column if not exists number bigint;
alter table public.measurement add column if not exists code varchar;
alter table public.measurement add column if not exists customer_name_snapshot varchar;
alter table public.measurement add column if not exists customer_tax_id_snapshot varchar;
alter table public.measurement add column if not exists customer_phone_snapshot varchar;
alter table public.measurement add column if not exists customer_mobile_snapshot varchar;
alter table public.measurement add column if not exists customer_email_snapshot varchar;
alter table public.measurement add column if not exists site_street varchar;
alter table public.measurement add column if not exists site_postal_code varchar;
alter table public.measurement add column if not exists site_city varchar;
alter table public.measurement add column if not exists site_region varchar;
alter table public.measurement add column if not exists site_country_code varchar default 'ES';
alter table public.measurement add column if not exists site_latitude numeric(10,7);
alter table public.measurement add column if not exists site_longitude numeric(10,7);
alter table public.measurement add column if not exists contact_method varchar;
alter table public.measurement add column if not exists commercial_name varchar;
alter table public.measurement add column if not exists assigned_user_id uuid;
alter table public.measurement add column if not exists assigned_mode varchar default 'UNASSIGNED';
alter table public.measurement add column if not exists measurement_date date;
alter table public.measurement add column if not exists measurement_time time;
alter table public.measurement add column if not exists reference_note text;
alter table public.measurement add column if not exists deleted_at timestamptz;
alter table public.measurement add column if not exists deleted_by uuid;
alter table public.measurement add column if not exists created_by uuid;
alter table public.measurement add column if not exists updated_by uuid;

update public.measurement
set year=coalesce(year,extract(year from coalesce(contact_date,current_date))::integer),
    number=coalesce(number,id),
    code=coalesce(code,'M-'||coalesce(extract(year from coalesce(contact_date,current_date))::integer,extract(year from current_date)::integer)::text||'-'||lpad(id::text,6,'0')),
    customer_name_snapshot=coalesce(customer_name_snapshot,name),
    customer_phone_snapshot=coalesce(customer_phone_snapshot,phone),
    customer_mobile_snapshot=coalesce(customer_mobile_snapshot,mobile),
    customer_email_snapshot=coalesce(customer_email_snapshot,email),
    site_street=coalesce(site_street,address),
    site_postal_code=coalesce(site_postal_code,postal_code),
    site_city=coalesce(site_city,city),
    site_country_code=coalesce(site_country_code,'ES'),
    measurement_date=coalesce(measurement_date, (measurement_at at time zone 'UTC')::date),
    measurement_time=coalesce(measurement_time, (measurement_at at time zone 'UTC')::time),
    assigned_mode=coalesce(assigned_mode,case when measurer_id is null then 'UNASSIGNED' else 'USER' end);

alter table public.measurement alter column year set not null;
alter table public.measurement alter column number set not null;
alter table public.measurement alter column code set not null;
alter table public.measurement alter column assigned_mode set default 'UNASSIGNED';
alter table public.measurement alter column site_country_code set default 'ES';

create unique index if not exists ux_measurement_company_year_number on public.measurement(company_id,year,number);
create unique index if not exists ux_measurement_company_code on public.measurement(company_id,code);
create index if not exists ix_measurement_company_status_deleted on public.measurement(company_id,status,deleted_at);
create index if not exists ix_measurement_customer_id on public.measurement(customer_id);
create index if not exists ix_measurement_date on public.measurement(company_id,measurement_date);

create table if not exists public.measurement_sequence (
  company_id bigint not null references public.company(id) on delete cascade,
  year integer not null,
  last_number bigint not null default 0,
  primary key(company_id,year)
);

insert into public.measurement_sequence(company_id,year,last_number)
select company_id,year,max(number) from public.measurement group by company_id,year
on conflict(company_id,year) do update set last_number=greatest(public.measurement_sequence.last_number,excluded.last_number);

create table if not exists public.measurement_activity (
  id bigint generated by default as identity primary key,
  measurement_id bigint not null references public.measurement(id) on delete cascade,
  event_type varchar not null,
  message text not null,
  created_at timestamptz not null default now(),
  created_by uuid
);
create index if not exists ix_measurement_activity_measurement on public.measurement_activity(measurement_id,created_at desc);

create or replace function public.create_measurement(
  p_company_id bigint,
  p_reference varchar,
  p_customer_id bigint,
  p_customer_name varchar,
  p_customer_tax_id varchar,
  p_customer_phone varchar,
  p_customer_mobile varchar,
  p_customer_email varchar,
  p_site_street varchar,
  p_site_postal_code varchar,
  p_site_city varchar,
  p_site_region varchar,
  p_site_country_code varchar,
  p_contact_method varchar,
  p_commercial_name varchar,
  p_assigned_user_id uuid,
  p_assigned_mode varchar,
  p_status varchar,
  p_contact_date date,
  p_measurement_date date,
  p_measurement_time time,
  p_observations text
) returns bigint
language plpgsql
security invoker
as $$
declare
  v_year integer := extract(year from coalesce(p_measurement_date,p_contact_date,current_date));
  v_number bigint;
  v_id bigint;
  v_user uuid := auth.uid();
begin
  if coalesce(trim(p_customer_name),'')='' then raise exception 'El cliente es obligatorio'; end if;
  if p_contact_date is null then raise exception 'La fecha de contacto es obligatoria'; end if;
  if p_assigned_mode='USER' and p_assigned_user_id is null then raise exception 'Debe indicar el medidor asignado'; end if;
  insert into public.measurement_sequence(company_id,year,last_number) values(p_company_id,v_year,1)
  on conflict(company_id,year) do update set last_number=public.measurement_sequence.last_number+1
  returning last_number into v_number;
  insert into public.measurement(company_id,year,number,code,reference,customer_id,customer_name_snapshot,customer_tax_id_snapshot,customer_phone_snapshot,customer_mobile_snapshot,customer_email_snapshot,site_street,site_postal_code,site_city,site_region,site_country_code,contact_method,commercial_name,assigned_user_id,assigned_mode,status,contact_date,measurement_date,measurement_time,notes,observations,created_by,updated_by)
  values(p_company_id,v_year,v_number,'M-'||v_year||'-'||lpad(v_number::text,6,'0'),nullif(trim(p_reference),''),p_customer_id,nullif(trim(p_customer_name),''),nullif(trim(p_customer_tax_id),''),nullif(trim(p_customer_phone),''),nullif(trim(p_customer_mobile),''),nullif(trim(p_customer_email),''),nullif(trim(p_site_street),''),nullif(trim(p_site_postal_code),''),nullif(trim(p_site_city),''),nullif(trim(p_site_region),''),coalesce(nullif(trim(p_site_country_code),''),'ES'),nullif(trim(p_contact_method),''),nullif(trim(p_commercial_name),''),p_assigned_user_id,coalesce(p_assigned_mode,'UNASSIGNED'),coalesce(p_status,'PLANNED'),p_contact_date,p_measurement_date,p_measurement_time,nullif(trim(p_observations),''),nullif(trim(p_observations),''),v_user,v_user)
  returning id into v_id;
  insert into public.measurement_activity(measurement_id,event_type,message,created_by) values(v_id,'CREATED','Medición creada',v_user);
  return v_id;
end;
$$;

alter table public.measurement enable row level security;
alter table public.measurement_activity enable row level security;
alter table public.measurement_sequence enable row level security;

create policy measurement_authenticated_select on public.measurement for select to authenticated using(auth.uid() is not null);
create policy measurement_authenticated_insert on public.measurement for insert to authenticated with check(auth.uid() is not null);
create policy measurement_authenticated_update on public.measurement for update to authenticated using(auth.uid() is not null) with check(auth.uid() is not null);
create policy measurement_activity_authenticated_select on public.measurement_activity for select to authenticated using(auth.uid() is not null);
create policy measurement_activity_authenticated_insert on public.measurement_activity for insert to authenticated with check(auth.uid() is not null);
create policy measurement_sequence_authenticated_select on public.measurement_sequence for select to authenticated using(auth.uid() is not null);
create policy measurement_sequence_authenticated_insert on public.measurement_sequence for insert to authenticated with check(auth.uid() is not null);
create policy measurement_sequence_authenticated_update on public.measurement_sequence for update to authenticated using(auth.uid() is not null) with check(auth.uid() is not null);
