-- Fase 3 del modelo Sistema -> Familia -> Artículo: precio y colores por
-- característica a nivel de ARTÍCULO.
--
-- product_attribute_assignment ya es, desde antes de esta serie de migraciones,
-- el mecanismo con el que un artículo "materializa" una característica propia:
-- toggleRequired en ProductFamilyCharacteristicsPanel ya crea una fila aquí
-- (vía assignProductAttribute, upsert por product_id+attribute_id) en cuanto el
-- usuario toca algo de una característica heredada de la familia — esa fila
-- pasa a tener source='article' y desde ahí manda sobre la de family. Se
-- reutiliza exactamente el mismo mecanismo para precio y color: mientras el
-- artículo no toque nada, hereda tal cual el precio/colores de la familia
-- (fase 2); en cuanto personaliza, se materializa una fila aquí con una copia
-- de los valores de la familia en ese momento (colores efectivos y
-- precio/escalado), y a partir de ahí evoluciona de forma independiente.

alter table public.product_attribute_assignment add column if not exists scaled boolean not null default false;
alter table public.product_attribute_assignment add column if not exists pvp numeric;

comment on column public.product_attribute_assignment.scaled is
  'Si es true, el precio de esta característica para el artículo se resuelve por tramos (product_attribute_assignment_scale) en vez del valor plano (pvp).';

create table if not exists public.product_attribute_assignment_scale (
  id bigint generated by default as identity primary key,
  assignment_id bigint not null references public.product_attribute_assignment(id) on delete cascade,
  dimension_1 numeric not null,
  dimension_2 numeric,
  price numeric not null,
  deleted_at timestamptz,
  deleted_by uuid,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint product_attribute_assignment_scale_price_ck check (price > 0),
  constraint product_attribute_assignment_scale_dim1_ck check (dimension_1 >= 0)
);

create index if not exists ix_product_attribute_assignment_scale_lookup
  on public.product_attribute_assignment_scale (assignment_id, dimension_1, dimension_2)
  where deleted_at is null;

alter table public.product_attribute_assignment_scale enable row level security;

drop policy if exists product_attribute_assignment_scale_company_access on public.product_attribute_assignment_scale;
create policy product_attribute_assignment_scale_company_access on public.product_attribute_assignment_scale
  for all using (
    exists (
      select 1 from public.product_attribute_assignment paa
      join public.product p on p.id = paa.product_id
      where paa.id = assignment_id and p.company_id = public.current_company_id()
    )
  )
  with check (
    exists (
      select 1 from public.product_attribute_assignment paa
      join public.product p on p.id = paa.product_id
      where paa.id = assignment_id and p.company_id = public.current_company_id()
    )
  );

create table if not exists public.product_attribute_assignment_color_exclusion (
  id bigint generated by default as identity primary key,
  assignment_id bigint not null references public.product_attribute_assignment(id) on delete cascade,
  color_id bigint not null references public.color(id),
  created_at timestamptz not null default now(),
  constraint product_attribute_assignment_color_exclusion_uk unique (assignment_id, color_id)
);

create index if not exists ix_product_attribute_assignment_color_exclusion_lookup
  on public.product_attribute_assignment_color_exclusion (assignment_id);

alter table public.product_attribute_assignment_color_exclusion enable row level security;

drop policy if exists product_attribute_assignment_color_exclusion_company_access on public.product_attribute_assignment_color_exclusion;
create policy product_attribute_assignment_color_exclusion_company_access on public.product_attribute_assignment_color_exclusion
  for all using (
    exists (
      select 1 from public.product_attribute_assignment paa
      join public.product p on p.id = paa.product_id
      where paa.id = assignment_id and p.company_id = public.current_company_id()
    )
  )
  with check (
    exists (
      select 1 from public.product_attribute_assignment paa
      join public.product p on p.id = paa.product_id
      where paa.id = assignment_id and p.company_id = public.current_company_id()
    )
  );

comment on table public.product_attribute_assignment_color_exclusion is
  'Colores que este artículo excluye para esta característica materializada (product_attribute_assignment). Al materializar desde la familia se copian aquí las exclusiones necesarias para reproducir el conjunto efectivo de la familia en ese momento; a partir de ahí el artículo evoluciona de forma independiente.';
