-- Migration: Sistema de Unidades de Medida y Conversiones para OTD y Catálogo

-- 1. Asegurar tabla magnitude y registros estándar
create table if not exists public.magnitude (
  id bigint generated by default as identity primary key,
  company_id bigint not null references public.company(id),
  code varchar not null,
  name varchar not null,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint magnitude_company_code_uk unique(company_id, code)
);

-- Insertar magnitudes base para todas las empresas existentes
insert into public.magnitude (company_id, code, name, active)
select c.id, m.code, m.name, true
from public.company c
cross join (values
  ('LENGTH', 'Longitud'),
  ('AREA', 'Superficie'),
  ('VOLUME', 'Volumen'),
  ('MASS', 'Masa / Peso'),
  ('COUNT', 'Cantidad / Unidades'),
  ('TIME', 'Tiempo')
) as m(code, name)
where not exists (
  select 1 from public.magnitude mag
  where mag.company_id = c.id and mag.code = m.code
);

-- 2. Asegurar columna magnitude_id en unit
alter table public.unit
  add column if not exists magnitude_id bigint references public.magnitude(id),
  add column if not exists symbol varchar;

-- Insertar o asociar unidades estándar para cada empresa
do $$
declare
  r_company record;
  r_mag record;
begin
  for r_company in select id from public.company loop
    -- LENGTH
    select id into r_mag from public.magnitude where company_id = r_company.id and code = 'LENGTH' limit 1;
    if r_mag.id is not null then
      insert into public.unit (company_id, code, name, magnitude_id, symbol, active)
      values
        (r_company.id, 'mm', 'Milímetro', r_mag.id, 'mm', true),
        (r_company.id, 'cm', 'Centímetro', r_mag.id, 'cm', true),
        (r_company.id, 'dm', 'Decímetro', r_mag.id, 'dm', true),
        (r_company.id, 'm', 'Metro', r_mag.id, 'm', true),
        (r_company.id, 'in', 'Pulgada', r_mag.id, 'in', true),
        (r_company.id, 'ft', 'Pie', r_mag.id, 'ft', true)
      on conflict do nothing;

      -- Actualizar existentes que no tengan magnitude_id
      update public.unit
      set magnitude_id = r_mag.id
      where company_id = r_company.id and lower(code) in ('mm', 'cm', 'dm', 'm', 'ml', 'mts', 'metro', 'milimetro', 'centimetro')
        and magnitude_id is null;
    end if;

    -- AREA
    select id into r_mag from public.magnitude where company_id = r_company.id and code = 'AREA' limit 1;
    if r_mag.id is not null then
      insert into public.unit (company_id, code, name, magnitude_id, symbol, active)
      values
        (r_company.id, 'mm2', 'Milímetro cuadrado', r_mag.id, 'mm²', true),
        (r_company.id, 'cm2', 'Centímetro cuadrado', r_mag.id, 'cm²', true),
        (r_company.id, 'dm2', 'Decímetro cuadrado', r_mag.id, 'dm²', true),
        (r_company.id, 'm2', 'Metro cuadrado', r_mag.id, 'm²', true)
      on conflict do nothing;

      update public.unit
      set magnitude_id = r_mag.id
      where company_id = r_company.id and lower(code) in ('m2', 'cm2', 'mm2', 'dm2', 'm²', 'cm²', 'mm²')
        and magnitude_id is null;
    end if;

    -- VOLUME
    select id into r_mag from public.magnitude where company_id = r_company.id and code = 'VOLUME' limit 1;
    if r_mag.id is not null then
      insert into public.unit (company_id, code, name, magnitude_id, symbol, active)
      values
        (r_company.id, 'l', 'Litro', r_mag.id, 'L', true),
        (r_company.id, 'ml_vol', 'Mililitro', r_mag.id, 'ml', true),
        (r_company.id, 'm3', 'Metro cúbico', r_mag.id, 'm³', true),
        (r_company.id, 'dm3', 'Decímetro cúbico', r_mag.id, 'dm³', true),
        (r_company.id, 'cm3', 'Centímetro cúbico', r_mag.id, 'cm³', true)
      on conflict do nothing;

      update public.unit
      set magnitude_id = r_mag.id
      where company_id = r_company.id and lower(code) in ('l', 'litro', 'm3', 'm³', 'cm3', 'cm³')
        and magnitude_id is null;
    end if;

    -- MASS
    select id into r_mag from public.magnitude where company_id = r_company.id and code = 'MASS' limit 1;
    if r_mag.id is not null then
      insert into public.unit (company_id, code, name, magnitude_id, symbol, active)
      values
        (r_company.id, 'g', 'Gramo', r_mag.id, 'g', true),
        (r_company.id, 'kg', 'Kilogramo', r_mag.id, 'kg', true),
        (r_company.id, 't', 'Tonelada', r_mag.id, 't', true)
      on conflict do nothing;

      update public.unit
      set magnitude_id = r_mag.id
      where company_id = r_company.id and lower(code) in ('kg', 'g', 'kilo', 'ton', 't')
        and magnitude_id is null;
    end if;

    -- COUNT
    select id into r_mag from public.magnitude where company_id = r_company.id and code = 'COUNT' limit 1;
    if r_mag.id is not null then
      insert into public.unit (company_id, code, name, magnitude_id, symbol, active)
      values
        (r_company.id, 'ud', 'Unidad', r_mag.id, 'ud', true),
        (r_company.id, 'un', 'Unidad', r_mag.id, 'un', true),
        (r_company.id, 'par', 'Par', r_mag.id, 'par', true),
        (r_company.id, 'caja', 'Caja', r_mag.id, 'caja', true),
        (r_company.id, 'pack', 'Pack', r_mag.id, 'pack', true)
      on conflict do nothing;

      update public.unit
      set magnitude_id = r_mag.id
      where company_id = r_company.id and lower(code) in ('ud', 'un', 'und', 'unidad', 'par', 'caja', 'pack', 'juego', 'set')
        and magnitude_id is null;
    end if;
  end loop;
end $$;

-- 3. Tabla central de conversión de unidades
create table if not exists public.unit_conversion (
  id bigint generated by default as identity primary key,
  company_id bigint not null references public.company(id),
  from_unit_id bigint not null references public.unit(id) on delete cascade,
  to_unit_id bigint not null references public.unit(id) on delete cascade,
  factor numeric(20, 10) not null check (factor > 0),
  offset_val numeric(20, 10) not null default 0,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint uq_unit_conversion unique(company_id, from_unit_id, to_unit_id)
);

create index if not exists ix_unit_conversion_lookup
  on public.unit_conversion(company_id, from_unit_id, to_unit_id, active);

alter table public.unit_conversion enable row level security;

drop policy if exists unit_conversion_authenticated_select on public.unit_conversion;
drop policy if exists unit_conversion_authenticated_insert on public.unit_conversion;
drop policy if exists unit_conversion_authenticated_update on public.unit_conversion;
drop policy if exists unit_conversion_authenticated_delete on public.unit_conversion;

create policy unit_conversion_authenticated_select on public.unit_conversion for select to authenticated using(auth.uid() is not null);
create policy unit_conversion_authenticated_insert on public.unit_conversion for insert to authenticated with check(auth.uid() is not null);
create policy unit_conversion_authenticated_update on public.unit_conversion for update to authenticated using(auth.uid() is not null) with check(auth.uid() is not null);
create policy unit_conversion_authenticated_delete on public.unit_conversion for delete to authenticated using(auth.uid() is not null);

-- 4. Semillar conversiones estándar para todas las empresas
do $$
declare
  r_company record;
  u_mm bigint; u_cm bigint; u_dm bigint; u_m bigint; u_in bigint; u_ft bigint;
  u_mm2 bigint; u_cm2 bigint; u_dm2 bigint; u_m2 bigint;
  u_g bigint; u_kg bigint; u_t bigint;
  u_l bigint; u_ml bigint; u_m3 bigint; u_dm3 bigint; u_cm3 bigint;
begin
  for r_company in select id from public.company loop
    -- Obtener IDs de unidades de longitud
    select id into u_mm from public.unit where company_id = r_company.id and lower(code) = 'mm' limit 1;
    select id into u_cm from public.unit where company_id = r_company.id and lower(code) = 'cm' limit 1;
    select id into u_dm from public.unit where company_id = r_company.id and lower(code) = 'dm' limit 1;
    select id into u_m from public.unit where company_id = r_company.id and lower(code) in ('m', 'ml', 'mts', 'metro') limit 1;
    select id into u_in from public.unit where company_id = r_company.id and lower(code) = 'in' limit 1;
    select id into u_ft from public.unit where company_id = r_company.id and lower(code) = 'ft' limit 1;

    -- Conversiones Longitud
    if u_mm is not null and u_cm is not null then
      insert into public.unit_conversion (company_id, from_unit_id, to_unit_id, factor) values
        (r_company.id, u_mm, u_cm, 0.1),
        (r_company.id, u_cm, u_mm, 10.0)
      on conflict (company_id, from_unit_id, to_unit_id) do update set factor = excluded.factor;
    end if;

    if u_mm is not null and u_m is not null then
      insert into public.unit_conversion (company_id, from_unit_id, to_unit_id, factor) values
        (r_company.id, u_mm, u_m, 0.001),
        (r_company.id, u_m, u_mm, 1000.0)
      on conflict (company_id, from_unit_id, to_unit_id) do update set factor = excluded.factor;
    end if;

    if u_cm is not null and u_m is not null then
      insert into public.unit_conversion (company_id, from_unit_id, to_unit_id, factor) values
        (r_company.id, u_cm, u_m, 0.01),
        (r_company.id, u_m, u_cm, 100.0)
      on conflict (company_id, from_unit_id, to_unit_id) do update set factor = excluded.factor;
    end if;

    if u_dm is not null and u_mm is not null then
      insert into public.unit_conversion (company_id, from_unit_id, to_unit_id, factor) values
        (r_company.id, u_dm, u_mm, 100.0),
        (r_company.id, u_mm, u_dm, 0.01)
      on conflict (company_id, from_unit_id, to_unit_id) do update set factor = excluded.factor;
    end if;

    if u_dm is not null and u_m is not null then
      insert into public.unit_conversion (company_id, from_unit_id, to_unit_id, factor) values
        (r_company.id, u_dm, u_m, 0.1),
        (r_company.id, u_m, u_dm, 10.0)
      on conflict (company_id, from_unit_id, to_unit_id) do update set factor = excluded.factor;
    end if;

    if u_in is not null and u_mm is not null then
      insert into public.unit_conversion (company_id, from_unit_id, to_unit_id, factor) values
        (r_company.id, u_in, u_mm, 25.4),
        (r_company.id, u_mm, u_in, 1.0 / 25.4)
      on conflict (company_id, from_unit_id, to_unit_id) do update set factor = excluded.factor;
    end if;

    -- Obtener IDs de unidades de superficie
    select id into u_mm2 from public.unit where company_id = r_company.id and lower(code) in ('mm2', 'mm²') limit 1;
    select id into u_cm2 from public.unit where company_id = r_company.id and lower(code) in ('cm2', 'cm²') limit 1;
    select id into u_dm2 from public.unit where company_id = r_company.id and lower(code) in ('dm2', 'dm²') limit 1;
    select id into u_m2 from public.unit where company_id = r_company.id and lower(code) in ('m2', 'm²') limit 1;

    if u_mm2 is not null and u_m2 is not null then
      insert into public.unit_conversion (company_id, from_unit_id, to_unit_id, factor) values
        (r_company.id, u_mm2, u_m2, 0.000001),
        (r_company.id, u_m2, u_mm2, 1000000.0)
      on conflict (company_id, from_unit_id, to_unit_id) do update set factor = excluded.factor;
    end if;

    if u_cm2 is not null and u_m2 is not null then
      insert into public.unit_conversion (company_id, from_unit_id, to_unit_id, factor) values
        (r_company.id, u_cm2, u_m2, 0.0001),
        (r_company.id, u_m2, u_cm2, 10000.0)
      on conflict (company_id, from_unit_id, to_unit_id) do update set factor = excluded.factor;
    end if;

    if u_cm2 is not null and u_mm2 is not null then
      insert into public.unit_conversion (company_id, from_unit_id, to_unit_id, factor) values
        (r_company.id, u_cm2, u_mm2, 100.0),
        (r_company.id, u_mm2, u_cm2, 0.01)
      on conflict (company_id, from_unit_id, to_unit_id) do update set factor = excluded.factor;
    end if;

    -- Obtener IDs de masa
    select id into u_g from public.unit where company_id = r_company.id and lower(code) = 'g' limit 1;
    select id into u_kg from public.unit where company_id = r_company.id and lower(code) in ('kg', 'kilo') limit 1;
    select id into u_t from public.unit where company_id = r_company.id and lower(code) in ('t', 'ton') limit 1;

    if u_g is not null and u_kg is not null then
      insert into public.unit_conversion (company_id, from_unit_id, to_unit_id, factor) values
        (r_company.id, u_g, u_kg, 0.001),
        (r_company.id, u_kg, u_g, 1000.0)
      on conflict (company_id, from_unit_id, to_unit_id) do update set factor = excluded.factor;
    end if;

    if u_kg is not null and u_t is not null then
      insert into public.unit_conversion (company_id, from_unit_id, to_unit_id, factor) values
        (r_company.id, u_kg, u_t, 0.001),
        (r_company.id, u_t, u_kg, 1000.0)
      on conflict (company_id, from_unit_id, to_unit_id) do update set factor = excluded.factor;
    end if;
  end loop;
end $$;

-- 5. Ampliar public.otd, public.otd_selection y public.otd_component con soporte de unidades
alter table public.otd
  add column if not exists work_unit_id bigint references public.unit(id);

alter table public.otd_selection
  add column if not exists unit_id bigint references public.unit(id);

alter table public.otd_component
  add column if not exists unit_id bigint references public.unit(id);

comment on column public.otd.work_unit_id is 'Unidad de trabajo visual en la que el usuario introduce dimensiones por defecto en el OTD.';
comment on column public.otd_selection.unit_id is 'Unidad específica para la selección numérica o de dimensión.';
comment on column public.otd_component.unit_id is 'Unidad requerida o de consumo del componente.';
