-- ONIN: hoja de corte para taller.
-- Cada ejecución de un corte dimensional genera un documento consultable
-- con la necesidad y las piezas de stock seleccionadas.

create sequence if not exists public.production_work_sheet_seq;

create table if not exists public.production_work_sheet (
  id bigint generated by default as identity primary key,
  company_id bigint not null,
  code varchar(50) not null,
  document_type varchar(30) not null default 'PROFILE_CUT',
  issue_date timestamptz not null default now(),
  status varchar(30) not null default 'ISSUED',
  sales_order_id bigint references public.sales_order(id),
  sales_order_line_id bigint references public.sales_order_line(id),
  sales_order_line_no integer,
  product_id bigint references public.product(id),
  product_code varchar(100),
  product_name text,
  characteristic_id bigint references public.product_characteristic(id),
  characteristic_code varchar(100),
  characteristic_name text,
  required_length numeric(15,3) not null,
  quantity numeric(15,4) not null,
  reference text,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint production_work_sheet_company_code_uk unique(company_id, code),
  constraint production_work_sheet_type_ck check (document_type in ('PROFILE_CUT')),
  constraint production_work_sheet_status_ck check (status in ('ISSUED','IN_PROGRESS','COMPLETED','CANCELLED')),
  constraint production_work_sheet_length_ck check (required_length > 0),
  constraint production_work_sheet_quantity_ck check (quantity > 0)
);

create table if not exists public.production_work_sheet_line (
  id bigint generated by default as identity primary key,
  work_sheet_id bigint not null references public.production_work_sheet(id) on delete cascade,
  line_no integer not null,
  warehouse_id bigint not null references public.warehouse(id),
  warehouse_code varchar(100),
  warehouse_name text,
  stock_item_id bigint references public.warehouse_stock_item(id),
  source_dimension_values jsonb not null default '[]'::jsonb,
  cut_dimension_values jsonb not null default '[]'::jsonb,
  quantity numeric(15,4) not null default 1,
  remainder_dimension_values jsonb not null default '[]'::jsonb,
  selected_snapshot jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  constraint production_work_sheet_line_no_uk unique(work_sheet_id, line_no),
  constraint production_work_sheet_line_qty_ck check (quantity > 0),
  constraint production_work_sheet_line_source_dims_ck check (jsonb_typeof(source_dimension_values) = 'array'),
  constraint production_work_sheet_line_cut_dims_ck check (jsonb_typeof(cut_dimension_values) = 'array'),
  constraint production_work_sheet_line_remainder_dims_ck check (jsonb_typeof(remainder_dimension_values) = 'array')
);

create index if not exists ix_production_work_sheet_company_date
  on public.production_work_sheet(company_id, issue_date desc);
create index if not exists ix_production_work_sheet_order
  on public.production_work_sheet(sales_order_id, issue_date desc);
create index if not exists ix_production_work_sheet_status
  on public.production_work_sheet(company_id, status);
create index if not exists ix_production_work_sheet_line_header
  on public.production_work_sheet_line(work_sheet_id, line_no);
create index if not exists ix_production_work_sheet_line_stock
  on public.production_work_sheet_line(stock_item_id);

alter table public.production_work_sheet enable row level security;
alter table public.production_work_sheet_line enable row level security;

create policy production_work_sheet_company_select on public.production_work_sheet
  for select using (company_id = (select company_id from public.user_account where auth_user_id = auth.uid()));
create policy production_work_sheet_company_insert on public.production_work_sheet
  for insert with check (company_id = (select company_id from public.user_account where auth_user_id = auth.uid()));
create policy production_work_sheet_company_update on public.production_work_sheet
  for update using (company_id = (select company_id from public.user_account where auth_user_id = auth.uid()))
  with check (company_id = (select company_id from public.user_account where auth_user_id = auth.uid()));
create policy production_work_sheet_company_delete on public.production_work_sheet
  for delete using (company_id = (select company_id from public.user_account where auth_user_id = auth.uid()));

create policy production_work_sheet_line_company_select on public.production_work_sheet_line
  for select using (exists(select 1 from public.production_work_sheet w where w.id = work_sheet_id and w.company_id = (select company_id from public.user_account where auth_user_id = auth.uid())));
create policy production_work_sheet_line_company_insert on public.production_work_sheet_line
  for insert with check (exists(select 1 from public.production_work_sheet w where w.id = work_sheet_id and w.company_id = (select company_id from public.user_account where auth_user_id = auth.uid())));
create policy production_work_sheet_line_company_update on public.production_work_sheet_line
  for update using (exists(select 1 from public.production_work_sheet w where w.id = work_sheet_id and w.company_id = (select company_id from public.user_account where auth_user_id = auth.uid())))
  with check (exists(select 1 from public.production_work_sheet w where w.id = work_sheet_id and w.company_id = (select company_id from public.user_account where auth_user_id = auth.uid())));
create policy production_work_sheet_line_company_delete on public.production_work_sheet_line
  for delete using (exists(select 1 from public.production_work_sheet w where w.id = work_sheet_id and w.company_id = (select company_id from public.user_account where auth_user_id = auth.uid())));

create or replace function public.generate_production_work_sheet_code(p_company_id bigint)
returns varchar
language plpgsql
as $$
declare
  y text := to_char(current_date, 'YYYY');
  n bigint;
begin
  select nextval('public.production_work_sheet_seq') into n;
  return 'HC-' || y || '/' || lpad(n::text, 6, '0');
end;
$$;

create or replace function public.execute_manual_dimensional_cut_with_work_sheet(
  p_company_id bigint,
  p_sales_order_id bigint,
  p_sales_order_line_id bigint,
  p_sales_order_line_no integer,
  p_product_id bigint,
  p_product_code varchar,
  p_product_name text,
  p_characteristic_id bigint,
  p_characteristic_code varchar,
  p_characteristic_name text,
  p_required_dimension_values jsonb,
  p_quantity numeric,
  p_selections jsonb,
  p_reference text default null,
  p_notes text default null
)
returns bigint
language plpgsql
security invoker
as $$
declare
  v_cut_result bigint;
  v_work_sheet_id bigint;
  v_code varchar;
  v_selection jsonb;
  v_line_no integer := 1;
  v_warehouse_id bigint;
  v_source_dims jsonb;
  v_source_length numeric;
  v_required_length numeric;
  v_qty numeric;
  v_remainder numeric;
  v_remainder_dims jsonb;
  v_warehouse_code varchar;
  v_warehouse_name text;
begin
  if p_quantity is null or p_quantity <= 0 then
    raise exception 'La cantidad de la hoja de corte debe ser mayor que cero';
  end if;
  if p_required_dimension_values is null or jsonb_typeof(p_required_dimension_values) <> 'array' then
    raise exception 'Las dimensiones de corte deben ser un array JSON';
  end if;
  if jsonb_array_length(p_required_dimension_values) <> 1 then
    raise exception 'La hoja de corte de perfil requiere actualmente una única dimensión de longitud';
  end if;
  if p_selections is null or jsonb_typeof(p_selections) <> 'array' or jsonb_array_length(p_selections) = 0 then
    raise exception 'La hoja de corte debe contener al menos una pieza seleccionada';
  end if;

  v_required_length := (p_required_dimension_values->>0)::numeric;
  if v_required_length <= 0 then
    raise exception 'La longitud de corte debe ser mayor que cero';
  end if;

  -- El corte y la creación del documento están dentro de la misma transacción.
  -- Si cualquiera de los dos falla, no queda ni consumo de stock ni documento.
  v_cut_result := public.execute_manual_dimensional_cut(
    p_company_id,
    p_product_id,
    p_characteristic_id,
    p_required_dimension_values,
    p_selections,
    p_reference,
    p_notes
  );

  v_code := public.generate_production_work_sheet_code(p_company_id);

  insert into public.production_work_sheet (
    company_id, code, document_type, issue_date, status,
    sales_order_id, sales_order_line_id, sales_order_line_no,
    product_id, product_code, product_name,
    characteristic_id, characteristic_code, characteristic_name,
    required_length, quantity, reference, notes
  ) values (
    p_company_id, v_code, 'PROFILE_CUT', now(), 'ISSUED',
    p_sales_order_id, p_sales_order_line_id, p_sales_order_line_no,
    p_product_id, p_product_code, p_product_name,
    p_characteristic_id, p_characteristic_code, p_characteristic_name,
    v_required_length, p_quantity, p_reference, p_notes
  ) returning id into v_work_sheet_id;

  for v_selection in select value from jsonb_array_elements(p_selections)
  loop
    v_warehouse_id := (v_selection->>'warehouse_id')::bigint;
    v_source_dims := coalesce(v_selection->'dimension_values', '[]'::jsonb);
    v_qty := coalesce((v_selection->>'quantity')::numeric, 0);

    if v_warehouse_id is null or v_qty <= 0 then
      raise exception 'Selección de stock inválida en la hoja de corte';
    end if;
    if jsonb_typeof(v_source_dims) <> 'array' or jsonb_array_length(v_source_dims) <> 1 then
      raise exception 'Cada pieza seleccionada debe tener una única dimensión de longitud';
    end if;

    v_source_length := (v_source_dims->>0)::numeric;
    v_remainder := greatest(0, v_source_length - v_required_length);
    v_remainder_dims := case when v_remainder > 0 then jsonb_build_array(v_remainder) else '[]'::jsonb end;

    select code, name into v_warehouse_code, v_warehouse_name
      from public.warehouse where id = v_warehouse_id;

    insert into public.production_work_sheet_line (
      work_sheet_id, line_no, warehouse_id, warehouse_code, warehouse_name,
      stock_item_id, source_dimension_values, cut_dimension_values,
      quantity, remainder_dimension_values, selected_snapshot
    ) values (
      v_work_sheet_id, v_line_no, v_warehouse_id, v_warehouse_code, v_warehouse_name,
      null, v_source_dims, p_required_dimension_values,
      v_qty, v_remainder_dims,
      jsonb_build_object(
        'warehouse_id', v_warehouse_id,
        'warehouse_code', v_warehouse_code,
        'warehouse_name', v_warehouse_name,
        'source_dimension_values', v_source_dims,
        'cut_dimension_values', p_required_dimension_values,
        'quantity', v_qty,
        'remainder_dimension_values', v_remainder_dims
      )
    );

    v_line_no := v_line_no + 1;
  end loop;

  return v_work_sheet_id;
end;
$$;

grant execute on function public.execute_manual_dimensional_cut_with_work_sheet(bigint,bigint,bigint,integer,bigint,varchar,text,bigint,varchar,text,jsonb,numeric,jsonb,text,text) to authenticated;
grant execute on function public.generate_production_work_sheet_code(bigint) to authenticated;
