-- Modelo Característica-Color (fase 1: esquema + motor de stock).
--
-- Hoy una característica (product_characteristic) hace de variante única: el nombre
-- del color se escribe a mano en su "description" y el stock se localiza solo por
-- characteristic_id. No existe ninguna relación real entre product_characteristic y
-- el catálogo color (que hasta ahora no tiene ni una sola FK ni pantalla propia).
--
-- A partir de aquí, una característica ("Metal") puede agrupar varios colores reales
-- del catálogo color (plateado, dorado, aluminio) mediante la tabla puente
-- characteristic_color. El precio sigue viviendo en la característica —
-- product_scale no cambia, sigue indexado solo por characteristic_id, así que todos
-- los colores de una misma característica ya comparten su escalado sin tocar nada
-- ahí— pero cada combinación característica+color necesita su propia referencia de
-- stock. color_id se añade en paralelo a characteristic_id, con el mismo patrón
-- nullable + "IS NOT DISTINCT FROM" que ya usa characteristic_id en todo el motor de
-- stock: un artículo o característica que no diferencia por color sigue funcionando
-- exactamente igual que hoy, con color_id a NULL en todas partes.

create table if not exists public.characteristic_color (
  id bigint generated by default as identity primary key,
  characteristic_id bigint not null references public.product_characteristic(id),
  color_id bigint not null references public.color(id),
  active boolean not null default true,
  deleted_at timestamptz,
  deleted_by uuid,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint characteristic_color_uk unique (characteristic_id, color_id)
);

create index if not exists ix_characteristic_color_characteristic
  on public.characteristic_color (characteristic_id)
  where deleted_at is null;

create index if not exists ix_characteristic_color_color
  on public.characteristic_color (color_id)
  where deleted_at is null;

alter table public.characteristic_color enable row level security;

drop policy if exists characteristic_color_company_access on public.characteristic_color;
create policy characteristic_color_company_access on public.characteristic_color
  for all using (
    exists (
      select 1 from public.product_characteristic pc
      join public.product p on p.id = pc.product_id
      where pc.id = characteristic_id and p.company_id = public.current_company_id()
    )
  )
  with check (
    exists (
      select 1 from public.product_characteristic pc
      join public.product p on p.id = pc.product_id
      where pc.id = characteristic_id and p.company_id = public.current_company_id()
    )
  );

comment on table public.characteristic_color is
  'Colores agrupados bajo una misma característica. Todos comparten el escalado de precio de la característica (product_scale, sin cambios); cada combinación característica+color tiene su propio saldo de stock.';

-- Stock: color_id en paralelo a characteristic_id, nullable, mismo patrón que hoy.
alter table public.warehouse_stock add column if not exists color_id bigint references public.color(id);
alter table public.warehouse_stock_item add column if not exists color_id bigint references public.color(id);
alter table public.stock_movement add column if not exists color_id bigint references public.color(id);
alter table public.stock_reservation add column if not exists color_id bigint references public.color(id);

comment on column public.warehouse_stock.color_id is 'Color concreto (vía characteristic_color) de esta partida de stock. NULL si la característica no diferencia por color.';
comment on column public.warehouse_stock_item.color_id is 'Color concreto de esta pieza física. NULL si la característica no diferencia por color.';
comment on column public.stock_movement.color_id is 'Color concreto afectado por el movimiento. NULL si la característica no diferencia por color.';
comment on column public.stock_reservation.color_id is 'Color concreto reservado. NULL si la característica no diferencia por color.';

-- Índices que localizan stock por característica pasan a incluir también el color.
drop index if exists uq_warehouse_stock_item;
create unique index if not exists uq_warehouse_stock_item
  on public.warehouse_stock (warehouse_id, product_id, coalesce(characteristic_id, 0), coalesce(color_id, 0));

drop index if exists idx_warehouse_stock_product_characteristic;
create index if not exists idx_warehouse_stock_product_characteristic
  on public.warehouse_stock (product_id, characteristic_id, color_id);

drop index if exists idx_warehouse_stock_item_lookup;
create index if not exists idx_warehouse_stock_item_lookup
  on public.warehouse_stock_item (warehouse_stock_id, product_id, characteristic_id, color_id, status);

drop index if exists idx_stock_movement_item_date;
create index if not exists idx_stock_movement_item_date
  on public.stock_movement (warehouse_id, product_id, characteristic_id, color_id, movement_date desc);

drop index if exists idx_stock_reservation_lookup;
create index if not exists idx_stock_reservation_lookup
  on public.stock_reservation (company_id, warehouse_id, product_id, characteristic_id, color_id, status);

-- Validación reutilizable: un color solo es válido en un movimiento/reserva si está
-- asociado (activo) a la característica indicada. Sin característica no puede haber color.
create or replace function public.validate_characteristic_color(p_characteristic_id bigint, p_color_id bigint)
returns void
language plpgsql
security invoker
as $$
begin
  if p_color_id is null then
    return;
  end if;
  if p_characteristic_id is null then
    raise exception 'No se puede indicar color sin indicar característica';
  end if;
  perform 1 from public.characteristic_color cc
    where cc.characteristic_id = p_characteristic_id
      and cc.color_id = p_color_id
      and cc.active = true
      and cc.deleted_at is null;
  if not found then
    raise exception 'El color no está asociado a la característica indicada';
  end if;
end;
$$;

-- register_stock_movement: añade p_color_id opcional sobre la versión vigente
-- (20260829090000_fix_register_stock_movement_null_dimensions.sql). Nullable con
-- default NULL: cualquier llamada existente que no lo pase sigue funcionando igual.
create or replace function public.register_stock_movement(
  p_company_id bigint,
  p_warehouse_id bigint,
  p_product_id bigint,
  p_quantity numeric,
  p_movement_type_code character varying,
  p_characteristic_id bigint default null,
  p_reference character varying default null,
  p_notes text default null,
  p_movement_date timestamp with time zone default now(),
  p_transfer_group_id uuid default null,
  p_dimension_values jsonb default null,
  p_color_id bigint default null
)
returns bigint
language plpgsql
security invoker
as $$
declare
  v_product public.product%rowtype;
  v_warehouse public.warehouse%rowtype;
  v_type public.stock_movement_type%rowtype;
  v_stock public.warehouse_stock%rowtype;
  v_has_characteristics boolean;
  v_signed numeric;
  v_movement_id bigint;
  v_dimension_array jsonb := '[]'::jsonb;
  v_dimension_units jsonb := '[]'::jsonb;
  v_dimension_count integer := 0;
  v_measurement_type_id bigint;
  v_item_quantity integer;
  v_item_index integer;
begin
  if p_quantity is null or p_quantity <= 0 then raise exception 'La cantidad debe ser mayor que cero'; end if;
  select * into v_product from public.product where id=p_product_id and company_id=p_company_id and deleted_at is null;
  if not found then raise exception 'El artículo no existe para la empresa indicada'; end if;
  if not v_product.stock_enabled then raise exception 'El artículo % no tiene la gestión de stock activada',v_product.code; end if;
  select * into v_warehouse from public.warehouse where id=p_warehouse_id and company_id=p_company_id and deleted_at is null;
  if not found then raise exception 'El almacén no existe para la empresa indicada'; end if;
  if not v_warehouse.active then raise exception 'El almacén está inactivo'; end if;
  select * into v_type from public.stock_movement_type where company_id=p_company_id and code=p_movement_type_code and active=true;
  if not found then raise exception 'Tipo de movimiento no válido: %',p_movement_type_code; end if;
  select exists(select 1 from public.product_characteristic pc where pc.product_id=p_product_id and pc.deleted_at is null and pc.active=true) into v_has_characteristics;
  if p_characteristic_id is not null then
    perform 1 from public.product_characteristic pc where pc.id=p_characteristic_id and pc.product_id=p_product_id and pc.deleted_at is null and pc.active=true;
    if not found then raise exception 'La característica no pertenece al artículo o no está activa'; end if;
  elsif v_product.include_stock_by_color and v_has_characteristics then
    raise exception 'El artículo requiere característica para gestionar stock por color';
  end if;
  perform public.validate_characteristic_color(p_characteristic_id, p_color_id);
  if p_dimension_values is not null and jsonb_typeof(p_dimension_values)='object' and (select count(*) from jsonb_each(p_dimension_values))>0 then
    v_measurement_type_id:=v_product.measurement_type_id;
    if v_measurement_type_id is null and v_product.family_id is not null then
      select pf.measurement_type_id into v_measurement_type_id from public.product_family pf where pf.id=v_product.family_id and pf.deleted_at is null;
    end if;
    if v_measurement_type_id is not null then
      select coalesce(jsonb_agg(case when p_dimension_values ? mtd.code then to_jsonb((p_dimension_values->>mtd.code)::numeric) else 'null'::jsonb end order by mtd.dimension_number),'[]'::jsonb), coalesce(jsonb_agg(coalesce(u.code,u.name) order by mtd.dimension_number),'[]'::jsonb), count(*) into v_dimension_array,v_dimension_units,v_dimension_count
      from public.measurement_type_dimension mtd left join public.unit u on u.id=mtd.unit_id where mtd.measurement_type_id=v_measurement_type_id;
    end if;
    if v_dimension_count=0 then
      select coalesce(jsonb_agg(to_jsonb(value)),'[]'::jsonb) into v_dimension_array from jsonb_each_text(p_dimension_values) as e(key,value);
      v_dimension_units:='[]'::jsonb;
    end if;
  end if;
  v_signed:=p_quantity*(v_type.direction);
  select * into v_stock from public.warehouse_stock where warehouse_id=p_warehouse_id and product_id=p_product_id and characteristic_id is not distinct from p_characteristic_id and color_id is not distinct from p_color_id for update;
  if not found then
    insert into public.warehouse_stock(warehouse_id,product_id,characteristic_id,color_id,quantity,reserved_quantity) values(p_warehouse_id,p_product_id,p_characteristic_id,p_color_id,0,0) returning * into v_stock;
  end if;
  if v_signed<0 and not v_product.allow_negative_stock and (v_stock.quantity+v_signed)<0 then raise exception 'Stock insuficiente. Disponible físico: %',v_stock.quantity; end if;
  update public.warehouse_stock set quantity=quantity+v_signed,updated_at=now() where id=v_stock.id;
  insert into public.stock_movement(company_id,warehouse_id,product_id,movement_type_id,characteristic_id,color_id,quantity,movement_date,reference,notes,transfer_group_id,dimension_values,dimension_units)
  values(p_company_id,p_warehouse_id,p_product_id,v_type.id,p_characteristic_id,p_color_id,p_quantity,p_movement_date,p_reference,p_notes,p_transfer_group_id,case when jsonb_array_length(v_dimension_array)>0 then v_dimension_array else coalesce(p_dimension_values,'[]'::jsonb) end,v_dimension_units)
  returning id into v_movement_id;
  if v_signed>0 and jsonb_array_length(v_dimension_array)>0 and coalesce(v_product.include_measurements_in_stock,false) then
    if p_quantity<>trunc(p_quantity) then raise exception 'El stock dimensional se registra por piezas físicas completas'; end if;
    v_item_quantity:=trunc(p_quantity)::integer;
    for v_item_index in 1..v_item_quantity loop
      insert into public.warehouse_stock_item(warehouse_stock_id,product_id,characteristic_id,color_id,quantity,dimension_values,dimension_units,status,source_stock_movement_id)
      values(v_stock.id,p_product_id,p_characteristic_id,p_color_id,1,v_dimension_array,v_dimension_units,'AVAILABLE',v_movement_id);
    end loop;
  end if;
  return v_movement_id;
end;
$$;

grant execute on function public.register_stock_movement(bigint,bigint,bigint,numeric,character varying,bigint,character varying,text,timestamp with time zone,uuid,jsonb,bigint) to authenticated;

-- register_stock_transfer: reenvía color_id a los dos movimientos que genera.
create or replace function public.register_stock_transfer(
  p_company_id bigint,
  p_source_warehouse_id bigint,
  p_target_warehouse_id bigint,
  p_product_id bigint,
  p_quantity numeric,
  p_characteristic_id bigint default null,
  p_reference character varying default null,
  p_notes text default null,
  p_movement_date timestamp with time zone default now(),
  p_color_id bigint default null
) returns uuid
language plpgsql security invoker as $$
declare v_group uuid := gen_random_uuid();
begin
  if p_source_warehouse_id = p_target_warehouse_id then raise exception 'El almacén origen y destino deben ser distintos'; end if;
  perform public.register_stock_movement(p_company_id,p_source_warehouse_id,p_product_id,p_quantity,'TRANSFER_OUT',p_characteristic_id,p_reference,p_notes,p_movement_date,v_group,null,p_color_id);
  perform public.register_stock_movement(p_company_id,p_target_warehouse_id,p_product_id,p_quantity,'TRANSFER_IN',p_characteristic_id,p_reference,p_notes,p_movement_date,v_group,null,p_color_id);
  return v_group;
end;
$$;

grant execute on function public.register_stock_transfer(bigint,bigint,bigint,bigint,numeric,bigint,character varying,text,timestamp with time zone,bigint) to authenticated;

-- reserve_stock / release_stock_reservation / consume_stock_reservation: color_id en paralelo.
create or replace function public.reserve_stock(
  p_company_id bigint,
  p_warehouse_id bigint,
  p_product_id bigint,
  p_quantity numeric,
  p_characteristic_id bigint default null,
  p_reference character varying default null,
  p_notes text default null,
  p_color_id bigint default null
) returns bigint
language plpgsql security invoker as $$
declare v_product public.product%rowtype; v_warehouse public.warehouse%rowtype; v_stock public.warehouse_stock%rowtype; v_id bigint;
begin
  if p_quantity is null or p_quantity <= 0 then raise exception 'La cantidad a reservar debe ser mayor que cero'; end if;
  select * into v_product from public.product where id=p_product_id and company_id=p_company_id and deleted_at is null;
  if not found then raise exception 'El artículo no existe'; end if;
  if not v_product.stock_enabled then raise exception 'El artículo no tiene la gestión de stock activada'; end if;
  select * into v_warehouse from public.warehouse where id=p_warehouse_id and company_id=p_company_id and deleted_at is null and active=true;
  if not found then raise exception 'El almacén no existe o está inactivo'; end if;
  if p_characteristic_id is not null then
    perform 1 from public.product_characteristic pc where pc.id=p_characteristic_id and pc.product_id=p_product_id and pc.deleted_at is null and pc.active=true;
    if not found then raise exception 'Característica no válida para el artículo'; end if;
  elsif v_product.include_stock_by_color then raise exception 'El artículo requiere característica para reservar stock'; end if;
  perform public.validate_characteristic_color(p_characteristic_id, p_color_id);
  select * into v_stock from public.warehouse_stock where warehouse_id=p_warehouse_id and product_id=p_product_id and characteristic_id is not distinct from p_characteristic_id and color_id is not distinct from p_color_id for update;
  if not found then
    insert into public.warehouse_stock (warehouse_id,product_id,characteristic_id,color_id,quantity,reserved_quantity) values (p_warehouse_id,p_product_id,p_characteristic_id,p_color_id,0,0) returning * into v_stock;
  end if;
  if (v_stock.quantity-v_stock.reserved_quantity)<p_quantity and not v_product.allow_negative_stock then
    raise exception 'Stock disponible insuficiente. Disponible: %',(v_stock.quantity-v_stock.reserved_quantity);
  end if;
  update public.warehouse_stock set reserved_quantity=reserved_quantity+p_quantity,updated_at=now() where id=v_stock.id;
  insert into public.stock_reservation (company_id,warehouse_id,product_id,characteristic_id,color_id,quantity,reference,notes) values (p_company_id,p_warehouse_id,p_product_id,p_characteristic_id,p_color_id,p_quantity,p_reference,p_notes) returning id into v_id;
  return v_id;
end;
$$;

grant execute on function public.reserve_stock(bigint,bigint,bigint,numeric,bigint,character varying,text,bigint) to authenticated;

create or replace function public.release_stock_reservation(p_reservation_id bigint) returns void language plpgsql security invoker as $$
declare v_res public.stock_reservation%rowtype;
begin
  select * into v_res from public.stock_reservation where id=p_reservation_id for update;
  if not found then raise exception 'Reserva no encontrada'; end if;
  if v_res.status<>'ACTIVE' then return; end if;
  update public.warehouse_stock set reserved_quantity=greatest(0,reserved_quantity-v_res.quantity),updated_at=now()
  where warehouse_id=v_res.warehouse_id and product_id=v_res.product_id and characteristic_id is not distinct from v_res.characteristic_id and color_id is not distinct from v_res.color_id;
  update public.stock_reservation set status='RELEASED',updated_at=now() where id=p_reservation_id;
end;
$$;

create or replace function public.consume_stock_reservation(p_reservation_id bigint) returns void language plpgsql security invoker as $$
declare v_res public.stock_reservation%rowtype;
begin
  select * into v_res from public.stock_reservation where id=p_reservation_id for update;
  if not found then raise exception 'Reserva no encontrada'; end if;
  if v_res.status<>'ACTIVE' then return; end if;
  update public.warehouse_stock set reserved_quantity=greatest(0,reserved_quantity-v_res.quantity),updated_at=now()
  where warehouse_id=v_res.warehouse_id and product_id=v_res.product_id and characteristic_id is not distinct from v_res.characteristic_id and color_id is not distinct from v_res.color_id;
  update public.stock_reservation set status='CONSUMED',updated_at=now() where id=p_reservation_id;
end;
$$;

-- reserve_dimensional_stock: color_id en paralelo a characteristic_id, mismo patrón IS NOT DISTINCT FROM.
create or replace function public.reserve_dimensional_stock(
  p_company_id bigint,
  p_warehouse_id bigint,
  p_product_id bigint,
  p_quantity numeric,
  p_characteristic_id bigint default null,
  p_dimension_values jsonb default '[]'::jsonb,
  p_reference character varying default null,
  p_notes text default null,
  p_color_id bigint default null
) returns bigint
language plpgsql
security invoker
as $$
declare
  v_product public.product%rowtype;
  v_family public.product_family%rowtype;
  v_reservation_id bigint;
  v_needed integer;
  v_allocated integer := 0;
  v_item record;
  v_source_dims jsonb;
  v_source_len numeric;
  v_requested_len numeric;
  v_remaining numeric;
  v_recuttable boolean := false;
  v_minimum_remainder numeric := 0;
begin
  if p_quantity is null or p_quantity <= 0 then raise exception 'La cantidad a reservar debe ser mayor que cero'; end if;
  if p_dimension_values is null or jsonb_typeof(p_dimension_values) <> 'array' then raise exception 'Las dimensiones solicitadas deben ser un array JSON'; end if;

  select * into v_product from public.product where id=p_product_id and company_id=p_company_id and deleted_at is null and active=true;
  if not found then raise exception 'El artículo no existe o no está activo'; end if;
  if not v_product.stock_enabled then raise exception 'El artículo no tiene la gestión de stock activada'; end if;
  if not v_product.include_measurements_in_stock then raise exception 'El artículo no tiene activado el control de stock dimensional'; end if;

  if v_product.family_id is not null then
    select * into v_family from public.product_family where id=v_product.family_id and deleted_at is null;
    if found then
      v_recuttable := coalesce(v_family.recuttable,false);
      v_minimum_remainder := coalesce(v_product.minimum_remainder,v_family.minimum_remainder,0);
    end if;
  end if;

  if p_characteristic_id is not null then
    perform 1 from public.product_characteristic pc where pc.id=p_characteristic_id and pc.product_id=p_product_id and pc.deleted_at is null and pc.active=true;
    if not found then raise exception 'La característica no pertenece al artículo o no está activa'; end if;
  elsif v_product.include_stock_by_color then
    raise exception 'El artículo requiere característica para reservar stock dimensional';
  end if;
  perform public.validate_characteristic_color(p_characteristic_id, p_color_id);

  if v_recuttable then
    if jsonb_array_length(p_dimension_values) <> 1 then
      raise exception 'El corte automático de remanentes requiere actualmente un único eje dimensional. Las piezas multidimensionales requieren una regla de corte específica';
    end if;
    v_requested_len := (p_dimension_values->>0)::numeric;
    if v_requested_len <= 0 then raise exception 'La dimensión solicitada debe ser mayor que cero'; end if;
  end if;

  v_needed := ceil(p_quantity);
  if p_quantity <> v_needed then raise exception 'El stock dimensional se reserva por piezas físicas completas'; end if;

  insert into public.stock_reservation(company_id,warehouse_id,product_id,characteristic_id,color_id,quantity,reference,notes,status,dimension_values)
  values(p_company_id,p_warehouse_id,p_product_id,p_characteristic_id,p_color_id,p_quantity,p_reference,p_notes,'ACTIVE',p_dimension_values)
  returning id into v_reservation_id;

  if v_recuttable then
    for v_item in
      select wsi.id,wsi.warehouse_stock_id,wsi.product_id,wsi.characteristic_id,wsi.quantity,wsi.dimension_values
      from public.warehouse_stock_item wsi
      join public.warehouse_stock ws on ws.id=wsi.warehouse_stock_id
      where ws.warehouse_id=p_warehouse_id
        and wsi.product_id=p_product_id
        and wsi.characteristic_id is not distinct from p_characteristic_id
        and wsi.color_id is not distinct from p_color_id
        and wsi.status='AVAILABLE'
        and jsonb_array_length(wsi.dimension_values)=1
        and (wsi.dimension_values->>0)::numeric >= v_requested_len
      order by (wsi.dimension_values->>0)::numeric asc,wsi.id
      for update of wsi skip locked
      limit v_needed
    loop
      v_source_dims := v_item.dimension_values;
      v_source_len := (v_source_dims->>0)::numeric;
      v_remaining := v_source_len-v_requested_len;
      insert into public.stock_reservation_item(reservation_id,stock_item_id,allocated_quantity,requested_dimension_values,remaining_dimension_values,status)
      values(v_reservation_id,v_item.id,1,p_dimension_values,case when v_remaining>0 then jsonb_build_array(v_remaining) else '[]'::jsonb end,'RESERVED');
      update public.warehouse_stock_item set status='RESERVED',updated_at=now() where id=v_item.id;
      update public.warehouse_stock set reserved_quantity=reserved_quantity+1,updated_at=now() where id=v_item.warehouse_stock_id;
      v_allocated := v_allocated+1;
    end loop;
  else
    for v_item in
      select wsi.id,wsi.warehouse_stock_id,wsi.product_id,wsi.characteristic_id,wsi.quantity,wsi.dimension_values
      from public.warehouse_stock_item wsi
      join public.warehouse_stock ws on ws.id=wsi.warehouse_stock_id
      where ws.warehouse_id=p_warehouse_id
        and wsi.product_id=p_product_id
        and wsi.characteristic_id is not distinct from p_characteristic_id
        and wsi.color_id is not distinct from p_color_id
        and wsi.status='AVAILABLE'
        and wsi.dimension_values = p_dimension_values
      order by wsi.id
      for update of wsi skip locked
      limit v_needed
    loop
      insert into public.stock_reservation_item(reservation_id,stock_item_id,allocated_quantity,requested_dimension_values,remaining_dimension_values,status)
      values(v_reservation_id,v_item.id,1,p_dimension_values,'[]'::jsonb,'RESERVED');
      update public.warehouse_stock_item set status='RESERVED',updated_at=now() where id=v_item.id;
      update public.warehouse_stock set reserved_quantity=reserved_quantity+1,updated_at=now() where id=v_item.warehouse_stock_id;
      v_allocated := v_allocated+1;
    end loop;
  end if;

  if v_allocated < v_needed then
    update public.warehouse_stock_item wsi
      set status='AVAILABLE',updated_at=now()
      where wsi.id in (select sri.stock_item_id from public.stock_reservation_item sri where sri.reservation_id=v_reservation_id);
    update public.warehouse_stock ws
      set reserved_quantity=greatest(0,ws.reserved_quantity-v_allocated),updated_at=now()
      where ws.id in (select wsi.warehouse_stock_id from public.warehouse_stock_item wsi join public.stock_reservation_item sri on sri.stock_item_id=wsi.id where sri.reservation_id=v_reservation_id);
    delete from public.stock_reservation_item where reservation_id=v_reservation_id;
    update public.stock_reservation set status='RELEASED',updated_at=now() where id=v_reservation_id;
    raise exception 'Stock dimensional insuficiente. Solicitadas: %, asignadas: %',v_needed,v_allocated;
  end if;

  return v_reservation_id;
end;
$$;

grant execute on function public.reserve_dimensional_stock(bigint,bigint,bigint,numeric,bigint,jsonb,character varying,text,bigint) to authenticated;

-- consume_dimensional_stock_reservation: arrastra v_res.color_id a los movimientos y al remanente.
create or replace function public.consume_dimensional_stock_reservation(p_reservation_id bigint)
returns void
language plpgsql
security invoker
as $$
declare
  v_res public.stock_reservation%rowtype;
  v_product public.product%rowtype;
  v_family public.product_family%rowtype;
  v_item record;
  v_stock public.warehouse_stock%rowtype;
  v_type public.stock_movement_type%rowtype;
  v_source_dims jsonb;
  v_remaining_dims jsonb;
  v_remaining numeric;
  v_minimum_remainder numeric := 0;
  v_recuttable boolean := false;
  v_new_item_id bigint;
  v_movement_id bigint;
begin
  select * into v_res from public.stock_reservation where id=p_reservation_id for update;
  if not found then raise exception 'Reserva no encontrada'; end if;
  if v_res.status<>'ACTIVE' then return; end if;
  select * into v_product from public.product where id=v_res.product_id and deleted_at is null;
  if not found then raise exception 'El artículo de la reserva no existe'; end if;
  if v_product.family_id is not null then
    select * into v_family from public.product_family where id=v_product.family_id and deleted_at is null;
    if found then
      v_recuttable:=coalesce(v_family.recuttable,false);
      v_minimum_remainder:=coalesce(v_product.minimum_remainder,v_family.minimum_remainder,0);
    end if;
  end if;

  select * into v_type from public.stock_movement_type where company_id=v_res.company_id and code='DIMENSIONAL_CONSUMPTION' and active=true;
  if not found then raise exception 'No existe el tipo de movimiento DIMENSIONAL_CONSUMPTION'; end if;

  for v_item in
    select sri.id sri_id,sri.stock_item_id,sri.requested_dimension_values,sri.remaining_dimension_values,
           wsi.warehouse_stock_id,wsi.product_id,wsi.characteristic_id,wsi.color_id,wsi.dimension_values,wsi.status
    from public.stock_reservation_item sri
    join public.warehouse_stock_item wsi on wsi.id=sri.stock_item_id
    where sri.reservation_id=p_reservation_id and sri.status='RESERVED'
    for update of sri,wsi
  loop
    if v_item.status<>'RESERVED' then raise exception 'La existencia % ya no está reservada',v_item.stock_item_id; end if;
    v_source_dims:=v_item.dimension_values;
    v_remaining_dims:=v_item.remaining_dimension_values;

    select * into v_stock from public.warehouse_stock where id=v_item.warehouse_stock_id for update;
    if not found then raise exception 'No existe el saldo agregado del stock %',v_item.warehouse_stock_id; end if;

    insert into public.stock_movement(company_id,warehouse_id,product_id,movement_type_id,characteristic_id,color_id,quantity,movement_date,reference,notes,dimension_values)
    values(v_res.company_id,v_res.warehouse_id,v_res.product_id,v_type.id,v_res.characteristic_id,v_res.color_id,1,now(),v_res.reference,coalesce(v_res.notes,'Consumo dimensional'),v_item.requested_dimension_values)
    returning id into v_movement_id;

    update public.warehouse_stock_item set status='CONSUMED',updated_at=now(),source_stock_movement_id=v_movement_id where id=v_item.stock_item_id;
    update public.warehouse_stock set quantity=greatest(0,quantity-1),reserved_quantity=greatest(0,reserved_quantity-1),updated_at=now() where id=v_item.warehouse_stock_id;

    if v_recuttable and jsonb_array_length(v_remaining_dims)=1 then
      v_remaining:=(v_remaining_dims->>0)::numeric;
      if v_remaining >= v_minimum_remainder and v_remaining > 0 then
        insert into public.warehouse_stock_item(warehouse_stock_id,product_id,characteristic_id,color_id,quantity,dimension_values,status,parent_stock_item_id,source_stock_movement_id)
        values(v_item.warehouse_stock_id,v_item.product_id,v_item.characteristic_id,v_item.color_id,1,v_remaining_dims,'AVAILABLE',v_item.stock_item_id,null)
        returning id into v_new_item_id;

        select * into v_type from public.stock_movement_type where company_id=v_res.company_id and code='DIMENSIONAL_REMNANT' and active=true;
        if not found then raise exception 'No existe el tipo de movimiento DIMENSIONAL_REMNANT'; end if;
        insert into public.stock_movement(company_id,warehouse_id,product_id,movement_type_id,characteristic_id,color_id,quantity,movement_date,reference,notes,dimension_values)
        values(v_res.company_id,v_res.warehouse_id,v_res.product_id,v_type.id,v_res.characteristic_id,v_res.color_id,1,now(),v_res.reference,format('Remanente de %s',v_item.stock_item_id),v_remaining_dims)
        returning id into v_movement_id;
        update public.warehouse_stock_item set source_stock_movement_id=v_movement_id where id=v_new_item_id;
        update public.warehouse_stock set quantity=quantity+1,updated_at=now() where id=v_item.warehouse_stock_id;
      else
        select * into v_type from public.stock_movement_type where company_id=v_res.company_id and code='DIMENSIONAL_SCRAP' and active=true;
        if not found then raise exception 'No existe el tipo de movimiento DIMENSIONAL_SCRAP'; end if;
        insert into public.stock_movement(company_id,warehouse_id,product_id,movement_type_id,characteristic_id,color_id,quantity,movement_date,reference,notes,dimension_values)
        values(v_res.company_id,v_res.warehouse_id,v_res.product_id,v_type.id,v_res.characteristic_id,v_res.color_id,1,now(),v_res.reference,format('Scrap de remanente de %s',v_item.stock_item_id),v_remaining_dims);
      end if;
    end if;

    update public.stock_reservation_item set status='CONSUMED',consumed_at=now(),updated_at=now() where id=v_item.sri_id;
  end loop;

  update public.stock_reservation set status='CONSUMED',updated_at=now() where id=p_reservation_id;
end;
$$;

-- execute_manual_dimensional_cut: añade p_color_id, valida la combinación y filtra
-- las piezas candidatas también por color.
create or replace function public.execute_manual_dimensional_cut(
  p_company_id bigint,p_product_id bigint,p_characteristic_id bigint,p_required_dimension_values jsonb,p_selections jsonb,
  p_reference character varying default null,p_notes text default null,p_color_id bigint default null
) returns bigint language plpgsql security invoker as $$
declare
  v_product public.product%rowtype; v_family public.product_family%rowtype; v_reservation_id bigint;
  v_selection jsonb; v_item record; v_requested_quantity integer; v_allocated integer:=0; v_remaining numeric; v_total_requested integer;
begin
  if p_required_dimension_values is null or jsonb_typeof(p_required_dimension_values)<>'array' or jsonb_array_length(p_required_dimension_values)<>1 then raise exception 'El corte dimensional actual requiere un único eje dimensional'; end if;
  if (p_required_dimension_values->>0)::numeric<=0 then raise exception 'La dimensión solicitada debe ser mayor que cero'; end if;
  if p_selections is null or jsonb_typeof(p_selections)<>'array' or jsonb_array_length(p_selections)=0 then raise exception 'Debes seleccionar al menos una pieza de stock'; end if;
  select * into v_product from public.product where id=p_product_id and company_id=p_company_id and deleted_at is null and active=true;
  if not found then raise exception 'El artículo no existe o no está activo'; end if;
  if not v_product.stock_enabled or not v_product.include_measurements_in_stock then raise exception 'El artículo no tiene gestión de stock dimensional activa'; end if;
  if p_characteristic_id is not null then
    perform 1 from public.product_characteristic where id=p_characteristic_id and product_id=p_product_id and active=true and deleted_at is null;
    if not found then raise exception 'La característica no pertenece al artículo o no está activa'; end if;
  end if;
  perform public.validate_characteristic_color(p_characteristic_id, p_color_id);
  if v_product.family_id is not null then select * into v_family from public.product_family where id=v_product.family_id and deleted_at is null; end if;
  if not coalesce(v_family.recuttable,false) then raise exception 'El artículo no está configurado como recortable'; end if;
  select coalesce(sum((s->>'quantity')::integer),0) into v_total_requested from jsonb_array_elements(p_selections) s;
  if v_total_requested<=0 then raise exception 'La cantidad seleccionada debe ser mayor que cero'; end if;
  insert into public.stock_reservation(company_id,warehouse_id,product_id,characteristic_id,color_id,quantity,reference,notes,status,dimension_values)
  values(p_company_id,((p_selections->0)->>'warehouse_id')::bigint,p_product_id,p_characteristic_id,p_color_id,v_total_requested,p_reference,p_notes,'ACTIVE',p_required_dimension_values)
  returning id into v_reservation_id;
  for v_selection in select value from jsonb_array_elements(p_selections) loop
    v_requested_quantity:=(v_selection->>'quantity')::integer;
    if v_requested_quantity<=0 then raise exception 'La cantidad seleccionada debe ser mayor que cero'; end if;
    for v_item in
      select wsi.id,wsi.warehouse_stock_id,wsi.product_id,wsi.characteristic_id,wsi.quantity,wsi.dimension_values
      from public.warehouse_stock_item wsi join public.warehouse_stock ws on ws.id=wsi.warehouse_stock_id
      where ws.warehouse_id=(v_selection->>'warehouse_id')::bigint and wsi.product_id=p_product_id and wsi.characteristic_id is not distinct from p_characteristic_id and wsi.color_id is not distinct from p_color_id and wsi.status='AVAILABLE' and wsi.dimension_values=(v_selection->'dimension_values') and ((wsi.dimension_values->>0)::numeric>=(p_required_dimension_values->>0)::numeric)
      order by (wsi.dimension_values->>0)::numeric,wsi.id for update of wsi skip locked limit v_requested_quantity
    loop
      v_remaining:=(v_item.dimension_values->>0)::numeric-(p_required_dimension_values->>0)::numeric;
      insert into public.stock_reservation_item(reservation_id,stock_item_id,allocated_quantity,requested_dimension_values,remaining_dimension_values,status)
      values(v_reservation_id,v_item.id,1,p_required_dimension_values,case when v_remaining>0 then jsonb_build_array(v_remaining) else '[]'::jsonb end,'RESERVED');
      update public.warehouse_stock_item set status='RESERVED',updated_at=now() where id=v_item.id;
      update public.warehouse_stock set reserved_quantity=reserved_quantity+1,updated_at=now() where id=v_item.warehouse_stock_id;
      v_allocated:=v_allocated+1;
    end loop;
  end loop;
  if v_allocated<>v_total_requested then raise exception 'El stock seleccionado ya no está disponible. Se pudieron asignar % piezas de las solicitadas.',v_allocated; end if;
  perform public.consume_dimensional_stock_reservation(v_reservation_id);
  return v_reservation_id;
end; $$;

grant execute on function public.execute_manual_dimensional_cut(bigint,bigint,bigint,jsonb,jsonb,character varying,text,bigint) to authenticated;
