-- Paso 8: modelo de datos de LineaPresupuesto.
-- La línea conserva su comportamiento efectivo mediante line_behavior_snapshot,
-- y los datos variables se almacenan en estructuras separadas para evitar una
-- línea monolítica con columnas específicas de cada tipo de artículo.

create table if not exists public.quotation_line_dimension (
  id bigint generated by default as identity primary key,
  quotation_line_id bigint not null references public.quotation_line(id) on delete cascade,
  code varchar not null,
  name varchar not null,
  value numeric,
  unit_id bigint references public.unit(id),
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint quotation_line_dimension_line_code_uk unique(quotation_line_id, code)
);

create index if not exists ix_quotation_line_dimension_line
  on public.quotation_line_dimension(quotation_line_id, sort_order);

create table if not exists public.quotation_line_characteristic (
  id bigint generated by default as identity primary key,
  quotation_line_id bigint not null references public.quotation_line(id) on delete cascade,
  attribute_id bigint references public.product_attribute(id),
  attribute_value_id bigint references public.product_attribute_value(id),
  value_text text,
  value_number numeric,
  value_boolean boolean,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint quotation_line_characteristic_value_ck check (
    num_nonnulls(value_text, value_number, value_boolean, attribute_value_id) = 1
  )
);

create index if not exists ix_quotation_line_characteristic_line
  on public.quotation_line_characteristic(quotation_line_id);

create index if not exists ix_quotation_line_characteristic_attribute
  on public.quotation_line_characteristic(attribute_id);

-- Datos propios del comportamiento de la línea que no forman parte del núcleo
-- común. Se utiliza como extensión controlada, no como sustituto de las
-- dimensiones ni de las características estructuradas.
alter table public.quotation_line
  add column if not exists specific_data jsonb not null default '{}'::jsonb;

comment on column public.quotation_line.specific_data is
  'Extensión específica del comportamiento efectivo de la línea. Las dimensiones y características deben almacenarse en sus tablas estructuradas.';

comment on table public.quotation_line_dimension is
  'Dimensiones capturadas en una línea de presupuesto; independientes del tipo de artículo.';

comment on table public.quotation_line_characteristic is
  'Características capturadas en una línea de presupuesto, incluyendo valores libres o valores del catálogo.';
