create table if not exists public.magnitude (
  id bigint generated by default as identity primary key,
  company_id bigint not null references public.company(id),
  code varchar not null,
  name varchar not null,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint magnitude_company_code_uk unique(company_id, code)
);

create table if not exists public.color (
  id bigint generated by default as identity primary key,
  company_id bigint not null references public.company(id),
  code varchar not null,
  name varchar not null,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint color_company_code_uk unique(company_id, code)
);

create table if not exists public.product_attribute (
  id bigint generated by default as identity primary key,
  company_id bigint not null references public.company(id),
  code varchar not null,
  name varchar not null,
  data_type varchar not null default 'TEXT',
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint product_attribute_company_code_uk unique(company_id, code),
  constraint product_attribute_data_type_ck check (data_type in ('TEXT','NUMBER','BOOLEAN','OPTION'))
);

create table if not exists public.product_attribute_value (
  id bigint generated by default as identity primary key,
  attribute_id bigint not null references public.product_attribute(id) on delete cascade,
  code varchar not null,
  name varchar not null,
  active boolean not null default true,
  sort_order integer not null default 0,
  constraint product_attribute_value_attribute_code_uk unique(attribute_id, code)
);

create index if not exists ix_magnitude_company_active on public.magnitude(company_id, active);
create index if not exists ix_color_company_active on public.color(company_id, active);
create index if not exists ix_product_attribute_company_active on public.product_attribute(company_id, active);
create index if not exists ix_product_attribute_value_attribute_active on public.product_attribute_value(attribute_id, active);