-- Mapa de mediciones y montajes organizado por zonas.
--
-- La medición ya tenía site_latitude/site_longitude (sin usar todavía). El pedido
-- (montaje) no tenía coordenadas propias: se geocodifica su installation_address_*.
-- No hace falta la extensión PostGIS — las zonas se dibujan a mano en el mapa
-- (Leaflet.draw) y se guardan como un polígono GeoJSON; el encaje punto-en-polígono
-- para sugerir la zona al geocodificar se calcula en el cliente (turf.js), el usuario
-- confirma/reasigna y el resultado se guarda como zone_id.

create table if not exists public.zone (
  id bigint generated by default as identity primary key,
  company_id bigint not null references public.company(id),
  name varchar(120) not null,
  color varchar(20) not null default '#5c7a74',
  boundary jsonb,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint zone_company_name_uk unique (company_id, name),
  constraint zone_boundary_ck check (boundary is null or jsonb_typeof(boundary) = 'object')
);

alter table public.zone enable row level security;

drop policy if exists zone_company_select on public.zone;
create policy zone_company_select on public.zone for select using (
  company_id = (select company_id from public.user_account where auth_user_id = auth.uid())
);
drop policy if exists zone_company_insert on public.zone;
create policy zone_company_insert on public.zone for insert with check (
  company_id = (select company_id from public.user_account where auth_user_id = auth.uid())
);
drop policy if exists zone_company_update on public.zone;
create policy zone_company_update on public.zone for update using (
  company_id = (select company_id from public.user_account where auth_user_id = auth.uid())
) with check (
  company_id = (select company_id from public.user_account where auth_user_id = auth.uid())
);
drop policy if exists zone_company_delete on public.zone;
create policy zone_company_delete on public.zone for delete using (
  company_id = (select company_id from public.user_account where auth_user_id = auth.uid())
);

-- Mediciones: ya existían site_latitude/site_longitude; se añade la zona asignada.
alter table public.measurement add column if not exists zone_id bigint references public.zone(id) on delete set null;
create index if not exists ix_measurement_zone on public.measurement(zone_id);

-- Pedidos (montaje): coordenadas de la dirección de instalación + zona asignada.
-- El montaje (installation) no tiene dirección propia, siempre usa la del pedido.
alter table public.sales_order add column if not exists installation_latitude numeric(10,7);
alter table public.sales_order add column if not exists installation_longitude numeric(10,7);
alter table public.sales_order add column if not exists zone_id bigint references public.zone(id) on delete set null;
create index if not exists ix_sales_order_zone on public.sales_order(zone_id);
