-- Facturación v1: factura generada a partir de un pedido ya fabricado, con
-- calendario de plazos derivado de su condición de pago (payment_term).
--
-- El .jar original de Toldos nunca tuvo una entidad Factura real (solo
-- DocumentosComerciales, un bean casi vacío: iid/presupuesto/comercial/
-- cantidad) — no hay nada que portar aquí, se diseña desde cero.
--
-- v1 factura el pedido completo de una vez (todas sus líneas), no permite
-- facturación parcial por línea/cantidad. Como máximo una factura activa
-- (no cancelada) por pedido — igual que el patrón ya usado en installation
-- para "como mucho una programación activa por pedido". El número de
-- factura se asigna al crearla (igual que el pedido ya hace con PED-), no
-- hay estado "borrador" editable previo.

create table if not exists public.invoice (
  id bigint generated by default as identity primary key,
  company_id bigint not null references public.company(id),
  sales_order_id bigint not null references public.sales_order(id),
  customer_id bigint not null,
  code varchar(50) not null,
  issue_date date not null default current_date,
  status varchar(20) not null default 'ISSUED',
  reference text,
  notes text,
  payment_method_id bigint,
  payment_term_id bigint,
  billing_address_street text,
  billing_address_city text,
  billing_address_postal_code text,
  billing_address_region text,
  net_amount numeric(15,2) not null default 0,
  discount_amount numeric(15,2) not null default 0,
  tax_amount numeric(15,2) not null default 0,
  total_amount numeric(15,2) not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint invoice_company_code_uk unique (company_id, code),
  constraint invoice_status_ck check (status in ('ISSUED', 'CANCELLED'))
);
create unique index if not exists ux_invoice_sales_order_active
  on public.invoice (sales_order_id) where status <> 'CANCELLED';
create index if not exists ix_invoice_company_date on public.invoice (company_id, issue_date);
create index if not exists ix_invoice_customer on public.invoice (customer_id);

create table if not exists public.invoice_line (
  id bigint generated by default as identity primary key,
  invoice_id bigint not null references public.invoice(id) on delete cascade,
  sales_order_line_id bigint references public.sales_order_line(id),
  line_no integer not null,
  product_id bigint,
  description text not null,
  quantity numeric(15,3) not null,
  unit_price numeric(15,4) not null,
  discount_percent numeric(6,3) not null default 0,
  tax_percent numeric(6,3) not null default 0,
  net_amount numeric(15,2) not null default 0,
  tax_amount numeric(15,2) not null default 0,
  total_amount numeric(15,2) not null default 0
);
create index if not exists ix_invoice_line_invoice on public.invoice_line (invoice_id);

-- Calendario de cobro derivado de la condición de pago del pedido en el
-- momento de facturar (congelado: si luego cambia el payment_term del
-- pedido o del catálogo, esta factura conserva sus plazos originales).
create table if not exists public.invoice_installment (
  id bigint generated by default as identity primary key,
  invoice_id bigint not null references public.invoice(id) on delete cascade,
  sequence integer not null,
  percentage numeric(6,3) not null,
  due_date date not null,
  amount numeric(15,2) not null,
  constraint invoice_installment_seq_uk unique (invoice_id, sequence)
);
create index if not exists ix_invoice_installment_invoice on public.invoice_installment (invoice_id);

alter table public.invoice enable row level security;
alter table public.invoice_line enable row level security;
alter table public.invoice_installment enable row level security;

drop policy if exists invoice_company_select on public.invoice;
create policy invoice_company_select on public.invoice for select using (
  company_id = (select company_id from public.user_account where auth_user_id = auth.uid())
);
drop policy if exists invoice_company_insert on public.invoice;
create policy invoice_company_insert on public.invoice for insert with check (
  company_id = (select company_id from public.user_account where auth_user_id = auth.uid())
);
drop policy if exists invoice_company_update on public.invoice;
create policy invoice_company_update on public.invoice for update using (
  company_id = (select company_id from public.user_account where auth_user_id = auth.uid())
) with check (
  company_id = (select company_id from public.user_account where auth_user_id = auth.uid())
);

drop policy if exists invoice_line_company_select on public.invoice_line;
create policy invoice_line_company_select on public.invoice_line for select using (
  exists(select 1 from public.invoice i where i.id = invoice_id and i.company_id = (select company_id from public.user_account where auth_user_id = auth.uid()))
);
drop policy if exists invoice_line_company_insert on public.invoice_line;
create policy invoice_line_company_insert on public.invoice_line for insert with check (
  exists(select 1 from public.invoice i where i.id = invoice_id and i.company_id = (select company_id from public.user_account where auth_user_id = auth.uid()))
);

drop policy if exists invoice_installment_company_select on public.invoice_installment;
create policy invoice_installment_company_select on public.invoice_installment for select using (
  exists(select 1 from public.invoice i where i.id = invoice_id and i.company_id = (select company_id from public.user_account where auth_user_id = auth.uid()))
);
drop policy if exists invoice_installment_company_insert on public.invoice_installment;
create policy invoice_installment_company_insert on public.invoice_installment for insert with check (
  exists(select 1 from public.invoice i where i.id = invoice_id and i.company_id = (select company_id from public.user_account where auth_user_id = auth.uid()))
);
drop policy if exists invoice_installment_company_update on public.invoice_installment;
create policy invoice_installment_company_update on public.invoice_installment for update using (
  exists(select 1 from public.invoice i where i.id = invoice_id and i.company_id = (select company_id from public.user_account where auth_user_id = auth.uid()))
) with check (
  exists(select 1 from public.invoice i where i.id = invoice_id and i.company_id = (select company_id from public.user_account where auth_user_id = auth.uid()))
);

create or replace function public.generate_invoice_code(p_company_id bigint) returns varchar
language plpgsql as $$
declare
  y text := to_char(current_date, 'YYYY');
  n integer;
begin
  select coalesce(max(nullif(regexp_replace(code, '^FRA-' || y || '/', ''), '')::integer), 0) + 1 into n
  from public.invoice where company_id = p_company_id and code like 'FRA-' || y || '/%';
  return 'FRA-' || y || '/' || lpad(n::text, 3, '0');
end;
$$;

create or replace function public.create_invoice_from_sales_order(p_sales_order_id bigint) returns bigint
language plpgsql
security invoker
as $$
declare
  o record;
  l record;
  pt record;
  i_id bigint;
  v_code varchar;
  v_line_no integer := 0;
  v_installment_count integer := 0;
  v_amount numeric;
  v_last_installment_id bigint;
  v_sum numeric;
begin
  select * into o from public.sales_order where id = p_sales_order_id;
  if not found then
    raise exception 'Pedido no encontrado';
  end if;
  if o.status not in ('MANUFACTURED', 'INSTALLATION_SCHEDULED', 'INSTALLED') then
    raise exception 'El pedido debe estar fabricado antes de generar la factura';
  end if;

  if exists(select 1 from public.invoice where sales_order_id = p_sales_order_id and status <> 'CANCELLED') then
    select id into i_id from public.invoice where sales_order_id = p_sales_order_id and status <> 'CANCELLED' order by id desc limit 1;
    return i_id;
  end if;

  v_code := public.generate_invoice_code(o.company_id);

  insert into public.invoice (
    company_id, sales_order_id, customer_id, code, issue_date, status, reference, notes,
    payment_method_id, payment_term_id,
    billing_address_street, billing_address_city, billing_address_postal_code, billing_address_region,
    net_amount, discount_amount, tax_amount, total_amount
  ) values (
    o.company_id, o.id, o.customer_id, v_code, current_date, 'ISSUED', o.reference, o.notes,
    o.payment_method_id, o.payment_term_id,
    o.billing_address_street, o.billing_address_city, o.billing_address_postal_code, o.billing_address_region,
    o.net_amount, o.discount_amount, o.tax_amount, o.total_amount
  ) returning id into i_id;

  for l in select * from public.sales_order_line where sales_order_id = p_sales_order_id order by line_no loop
    v_line_no := v_line_no + 1;
    insert into public.invoice_line (
      invoice_id, sales_order_line_id, line_no, product_id, description, quantity, unit_price,
      discount_percent, tax_percent, net_amount, tax_amount, total_amount
    ) values (
      i_id, l.id, v_line_no, l.product_id, l.description, l.quantity, l.unit_price,
      l.discount_percent, l.tax_percent, l.net_amount, l.tax_amount, l.total_amount
    );
  end loop;

  -- Plazos: derivados de la condición de pago del pedido; si no tiene, un
  -- único plazo del 100% con vencimiento en la propia fecha de emisión.
  if o.payment_term_id is not null then
    select count(*) into v_installment_count from public.payment_term_installment where payment_term_id = o.payment_term_id;
  end if;

  if v_installment_count > 0 then
    for pt in select * from public.payment_term_installment where payment_term_id = o.payment_term_id order by sequence loop
      v_amount := round(o.total_amount * pt.percentage / 100, 2);
      insert into public.invoice_installment (invoice_id, sequence, percentage, due_date, amount)
      values (i_id, pt.sequence, pt.percentage, current_date + pt.days_offset, v_amount)
      returning id into v_last_installment_id;
    end loop;
    -- Ajuste de redondeo: el último plazo absorbe la diferencia frente al total exacto de la factura.
    select coalesce(sum(amount), 0) into v_sum from public.invoice_installment where invoice_id = i_id;
    update public.invoice_installment set amount = amount + (o.total_amount - v_sum) where id = v_last_installment_id;
  else
    insert into public.invoice_installment (invoice_id, sequence, percentage, due_date, amount)
    values (i_id, 1, 100, current_date, o.total_amount);
  end if;

  return i_id;
end;
$$;

grant execute on function public.create_invoice_from_sales_order(bigint) to authenticated;

create or replace function public.cancel_invoice(p_invoice_id bigint) returns void
language plpgsql
security invoker
as $$
begin
  update public.invoice set status = 'CANCELLED', updated_at = now()
    where id = p_invoice_id and status <> 'CANCELLED';
  if not found then
    raise exception 'Factura no encontrada o ya cancelada';
  end if;
end;
$$;

grant execute on function public.cancel_invoice(bigint) to authenticated;
