-- Huecos de una medición: cada visita puede cubrir varios puntos a instalar
-- (varios toldos en una misma casa), cada uno con sus propias condiciones de
-- instalación. Un mismo hueco puede albergar más de un producto (p. ej. dos
-- toldos independientes en el mismo balcón) — de ahí la separación entre
-- measurement_opening (el punto físico) y measurement_opening_product (cada
-- OTD dentro de ese punto, con sus propias medidas reales). El objetivo es
-- que esto alimente directamente la línea OTD del presupuesto generado desde
-- la medición, sin retecleo.

create table if not exists public.measurement_opening (
  id bigint generated by default as identity primary key,
  measurement_id bigint not null references public.measurement(id) on delete cascade,
  sort_order integer not null default 0,
  label varchar,
  observations text,
  active boolean not null default true,
  deleted_at timestamptz,
  deleted_by uuid,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists ix_measurement_opening_measurement
  on public.measurement_opening(measurement_id, sort_order);

comment on table public.measurement_opening is
  'Un hueco/punto a cubrir dentro de una medición (una visita puede tener varios). Puede albergar más de un producto — ver measurement_opening_product.';

-- Cada producto (OTD) dentro de un hueco.
create table if not exists public.measurement_opening_product (
  id bigint generated by default as identity primary key,
  opening_id bigint not null references public.measurement_opening(id) on delete cascade,
  sort_order integer not null default 0,
  otd_id bigint references public.otd(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists ix_measurement_opening_product_opening
  on public.measurement_opening_product(opening_id, sort_order);

comment on table public.measurement_opening_product is
  'Un producto (OTD) dentro de un hueco — un hueco puede tener más de un toldo/pérgola.';
comment on column public.measurement_opening_product.otd_id is
  'OTD sugerido por quien mide, in situ. Selección manual, no automática. Define qué selecciones/dimensiones aplican (otd_selection con is_dimension = true).';

-- Medidas reales de cada producto. Mismo shape que quotation_line_dimension a
-- propósito: al generar la línea de presupuesto desde el hueco, copiar de
-- aquí a allí es una operación 1:1, sin transformación.
create table if not exists public.measurement_opening_dimension (
  id bigint generated by default as identity primary key,
  opening_product_id bigint not null references public.measurement_opening_product(id) on delete cascade,
  code varchar not null,
  name varchar not null,
  value numeric,
  unit_id bigint references public.unit(id),
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint measurement_opening_dimension_product_code_uk unique(opening_product_id, code)
);

create index if not exists ix_measurement_opening_dimension_product
  on public.measurement_opening_dimension(opening_product_id, sort_order);

-- Catálogo de condiciones de instalación observables en campo (tipo de
-- superficie, material del soporte, obstáculos, accesibilidad...). Son del
-- punto físico (measurement_opening), no de cada producto por separado.
-- Configurable por empresa, igual que measurement_type o payment_method,
-- para no meter un alta por migración cada vez que se quiera comprobar algo
-- nuevo en campo.
create table if not exists public.installation_condition_type (
  id bigint generated by default as identity primary key,
  company_id bigint not null references public.company(id),
  code varchar not null,
  name varchar not null,
  data_type varchar not null,
  unit_id bigint references public.unit(id),
  sort_order integer not null default 0,
  active boolean not null default true,
  deleted_at timestamptz,
  deleted_by uuid,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint installation_condition_type_company_code_uk unique(company_id, code),
  constraint installation_condition_type_data_type_ck
    check (data_type in ('BOOLEAN','TEXT','NUMBER','SELECT'))
);

create table if not exists public.installation_condition_option (
  id bigint generated by default as identity primary key,
  condition_type_id bigint not null references public.installation_condition_type(id) on delete cascade,
  code varchar not null,
  name varchar not null,
  sort_order integer not null default 0,
  active boolean not null default true,
  constraint installation_condition_option_type_code_uk unique(condition_type_id, code)
);

create index if not exists ix_installation_condition_option_type
  on public.installation_condition_option(condition_type_id, sort_order);

-- Valor de cada condición para un hueco concreto. Mismo patrón que
-- quotation_line_characteristic: exactamente un tipo de valor relleno según
-- installation_condition_type.data_type.
create table if not exists public.measurement_opening_condition (
  id bigint generated by default as identity primary key,
  opening_id bigint not null references public.measurement_opening(id) on delete cascade,
  condition_type_id bigint not null references public.installation_condition_type(id),
  option_id bigint references public.installation_condition_option(id),
  value_text text,
  value_number numeric,
  value_boolean boolean,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint measurement_opening_condition_opening_type_uk unique(opening_id, condition_type_id),
  constraint measurement_opening_condition_value_ck
    check (num_nonnulls(value_text, value_number, value_boolean, option_id) = 1)
);

create index if not exists ix_measurement_opening_condition_opening
  on public.measurement_opening_condition(opening_id);

-- Enlazar cada foto al hueco concreto (opcional: sigue permitiendo fotos
-- generales de la visita con opening_id nulo).
alter table public.measurement_photo
  add column if not exists opening_id bigint references public.measurement_opening(id) on delete set null;

create index if not exists ix_measurement_photo_opening
  on public.measurement_photo(opening_id);

-- RLS: mismo patrón que el resto del modelo (child tables via join a la
-- entidad que sí tiene company_id; catálogos con company_id directo).
alter table public.measurement_opening enable row level security;
alter table public.measurement_opening_product enable row level security;
alter table public.measurement_opening_dimension enable row level security;
alter table public.installation_condition_type enable row level security;
alter table public.installation_condition_option enable row level security;
alter table public.measurement_opening_condition enable row level security;

drop policy if exists measurement_opening_company_access on public.measurement_opening;
create policy measurement_opening_company_access on public.measurement_opening for all
  using (exists(select 1 from public.measurement m where m.id=measurement_id and m.company_id=public.current_company_id()))
  with check (exists(select 1 from public.measurement m where m.id=measurement_id and m.company_id=public.current_company_id()));

drop policy if exists measurement_opening_product_company_access on public.measurement_opening_product;
create policy measurement_opening_product_company_access on public.measurement_opening_product for all
  using (exists(select 1 from public.measurement_opening o join public.measurement m on m.id=o.measurement_id where o.id=opening_id and m.company_id=public.current_company_id()))
  with check (exists(select 1 from public.measurement_opening o join public.measurement m on m.id=o.measurement_id where o.id=opening_id and m.company_id=public.current_company_id()));

drop policy if exists measurement_opening_dimension_company_access on public.measurement_opening_dimension;
create policy measurement_opening_dimension_company_access on public.measurement_opening_dimension for all
  using (exists(select 1 from public.measurement_opening_product p join public.measurement_opening o on o.id=p.opening_id join public.measurement m on m.id=o.measurement_id where p.id=opening_product_id and m.company_id=public.current_company_id()))
  with check (exists(select 1 from public.measurement_opening_product p join public.measurement_opening o on o.id=p.opening_id join public.measurement m on m.id=o.measurement_id where p.id=opening_product_id and m.company_id=public.current_company_id()));

drop policy if exists installation_condition_type_company_select on public.installation_condition_type;
drop policy if exists installation_condition_type_company_insert on public.installation_condition_type;
drop policy if exists installation_condition_type_company_update on public.installation_condition_type;
create policy installation_condition_type_company_select on public.installation_condition_type for select using (company_id=public.current_company_id());
create policy installation_condition_type_company_insert on public.installation_condition_type for insert with check (company_id=public.current_company_id());
create policy installation_condition_type_company_update on public.installation_condition_type for update using (company_id=public.current_company_id()) with check (company_id=public.current_company_id());

drop policy if exists installation_condition_option_company_access on public.installation_condition_option;
create policy installation_condition_option_company_access on public.installation_condition_option for all
  using (exists(select 1 from public.installation_condition_type t where t.id=condition_type_id and t.company_id=public.current_company_id()))
  with check (exists(select 1 from public.installation_condition_type t where t.id=condition_type_id and t.company_id=public.current_company_id()));

drop policy if exists measurement_opening_condition_company_access on public.measurement_opening_condition;
create policy measurement_opening_condition_company_access on public.measurement_opening_condition for all
  using (exists(select 1 from public.measurement_opening o join public.measurement m on m.id=o.measurement_id where o.id=opening_id and m.company_id=public.current_company_id()))
  with check (exists(select 1 from public.measurement_opening o join public.measurement m on m.id=o.measurement_id where o.id=opening_id and m.company_id=public.current_company_id()));
