create table if not exists public.measurement_photo (
  id bigint generated by default as identity primary key,
  measurement_id bigint not null references public.measurement(id) on delete cascade,
  storage_path text not null unique,
  created_at timestamptz not null default now(),
  created_by uuid
);

create index if not exists ix_measurement_photo_measurement on public.measurement_photo(measurement_id, created_at desc);

alter table public.measurement_photo enable row level security;

drop policy if exists measurement_photo_select_assigned on public.measurement_photo;
drop policy if exists measurement_photo_insert_assigned on public.measurement_photo;
drop policy if exists measurement_photo_delete_assigned on public.measurement_photo;

create policy measurement_photo_select_assigned on public.measurement_photo
for select to authenticated
using (
  exists (
    select 1 from public.measurement m
    where m.id = measurement_id
      and m.assigned_user_id = auth.uid()
  )
);

create policy measurement_photo_insert_assigned on public.measurement_photo
for insert to authenticated
with check (
  created_by = auth.uid()
  and exists (
    select 1 from public.measurement m
    where m.id = measurement_id
      and m.assigned_user_id = auth.uid()
      and m.assigned_mode = 'USER'
      and m.status = 'ASSIGNED'
  )
);

create policy measurement_photo_delete_assigned on public.measurement_photo
for delete to authenticated
using (
  exists (
    select 1 from public.measurement m
    where m.id = measurement_id
      and m.assigned_user_id = auth.uid()
      and m.assigned_mode = 'USER'
      and m.status = 'ASSIGNED'
  )
);

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('measurement-photos', 'measurement-photos', false, 10485760, array['image/jpeg','image/png','image/webp']::text[])
on conflict (id) do update set public = false, file_size_limit = 10485760, allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists measurement_photos_select_assigned on storage.objects;
drop policy if exists measurement_photos_insert_assigned on storage.objects;
drop policy if exists measurement_photos_delete_assigned on storage.objects;

create policy measurement_photos_select_assigned on storage.objects
for select to authenticated
using (
  bucket_id = 'measurement-photos'
  and split_part(name, '/', 1) = 'measurements'
  and split_part(name, '/', 2) ~ '^[0-9]+$'
  and exists (
    select 1 from public.measurement m
    where m.id = split_part(name, '/', 2)::bigint
      and m.assigned_user_id = auth.uid()
  )
);

create policy measurement_photos_insert_assigned on storage.objects
for insert to authenticated
with check (
  bucket_id = 'measurement-photos'
  and split_part(name, '/', 1) = 'measurements'
  and split_part(name, '/', 2) ~ '^[0-9]+$'
  and exists (
    select 1 from public.measurement m
    where m.id = split_part(name, '/', 2)::bigint
      and m.assigned_user_id = auth.uid()
      and m.assigned_mode = 'USER'
      and m.status = 'ASSIGNED'
  )
);

create policy measurement_photos_delete_assigned on storage.objects
for delete to authenticated
using (
  bucket_id = 'measurement-photos'
  and split_part(name, '/', 1) = 'measurements'
  and split_part(name, '/', 2) ~ '^[0-9]+$'
  and exists (
    select 1 from public.measurement m
    where m.id = split_part(name, '/', 2)::bigint
      and m.assigned_user_id = auth.uid()
      and m.assigned_mode = 'USER'
      and m.status = 'ASSIGNED'
  )
);
