-- Sustituye el campo único "Observaciones" de cabecera por comentarios: varios por
-- presupuesto, a nivel de cabecera (quotation_line_id null) o de línea concreta, cada uno
-- marcable como "público" (se imprime en el PDF del presupuesto) o interno. Los comentarios
-- NO públicos se heredan al crear un pedido desde el presupuesto (notas de fabricación).

create table if not exists public.quotation_comment (
  id bigint generated by default as identity primary key,
  quotation_id bigint not null references public.quotation(id) on delete cascade,
  quotation_line_id bigint references public.quotation_line(id) on delete cascade,
  text text not null,
  is_public boolean not null default false,
  created_at timestamptz not null default now()
);
create index if not exists ix_quotation_comment_quotation on public.quotation_comment(quotation_id);
create index if not exists ix_quotation_comment_line on public.quotation_comment(quotation_line_id);

alter table public.quotation_comment enable row level security;

drop policy if exists quotation_comment_company_select on public.quotation_comment;
create policy quotation_comment_company_select on public.quotation_comment for select using (
  exists(select 1 from public.quotation q where q.id = quotation_id and q.company_id = (select company_id from public.user_account where auth_user_id = auth.uid()))
);
drop policy if exists quotation_comment_company_insert on public.quotation_comment;
create policy quotation_comment_company_insert on public.quotation_comment for insert with check (
  exists(select 1 from public.quotation q where q.id = quotation_id and q.company_id = (select company_id from public.user_account where auth_user_id = auth.uid()))
);
drop policy if exists quotation_comment_company_update on public.quotation_comment;
create policy quotation_comment_company_update on public.quotation_comment for update using (
  exists(select 1 from public.quotation q where q.id = quotation_id and q.company_id = (select company_id from public.user_account where auth_user_id = auth.uid()))
) with check (
  exists(select 1 from public.quotation q where q.id = quotation_id and q.company_id = (select company_id from public.user_account where auth_user_id = auth.uid()))
);
drop policy if exists quotation_comment_company_delete on public.quotation_comment;
create policy quotation_comment_company_delete on public.quotation_comment for delete using (
  exists(select 1 from public.quotation q where q.id = quotation_id and q.company_id = (select company_id from public.user_account where auth_user_id = auth.uid()))
);

-- Comentarios heredados por el pedido (solo los no públicos del presupuesto de origen; el
-- pedido no imprime presupuesto al cliente, así que aquí no hace falta distinguir públicos).
create table if not exists public.sales_order_comment (
  id bigint generated by default as identity primary key,
  sales_order_id bigint not null references public.sales_order(id) on delete cascade,
  sales_order_line_id bigint references public.sales_order_line(id) on delete cascade,
  text text not null,
  is_public boolean not null default false,
  created_at timestamptz not null default now()
);
create index if not exists ix_sales_order_comment_order on public.sales_order_comment(sales_order_id);
create index if not exists ix_sales_order_comment_line on public.sales_order_comment(sales_order_line_id);

alter table public.sales_order_comment enable row level security;

drop policy if exists sales_order_comment_company_select on public.sales_order_comment;
create policy sales_order_comment_company_select on public.sales_order_comment for select using (
  exists(select 1 from public.sales_order o where o.id = sales_order_id and o.company_id = (select company_id from public.user_account where auth_user_id = auth.uid()))
);
drop policy if exists sales_order_comment_company_insert on public.sales_order_comment;
create policy sales_order_comment_company_insert on public.sales_order_comment for insert with check (
  exists(select 1 from public.sales_order o where o.id = sales_order_id and o.company_id = (select company_id from public.user_account where auth_user_id = auth.uid()))
);
drop policy if exists sales_order_comment_company_update on public.sales_order_comment;
create policy sales_order_comment_company_update on public.sales_order_comment for update using (
  exists(select 1 from public.sales_order o where o.id = sales_order_id and o.company_id = (select company_id from public.user_account where auth_user_id = auth.uid()))
) with check (
  exists(select 1 from public.sales_order o where o.id = sales_order_id and o.company_id = (select company_id from public.user_account where auth_user_id = auth.uid()))
);
drop policy if exists sales_order_comment_company_delete on public.sales_order_comment;
create policy sales_order_comment_company_delete on public.sales_order_comment for delete using (
  exists(select 1 from public.sales_order o where o.id = sales_order_id and o.company_id = (select company_id from public.user_account where auth_user_id = auth.uid()))
);

-- create_sales_order_from_quotation ya existía (conversión parcial por línea); se reescribe
-- para además copiar al pedido los comentarios NO públicos del presupuesto: los de cabecera
-- (una vez por pedido creado) y los de cada línea convertida (a la línea de pedido resultante).
drop function if exists public.create_sales_order_from_quotation(bigint, jsonb);

create or replace function public.create_sales_order_from_quotation(p_quotation_id bigint, p_lines jsonb)
returns bigint
language plpgsql
security invoker
as $$
declare
  q record;
  l record;
  item jsonb;
  o_id bigint;
  new_line_id bigint;
  v_code varchar;
  v_qty numeric;
  v_remaining numeric;
  v_ratio numeric;
  v_line_no integer := 0;
  v_net numeric := 0;
  v_tax numeric := 0;
  v_total numeric := 0;
begin
  select * into q from public.quotation where id = p_quotation_id;
  if not found then
    raise exception 'Presupuesto no encontrado';
  end if;
  if q.status <> 'ACCEPTED' then
    raise exception 'Solo se puede crear un pedido desde un presupuesto aceptado';
  end if;
  if q.customer_id is null then
    raise exception 'El presupuesto debe tener cliente antes de crear el pedido';
  end if;
  if p_lines is null or jsonb_array_length(p_lines) = 0 then
    raise exception 'Selecciona al menos una línea para crear el pedido';
  end if;

  v_code := public.generate_sales_order_code(q.company_id);

  insert into public.sales_order (
    company_id, quotation_id, customer_id, code, issue_date, requested_delivery_date, status,
    reference, notes, net_amount, discount_amount, tax_amount, total_amount,
    billing_address_street, billing_address_city, billing_address_postal_code, billing_address_region,
    installation_address_street, installation_address_city, installation_address_postal_code, installation_address_region,
    contact_id, contact_name, contact_email, contact_phone,
    commercial_id, warehouse_id, payment_method_id, payment_term_id, measurement_id
  ) values (
    q.company_id, q.id, q.customer_id, v_code, current_date, null, 'PENDING_MANUFACTURING',
    q.reference, q.notes, 0, 0, 0, 0,
    q.billing_address_street, q.billing_address_city, q.billing_address_postal_code, q.billing_address_region,
    q.installation_address_street, q.installation_address_city, q.installation_address_postal_code, q.installation_address_region,
    q.contact_id, q.contact_name, q.contact_email, q.contact_phone,
    q.commercial_id, q.warehouse_id, q.payment_method_id, q.payment_term_id, q.measurement_id
  ) returning id into o_id;

  insert into public.sales_order_comment (sales_order_id, sales_order_line_id, text, is_public)
    select o_id, null, text, false
    from public.quotation_comment
    where quotation_id = p_quotation_id and quotation_line_id is null and is_public = false;

  for item in select * from jsonb_array_elements(p_lines)
  loop
    select * into l from public.quotation_line
      where id = (item->>'quotation_line_id')::bigint and quotation_id = p_quotation_id;
    if not found then
      raise exception 'Línea de presupuesto no válida';
    end if;

    v_qty := (item->>'quantity')::numeric;
    if v_qty is null or v_qty <= 0 then
      raise exception 'Cantidad no válida para la línea %', l.line_no;
    end if;

    select l.quantity - coalesce(sum(sol.quantity) filter (where so.status <> 'CANCELLED'), 0)
      into v_remaining
      from public.sales_order_line sol
      join public.sales_order so on so.id = sol.sales_order_id
      where sol.quotation_line_id = l.id;
    v_remaining := coalesce(v_remaining, l.quantity);

    if v_qty > v_remaining then
      raise exception 'La cantidad solicitada para la línea % supera lo disponible (% de %)', l.line_no, v_remaining, l.quantity;
    end if;

    v_ratio := v_qty / l.quantity;
    v_line_no := v_line_no + 1;

    insert into public.sales_order_line (
      sales_order_id, quotation_line_id, line_no, product_id, description, quantity,
      unit_price, discount_percent, tax_percent, net_amount, tax_amount, total_amount, specific_data
    ) values (
      o_id, l.id, v_line_no, l.product_id, l.description, v_qty,
      l.unit_price, l.discount_percent, l.tax_percent,
      round(l.net_amount * v_ratio, 2), round(l.tax_amount * v_ratio, 2), round(l.total_amount * v_ratio, 2),
      coalesce(l.specific_data, '{}'::jsonb)
    ) returning id into new_line_id;

    insert into public.sales_order_comment (sales_order_id, sales_order_line_id, text, is_public)
      select o_id, new_line_id, text, false
      from public.quotation_comment
      where quotation_line_id = l.id and is_public = false;

    v_net := v_net + round(l.net_amount * v_ratio, 2);
    v_tax := v_tax + round(l.tax_amount * v_ratio, 2);
    v_total := v_total + round(l.total_amount * v_ratio, 2);
  end loop;

  update public.sales_order set net_amount = v_net, tax_amount = v_tax, total_amount = v_total
    where id = o_id;

  return o_id;
end;
$$;

grant execute on function public.create_sales_order_from_quotation(bigint, jsonb) to authenticated;
