-- 2B.3: atributos configurables asignados a un artículo.
-- product_attribute define el catálogo reutilizable; esta tabla define qué
-- atributos están disponibles para un artículo concreto.
create table if not exists public.product_attribute_assignment (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.product(id) on delete cascade,
  attribute_id bigint not null references public.product_attribute(id),
  required boolean not null default false,
  sort_order integer not null default 0,
  active boolean not null default true,
  deleted_at timestamptz,
  deleted_by uuid,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint product_attribute_assignment_uk unique(product_id, attribute_id)
);
create index if not exists ix_product_attribute_assignment_product on public.product_attribute_assignment(product_id, active, sort_order);
create index if not exists ix_product_attribute_assignment_attribute on public.product_attribute_assignment(attribute_id);
