create table if not exists public.user_company (
  id bigint generated by default as identity primary key,
  user_account_id bigint not null references public.user_account(id) on delete cascade,
  company_id bigint not null references public.company(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique(user_account_id, company_id)
);

alter table public.user_company enable row level security;
drop policy if exists user_company_self_select on public.user_company;
create policy user_company_self_select on public.user_company for select using (
  user_account_id = (select id from public.user_account where auth_user_id = auth.uid())
);

drop function if exists public.list_my_companies();
create or replace function public.list_my_companies()
returns table(id bigint, code varchar, name varchar, active boolean, is_current boolean)
language sql security definer set search_path = public
as $$
  select c.id, c.code, c.name, c.active, (c.id = ua.company_id)
  from public.user_account ua
  join public.user_company uc on uc.user_account_id = ua.id
  join public.company c on c.id = uc.company_id
  where ua.auth_user_id = auth.uid() and ua.active = true and c.active = true
  order by (c.id = ua.company_id) desc, c.name;
$$;
revoke execute on function public.list_my_companies() from public;
grant execute on function public.list_my_companies() to authenticated;

drop function if exists public.switch_my_company(bigint);
create or replace function public.switch_my_company(p_company_id bigint)
returns void
language plpgsql security definer set search_path = public
as $$
declare v_user_id bigint;
begin
  select id into v_user_id from public.user_account where auth_user_id = auth.uid() and active = true;
  if v_user_id is null then raise exception 'Usuario no encontrado o inactivo'; end if;
  if not exists (select 1 from public.user_company where user_account_id = v_user_id and company_id = p_company_id)
     or not exists (select 1 from public.company where id = p_company_id and active = true) then
    raise exception 'No tienes acceso a esa empresa';
  end if;
  update public.user_account set company_id = p_company_id, updated_at = now() where id = v_user_id;
end;
$$;
revoke execute on function public.switch_my_company(bigint) from public;
grant execute on function public.switch_my_company(bigint) to authenticated;

insert into public.user_company(user_account_id, company_id)
select id, company_id from public.user_account where company_id is not null
on conflict (user_account_id, company_id) do nothing;

insert into public.company(code, name, tax_id, active)
values ('ONIN-DEMO', 'ONIN Demo', 'B00000000', true)
on conflict (code) do nothing;

insert into public.user_company(user_account_id, company_id)
select ua.id, c.id
from public.user_account ua
cross join public.company c
where ua.role_code = 'ADMIN' and c.code = 'ONIN-DEMO'
on conflict (user_account_id, company_id) do nothing;

do $$
declare
  v_source bigint := (select id from public.company where code = 'ONIN');
  v_demo bigint := (select id from public.company where code = 'ONIN-DEMO');
  v_offset bigint := 1000000;
  v_table text;
  v_cols text;
  v_exprs text;
  v_where text;
  v_fk record;
  v_seq text;
  v_sql text;
  v_tables text[] := array[
    'unit','unit_conversion','product_type','product_control_type','product_mounting_type','product_line_behavior',
    'measurement_type','measurement_type_dimension','magnitude','tax_rate','payment_method','payment_term','payment_term_installment',
    'stock_movement_type','document_type','document_series','installation_type','product_family','product_attribute','product_attribute_value',
    'product_family_attribute','product_family_attribute_exclusion','party','address','contact','party_role','customer','commercial',
    'product','product_attribute_assignment','product_characteristic','product_scale','product_supplier','customer_family_discount',
    'product_customer_discount','price_list','price_list_line','party_price_list','warehouse','zone','warehouse_stock','warehouse_stock_item',
    'stock_movement','stock_reservation','stock_reservation_item','measurement','measurement_activity','otd','otd_component','otd_breakdown',
    'otd_rule','otd_selection','otd_selection_option','otd_variable','otd_version','sales_document','sales_document_line','sales_document_otd',
    'document_relation','quotation','quotation_line','quotation_line_characteristic','quotation_line_dimension','quotation_comment',
    'sales_order','sales_order_line','sales_order_comment','production_work_sheet','production_work_sheet_line','purchase_document',
    'purchase_document_line','invoice','invoice_line','invoice_installment','invoice_tax_breakdown','invoice_payment'
  ];
begin
  if v_source is null or v_demo is null then raise exception 'No se encuentran las empresas ONIN/ONIN-DEMO'; end if;
  if exists (select 1 from public.party where company_id = v_demo) then return; end if;

  foreach v_table in array v_tables loop
    v_cols := '';
    v_exprs := '';
    for v_fk in
      select c.column_name,
        (select ccu.table_name
         from information_schema.table_constraints tc
         join information_schema.key_column_usage kcu on kcu.constraint_schema=tc.constraint_schema and kcu.constraint_name=tc.constraint_name
         join information_schema.constraint_column_usage ccu on ccu.constraint_schema=tc.constraint_schema and ccu.constraint_name=tc.constraint_name
         where tc.constraint_schema='public' and tc.table_name=c.table_name and tc.constraint_type='FOREIGN KEY' and kcu.column_name=c.column_name
         limit 1) ref_table
      from information_schema.columns c
      where c.table_schema='public' and c.table_name=v_table and c.is_generated='NEVER'
      order by c.ordinal_position
    loop
      v_cols := v_cols || case when v_cols='' then '' else ', ' end || format('%I',v_fk.column_name);
      if v_fk.column_name='id' then
        v_exprs := v_exprs || case when v_exprs='' then '' else ', ' end || 's.id+'||v_offset;
      elsif v_fk.column_name='company_id' then
        v_exprs := v_exprs || case when v_exprs='' then '' else ', ' end || v_demo;
      elsif v_fk.column_name in ('rectifies_invoice_id','rectified_by_invoice_id','parent_stock_item_id','source_stock_movement_id','source_work_sheet_id','source_work_sheet_line_id','source_sales_order_id','source_sales_order_line_id') then
        v_exprs := v_exprs || case when v_exprs='' then '' else ', ' end || 'null';
      elsif v_fk.ref_table=any(v_tables) then
        v_exprs := v_exprs || case when v_exprs='' then '' else ', ' end || format('case when s.%I is null then null else s.%I+%s end',v_fk.column_name,v_fk.column_name,v_offset);
      else
        v_exprs := v_exprs || case when v_exprs='' then '' else ', ' end || format('s.%I',v_fk.column_name);
      end if;
    end loop;

    if v_table='product' then
      v_where := format('where s.company_id=%s and s.code not like ''__DRAFT__%%''',v_source);
    elsif exists(select 1 from information_schema.columns where table_schema='public' and table_name=v_table and column_name='company_id') then
      v_where := format('where s.company_id=%s',v_source);
    elsif v_table in ('address','contact','party_role','customer','commercial','party_price_list') then
      v_where := format('where s.party_id in(select id from public.party where company_id=%s)',v_source);
    elsif v_table='payment_term_installment' then
      v_where := format('where s.payment_term_id in(select id from public.payment_term where company_id=%s)',v_source);
    elsif v_table='measurement_type_dimension' then
      v_where := format('where s.measurement_type_id in(select id from public.measurement_type where company_id=%s)',v_source);
    elsif v_table='product_attribute_value' then
      v_where := format('where s.attribute_id in(select id from public.product_attribute where company_id=%s)',v_source);
    elsif v_table='product_family_attribute' then
      v_where := format('where s.family_id in(select id from public.product_family where company_id=%s)',v_source);
    elsif v_table='product_family_attribute_exclusion' then
      v_where := format('where s.product_id in(select id from public.product where company_id=%s)',v_source);
    elsif v_table in ('product_attribute_assignment','product_characteristic','product_scale','product_supplier','product_customer_discount') then
      v_where := format('where s.product_id in(select id from public.product where company_id=%s)',v_source);
    elsif v_table='price_list_line' then
      v_where := format('where s.price_list_id in(select id from public.price_list where company_id=%s)',v_source);
    elsif v_table='warehouse_stock' then
      v_where := format('where s.warehouse_id in(select id from public.warehouse where company_id=%s)',v_source);
    elsif v_table='warehouse_stock_item' then
      v_where := format('where s.warehouse_stock_id in(select id from public.warehouse_stock where warehouse_id in(select id from public.warehouse where company_id=%s))',v_source);
    elsif v_table='stock_reservation_item' then
      v_where := format('where s.reservation_id in(select id from public.stock_reservation where company_id=%s)',v_source);
    elsif v_table='measurement_activity' then
      v_where := format('where s.measurement_id in(select id from public.measurement where company_id=%s)',v_source);
    elsif v_table in ('otd_component','otd_breakdown','otd_rule','otd_selection','otd_variable','otd_version') then
      v_where := format('where s.otd_id in(select id from public.otd where company_id=%s)',v_source);
    elsif v_table='otd_selection_option' then
      v_where := format('where s.selection_id in(select id from public.otd_selection where otd_id in(select id from public.otd where company_id=%s))',v_source);
    elsif v_table='sales_document_line' then
      v_where := format('where s.sales_document_id in(select id from public.sales_document where company_id=%s)',v_source);
    elsif v_table='sales_document_otd' then
      v_where := format('where s.sales_document_line_id in(select id from public.sales_document_line where sales_document_id in(select id from public.sales_document where company_id=%s))',v_source);
    elsif v_table='document_relation' then
      v_where := format('where s.source_document_id in(select id from public.sales_document where company_id=%s) and s.target_document_id in(select id from public.sales_document where company_id=%s)',v_source,v_source);
    elsif v_table in ('quotation_line','quotation_comment') then
      v_where := format('where s.quotation_id in(select id from public.quotation where company_id=%s)',v_source);
    elsif v_table in ('quotation_line_characteristic','quotation_line_dimension') then
      v_where := format('where s.quotation_line_id in(select id from public.quotation_line where quotation_id in(select id from public.quotation where company_id=%s))',v_source);
    elsif v_table in ('sales_order_line','sales_order_comment') then
      v_where := format('where s.sales_order_id in(select id from public.sales_order where company_id=%s)',v_source);
    elsif v_table='production_work_sheet_line' then
      v_where := format('where s.work_sheet_id in(select id from public.production_work_sheet where company_id=%s)',v_source);
    elsif v_table='purchase_document_line' then
      v_where := format('where s.purchase_document_id in(select id from public.purchase_document where company_id=%s)',v_source);
    elsif v_table in ('invoice_line','invoice_installment','invoice_tax_breakdown') then
      v_where := format('where s.invoice_id in(select id from public.invoice where company_id=%s)',v_source);
    else
      continue;
    end if;

    v_sql := format('insert into public.%I (%s) select %s from public.%I s %s',v_table,v_cols,v_exprs,v_table,v_where);
    execute v_sql;
  end loop;

  foreach v_table in array v_tables loop
    begin
      select pg_get_serial_sequence(format('public.%I',v_table),'id') into v_seq;
      if v_seq is not null then
        execute format('select setval(%L,greatest(coalesce((select max(id) from public.%I),1),1),true)',v_seq,v_table);
      end if;
    exception when others then null;
    end;
  end loop;
end $$;

update public.party
set legal_name='[DEMO] '||legal_name,
    trade_name=case when trade_name is null then null else '[DEMO] '||trade_name end
where company_id=(select id from public.company where code='ONIN-DEMO');

update public.product
set commercial_description='[DEMO] '||coalesce(commercial_description,code)
where company_id=(select id from public.company where code='ONIN-DEMO');
