import { supabase } from '../../lib/supabase';
import { CoreRepositoryError } from '../core/coreRepository';
export type ProductAttributeRef={id:number;code:string;name:string;data_type:string};
export type ProductAttributeAssignment=ProductAttributeRef&{assignment_id:number;required:boolean;sort_order:number;active:boolean;deleted_at:string|null};
function client(){if(!supabase)throw new CoreRepositoryError('Supabase no está configurado.');return supabase;}
export async function listProductAttributeAssignments(productId:number):Promise<ProductAttributeAssignment[]>{const c=client();const {data,error}=await c.from('product_attribute_assignment').select('id,attribute_id,required,sort_order,active,deleted_at,product_attribute!inner(id,code,name,data_type)').eq('product_id',productId).is('deleted_at',null).order('sort_order').order('attribute_id');if(error)throw new CoreRepositoryError(error.message);return(data??[]).map((r:any)=>({assignment_id:r.id,id:r.product_attribute.id,code:r.product_attribute.code,name:r.product_attribute.name,data_type:r.product_attribute.data_type,required:!!r.required,sort_order:r.sort_order,active:!!r.active,deleted_at:r.deleted_at??null}));}
export async function listAvailableProductAttributes(companyId:number,productId:number):Promise<ProductAttributeRef[]>{const c=client();const [attrs,assigned]=await Promise.all([c.from('product_attribute').select('id,code,name,data_type').eq('company_id',companyId).eq('active',true).is('deleted_at',null).order('code'),c.from('product_attribute_assignment').select('attribute_id').eq('product_id',productId).is('deleted_at',null)]);if(attrs.error)throw new CoreRepositoryError(attrs.error.message);if(assigned.error)throw new CoreRepositoryError(assigned.error.message);const ids=new Set((assigned.data??[]).map((x:any)=>Number(x.attribute_id)));return((attrs.data??[])as ProductAttributeRef[]).filter(x=>!ids.has(x.id));}
export async function assignProductAttribute(productId:number,attributeId:number,required=false,sortOrder=0):Promise<void>{const c=client();const {error}=await c.from('product_attribute_assignment').upsert({product_id:productId,attribute_id:attributeId,required,sort_order:sortOrder,active:true,deleted_at:null,deleted_by:null},{onConflict:'product_id,attribute_id'});if(error)throw new CoreRepositoryError(error.message);}
export async function updateProductAttributeAssignment(id:number,input:{required?:boolean;sort_order?:number;active?:boolean}):Promise<void>{const c=client();const {error}=await c.from('product_attribute_assignment').update(input).eq('id',id).is('deleted_at',null);if(error)throw new CoreRepositoryError(error.message);}
export async function removeProductAttributeAssignment(id:number):Promise<void>{const c=client();const {data:user}=await c.auth.getUser();const {error}=await c.from('product_attribute_assignment').update({active:false,deleted_at:new Date().toISOString(),deleted_by:user.user?.id??null}).eq('id',id).is('deleted_at',null);if(error)throw new CoreRepositoryError(error.message);}
