import { supabase } from '../../lib/supabase';
import { CoreRepositoryError } from '../core/coreRepository';
export type ProductSupplierRow={id:number;product_id:number;supplier_party_id:number;supplier_code:string|null;price_type:string|null;price:number|null;discount_percent:number;active:boolean;characteristic_id:number|null;delivery_days:number|null;deleted_at:string|null;deleted_by:number|null;supplier_name:string;characteristic_code:string|null};
export type ProductScaleRow={id:number;product_id:number;dimension_values:number[];dimension_1:number;dimension_2:number|null;price:number;characteristic_id:number|null;characteristic_code:string|null;characteristic_description:string|null;deleted_at:string|null;deleted_by:number|null};
export type ProductSupplierInput=Omit<ProductSupplierRow,'id'|'product_id'|'supplier_name'|'characteristic_code'|'deleted_at'|'deleted_by'>;
export type ProductScaleInput={dimension_values:number[];price:number;characteristic_id:number|null};
function client(){if(!supabase)throw new CoreRepositoryError('Supabase no está configurado.');return supabase;}
export async function listProductSuppliers(productId:number):Promise<ProductSupplierRow[]>{const c=client();const {data,error}=await c.from('product_supplier').select('id,product_id,supplier_party_id,supplier_code,price_type,price,discount_percent,active,characteristic_id,delivery_days,deleted_at,deleted_by').eq('product_id',productId).is('deleted_at',null).order('active',{ascending:false}).order('id');if(error)throw new CoreRepositoryError(error.message);const rows=(data??[]) as Omit<ProductSupplierRow,'supplier_name'|'characteristic_code'>[];const ids=[...new Set(rows.map(r=>r.supplier_party_id))];const chars=[...new Set(rows.map(r=>r.characteristic_id).filter((v):v is number=>v!==null))];const [sup,chr]=await Promise.all([ids.length?c.from('party').select('id,legal_name,trade_name').in('id',ids):Promise.resolve({data:[],error:null} as any),chars.length?c.from('product_characteristic').select('id,code').in('id',chars):Promise.resolve({data:[],error:null} as any)]);if(sup.error)throw new CoreRepositoryError(sup.error.message);if(chr.error)throw new CoreRepositoryError(chr.error.message);const names=new Map((sup.data??[]).map((x:any)=>[x.id,x.trade_name||x.legal_name||`Proveedor ${x.id}`] as const));const codes=new Map((chr.data??[]).map((x:any)=>[x.id,x.code] as const));return rows.map(r=>({...r,supplier_name:names.get(r.supplier_party_id)??`Proveedor ${r.supplier_party_id}`,characteristic_code:r.characteristic_id?codes.get(r.characteristic_id)??null:null}));}
function normalizeDimensionValues(row:any):number[]{if(Array.isArray(row.dimension_values)&&row.dimension_values.length)return row.dimension_values.map((v:any)=>Number(v));const values=[Number(row.dimension_1)];if(row.dimension_2!=null)values.push(Number(row.dimension_2));return values;}
export async function listProductScales(productId:number):Promise<ProductScaleRow[]>{const c=client();const {data,error}=await c.from('product_scale').select('id,product_id,dimension_values,dimension_1,dimension_2,price,characteristic_id,deleted_at,deleted_by').eq('product_id',productId).is('deleted_at',null).order('dimension_1').order('dimension_2');if(error)throw new CoreRepositoryError(error.message);const rows=(data??[]) as any[];const ids=[...new Set(rows.map(r=>r.characteristic_id).filter((v):v is number=>v!==null))];const chr=ids.length?await c.from('product_characteristic').select('id,code,description').in('id',ids):{data:[],error:null} as any;if(chr.error)throw new CoreRepositoryError(chr.error.message);const map=new Map((chr.data??[]).map((x:any)=>[x.id,x] as const));return rows.map(r=>({...r,dimension_values:normalizeDimensionValues(r),characteristic_code:r.characteristic_id?map.get(r.characteristic_id)?.code??null:null,characteristic_description:r.characteristic_id?map.get(r.characteristic_id)?.description??null:null}));}
export async function createProductSupplier(productId:number,input:ProductSupplierInput):Promise<void>{const c=client();const {error}=await c.from('product_supplier').insert({product_id:productId,...input,deleted_at:null,deleted_by:null});if(error)throw new CoreRepositoryError(error.message);}
export async function updateProductSupplier(id:number,input:Partial<ProductSupplierInput>):Promise<void>{const c=client();const {error}=await c.from('product_supplier').update(input).eq('id',id).is('deleted_at',null);if(error)throw new CoreRepositoryError(error.message);}
export async function markProductSupplierForDeletion(id:number):Promise<void>{const c=client();const {error}=await c.from('product_supplier').update({active:false,deleted_at:new Date().toISOString()}).eq('id',id).is('deleted_at',null);if(error)throw new CoreRepositoryError(error.message);}
export async function restoreProductSupplier(id:number):Promise<void>{const c=client();const {error}=await c.from('product_supplier').update({active:true,deleted_at:null,deleted_by:null}).eq('id',id);if(error)throw new CoreRepositoryError(error.message);}
function scalePayload(input:ProductScaleInput){const values=input.dimension_values.map(Number);if(!values.length||values.some(v=>!Number.isFinite(v)||v<0))throw new CoreRepositoryError('Las dimensiones del escalado deben ser válidas.');return {dimension_values:values,dimension_1:values[0],dimension_2:values.length>1?values[1]:null,price:Number(input.price),characteristic_id:input.characteristic_id};}
export async function createProductScale(productId:number,input:ProductScaleInput):Promise<void>{if(input.price<=0)throw new CoreRepositoryError('El precio del escalado debe ser mayor que 0.');const c=client();const {error}=await c.from('product_scale').insert({product_id:productId,...scalePayload(input),deleted_at:null,deleted_by:null});if(error)throw new CoreRepositoryError(error.message);}
export async function updateProductScale(id:number,input:ProductScaleInput):Promise<void>{if(input.price<=0)throw new CoreRepositoryError('El precio del escalado debe ser mayor que 0.');const c=client();const {error}=await c.from('product_scale').update(scalePayload(input)).eq('id',id).is('deleted_at',null);if(error)throw new CoreRepositoryError(error.message);}
export async function markProductScaleForDeletion(id:number):Promise<void>{const c=client();const {error}=await c.from('product_scale').update({deleted_at:new Date().toISOString()}).eq('id',id).is('deleted_at',null);if(error)throw new CoreRepositoryError(error.message);}
export async function restoreProductScale(id:number):Promise<void>{const c=client();const {error}=await c.from('product_scale').update({deleted_at:null,deleted_by:null}).eq('id',id);if(error)throw new CoreRepositoryError(error.message);}
