import { supabase } from '../../lib/supabase';
import { CoreRepositoryError } from '../core/coreRepository';
import type { Product, ProductCharacteristic, ProductFamilyRef, ProductLineBehavior } from './productRepository';
import type { ProductScaleRow } from './productCommercialRepository';
import type { MeasurementDimension, MeasurementType } from './measurementTypeRepository';
import { resolveEffectiveDimensions } from './measurementTypeRepository';
import { listProductCharacteristicConfiguration, listProductAttributeScales, listEffectiveAttributeColors } from './productAttributeRepository';
import { listFamilyAttributeScales } from './familyAttributeRepository';

export type MasterProductAttributeScaleRow = { dimension_1:number; dimension_2:number|null; price:number };
export type MasterProductConfiguration = {
  product: Product; family: ProductFamilyRef | null; lineBehavior: ProductLineBehavior | null; baseUnit: { id:number; code:string; name:string } | null;
  measurementType: (MeasurementType & { dimensions: MeasurementDimension[] }) | null; dimensions: MeasurementDimension[];
  attributes: Array<{assignment_id:number;attribute_id:number;code:string;name:string;required:boolean;sort_order:number;scaled:boolean;pvp:number|null;scaleRows:MasterProductAttributeScaleRow[];colors:Array<{color_id:number;code:string;name:string}>}>;
  characteristics: ProductCharacteristic[]; scales: ProductScaleRow[];
  bomComponents: Array<{id:number;code:string;description:string|null;quantity_expression:string|null;unit_id:number|null;unit_code?:string|null;unit_name?:string|null;product_id:number|null;product_code?:string|null;product_name?:string|null;unit_price?:number;unit_cost?:number;sort_order:number;active:boolean}>;
  unitsMap: Map<number,{id:number;code:string;name:string}>; loadedAt:string; versionHash:string;
};
function client(){if(!supabase)throw new CoreRepositoryError('Supabase no está configurado.');return supabase;}
function generateVersionHash(data:{product:Product;scales:ProductScaleRow[];characteristics:ProductCharacteristic[];attributes:any[];bomComponents:any[];measurementType:any}):string{return[data.product.id,data.product.sales_price,data.product.purchase_price,data.product.price_increment,data.product.measurement_type_id,data.product.scaled?'1':'0',data.product.scaled_by_characteristic?'1':'0',data.scales.map(s=>`${s.dimension_1}-${s.dimension_2}-${s.price}-${s.characteristic_id}-${JSON.stringify(s.attribute_values??{})}`).join('|'),data.characteristics.map(c=>`${c.id}-${c.code}-${c.pvp}-${c.price_increment}-${c.active}`).join('|'),data.attributes.map(a=>`${a.attribute_id}-${a.required}-${a.scaled}-${a.pvp}-${a.colors.map((v:any)=>v.color_id).join(',')}`).join('|'),data.bomComponents.map(b=>`${b.id}-${b.code}-${b.quantity_expression}`).join('|'),data.measurementType?.dimensions?.map((d:any)=>`${d.dimension_number}-${d.code}-${d.unit_id}-${d.decimals}`).join('|')??''].join('::');}
export async function loadMasterProductConfiguration(productId:number,companyId?:number|null):Promise<MasterProductConfiguration>{
 const c=client();const productRes=await c.from('product').select('*').eq('id',productId).single();if(productRes.error)throw new CoreRepositoryError(productRes.error.message||'Artículo no encontrado');const product=productRes.data as Product;const actualCompanyId=product.company_id??companyId??1;
 const fetchFamiliesSafe=async()=>{const res=await c.from('product_family').select('id,code,name,product_type_id,measurement_type_id,minimum_remainder,confectionable,recuttable,line_behavior_id').eq('company_id',actualCompanyId).eq('active',true).is('deleted_at',null);if(!res.error)return res;if(res.error.message?.includes('measurement_type_id'))return await c.from('product_family').select('id,code,name,product_type_id,minimum_remainder,confectionable,recuttable,line_behavior_id').eq('company_id',actualCompanyId).eq('active',true).is('deleted_at',null);return res;};
 const [unitsRes,familiesRes,lineBehaviorsRes,characteristicsRes,scalesRes,effectiveAttrs,otdRes]=await Promise.all([c.from('unit').select('id,code,name').eq('company_id',actualCompanyId).eq('active',true).is('deleted_at',null),fetchFamiliesSafe(),c.from('product_line_behavior').select('*').eq('company_id',actualCompanyId).eq('active',true).is('deleted_at',null),c.from('product_characteristic').select('*').eq('product_id',productId).eq('active',true).is('deleted_at',null).order('code'),c.from('product_scale').select('*').eq('product_id',productId).is('deleted_at',null).order('dimension_1').order('dimension_2'),listProductCharacteristicConfiguration(productId).then(rows=>rows.filter(r=>!r.excluded)),c.from('otd_component').select('*').eq('product_id',productId).eq('active',true).is('deleted_at',null).order('sort_order')]);
 const unitsList=(unitsRes.data??[]) as Array<{id:number;code:string;name:string}>;const unitsMap=new Map(unitsList.map(u=>[u.id,u]));const baseUnit=product.base_unit_id?unitsMap.get(product.base_unit_id)??null:null;const lineBehaviors=(lineBehaviorsRes.data??[]) as ProductLineBehavior[];const lineBehaviorsMap=new Map(lineBehaviors.map(b=>[b.id,b]));const families=(familiesRes.data??[]).map((f:any)=>({...f,lineBehavior:f.line_behavior_id?lineBehaviorsMap.get(f.line_behavior_id)??null:null})) as ProductFamilyRef[];const family=product.family_id?families.find(f=>f.id===product.family_id)??null:null;const lineBehavior=family?.lineBehavior??null;
 const effectiveMeasurementTypeId=product.measurement_type_id??family?.measurement_type_id??null;
 const {measurementType,dimensions}=await resolveEffectiveDimensions(effectiveMeasurementTypeId);
 const scaledAttrs=effectiveAttrs.filter(a=>a.scaled);
 const scaleRowsByAssignment=new Map<number,MasterProductAttributeScaleRow[]>();
 await Promise.all(scaledAttrs.map(async a=>{
   const rows=a.source==='family'?await listFamilyAttributeScales(a.assignment_id):await listProductAttributeScales(a.assignment_id);
   scaleRowsByAssignment.set(a.assignment_id,rows.map(r=>({dimension_1:r.dimension_1,dimension_2:r.dimension_2,price:r.price})));
 }));
 const colorsByAssignment=new Map<number,Array<{color_id:number;code:string;name:string}>>();
 await Promise.all(effectiveAttrs.map(async a=>{
   const cols=await listEffectiveAttributeColors(a.attribute_id,a.source,a.assignment_id);
   colorsByAssignment.set(a.assignment_id,cols);
 }));
 const attributes=effectiveAttrs.map(a=>({assignment_id:a.assignment_id,attribute_id:a.attribute_id,code:a.code,name:a.name,required:a.required,sort_order:a.sort_order,scaled:a.scaled,pvp:a.pvp,scaleRows:scaleRowsByAssignment.get(a.assignment_id)??[],colors:colorsByAssignment.get(a.assignment_id)??[]}));const characteristics=(characteristicsRes.data??[]) as ProductCharacteristic[];const scales=(scalesRes.data??[]) as ProductScaleRow[];
 const rawBom=(otdRes.data??[]) as any[];const componentProductIds=rawBom.map(b=>b.product_id).filter((id):id is number=>id!=null);const componentProductsMap=new Map<number,Product>();if(componentProductIds.length){const {data:cpData}=await c.from('product').select('id,code,commercial_description,technical_description,sales_price,purchase_price,base_unit_id').in('id',[...new Set(componentProductIds)]);for(const cp of cpData??[])componentProductsMap.set(Number(cp.id),cp as Product);}const bomComponents=rawBom.map(b=>{const compProd=b.product_id?componentProductsMap.get(Number(b.product_id)):null;const unit=b.unit_id?unitsMap.get(Number(b.unit_id)):compProd?.base_unit_id?unitsMap.get(Number(compProd.base_unit_id)):null;return{id:Number(b.id),code:String(b.code||''),description:b.description||compProd?.commercial_description||compProd?.technical_description||null,quantity_expression:b.quantity_expression||null,unit_id:unit?.id??null,unit_code:unit?.code??null,unit_name:unit?.name??null,product_id:b.product_id?Number(b.product_id):null,product_code:compProd?.code??null,product_name:compProd?.commercial_description||compProd?.technical_description||null,unit_price:Number(compProd?.sales_price??0),unit_cost:Number(compProd?.purchase_price??0),sort_order:Number(b.sort_order??0),active:Boolean(b.active)};});const versionHash=generateVersionHash({product,scales,characteristics,attributes,bomComponents,measurementType});return{product,family,lineBehavior,baseUnit,measurementType,dimensions,attributes,characteristics,scales,bomComponents,unitsMap,loadedAt:new Date().toISOString(),versionHash};
}
